/-
  Shared algebra for the D12 compound restriction certificates.
  Auto-generated by scripts/export_d12_compound_lean.py.
  DO NOT HAND-EDIT.
  Schema: v14.d12.compound.restriction.v2
  Source JSON sha256: 76c6196f29afe1a8398af99502447f48ebeed4bcb3805fc5dbec693940bc04b0
-/
module

public import V14Formalization.D12PolynomialCore
public import Mathlib.Tactic.LinearCombination

/-!
# Bridge lemmas for the compound restriction certificates

`B_poly` is sparse with half-integer entries.  Every generated
certificate is therefore stated for *twice* a difference, so that
only integer scalars survive into its arithmetic; `of_two` undoes
the doubling once, and the two families of collapse lemmas below
do the sparse bookkeeping once per column and once per row instead
of once per certificate.
-/

noncomputable section

open Matrix Polynomial

namespace V14Formalization.D12CompoundBridge

open D12PolynomialData

theorem C_half_two : (2 : Polynomial ℚ) * C (1 / 2 : ℚ) = 1 := by
  rw [show (2 : Polynomial ℚ) = C 2 by exact (map_natCast C 2).symm, ← map_mul]
  norm_num

theorem C_neg_half_two : (2 : Polynomial ℚ) * C (-1 / 2 : ℚ) = -1 := by
  rw [show (2 : Polynomial ℚ) = C 2 by exact (map_natCast C 2).symm, ← map_mul]
  norm_num

/-- Undo the doubling that keeps the certificates integral. -/
public theorem of_two {D q : Polynomial ℚ}
    (h : (2 : Polynomial ℚ) * D = Phi11 * q) :
    ∃ q' : Polynomial ℚ, D = Phi11 * q' := by
  refine ⟨C (1 / 2 : ℚ) * q, ?_⟩
  calc D = (2 : Polynomial ℚ) * C (1 / 2 : ℚ) * D := by
        rw [C_half_two, one_mul]
    _ = C (1 / 2 : ℚ) * ((2 : Polynomial ℚ) * D) := by ring
    _ = C (1 / 2 : ℚ) * (Phi11 * q) := by rw [h]
    _ = Phi11 * (C (1 / 2 : ℚ) * q) := by ring

/-! ### Every constant in terms of the single atom `C (1/22)` -/

public theorem C_1_over_11 :
    C (1 / 11 : ℚ) = (2 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (2 : Polynomial ℚ) = C 2 by exact (map_natCast C 2).symm, ← map_mul]
  norm_num

public theorem C_2_over_11 :
    C (2 / 11 : ℚ) = (4 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (4 : Polynomial ℚ) = C 4 by exact (map_natCast C 4).symm, ← map_mul]
  norm_num

public theorem C_3_over_11 :
    C (3 / 11 : ℚ) = (6 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (6 : Polynomial ℚ) = C 6 by exact (map_natCast C 6).symm, ← map_mul]
  norm_num

public theorem C_4_over_11 :
    C (4 / 11 : ℚ) = (8 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (8 : Polynomial ℚ) = C 8 by exact (map_natCast C 8).symm, ← map_mul]
  norm_num

public theorem C_5_over_11 :
    C (5 / 11 : ℚ) = (10 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (10 : Polynomial ℚ) = C 10 by exact (map_natCast C 10).symm, ← map_mul]
  norm_num

public theorem C_6_over_11 :
    C (6 / 11 : ℚ) = (12 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (12 : Polynomial ℚ) = C 12 by exact (map_natCast C 12).symm, ← map_mul]
  norm_num

public theorem C_7_over_11 :
    C (7 / 11 : ℚ) = (14 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (14 : Polynomial ℚ) = C 14 by exact (map_natCast C 14).symm, ← map_mul]
  norm_num

public theorem C_8_over_11 :
    C (8 / 11 : ℚ) = (16 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (16 : Polynomial ℚ) = C 16 by exact (map_natCast C 16).symm, ← map_mul]
  norm_num

public theorem C_3_over_22 :
    C (3 / 22 : ℚ) = (3 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (3 : Polynomial ℚ) = C 3 by exact (map_natCast C 3).symm, ← map_mul]
  norm_num

public theorem C_5_over_22 :
    C (5 / 22 : ℚ) = (5 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (5 : Polynomial ℚ) = C 5 by exact (map_natCast C 5).symm, ← map_mul]
  norm_num

public theorem C_7_over_22 :
    C (7 / 22 : ℚ) = (7 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (7 : Polynomial ℚ) = C 7 by exact (map_natCast C 7).symm, ← map_mul]
  norm_num

public theorem C_9_over_22 :
    C (9 / 22 : ℚ) = (9 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (9 : Polynomial ℚ) = C 9 by exact (map_natCast C 9).symm, ← map_mul]
  norm_num

public theorem C_11_over_22 :
    C (11 / 22 : ℚ) = (11 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (11 : Polynomial ℚ) = C 11 by exact (map_natCast C 11).symm, ← map_mul]
  norm_num

public theorem C_13_over_22 :
    C (13 / 22 : ℚ) = (13 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (13 : Polynomial ℚ) = C 13 by exact (map_natCast C 13).symm, ← map_mul]
  norm_num

public theorem C_15_over_22 :
    C (15 / 22 : ℚ) = (15 : Polynomial ℚ) * C (1 / 22 : ℚ) := by
  rw [show (15 : Polynomial ℚ) = C 15 by exact (map_natCast C 15).symm, ← map_mul]
  norm_num

public theorem C_one_over_22_sq :
    C (1 / 22 : ℚ) =
      (22 : Polynomial ℚ) *
        (C (1 / 22 : ℚ) * C (1 / 22 : ℚ)) := by
  rw [show (22 : Polynomial ℚ) = C 22 by exact (map_natCast C 22).symm,
    ← map_mul, ← map_mul]
  congr 1
  norm_num

/-! ### Twice a column of `M * B_poly`, with `B` collapsed once -/

public theorem two_mul_B_col0
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (0 : Fin 10) =
      (2 : Polynomial ℚ) * M i (0 : Fin 15) - M i (13 : Fin 15) := by
  have hB : (M * B_poly) i (0 : Fin 10) =
      M i (0 : Fin 15) + M i (13 : Fin 15) * C (-1/2 : ℚ) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (M i (13 : Fin 15)) * C_neg_half_two

public theorem two_mul_B_col1
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (1 : Fin 10) =
      (2 : Polynomial ℚ) * M i (1 : Fin 15) + M i (8 : Fin 15) := by
  have hB : (M * B_poly) i (1 : Fin 10) =
      M i (1 : Fin 15) + M i (8 : Fin 15) * C (1/2 : ℚ) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (M i (8 : Fin 15)) * C_half_two

public theorem two_mul_B_col2
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (2 : Fin 10) =
      (2 : Polynomial ℚ) * M i (2 : Fin 15) - M i (10 : Fin 15) := by
  have hB : (M * B_poly) i (2 : Fin 10) =
      M i (2 : Fin 15) + M i (10 : Fin 15) * C (-1/2 : ℚ) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (M i (10 : Fin 15)) * C_neg_half_two

public theorem two_mul_B_col3
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (3 : Fin 10) =
      (2 : Polynomial ℚ) * M i (3 : Fin 15) - M i (5 : Fin 15) := by
  have hB : (M * B_poly) i (3 : Fin 10) =
      M i (3 : Fin 15) + M i (5 : Fin 15) * C (-1/2 : ℚ) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (M i (5 : Fin 15)) * C_neg_half_two

public theorem two_mul_B_col4
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (4 : Fin 10) =
      (2 : Polynomial ℚ) * M i (4 : Fin 15) + M i (12 : Fin 15) := by
  have hB : (M * B_poly) i (4 : Fin 10) =
      M i (4 : Fin 15) + M i (12 : Fin 15) * C (1/2 : ℚ) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (M i (12 : Fin 15)) * C_half_two

public theorem two_mul_B_col5
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (5 : Fin 10) =
      (2 : Polynomial ℚ) * M i (6 : Fin 15) := by
  have hB : (M * B_poly) i (5 : Fin 10) =
      M i (6 : Fin 15) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_mul_B_col6
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (6 : Fin 10) =
      (2 : Polynomial ℚ) * M i (7 : Fin 15) := by
  have hB : (M * B_poly) i (6 : Fin 10) =
      M i (7 : Fin 15) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_mul_B_col7
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (7 : Fin 10) =
      (2 : Polynomial ℚ) * M i (9 : Fin 15) := by
  have hB : (M * B_poly) i (7 : Fin 10) =
      M i (9 : Fin 15) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_mul_B_col8
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (8 : Fin 10) =
      (2 : Polynomial ℚ) * M i (11 : Fin 15) := by
  have hB : (M * B_poly) i (8 : Fin 10) =
      M i (11 : Fin 15) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_mul_B_col9
    (M : Matrix (Fin 15) (Fin 15) PolyQ) (i : Fin 15) :
    (2 : Polynomial ℚ) * (M * B_poly) i (9 : Fin 10) =
      (2 : Polynomial ℚ) * M i (14 : Fin 15) := by
  have hB : (M * B_poly) i (9 : Fin 10) =
      M i (14 : Fin 15) := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

/-! ### Twice a row of `B_poly * N`, with `B` collapsed once -/

public theorem two_B_mul_row0
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (0 : Fin 15) j =
      (2 : Polynomial ℚ) * N (0 : Fin 10) j := by
  have hB : (B_poly * N) (0 : Fin 15) j = N (0 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_B_mul_row1
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (1 : Fin 15) j =
      (2 : Polynomial ℚ) * N (1 : Fin 10) j := by
  have hB : (B_poly * N) (1 : Fin 15) j = N (1 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_B_mul_row2
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (2 : Fin 15) j =
      (2 : Polynomial ℚ) * N (2 : Fin 10) j := by
  have hB : (B_poly * N) (2 : Fin 15) j = N (2 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_B_mul_row3
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (3 : Fin 15) j =
      (2 : Polynomial ℚ) * N (3 : Fin 10) j := by
  have hB : (B_poly * N) (3 : Fin 15) j = N (3 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_B_mul_row4
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (4 : Fin 15) j =
      (2 : Polynomial ℚ) * N (4 : Fin 10) j := by
  have hB : (B_poly * N) (4 : Fin 15) j = N (4 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_B_mul_row5
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (5 : Fin 15) j =
      -N (3 : Fin 10) j := by
  have hB : (B_poly * N) (5 : Fin 15) j = C (-1/2 : ℚ) * N (3 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (N (3 : Fin 10) j) * C_neg_half_two

public theorem two_B_mul_row6
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (6 : Fin 15) j =
      (2 : Polynomial ℚ) * N (5 : Fin 10) j := by
  have hB : (B_poly * N) (6 : Fin 15) j = N (5 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_B_mul_row7
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (7 : Fin 15) j =
      (2 : Polynomial ℚ) * N (6 : Fin 10) j := by
  have hB : (B_poly * N) (7 : Fin 15) j = N (6 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_B_mul_row8
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (8 : Fin 15) j =
      N (1 : Fin 10) j := by
  have hB : (B_poly * N) (8 : Fin 15) j = C (1/2 : ℚ) * N (1 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (N (1 : Fin 10) j) * C_half_two

public theorem two_B_mul_row9
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (9 : Fin 15) j =
      (2 : Polynomial ℚ) * N (7 : Fin 10) j := by
  have hB : (B_poly * N) (9 : Fin 15) j = N (7 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_B_mul_row10
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (10 : Fin 15) j =
      -N (2 : Fin 10) j := by
  have hB : (B_poly * N) (10 : Fin 15) j = C (-1/2 : ℚ) * N (2 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (N (2 : Fin 10) j) * C_neg_half_two

public theorem two_B_mul_row11
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (11 : Fin 15) j =
      (2 : Polynomial ℚ) * N (8 : Fin 10) j := by
  have hB : (B_poly * N) (11 : Fin 15) j = N (8 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

public theorem two_B_mul_row12
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (12 : Fin 15) j =
      N (4 : Fin 10) j := by
  have hB : (B_poly * N) (12 : Fin 15) j = C (1/2 : ℚ) * N (4 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (N (4 : Fin 10) j) * C_half_two

public theorem two_B_mul_row13
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (13 : Fin 15) j =
      -N (0 : Fin 10) j := by
  have hB : (B_poly * N) (13 : Fin 15) j = C (-1/2 : ℚ) * N (0 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]
  linear_combination (N (0 : Fin 10) j) * C_neg_half_two

public theorem two_B_mul_row14
    (N : Matrix (Fin 10) (Fin 10) PolyQ) (j : Fin 10) :
    (2 : Polynomial ℚ) * (B_poly * N) (14 : Fin 15) j =
      (2 : Polynomial ℚ) * N (9 : Fin 10) j := by
  have hB : (B_poly * N) (14 : Fin 15) j = N (9 : Fin 10) j := by
    simp [Matrix.mul_apply, Fin.sum_univ_succ, B_poly, Matrix.of_apply]
    all_goals ring
  rw [hB]

end V14Formalization.D12CompoundBridge
