/-
  D12 character-piece rational-vector action base.
  Auto-generated by scripts/export_d12_piece_vec_lean.py.
  Payload sha256: 76c6196f29afe1a8398af99502447f48ebeed4bcb3805fc5dbec693940bc04b0
-/
import V14Formalization.D12CyclotomicVec
import V14Formalization.D12PieceAction
import V14Formalization.D12PolynomialRM
import V14Formalization.D12PolynomialSM

noncomputable section

open Matrix Polynomial

namespace V14Formalization.D12PieceVecBase

open D12CyclotomicVec D12PolynomialData D12PolynomialEvaluation

theorem eval_of10 (v : Coeff10) :
    D12CyclotomicVec.eval v = evalK (of10 v) := by
  unfold D12CyclotomicVec.eval
  simp [evalK, evalPolyAt, of10, map_sum, map_mul, map_pow, aeval_def]

def RMVecRow0 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM0c0
  | 1 => RM0c1
  | 2 => RM0c2
  | 3 => RM0c3
  | 4 => RM0c4
  | 5 => RM0c5
  | 6 => RM0c6
  | 7 => RM0c7
  | 8 => RM0c8
  | 9 => RM0c9
  | _ => 0

def RMVecRow1 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM1c0
  | 1 => RM1c1
  | 2 => RM1c2
  | 3 => RM1c3
  | 4 => RM1c4
  | 5 => RM1c5
  | 6 => RM1c6
  | 7 => RM1c7
  | 8 => RM1c8
  | 9 => RM1c9
  | _ => 0

def RMVecRow2 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM2c0
  | 1 => RM2c1
  | 2 => RM2c2
  | 3 => RM2c3
  | 4 => RM2c4
  | 5 => RM2c5
  | 6 => RM2c6
  | 7 => RM2c7
  | 8 => RM2c8
  | 9 => RM2c9
  | _ => 0

def RMVecRow3 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM3c0
  | 1 => RM3c1
  | 2 => RM3c2
  | 3 => RM3c3
  | 4 => RM3c4
  | 5 => RM3c5
  | 6 => RM3c6
  | 7 => RM3c7
  | 8 => RM3c8
  | 9 => RM3c9
  | _ => 0

def RMVecRow4 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM4c0
  | 1 => RM4c1
  | 2 => RM4c2
  | 3 => RM4c3
  | 4 => RM4c4
  | 5 => RM4c5
  | 6 => RM4c6
  | 7 => RM4c7
  | 8 => RM4c8
  | 9 => RM4c9
  | _ => 0

def RMVecRow5 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM5c0
  | 1 => RM5c1
  | 2 => RM5c2
  | 3 => RM5c3
  | 4 => RM5c4
  | 5 => RM5c5
  | 6 => RM5c6
  | 7 => RM5c7
  | 8 => RM5c8
  | 9 => RM5c9
  | _ => 0

def RMVecRow6 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM6c0
  | 1 => RM6c1
  | 2 => RM6c2
  | 3 => RM6c3
  | 4 => RM6c4
  | 5 => RM6c5
  | 6 => RM6c6
  | 7 => RM6c7
  | 8 => RM6c8
  | 9 => RM6c9
  | _ => 0

def RMVecRow7 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM7c0
  | 1 => RM7c1
  | 2 => RM7c2
  | 3 => RM7c3
  | 4 => RM7c4
  | 5 => RM7c5
  | 6 => RM7c6
  | 7 => RM7c7
  | 8 => RM7c8
  | 9 => RM7c9
  | _ => 0

def RMVecRow8 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM8c0
  | 1 => RM8c1
  | 2 => RM8c2
  | 3 => RM8c3
  | 4 => RM8c4
  | 5 => RM8c5
  | 6 => RM8c6
  | 7 => RM8c7
  | 8 => RM8c8
  | 9 => RM8c9
  | _ => 0

def RMVecRow9 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => RM9c0
  | 1 => RM9c1
  | 2 => RM9c2
  | 3 => RM9c3
  | 4 => RM9c4
  | 5 => RM9c5
  | 6 => RM9c6
  | 7 => RM9c7
  | 8 => RM9c8
  | 9 => RM9c9
  | _ => 0

def RMVec : Matrix (Fin 10) (Fin 10) Vec :=
  fun i j => match i.val with
  | 0 => RMVecRow0 j
  | 1 => RMVecRow1 j
  | 2 => RMVecRow2 j
  | 3 => RMVecRow3 j
  | 4 => RMVecRow4 j
  | 5 => RMVecRow5 j
  | 6 => RMVecRow6 j
  | 7 => RMVecRow7 j
  | 8 => RMVecRow8 j
  | 9 => RMVecRow9 j
  | _ => 0

theorem RMVecRow0_of10 (j : Fin 10) :
    of10 (RMVecRow0 j) = RMrow0 j := by
  fin_cases j <;> rfl

theorem RMVecRow1_of10 (j : Fin 10) :
    of10 (RMVecRow1 j) = RMrow1 j := by
  fin_cases j <;> rfl

theorem RMVecRow2_of10 (j : Fin 10) :
    of10 (RMVecRow2 j) = RMrow2 j := by
  fin_cases j <;> rfl

theorem RMVecRow3_of10 (j : Fin 10) :
    of10 (RMVecRow3 j) = RMrow3 j := by
  fin_cases j <;> rfl

theorem RMVecRow4_of10 (j : Fin 10) :
    of10 (RMVecRow4 j) = RMrow4 j := by
  fin_cases j <;> rfl

theorem RMVecRow5_of10 (j : Fin 10) :
    of10 (RMVecRow5 j) = RMrow5 j := by
  fin_cases j <;> rfl

theorem RMVecRow6_of10 (j : Fin 10) :
    of10 (RMVecRow6 j) = RMrow6 j := by
  fin_cases j <;> rfl

theorem RMVecRow7_of10 (j : Fin 10) :
    of10 (RMVecRow7 j) = RMrow7 j := by
  fin_cases j <;> rfl

theorem RMVecRow8_of10 (j : Fin 10) :
    of10 (RMVecRow8 j) = RMrow8 j := by
  fin_cases j <;> rfl

theorem RMVecRow9_of10 (j : Fin 10) :
    of10 (RMVecRow9 j) = RMrow9 j := by
  fin_cases j <;> rfl

theorem RMVec_of10 (i j : Fin 10) :
    of10 (RMVec i j) = RM_poly i j := by
  fin_cases i
  · exact RMVecRow0_of10 j
  · exact RMVecRow1_of10 j
  · exact RMVecRow2_of10 j
  · exact RMVecRow3_of10 j
  · exact RMVecRow4_of10 j
  · exact RMVecRow5_of10 j
  · exact RMVecRow6_of10 j
  · exact RMVecRow7_of10 j
  · exact RMVecRow8_of10 j
  · exact RMVecRow9_of10 j

theorem evalMatrix_RMVec :
    evalMatrix RMVec = evalMatrixK RM_poly := by
  ext i j
  change D12CyclotomicVec.eval (RMVec i j) =
    evalK (RM_poly i j)
  rw [eval_of10, RMVec_of10]

def SMVecRow0 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM0c0
  | 1 => SM0c1
  | 2 => SM0c2
  | 3 => SM0c3
  | 4 => SM0c4
  | 5 => SM0c5
  | 6 => SM0c6
  | 7 => SM0c7
  | 8 => SM0c8
  | 9 => SM0c9
  | _ => 0

def SMVecRow1 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM1c0
  | 1 => SM1c1
  | 2 => SM1c2
  | 3 => SM1c3
  | 4 => SM1c4
  | 5 => SM1c5
  | 6 => SM1c6
  | 7 => SM1c7
  | 8 => SM1c8
  | 9 => SM1c9
  | _ => 0

def SMVecRow2 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM2c0
  | 1 => SM2c1
  | 2 => SM2c2
  | 3 => SM2c3
  | 4 => SM2c4
  | 5 => SM2c5
  | 6 => SM2c6
  | 7 => SM2c7
  | 8 => SM2c8
  | 9 => SM2c9
  | _ => 0

def SMVecRow3 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM3c0
  | 1 => SM3c1
  | 2 => SM3c2
  | 3 => SM3c3
  | 4 => SM3c4
  | 5 => SM3c5
  | 6 => SM3c6
  | 7 => SM3c7
  | 8 => SM3c8
  | 9 => SM3c9
  | _ => 0

def SMVecRow4 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM4c0
  | 1 => SM4c1
  | 2 => SM4c2
  | 3 => SM4c3
  | 4 => SM4c4
  | 5 => SM4c5
  | 6 => SM4c6
  | 7 => SM4c7
  | 8 => SM4c8
  | 9 => SM4c9
  | _ => 0

def SMVecRow5 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM5c0
  | 1 => SM5c1
  | 2 => SM5c2
  | 3 => SM5c3
  | 4 => SM5c4
  | 5 => SM5c5
  | 6 => SM5c6
  | 7 => SM5c7
  | 8 => SM5c8
  | 9 => SM5c9
  | _ => 0

def SMVecRow6 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM6c0
  | 1 => SM6c1
  | 2 => SM6c2
  | 3 => SM6c3
  | 4 => SM6c4
  | 5 => SM6c5
  | 6 => SM6c6
  | 7 => SM6c7
  | 8 => SM6c8
  | 9 => SM6c9
  | _ => 0

def SMVecRow7 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM7c0
  | 1 => SM7c1
  | 2 => SM7c2
  | 3 => SM7c3
  | 4 => SM7c4
  | 5 => SM7c5
  | 6 => SM7c6
  | 7 => SM7c7
  | 8 => SM7c8
  | 9 => SM7c9
  | _ => 0

def SMVecRow8 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM8c0
  | 1 => SM8c1
  | 2 => SM8c2
  | 3 => SM8c3
  | 4 => SM8c4
  | 5 => SM8c5
  | 6 => SM8c6
  | 7 => SM8c7
  | 8 => SM8c8
  | 9 => SM8c9
  | _ => 0

def SMVecRow9 (j : Fin 10) : Vec :=
  match j.val with
  | 0 => SM9c0
  | 1 => SM9c1
  | 2 => SM9c2
  | 3 => SM9c3
  | 4 => SM9c4
  | 5 => SM9c5
  | 6 => SM9c6
  | 7 => SM9c7
  | 8 => SM9c8
  | 9 => SM9c9
  | _ => 0

def SMVec : Matrix (Fin 10) (Fin 10) Vec :=
  fun i j => match i.val with
  | 0 => SMVecRow0 j
  | 1 => SMVecRow1 j
  | 2 => SMVecRow2 j
  | 3 => SMVecRow3 j
  | 4 => SMVecRow4 j
  | 5 => SMVecRow5 j
  | 6 => SMVecRow6 j
  | 7 => SMVecRow7 j
  | 8 => SMVecRow8 j
  | 9 => SMVecRow9 j
  | _ => 0

theorem SMVecRow0_of10 (j : Fin 10) :
    of10 (SMVecRow0 j) = SMrow0 j := by
  fin_cases j <;> rfl

theorem SMVecRow1_of10 (j : Fin 10) :
    of10 (SMVecRow1 j) = SMrow1 j := by
  fin_cases j <;> rfl

theorem SMVecRow2_of10 (j : Fin 10) :
    of10 (SMVecRow2 j) = SMrow2 j := by
  fin_cases j <;> rfl

theorem SMVecRow3_of10 (j : Fin 10) :
    of10 (SMVecRow3 j) = SMrow3 j := by
  fin_cases j <;> rfl

theorem SMVecRow4_of10 (j : Fin 10) :
    of10 (SMVecRow4 j) = SMrow4 j := by
  fin_cases j <;> rfl

theorem SMVecRow5_of10 (j : Fin 10) :
    of10 (SMVecRow5 j) = SMrow5 j := by
  fin_cases j <;> rfl

theorem SMVecRow6_of10 (j : Fin 10) :
    of10 (SMVecRow6 j) = SMrow6 j := by
  fin_cases j <;> rfl

theorem SMVecRow7_of10 (j : Fin 10) :
    of10 (SMVecRow7 j) = SMrow7 j := by
  fin_cases j <;> rfl

theorem SMVecRow8_of10 (j : Fin 10) :
    of10 (SMVecRow8 j) = SMrow8 j := by
  fin_cases j <;> rfl

theorem SMVecRow9_of10 (j : Fin 10) :
    of10 (SMVecRow9 j) = SMrow9 j := by
  fin_cases j <;> rfl

theorem SMVec_of10 (i j : Fin 10) :
    of10 (SMVec i j) = SM_poly i j := by
  fin_cases i
  · exact SMVecRow0_of10 j
  · exact SMVecRow1_of10 j
  · exact SMVecRow2_of10 j
  · exact SMVecRow3_of10 j
  · exact SMVecRow4_of10 j
  · exact SMVecRow5_of10 j
  · exact SMVecRow6_of10 j
  · exact SMVecRow7_of10 j
  · exact SMVecRow8_of10 j
  · exact SMVecRow9_of10 j

theorem evalMatrix_SMVec :
    evalMatrix SMVec = evalMatrixK SM_poly := by
  ext i j
  change D12CyclotomicVec.eval (SMVec i j) =
    evalK (SM_poly i j)
  rw [eval_of10, SMVec_of10]

def characterStackVec
    (RM SM : Matrix (Fin 10) (Fin 10) Vec) (r s : ℚ) :
    Matrix (Fin 20) (Fin 10) Vec :=
  fun i j =>
    Fin.addCases
      (fun a : Fin 10 => RM a j - if a = j then constVec r else 0)
      (fun b : Fin 10 => SM b j - if b = j then constVec s else 0)
      (i : Fin (10 + 10))

theorem eval_characterStackVec
    (RM SM : Matrix (Fin 10) (Fin 10) Vec) (r s : ℚ) :
    evalMatrix (characterStackVec RM SM r s) =
      D12PieceAction.characterStack (evalMatrix RM) (evalMatrix SM)
        (algebraMap ℚ WeilRep.K r) (algebraMap ℚ WeilRep.K s) := by
  ext i j
  change D12CyclotomicVec.eval
      (Fin.addCases
        (fun a : Fin 10 => RM a j - if a = j then constVec r else 0)
        (fun b : Fin 10 => SM b j - if b = j then constVec s else 0) i) =
    Fin.addCases
      (fun a : Fin 10 => D12CyclotomicVec.eval (RM a j) -
        if a = j then algebraMap ℚ WeilRep.K r else 0)
      (fun b : Fin 10 => D12CyclotomicVec.eval (SM b j) -
        if b = j then algebraMap ℚ WeilRep.K s else 0) i
  refine Fin.addCases (m := 10) (n := 10)
    (fun a => ?_) (fun b => ?_) (i : Fin (10 + 10))
  · simp only [Fin.addCases_left]
    by_cases h : a = j <;>
      simp [h, D12CyclotomicVec.eval_sub]
  · simp only [Fin.addCases_right]
    by_cases h : b = j <;>
      simp [h, D12CyclotomicVec.eval_sub]

end V14Formalization.D12PieceVecBase
