/-
  D12 polynomial F-row shard — ambient row 3.
  Auto-generated by scripts/export_d12_poly_lean.py — DO NOT HAND-EDIT.
  Schema: v14.fix_ix.d12_poly.v29_F_rows_1_2_3_4
  Payload sha256: 3686e269199b03cdb1b592f55f679497ea6763f75369e7586a4cba5d2f90c61e
  Depends on: D12PolynomialCore + D12PolynomialSM (canonical SM_poly)

  * F*B = B*SM on ambient row 3 (SM source row 3, B-scale 1).
  * Shared SM_poly only — no local SM copy.
  * BSM: collapse sparse B, rw SM_poly_row3, SMrow3_j; never simp [SM_poly].
  * FB: of10 algebra + funext/fin_cases/norm_num on coefficient vectors.
-/
import V14Formalization.D12PolynomialCore
import V14Formalization.D12PolynomialSM
import Mathlib.Tactic.FinCases

noncomputable section

open Polynomial BigOperators Matrix
open V14Formalization.D12PolynomialData

namespace V14Formalization
namespace D12PolynomialData
namespace FRow3

def ambientRow : Nat := 3
def smSourceRow : Nat := 3

/-! ### F row 3 coefficient vectors -/
def F3c0 : Coeff10 := ![0, 0, (-1 / 11 : ℚ), (-1 / 11 : ℚ), 0, 0, 0, 0, (2 / 11 : ℚ), 0]
def F3c1 : Coeff10 := ![0, (-1 / 11 : ℚ), (2 / 11 : ℚ), (-1 / 11 : ℚ), 0, 0, 0, 0, 0, 0]
def F3c2 : Coeff10 := ![(1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (3 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), 0, (1 / 11 : ℚ), (1 / 11 : ℚ)]
def F3c3 : Coeff10 := ![(2 / 11 : ℚ), 0, (-1 / 11 : ℚ), 0, 0, 0, 0, 0, 0, (-1 / 11 : ℚ)]
def F3c4 : Coeff10 := ![0, (-1 / 11 : ℚ), 0, 0, (2 / 11 : ℚ), 0, 0, (-1 / 11 : ℚ), 0, 0]
def F3c5 : Coeff10 := ![(2 / 11 : ℚ), 0, (2 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), (4 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ)]
def F3c6 : Coeff10 := ![0, 0, 0, 0, 0, (-2 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), (-2 / 11 : ℚ), 0]
def F3c7 : Coeff10 := ![(-2 / 11 : ℚ), 0, 0, (2 / 11 : ℚ), (2 / 11 : ℚ), 0, 0, (-2 / 11 : ℚ), 0, 0]
def F3c8 : Coeff10 := ![(2 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), 0, (2 / 11 : ℚ), (4 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ)]
def F3c9 : Coeff10 := ![(2 / 11 : ℚ), (2 / 11 : ℚ), 0, (2 / 11 : ℚ), (2 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ)]
def F3c10 : Coeff10 := ![0, (-2 / 11 : ℚ), (2 / 11 : ℚ), 0, (2 / 11 : ℚ), (-2 / 11 : ℚ), 0, 0, 0, 0]
def F3c11 : Coeff10 := ![(2 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), 0, (2 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ)]
def F3c12 : Coeff10 := ![(2 / 11 : ℚ), 0, (-2 / 11 : ℚ), 0, 0, 0, (-2 / 11 : ℚ), 0, (2 / 11 : ℚ), 0]
def F3c13 : Coeff10 := ![(-2 / 11 : ℚ), (2 / 11 : ℚ), 0, 0, (2 / 11 : ℚ), (-2 / 11 : ℚ), 0, 0, 0, 0]
def F3c14 : Coeff10 := ![0, 0, (-2 / 11 : ℚ), (2 / 11 : ℚ), 0, 0, 0, (2 / 11 : ℚ), (-2 / 11 : ℚ), 0]

def F_poly : Matrix (Fin 15) (Fin 15) PolyQ :=
  Matrix.of fun i j =>
    match i.val, j.val with
    | 3, 0 => of10 F3c0
    | 3, 1 => of10 F3c1
    | 3, 2 => of10 F3c2
    | 3, 3 => of10 F3c3
    | 3, 4 => of10 F3c4
    | 3, 5 => of10 F3c5
    | 3, 6 => of10 F3c6
    | 3, 7 => of10 F3c7
    | 3, 8 => of10 F3c8
    | 3, 9 => of10 F3c9
    | 3, 10 => of10 F3c10
    | 3, 11 => of10 F3c11
    | 3, 12 => of10 F3c12
    | 3, 13 => of10 F3c13
    | 3, 14 => of10 F3c14
    | _, _ => 0

/-! ### F * B = B * SM on ambient row 3 (shared SM_poly) -/

theorem BSM_3_0 :
    (B_poly * SM_poly) (3 : Fin 15) (0 : Fin 10) = of10 SM3c0 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_0

theorem FB_3_0 :
    (F_poly * B_poly) (3 : Fin 15) (0 : Fin 10) = of10 SM3c0 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c0, F3c13, SM3c0]

theorem F_mul_B_eq_B_mul_SM_row3_j0 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (0 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_0, BSM_3_0, sub_self]


theorem BSM_3_1 :
    (B_poly * SM_poly) (3 : Fin 15) (1 : Fin 10) = of10 SM3c1 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_1

theorem FB_3_1 :
    (F_poly * B_poly) (3 : Fin 15) (1 : Fin 10) = of10 SM3c1 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c1, F3c8, SM3c1]

theorem F_mul_B_eq_B_mul_SM_row3_j1 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (1 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_1, BSM_3_1, sub_self]


theorem BSM_3_2 :
    (B_poly * SM_poly) (3 : Fin 15) (2 : Fin 10) = of10 SM3c2 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_2

theorem FB_3_2 :
    (F_poly * B_poly) (3 : Fin 15) (2 : Fin 10) = of10 SM3c2 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c2, F3c10, SM3c2]

theorem F_mul_B_eq_B_mul_SM_row3_j2 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (2 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_2, BSM_3_2, sub_self]


theorem BSM_3_3 :
    (B_poly * SM_poly) (3 : Fin 15) (3 : Fin 10) = of10 SM3c3 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_3

theorem FB_3_3 :
    (F_poly * B_poly) (3 : Fin 15) (3 : Fin 10) = of10 SM3c3 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c3, F3c5, SM3c3]

theorem F_mul_B_eq_B_mul_SM_row3_j3 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (3 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_3, BSM_3_3, sub_self]


theorem BSM_3_4 :
    (B_poly * SM_poly) (3 : Fin 15) (4 : Fin 10) = of10 SM3c4 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_4

theorem FB_3_4 :
    (F_poly * B_poly) (3 : Fin 15) (4 : Fin 10) = of10 SM3c4 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c4, F3c12, SM3c4]

theorem F_mul_B_eq_B_mul_SM_row3_j4 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (4 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_4, BSM_3_4, sub_self]


theorem BSM_3_5 :
    (B_poly * SM_poly) (3 : Fin 15) (5 : Fin 10) = of10 SM3c5 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_5

theorem FB_3_5 :
    (F_poly * B_poly) (3 : Fin 15) (5 : Fin 10) = of10 SM3c5 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c6, SM3c5]

theorem F_mul_B_eq_B_mul_SM_row3_j5 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (5 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_5, BSM_3_5, sub_self]


theorem BSM_3_6 :
    (B_poly * SM_poly) (3 : Fin 15) (6 : Fin 10) = of10 SM3c6 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_6

theorem FB_3_6 :
    (F_poly * B_poly) (3 : Fin 15) (6 : Fin 10) = of10 SM3c6 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c7, SM3c6]

theorem F_mul_B_eq_B_mul_SM_row3_j6 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (6 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_6, BSM_3_6, sub_self]


theorem BSM_3_7 :
    (B_poly * SM_poly) (3 : Fin 15) (7 : Fin 10) = of10 SM3c7 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_7

theorem FB_3_7 :
    (F_poly * B_poly) (3 : Fin 15) (7 : Fin 10) = of10 SM3c7 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c9, SM3c7]

theorem F_mul_B_eq_B_mul_SM_row3_j7 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (7 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_7, BSM_3_7, sub_self]


theorem BSM_3_8 :
    (B_poly * SM_poly) (3 : Fin 15) (8 : Fin 10) = of10 SM3c8 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_8

theorem FB_3_8 :
    (F_poly * B_poly) (3 : Fin 15) (8 : Fin 10) = of10 SM3c8 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c11, SM3c8]

theorem F_mul_B_eq_B_mul_SM_row3_j8 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (8 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_8, BSM_3_8, sub_self]


theorem BSM_3_9 :
    (B_poly * SM_poly) (3 : Fin 15) (9 : Fin 10) = of10 SM3c9 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row3]
  exact SMrow3_9

theorem FB_3_9 :
    (F_poly * B_poly) (3 : Fin 15) (9 : Fin 10) = of10 SM3c9 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F3c14, SM3c9]

theorem F_mul_B_eq_B_mul_SM_row3_j9 :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) (9 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_3_9, BSM_3_9, sub_self]


/-- Pure row dispatcher for ambient F row 3. -/
theorem F_mul_B_eq_B_mul_SM_row3 (j : Fin 10) :
    (F_poly * B_poly - B_poly * SM_poly) (3 : Fin 15) j = (0 : PolyQ) :=
  match j with
  | ⟨0, _⟩ => F_mul_B_eq_B_mul_SM_row3_j0
  | ⟨1, _⟩ => F_mul_B_eq_B_mul_SM_row3_j1
  | ⟨2, _⟩ => F_mul_B_eq_B_mul_SM_row3_j2
  | ⟨3, _⟩ => F_mul_B_eq_B_mul_SM_row3_j3
  | ⟨4, _⟩ => F_mul_B_eq_B_mul_SM_row3_j4
  | ⟨5, _⟩ => F_mul_B_eq_B_mul_SM_row3_j5
  | ⟨6, _⟩ => F_mul_B_eq_B_mul_SM_row3_j6
  | ⟨7, _⟩ => F_mul_B_eq_B_mul_SM_row3_j7
  | ⟨8, _⟩ => F_mul_B_eq_B_mul_SM_row3_j8
  | ⟨9, _⟩ => F_mul_B_eq_B_mul_SM_row3_j9

#print axioms F_mul_B_eq_B_mul_SM_row3
#print axioms F_mul_B_eq_B_mul_SM_row3_j0
#print axioms F_mul_B_eq_B_mul_SM_row3_j5
#print axioms F_mul_B_eq_B_mul_SM_row3_j9

end FRow3
end D12PolynomialData
end V14Formalization
