/-
  D12 polynomial F-row shard — ambient row 7.
  Auto-generated by scripts/export_d12_poly_lean.py — DO NOT HAND-EDIT.
  Schema: v14.fix_ix.d12_poly.v30_F_rows_6_7_8_9
  Payload sha256: ab2ebeee9c88753468b4affacff1cedd1af2f44c0cf2e20a0ec48b3b904fa951
  Depends on: D12PolynomialCore + D12PolynomialSM (canonical SM_poly)

  * F*B = B*SM on ambient row 7 (SM source row 6, B-scale 1).
  * Shared SM_poly only — no local SM copy.
  * BSM: collapse sparse B, rw SM_poly_row6, SMrow6_j; never simp [SM_poly].
  * FB: of10 algebra + funext/fin_cases/norm_num on coefficient vectors.
-/
module

public import V14Formalization.D12PolynomialCore
public import V14Formalization.D12PolynomialSM
public import Mathlib.Tactic.FinCases

noncomputable section

open Polynomial BigOperators Matrix
open V14Formalization.D12PolynomialData

namespace V14Formalization
namespace D12PolynomialData
namespace FRow7

def ambientRow : Nat := 7
def smSourceRow : Nat := 6

/-! ### F row 7 coefficient vectors -/
@[expose] public def F7c0 : Coeff10 := ![0, 0, 0, (1 / 11 : ℚ), (-1 / 11 : ℚ), (-1 / 11 : ℚ), (1 / 11 : ℚ), 0, 0, 0]
@[expose] public def F7c1 : Coeff10 := ![0, (1 / 11 : ℚ), 0, (-1 / 11 : ℚ), 0, (-1 / 11 : ℚ), 0, (1 / 11 : ℚ), 0, 0]
@[expose] public def F7c2 : Coeff10 := ![0, (-1 / 11 : ℚ), 0, 0, (1 / 11 : ℚ), 0, (1 / 11 : ℚ), 0, 0, (-1 / 11 : ℚ)]
@[expose] public def F7c3 : Coeff10 := ![(-1 / 11 : ℚ), 0, 0, 0, (-1 / 11 : ℚ), 0, 0, (1 / 11 : ℚ), (1 / 11 : ℚ), 0]
@[expose] public def F7c4 : Coeff10 := ![0, 0, 0, (-1 / 11 : ℚ), (1 / 11 : ℚ), 0, 0, 0, (1 / 11 : ℚ), (-1 / 11 : ℚ)]
@[expose] public def F7c5 : Coeff10 := ![(1 / 11 : ℚ), 0, 0, 0, (1 / 11 : ℚ), 0, 0, (-1 / 11 : ℚ), (-1 / 11 : ℚ), 0]
@[expose] public def F7c6 : Coeff10 := ![(-2 / 11 : ℚ), (-1 / 11 : ℚ), (-1 / 11 : ℚ), (-3 / 11 : ℚ), (-1 / 11 : ℚ), (-1 / 11 : ℚ), (-2 / 11 : ℚ), 0, 0, 0]
@[expose] public def F7c7 : Coeff10 := ![(1 / 11 : ℚ), 0, (-2 / 11 : ℚ), (-1 / 11 : ℚ), (-1 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-1 / 11 : ℚ), (-1 / 11 : ℚ), (-2 / 11 : ℚ)]
@[expose] public def F7c8 : Coeff10 := ![0, (1 / 11 : ℚ), 0, (-1 / 11 : ℚ), 0, (-1 / 11 : ℚ), 0, (1 / 11 : ℚ), 0, 0]
@[expose] public def F7c9 : Coeff10 := ![(-1 / 11 : ℚ), (-2 / 11 : ℚ), (-1 / 11 : ℚ), (-1 / 11 : ℚ), (-2 / 11 : ℚ), (-1 / 11 : ℚ), 0, (-2 / 11 : ℚ), (1 / 11 : ℚ), (-2 / 11 : ℚ)]
@[expose] public def F7c10 : Coeff10 := ![0, (1 / 11 : ℚ), 0, 0, (-1 / 11 : ℚ), 0, (-1 / 11 : ℚ), 0, 0, (1 / 11 : ℚ)]
@[expose] public def F7c11 : Coeff10 := ![(-1 / 11 : ℚ), 0, (-1 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-1 / 11 : ℚ), 0, (-1 / 11 : ℚ), 0, (-3 / 11 : ℚ)]
@[expose] public def F7c12 : Coeff10 := ![0, 0, 0, (-1 / 11 : ℚ), (1 / 11 : ℚ), 0, 0, 0, (1 / 11 : ℚ), (-1 / 11 : ℚ)]
@[expose] public def F7c13 : Coeff10 := ![0, 0, 0, (-1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (-1 / 11 : ℚ), 0, 0, 0]
@[expose] public def F7c14 : Coeff10 := ![(2 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (2 / 11 : ℚ), 0, 0, (1 / 11 : ℚ), (3 / 11 : ℚ), (1 / 11 : ℚ), 0]

@[expose] public def F_poly : Matrix (Fin 15) (Fin 15) PolyQ :=
  Matrix.of fun i j =>
    match i.val, j.val with
    | 7, 0 => of10 F7c0
    | 7, 1 => of10 F7c1
    | 7, 2 => of10 F7c2
    | 7, 3 => of10 F7c3
    | 7, 4 => of10 F7c4
    | 7, 5 => of10 F7c5
    | 7, 6 => of10 F7c6
    | 7, 7 => of10 F7c7
    | 7, 8 => of10 F7c8
    | 7, 9 => of10 F7c9
    | 7, 10 => of10 F7c10
    | 7, 11 => of10 F7c11
    | 7, 12 => of10 F7c12
    | 7, 13 => of10 F7c13
    | 7, 14 => of10 F7c14
    | _, _ => 0

/-! ### F * B = B * SM on ambient row 7 (shared SM_poly) -/

theorem BSM_7_0 :
    (B_poly * SM_poly) (7 : Fin 15) (0 : Fin 10) = of10 SM6c0 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_0

theorem FB_7_0 :
    (F_poly * B_poly) (7 : Fin 15) (0 : Fin 10) = of10 SM6c0 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c0, F7c13, SM6c0]

theorem F_mul_B_eq_B_mul_SM_row7_j0 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (0 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_0, BSM_7_0, sub_self]


theorem BSM_7_1 :
    (B_poly * SM_poly) (7 : Fin 15) (1 : Fin 10) = of10 SM6c1 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_1

theorem FB_7_1 :
    (F_poly * B_poly) (7 : Fin 15) (1 : Fin 10) = of10 SM6c1 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c1, F7c8, SM6c1]

theorem F_mul_B_eq_B_mul_SM_row7_j1 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (1 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_1, BSM_7_1, sub_self]


theorem BSM_7_2 :
    (B_poly * SM_poly) (7 : Fin 15) (2 : Fin 10) = of10 SM6c2 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_2

theorem FB_7_2 :
    (F_poly * B_poly) (7 : Fin 15) (2 : Fin 10) = of10 SM6c2 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c2, F7c10, SM6c2]

theorem F_mul_B_eq_B_mul_SM_row7_j2 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (2 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_2, BSM_7_2, sub_self]


theorem BSM_7_3 :
    (B_poly * SM_poly) (7 : Fin 15) (3 : Fin 10) = of10 SM6c3 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_3

theorem FB_7_3 :
    (F_poly * B_poly) (7 : Fin 15) (3 : Fin 10) = of10 SM6c3 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c3, F7c5, SM6c3]

theorem F_mul_B_eq_B_mul_SM_row7_j3 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (3 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_3, BSM_7_3, sub_self]


theorem BSM_7_4 :
    (B_poly * SM_poly) (7 : Fin 15) (4 : Fin 10) = of10 SM6c4 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_4

theorem FB_7_4 :
    (F_poly * B_poly) (7 : Fin 15) (4 : Fin 10) = of10 SM6c4 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c4, F7c12, SM6c4]

theorem F_mul_B_eq_B_mul_SM_row7_j4 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (4 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_4, BSM_7_4, sub_self]


theorem BSM_7_5 :
    (B_poly * SM_poly) (7 : Fin 15) (5 : Fin 10) = of10 SM6c5 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_5

theorem FB_7_5 :
    (F_poly * B_poly) (7 : Fin 15) (5 : Fin 10) = of10 SM6c5 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c6, SM6c5]

theorem F_mul_B_eq_B_mul_SM_row7_j5 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (5 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_5, BSM_7_5, sub_self]


theorem BSM_7_6 :
    (B_poly * SM_poly) (7 : Fin 15) (6 : Fin 10) = of10 SM6c6 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_6

theorem FB_7_6 :
    (F_poly * B_poly) (7 : Fin 15) (6 : Fin 10) = of10 SM6c6 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c7, SM6c6]

theorem F_mul_B_eq_B_mul_SM_row7_j6 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (6 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_6, BSM_7_6, sub_self]


theorem BSM_7_7 :
    (B_poly * SM_poly) (7 : Fin 15) (7 : Fin 10) = of10 SM6c7 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_7

theorem FB_7_7 :
    (F_poly * B_poly) (7 : Fin 15) (7 : Fin 10) = of10 SM6c7 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c9, SM6c7]

theorem F_mul_B_eq_B_mul_SM_row7_j7 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (7 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_7, BSM_7_7, sub_self]


theorem BSM_7_8 :
    (B_poly * SM_poly) (7 : Fin 15) (8 : Fin 10) = of10 SM6c8 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_8

theorem FB_7_8 :
    (F_poly * B_poly) (7 : Fin 15) (8 : Fin 10) = of10 SM6c8 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c11, SM6c8]

theorem F_mul_B_eq_B_mul_SM_row7_j8 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (8 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_8, BSM_7_8, sub_self]


theorem BSM_7_9 :
    (B_poly * SM_poly) (7 : Fin 15) (9 : Fin 10) = of10 SM6c9 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row6]
  exact SMrow6_9

theorem FB_7_9 :
    (F_poly * B_poly) (7 : Fin 15) (9 : Fin 10) = of10 SM6c9 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F7c14, SM6c9]

theorem F_mul_B_eq_B_mul_SM_row7_j9 :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) (9 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_7_9, BSM_7_9, sub_self]


/-- Pure row dispatcher for ambient F row 7. -/
public theorem F_mul_B_eq_B_mul_SM_row7 (j : Fin 10) :
    (F_poly * B_poly - B_poly * SM_poly) (7 : Fin 15) j = (0 : PolyQ) :=
  match j with
  | ⟨0, _⟩ => F_mul_B_eq_B_mul_SM_row7_j0
  | ⟨1, _⟩ => F_mul_B_eq_B_mul_SM_row7_j1
  | ⟨2, _⟩ => F_mul_B_eq_B_mul_SM_row7_j2
  | ⟨3, _⟩ => F_mul_B_eq_B_mul_SM_row7_j3
  | ⟨4, _⟩ => F_mul_B_eq_B_mul_SM_row7_j4
  | ⟨5, _⟩ => F_mul_B_eq_B_mul_SM_row7_j5
  | ⟨6, _⟩ => F_mul_B_eq_B_mul_SM_row7_j6
  | ⟨7, _⟩ => F_mul_B_eq_B_mul_SM_row7_j7
  | ⟨8, _⟩ => F_mul_B_eq_B_mul_SM_row7_j8
  | ⟨9, _⟩ => F_mul_B_eq_B_mul_SM_row7_j9

#print axioms F_mul_B_eq_B_mul_SM_row7
#print axioms F_mul_B_eq_B_mul_SM_row7_j0
#print axioms F_mul_B_eq_B_mul_SM_row7_j5
#print axioms F_mul_B_eq_B_mul_SM_row7_j9

end FRow7
end D12PolynomialData
end V14Formalization
