/-
  D12 polynomial F-row shard — ambient row 1.
  Auto-generated by scripts/export_d12_poly_lean.py — DO NOT HAND-EDIT.
  Schema: v14.fix_ix.d12_poly.v29_F_rows_1_2_3_4
  Payload sha256: 3686e269199b03cdb1b592f55f679497ea6763f75369e7586a4cba5d2f90c61e
  Depends on: D12PolynomialCore + D12PolynomialSM (canonical SM_poly)

  * F*B = B*SM on ambient row 1 (SM source row 1, B-scale 1).
  * Shared SM_poly only — no local SM copy.
  * BSM: collapse sparse B, rw SM_poly_row1, SMrow1_j; never simp [SM_poly].
  * FB: of10 algebra + funext/fin_cases/norm_num on coefficient vectors.
-/
module

public import V14Formalization.D12PolynomialCore
public import V14Formalization.D12PolynomialSM
public import Mathlib.Tactic.FinCases

noncomputable section

open Polynomial BigOperators Matrix
open V14Formalization.D12PolynomialData

namespace V14Formalization
namespace D12PolynomialData
namespace FRow1

def ambientRow : Nat := 1
def smSourceRow : Nat := 1

/-! ### F row 1 coefficient vectors -/
@[expose] public def F1c0 : Coeff10 := ![0, 0, 0, (-1 / 11 : ℚ), 0, 0, (2 / 11 : ℚ), 0, 0, (-1 / 11 : ℚ)]
@[expose] public def F1c1 : Coeff10 := ![(2 / 11 : ℚ), 0, 0, 0, 0, (-1 / 11 : ℚ), (-1 / 11 : ℚ), 0, 0, 0]
@[expose] public def F1c2 : Coeff10 := ![(1 / 11 : ℚ), (3 / 11 : ℚ), (1 / 11 : ℚ), 0, (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ)]
@[expose] public def F1c3 : Coeff10 := ![(1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), (1 / 11 : ℚ), 0, (3 / 11 : ℚ)]
@[expose] public def F1c4 : Coeff10 := ![0, 0, (2 / 11 : ℚ), 0, 0, 0, (-1 / 11 : ℚ), 0, 0, (-1 / 11 : ℚ)]
@[expose] public def F1c5 : Coeff10 := ![0, (2 / 11 : ℚ), 0, (-2 / 11 : ℚ), (-2 / 11 : ℚ), 0, (2 / 11 : ℚ), 0, 0, 0]
@[expose] public def F1c6 : Coeff10 := ![0, (-2 / 11 : ℚ), (2 / 11 : ℚ), 0, 0, 0, 0, (2 / 11 : ℚ), (-2 / 11 : ℚ), 0]
@[expose] public def F1c7 : Coeff10 := ![(-2 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), 0, (-2 / 11 : ℚ), (-4 / 11 : ℚ), (-2 / 11 : ℚ), (-4 / 11 : ℚ), (-2 / 11 : ℚ)]
@[expose] public def F1c8 : Coeff10 := ![0, 0, 0, (2 / 11 : ℚ), (-2 / 11 : ℚ), 0, 0, (-2 / 11 : ℚ), (2 / 11 : ℚ), 0]
@[expose] public def F1c9 : Coeff10 := ![(-2 / 11 : ℚ), (-2 / 11 : ℚ), (-4 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-4 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), 0]
@[expose] public def F1c10 : Coeff10 := ![(-2 / 11 : ℚ), 0, (-2 / 11 : ℚ), 0, 0, 0, (2 / 11 : ℚ), (2 / 11 : ℚ), 0, 0]
@[expose] public def F1c11 : Coeff10 := ![0, (-4 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-2 / 11 : ℚ), (-4 / 11 : ℚ)]
@[expose] public def F1c12 : Coeff10 := ![(2 / 11 : ℚ), (-2 / 11 : ℚ), 0, (-2 / 11 : ℚ), (2 / 11 : ℚ), 0, 0, 0, 0, 0]
@[expose] public def F1c13 : Coeff10 := ![(2 / 11 : ℚ), (2 / 11 : ℚ), 0, (2 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ)]
@[expose] public def F1c14 : Coeff10 := ![(2 / 11 : ℚ), (2 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ), (4 / 11 : ℚ), (2 / 11 : ℚ), (2 / 11 : ℚ), 0, (2 / 11 : ℚ), (2 / 11 : ℚ)]

@[expose] public def F_poly : Matrix (Fin 15) (Fin 15) PolyQ :=
  Matrix.of fun i j =>
    match i.val, j.val with
    | 1, 0 => of10 F1c0
    | 1, 1 => of10 F1c1
    | 1, 2 => of10 F1c2
    | 1, 3 => of10 F1c3
    | 1, 4 => of10 F1c4
    | 1, 5 => of10 F1c5
    | 1, 6 => of10 F1c6
    | 1, 7 => of10 F1c7
    | 1, 8 => of10 F1c8
    | 1, 9 => of10 F1c9
    | 1, 10 => of10 F1c10
    | 1, 11 => of10 F1c11
    | 1, 12 => of10 F1c12
    | 1, 13 => of10 F1c13
    | 1, 14 => of10 F1c14
    | _, _ => 0

/-! ### F * B = B * SM on ambient row 1 (shared SM_poly) -/

theorem BSM_1_0 :
    (B_poly * SM_poly) (1 : Fin 15) (0 : Fin 10) = of10 SM1c0 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_0

theorem FB_1_0 :
    (F_poly * B_poly) (1 : Fin 15) (0 : Fin 10) = of10 SM1c0 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c0, F1c13, SM1c0]

theorem F_mul_B_eq_B_mul_SM_row1_j0 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (0 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_0, BSM_1_0, sub_self]


theorem BSM_1_1 :
    (B_poly * SM_poly) (1 : Fin 15) (1 : Fin 10) = of10 SM1c1 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_1

theorem FB_1_1 :
    (F_poly * B_poly) (1 : Fin 15) (1 : Fin 10) = of10 SM1c1 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c1, F1c8, SM1c1]

theorem F_mul_B_eq_B_mul_SM_row1_j1 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (1 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_1, BSM_1_1, sub_self]


theorem BSM_1_2 :
    (B_poly * SM_poly) (1 : Fin 15) (2 : Fin 10) = of10 SM1c2 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_2

theorem FB_1_2 :
    (F_poly * B_poly) (1 : Fin 15) (2 : Fin 10) = of10 SM1c2 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c2, F1c10, SM1c2]

theorem F_mul_B_eq_B_mul_SM_row1_j2 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (2 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_2, BSM_1_2, sub_self]


theorem BSM_1_3 :
    (B_poly * SM_poly) (1 : Fin 15) (3 : Fin 10) = of10 SM1c3 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_3

theorem FB_1_3 :
    (F_poly * B_poly) (1 : Fin 15) (3 : Fin 10) = of10 SM1c3 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c3, F1c5, SM1c3]

theorem F_mul_B_eq_B_mul_SM_row1_j3 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (3 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_3, BSM_1_3, sub_self]


theorem BSM_1_4 :
    (B_poly * SM_poly) (1 : Fin 15) (4 : Fin 10) = of10 SM1c4 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_4

theorem FB_1_4 :
    (F_poly * B_poly) (1 : Fin 15) (4 : Fin 10) = of10 SM1c4 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c4, F1c12, SM1c4]

theorem F_mul_B_eq_B_mul_SM_row1_j4 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (4 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_4, BSM_1_4, sub_self]


theorem BSM_1_5 :
    (B_poly * SM_poly) (1 : Fin 15) (5 : Fin 10) = of10 SM1c5 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_5

theorem FB_1_5 :
    (F_poly * B_poly) (1 : Fin 15) (5 : Fin 10) = of10 SM1c5 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c6, SM1c5]

theorem F_mul_B_eq_B_mul_SM_row1_j5 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (5 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_5, BSM_1_5, sub_self]


theorem BSM_1_6 :
    (B_poly * SM_poly) (1 : Fin 15) (6 : Fin 10) = of10 SM1c6 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_6

theorem FB_1_6 :
    (F_poly * B_poly) (1 : Fin 15) (6 : Fin 10) = of10 SM1c6 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c7, SM1c6]

theorem F_mul_B_eq_B_mul_SM_row1_j6 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (6 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_6, BSM_1_6, sub_self]


theorem BSM_1_7 :
    (B_poly * SM_poly) (1 : Fin 15) (7 : Fin 10) = of10 SM1c7 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_7

theorem FB_1_7 :
    (F_poly * B_poly) (1 : Fin 15) (7 : Fin 10) = of10 SM1c7 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c9, SM1c7]

theorem F_mul_B_eq_B_mul_SM_row1_j7 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (7 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_7, BSM_1_7, sub_self]


theorem BSM_1_8 :
    (B_poly * SM_poly) (1 : Fin 15) (8 : Fin 10) = of10 SM1c8 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_8

theorem FB_1_8 :
    (F_poly * B_poly) (1 : Fin 15) (8 : Fin 10) = of10 SM1c8 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c11, SM1c8]

theorem F_mul_B_eq_B_mul_SM_row1_j8 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (8 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_8, BSM_1_8, sub_self]


theorem BSM_1_9 :
    (B_poly * SM_poly) (1 : Fin 15) (9 : Fin 10) = of10 SM1c9 := by
  simp only [Matrix.mul_apply]
  -- Collapse sparse B only — do not unfold SM_poly.
  simp [Fin.sum_univ_succ, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, one_mul, mul_one]
  -- Single surviving SM entry via row-selection + fixed-column accessor.
  rw [SM_poly_row1]
  exact SMrow1_9

theorem FB_1_9 :
    (F_poly * B_poly) (1 : Fin 15) (9 : Fin 10) = of10 SM1c9 := by
  simp only [Matrix.mul_apply]
  simp [Fin.sum_univ_succ, F_poly, B_poly, Matrix.of_apply,
    mul_zero, zero_mul, add_zero, zero_add, mul_one, one_mul]
  try rw [of10_mul_C, C_mul_of10]
  try simp only [of10_mul_C, C_mul_of10, of10_add, mul_one, one_mul]
  first
  | rfl
  | · apply congrArg of10
      funext t; fin_cases t <;> norm_num [F1c14, SM1c9]

theorem F_mul_B_eq_B_mul_SM_row1_j9 :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) (9 : Fin 10) =
      (0 : PolyQ) := by
  simp only [Matrix.sub_apply, FB_1_9, BSM_1_9, sub_self]


/-- Pure row dispatcher for ambient F row 1. -/
public theorem F_mul_B_eq_B_mul_SM_row1 (j : Fin 10) :
    (F_poly * B_poly - B_poly * SM_poly) (1 : Fin 15) j = (0 : PolyQ) :=
  match j with
  | ⟨0, _⟩ => F_mul_B_eq_B_mul_SM_row1_j0
  | ⟨1, _⟩ => F_mul_B_eq_B_mul_SM_row1_j1
  | ⟨2, _⟩ => F_mul_B_eq_B_mul_SM_row1_j2
  | ⟨3, _⟩ => F_mul_B_eq_B_mul_SM_row1_j3
  | ⟨4, _⟩ => F_mul_B_eq_B_mul_SM_row1_j4
  | ⟨5, _⟩ => F_mul_B_eq_B_mul_SM_row1_j5
  | ⟨6, _⟩ => F_mul_B_eq_B_mul_SM_row1_j6
  | ⟨7, _⟩ => F_mul_B_eq_B_mul_SM_row1_j7
  | ⟨8, _⟩ => F_mul_B_eq_B_mul_SM_row1_j8
  | ⟨9, _⟩ => F_mul_B_eq_B_mul_SM_row1_j9

#print axioms F_mul_B_eq_B_mul_SM_row1
#print axioms F_mul_B_eq_B_mul_SM_row1_j0
#print axioms F_mul_B_eq_B_mul_SM_row1_j5
#print axioms F_mul_B_eq_B_mul_SM_row1_j9

end FRow1
end D12PolynomialData
end V14Formalization
