/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
import V14Formalization.D12SigmaPlusSegreEval
import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def UM_qre_9_11 : Polynomial ℚ := C (1) + C (-1) * X + C ((13 / 22 : ℚ)) * X ^ 2 + C ((-9 / 22 : ℚ)) * X ^ 3 + C ((1 / 2 : ℚ)) * X ^ 5 + C ((-1 / 2 : ℚ)) * X ^ 6 + C ((13 / 22 : ℚ)) * X ^ 7 + C ((-9 / 22 : ℚ)) * X ^ 8
def UM_qim_9_11 : Polynomial ℚ := (0 : Polynomial ℚ)

def UM_pre_9_11_0 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_9_11_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_9_11_0 :
    spanU_entry_9_0 * minorQ_entry_0_11 =
      ofLadj UM_pre_9_11_0 UM_pim_9_11_0 := by
  have hz : spanU_entry_9_0 = 0 := by
    rw [spanU_entry_9_0]; exact ofLadj_zero
  rw [hz, UM_pre_9_11_0, UM_pim_9_11_0]
  simp [ofLadj_zero]

def UM_pre_9_11_1 : Polynomial ℚ := C ((1 / 22 : ℚ)) * X ^ 2 + C ((1 / 11 : ℚ)) * X ^ 3 + C ((-7 / 44 : ℚ)) * X ^ 4 + C ((1 / 11 : ℚ)) * X ^ 5 + C ((-7 / 44 : ℚ)) * X ^ 6 + C ((3 / 22 : ℚ)) * X ^ 7 + C ((2 / 11 : ℚ)) * X ^ 8 + C ((-3 / 44 : ℚ)) * X ^ 9 + C ((2 / 11 : ℚ)) * X ^ 10 + C ((-7 / 22 : ℚ)) * X ^ 11 + C ((2 / 11 : ℚ)) * X ^ 12 + C ((-5 / 44 : ℚ)) * X ^ 13 + C ((1 / 11 : ℚ)) * X ^ 14 + C ((1 / 11 : ℚ)) * X ^ 15 + C ((-7 / 44 : ℚ)) * X ^ 16 + C ((1 / 11 : ℚ)) * X ^ 17 + C ((-9 / 44 : ℚ)) * X ^ 18
def UM_pim_9_11_1 : Polynomial ℚ := C ((7 / 22 : ℚ)) * X ^ 2 + C ((-1 / 11 : ℚ)) * X ^ 4 + C ((-1 / 22 : ℚ)) * X ^ 5 + C ((-1 / 11 : ℚ)) * X ^ 6 + C ((17 / 44 : ℚ)) * X ^ 7 + C ((-5 / 44 : ℚ)) * X ^ 8 + C ((1 / 44 : ℚ)) * X ^ 9 + C ((-5 / 44 : ℚ)) * X ^ 10 + C ((5 / 44 : ℚ)) * X ^ 12 + C ((-15 / 44 : ℚ)) * X ^ 13 + C ((5 / 44 : ℚ)) * X ^ 14 + C ((-3 / 44 : ℚ)) * X ^ 15 + C ((1 / 11 : ℚ)) * X ^ 16 + C ((1 / 22 : ℚ)) * X ^ 17 + C ((-5 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_9_11_1 :
    spanU_re_9_1 * minorQ_re_1_11 - spanU_im_9_1 * minorQ_im_1_11 =
      UM_pre_9_11_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_9_1, spanU_im_9_1, minorQ_re_1_11, minorQ_im_1_11,
    UM_pre_9_11_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_9_11_1 :
    spanU_re_9_1 * minorQ_im_1_11 + spanU_im_9_1 * minorQ_re_1_11 =
      UM_pim_9_11_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_9_1, spanU_im_9_1, minorQ_re_1_11, minorQ_im_1_11,
    UM_pim_9_11_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_9_11_1 :
    spanU_entry_9_1 * minorQ_entry_1_11 =
      ofLadj UM_pre_9_11_1 UM_pim_9_11_1 := by
  rw [spanU_entry_9_1, minorQ_entry_1_11, ofLadj_mul,
    UM_pre_eq_9_11_1, UM_pim_eq_9_11_1]

def UM_pre_9_11_2 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_9_11_2 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_9_11_2 :
    spanU_entry_9_2 * minorQ_entry_2_11 =
      ofLadj UM_pre_9_11_2 UM_pim_9_11_2 := by
  have hz : spanU_entry_9_2 = 0 := by
    rw [spanU_entry_9_2]; exact ofLadj_zero
  rw [hz, UM_pre_9_11_2, UM_pim_9_11_2]
  simp [ofLadj_zero]

def UM_pre_9_11_3 : Polynomial ℚ := C ((1 / 22 : ℚ)) * X ^ 2 + C ((1 / 11 : ℚ)) * X ^ 3 + C ((-7 / 44 : ℚ)) * X ^ 4 + C ((1 / 11 : ℚ)) * X ^ 5 + C ((-7 / 44 : ℚ)) * X ^ 6 + C ((3 / 22 : ℚ)) * X ^ 7 + C ((2 / 11 : ℚ)) * X ^ 8 + C ((-3 / 44 : ℚ)) * X ^ 9 + C ((2 / 11 : ℚ)) * X ^ 10 + C ((-7 / 22 : ℚ)) * X ^ 11 + C ((2 / 11 : ℚ)) * X ^ 12 + C ((-5 / 44 : ℚ)) * X ^ 13 + C ((1 / 11 : ℚ)) * X ^ 14 + C ((1 / 11 : ℚ)) * X ^ 15 + C ((-7 / 44 : ℚ)) * X ^ 16 + C ((1 / 11 : ℚ)) * X ^ 17 + C ((-9 / 44 : ℚ)) * X ^ 18
def UM_pim_9_11_3 : Polynomial ℚ := C ((-7 / 22 : ℚ)) * X ^ 2 + C ((1 / 11 : ℚ)) * X ^ 4 + C ((1 / 22 : ℚ)) * X ^ 5 + C ((1 / 11 : ℚ)) * X ^ 6 + C ((-17 / 44 : ℚ)) * X ^ 7 + C ((5 / 44 : ℚ)) * X ^ 8 + C ((-1 / 44 : ℚ)) * X ^ 9 + C ((5 / 44 : ℚ)) * X ^ 10 + C ((-5 / 44 : ℚ)) * X ^ 12 + C ((15 / 44 : ℚ)) * X ^ 13 + C ((-5 / 44 : ℚ)) * X ^ 14 + C ((3 / 44 : ℚ)) * X ^ 15 + C ((-1 / 11 : ℚ)) * X ^ 16 + C ((-1 / 22 : ℚ)) * X ^ 17 + C ((5 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_9_11_3 :
    spanU_re_9_3 * minorQ_re_3_11 - spanU_im_9_3 * minorQ_im_3_11 =
      UM_pre_9_11_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_9_3, spanU_im_9_3, minorQ_re_3_11, minorQ_im_3_11,
    UM_pre_9_11_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_9_11_3 :
    spanU_re_9_3 * minorQ_im_3_11 + spanU_im_9_3 * minorQ_re_3_11 =
      UM_pim_9_11_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_9_3, spanU_im_9_3, minorQ_re_3_11, minorQ_im_3_11,
    UM_pim_9_11_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_9_11_3 :
    spanU_entry_9_3 * minorQ_entry_3_11 =
      ofLadj UM_pre_9_11_3 UM_pim_9_11_3 := by
  rw [spanU_entry_9_3, minorQ_entry_3_11, ofLadj_mul,
    UM_pre_eq_9_11_3, UM_pim_eq_9_11_3]

def UM_pre_9_11_4 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_9_11_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_9_11_4 :
    spanU_entry_9_4 * minorQ_entry_4_11 =
      ofLadj UM_pre_9_11_4 UM_pim_9_11_4 := by
  have hz : spanU_entry_9_4 = 0 := by
    rw [spanU_entry_9_4]; exact ofLadj_zero
  rw [hz, UM_pre_9_11_4, UM_pim_9_11_4]
  simp [ofLadj_zero]

def UM_pre_9_11_5 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_9_11_5 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_9_11_5 :
    spanU_entry_9_5 * minorQ_entry_5_11 =
      ofLadj UM_pre_9_11_5 UM_pim_9_11_5 := by
  have hz : spanU_entry_9_5 = 0 := by
    rw [spanU_entry_9_5]; exact ofLadj_zero
  rw [hz, UM_pre_9_11_5, UM_pim_9_11_5]
  simp [ofLadj_zero]

def UM_pre_9_11_6 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_9_11_6 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_9_11_6 :
    spanU_entry_9_6 * minorQ_entry_6_11 =
      ofLadj UM_pre_9_11_6 UM_pim_9_11_6 := by
  have hz : spanU_entry_9_6 = 0 := by
    rw [spanU_entry_9_6]; exact ofLadj_zero
  rw [hz, UM_pre_9_11_6, UM_pim_9_11_6]
  simp [ofLadj_zero]

def UM_pre_9_11_7 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_9_11_7 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_9_11_7 :
    spanU_entry_9_7 * minorQ_entry_7_11 =
      ofLadj UM_pre_9_11_7 UM_pim_9_11_7 := by
  have hz : spanU_entry_9_7 = 0 := by
    rw [spanU_entry_9_7]; exact ofLadj_zero
  rw [hz, UM_pre_9_11_7, UM_pim_9_11_7]
  simp [ofLadj_zero]

def UM_pre_9_11_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_9_11_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_9_11_8 :
    spanU_entry_9_8 * minorQ_entry_8_11 =
      ofLadj UM_pre_9_11_8 UM_pim_9_11_8 := by
  have hz : spanU_entry_9_8 = 0 := by
    rw [spanU_entry_9_8]; exact ofLadj_zero
  rw [hz, UM_pre_9_11_8, UM_pim_9_11_8]
  simp [ofLadj_zero]

theorem UM_sum_poly_re_9_11 :
    UM_pre_9_11_0 + UM_pre_9_11_1 + UM_pre_9_11_2 + UM_pre_9_11_3 + UM_pre_9_11_4 + UM_pre_9_11_5 + UM_pre_9_11_6 + UM_pre_9_11_7 + UM_pre_9_11_8 = Qplus_re_9_11 + Phi11 * UM_qre_9_11 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pre_9_11_0, UM_pre_9_11_1, UM_pre_9_11_2, UM_pre_9_11_3, UM_pre_9_11_4, UM_pre_9_11_5, UM_pre_9_11_6, UM_pre_9_11_7, UM_pre_9_11_8, Qplus_re_9_11, UM_qre_9_11]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_poly_im_9_11 :
    UM_pim_9_11_0 + UM_pim_9_11_1 + UM_pim_9_11_2 + UM_pim_9_11_3 + UM_pim_9_11_4 + UM_pim_9_11_5 + UM_pim_9_11_6 + UM_pim_9_11_7 + UM_pim_9_11_8 = Qplus_im_9_11 + Phi11 * UM_qim_9_11 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pim_9_11_0, UM_pim_9_11_1, UM_pim_9_11_2, UM_pim_9_11_3, UM_pim_9_11_4, UM_pim_9_11_5, UM_pim_9_11_6, UM_pim_9_11_7, UM_pim_9_11_8, Qplus_im_9_11, UM_qim_9_11]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_entries_9_11 :
    spanU_entry_9_0 * minorQ_entry_0_11 + spanU_entry_9_1 * minorQ_entry_1_11 + spanU_entry_9_2 * minorQ_entry_2_11 + spanU_entry_9_3 * minorQ_entry_3_11 + spanU_entry_9_4 * minorQ_entry_4_11 + spanU_entry_9_5 * minorQ_entry_5_11 + spanU_entry_9_6 * minorQ_entry_6_11 + spanU_entry_9_7 * minorQ_entry_7_11 + spanU_entry_9_8 * minorQ_entry_8_11 =
      ofLadj (UM_pre_9_11_0 + UM_pre_9_11_1 + UM_pre_9_11_2 + UM_pre_9_11_3 + UM_pre_9_11_4 + UM_pre_9_11_5 + UM_pre_9_11_6 + UM_pre_9_11_7 + UM_pre_9_11_8) (UM_pim_9_11_0 + UM_pim_9_11_1 + UM_pim_9_11_2 + UM_pim_9_11_3 + UM_pim_9_11_4 + UM_pim_9_11_5 + UM_pim_9_11_6 + UM_pim_9_11_7 + UM_pim_9_11_8) := by
  simp only [UM_term_9_11_0, UM_term_9_11_1, UM_term_9_11_2, UM_term_9_11_3, UM_term_9_11_4, UM_term_9_11_5, UM_term_9_11_6, UM_term_9_11_7, UM_term_9_11_8]
  simpa [add_assoc] using ofLadj_add9 UM_pre_9_11_0 UM_pim_9_11_0 UM_pre_9_11_1 UM_pim_9_11_1 UM_pre_9_11_2 UM_pim_9_11_2 UM_pre_9_11_3 UM_pim_9_11_3 UM_pre_9_11_4 UM_pim_9_11_4 UM_pre_9_11_5 UM_pim_9_11_5 UM_pre_9_11_6 UM_pim_9_11_6 UM_pre_9_11_7 UM_pim_9_11_7 UM_pre_9_11_8 UM_pim_9_11_8

theorem UM_eval_9_11 :
    ofLadj (UM_pre_9_11_0 + UM_pre_9_11_1 + UM_pre_9_11_2 + UM_pre_9_11_3 + UM_pre_9_11_4 + UM_pre_9_11_5 + UM_pre_9_11_6 + UM_pre_9_11_7 + UM_pre_9_11_8) (UM_pim_9_11_0 + UM_pim_9_11_1 + UM_pim_9_11_2 + UM_pim_9_11_3 + UM_pim_9_11_4 + UM_pim_9_11_5 + UM_pim_9_11_6 + UM_pim_9_11_7 + UM_pim_9_11_8) = Qplus_entry_9_11 := by
  rw [UM_sum_poly_re_9_11, UM_sum_poly_im_9_11,
    ofLadj_add_Phi11, Qplus_entry_9_11]

theorem UM_entry_9_11 : (spanU * minorQ) 9 11 = Qplus 9 11 := by
  rw [Matrix.mul_apply]
  rw [sum_fin9]
  change spanU_entry_9_0 * minorQ_entry_0_11 + spanU_entry_9_1 * minorQ_entry_1_11 + spanU_entry_9_2 * minorQ_entry_2_11 + spanU_entry_9_3 * minorQ_entry_3_11 + spanU_entry_9_4 * minorQ_entry_4_11 + spanU_entry_9_5 * minorQ_entry_5_11 + spanU_entry_9_6 * minorQ_entry_6_11 + spanU_entry_9_7 * minorQ_entry_7_11 + spanU_entry_9_8 * minorQ_entry_8_11 = Qplus_entry_9_11
  exact (UM_sum_entries_9_11).trans UM_eval_9_11

end V14Formalization.D12SigmaPlusSegreCore
