/-
Apply lemmas for Bplus_poly.
-/
module

public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_0
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_1
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_2
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_3
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_4
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_5
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_6
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_7
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_8
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_9
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_10
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_11
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_12
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_13
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_14
