/-
Auto-generated by scripts/export_sigma_plus_identities.py.
Stock-limit, kernel-checkable plus Segre entry identities.
-/
import V14Formalization.D12SigmaPlusSegreEval
import V14Formalization.D12SigmaPlusSegreApplyL
import V14Formalization.D12SigmaPlusSegreApplyK

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def LK_qre_1_1 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_qim_1_1 : Polynomial ℚ := (0 : Polynomial ℚ)

def LK_pre_1_1_0 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_pim_1_1_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem LK_pre_eq_1_1_0 :
    L_re_1_0 * K_re_0_1 - L_im_1_0 * K_im_0_1 =
      LK_pre_1_1_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_0, L_im_1_0, K_re_0_1, K_im_0_1,
    LK_pre_1_1_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_pim_eq_1_1_0 :
    L_re_1_0 * K_im_0_1 + L_im_1_0 * K_re_0_1 =
      LK_pim_1_1_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_0, L_im_1_0, K_re_0_1, K_im_0_1,
    LK_pim_1_1_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_term_1_1_0 :
    L_entry_1_0 * K_entry_0_1 =
      ofLadj LK_pre_1_1_0 LK_pim_1_1_0 := by
  rw [L_entry_1_0, K_entry_0_1, ofLadj_mul,
    LK_pre_eq_1_1_0, LK_pim_eq_1_1_0]

def LK_pre_1_1_1 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_pim_1_1_1 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem LK_pre_eq_1_1_1 :
    L_re_1_1 * K_re_1_1 - L_im_1_1 * K_im_1_1 =
      LK_pre_1_1_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_1, L_im_1_1, K_re_1_1, K_im_1_1,
    LK_pre_1_1_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_pim_eq_1_1_1 :
    L_re_1_1 * K_im_1_1 + L_im_1_1 * K_re_1_1 =
      LK_pim_1_1_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_1, L_im_1_1, K_re_1_1, K_im_1_1,
    LK_pim_1_1_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_term_1_1_1 :
    L_entry_1_1 * K_entry_1_1 =
      ofLadj LK_pre_1_1_1 LK_pim_1_1_1 := by
  rw [L_entry_1_1, K_entry_1_1, ofLadj_mul,
    LK_pre_eq_1_1_1, LK_pim_eq_1_1_1]

def LK_pre_1_1_2 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_pim_1_1_2 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem LK_pre_eq_1_1_2 :
    L_re_1_2 * K_re_2_1 - L_im_1_2 * K_im_2_1 =
      LK_pre_1_1_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_2, L_im_1_2, K_re_2_1, K_im_2_1,
    LK_pre_1_1_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_pim_eq_1_1_2 :
    L_re_1_2 * K_im_2_1 + L_im_1_2 * K_re_2_1 =
      LK_pim_1_1_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_2, L_im_1_2, K_re_2_1, K_im_2_1,
    LK_pim_1_1_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_term_1_1_2 :
    L_entry_1_2 * K_entry_2_1 =
      ofLadj LK_pre_1_1_2 LK_pim_1_1_2 := by
  rw [L_entry_1_2, K_entry_2_1, ofLadj_mul,
    LK_pre_eq_1_1_2, LK_pim_eq_1_1_2]

def LK_pre_1_1_3 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_pim_1_1_3 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem LK_pre_eq_1_1_3 :
    L_re_1_3 * K_re_3_1 - L_im_1_3 * K_im_3_1 =
      LK_pre_1_1_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_3, L_im_1_3, K_re_3_1, K_im_3_1,
    LK_pre_1_1_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_pim_eq_1_1_3 :
    L_re_1_3 * K_im_3_1 + L_im_1_3 * K_re_3_1 =
      LK_pim_1_1_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_3, L_im_1_3, K_re_3_1, K_im_3_1,
    LK_pim_1_1_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_term_1_1_3 :
    L_entry_1_3 * K_entry_3_1 =
      ofLadj LK_pre_1_1_3 LK_pim_1_1_3 := by
  rw [L_entry_1_3, K_entry_3_1, ofLadj_mul,
    LK_pre_eq_1_1_3, LK_pim_eq_1_1_3]

def LK_pre_1_1_4 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_pim_1_1_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem LK_pre_eq_1_1_4 :
    L_re_1_4 * K_re_4_1 - L_im_1_4 * K_im_4_1 =
      LK_pre_1_1_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_4, L_im_1_4, K_re_4_1, K_im_4_1,
    LK_pre_1_1_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_pim_eq_1_1_4 :
    L_re_1_4 * K_im_4_1 + L_im_1_4 * K_re_4_1 =
      LK_pim_1_1_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_4, L_im_1_4, K_re_4_1, K_im_4_1,
    LK_pim_1_1_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_term_1_1_4 :
    L_entry_1_4 * K_entry_4_1 =
      ofLadj LK_pre_1_1_4 LK_pim_1_1_4 := by
  rw [L_entry_1_4, K_entry_4_1, ofLadj_mul,
    LK_pre_eq_1_1_4, LK_pim_eq_1_1_4]

def LK_pre_1_1_5 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_pim_1_1_5 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem LK_pre_eq_1_1_5 :
    L_re_1_5 * K_re_5_1 - L_im_1_5 * K_im_5_1 =
      LK_pre_1_1_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_5, L_im_1_5, K_re_5_1, K_im_5_1,
    LK_pre_1_1_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_pim_eq_1_1_5 :
    L_re_1_5 * K_im_5_1 + L_im_1_5 * K_re_5_1 =
      LK_pim_1_1_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_5, L_im_1_5, K_re_5_1, K_im_5_1,
    LK_pim_1_1_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_term_1_1_5 :
    L_entry_1_5 * K_entry_5_1 =
      ofLadj LK_pre_1_1_5 LK_pim_1_1_5 := by
  rw [L_entry_1_5, K_entry_5_1, ofLadj_mul,
    LK_pre_eq_1_1_5, LK_pim_eq_1_1_5]

def LK_pre_1_1_6 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_pim_1_1_6 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem LK_pre_eq_1_1_6 :
    L_re_1_6 * K_re_6_1 - L_im_1_6 * K_im_6_1 =
      LK_pre_1_1_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_6, L_im_1_6, K_re_6_1, K_im_6_1,
    LK_pre_1_1_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_pim_eq_1_1_6 :
    L_re_1_6 * K_im_6_1 + L_im_1_6 * K_re_6_1 =
      LK_pim_1_1_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_6, L_im_1_6, K_re_6_1, K_im_6_1,
    LK_pim_1_1_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_term_1_1_6 :
    L_entry_1_6 * K_entry_6_1 =
      ofLadj LK_pre_1_1_6 LK_pim_1_1_6 := by
  rw [L_entry_1_6, K_entry_6_1, ofLadj_mul,
    LK_pre_eq_1_1_6, LK_pim_eq_1_1_6]

def LK_pre_1_1_7 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_pim_1_1_7 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem LK_pre_eq_1_1_7 :
    L_re_1_7 * K_re_7_1 - L_im_1_7 * K_im_7_1 =
      LK_pre_1_1_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_7, L_im_1_7, K_re_7_1, K_im_7_1,
    LK_pre_1_1_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_pim_eq_1_1_7 :
    L_re_1_7 * K_im_7_1 + L_im_1_7 * K_re_7_1 =
      LK_pim_1_1_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_7, L_im_1_7, K_re_7_1, K_im_7_1,
    LK_pim_1_1_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_term_1_1_7 :
    L_entry_1_7 * K_entry_7_1 =
      ofLadj LK_pre_1_1_7 LK_pim_1_1_7 := by
  rw [L_entry_1_7, K_entry_7_1, ofLadj_mul,
    LK_pre_eq_1_1_7, LK_pim_eq_1_1_7]

def LK_pre_1_1_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def LK_pim_1_1_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem LK_pre_eq_1_1_8 :
    L_re_1_8 * K_re_8_1 - L_im_1_8 * K_im_8_1 =
      LK_pre_1_1_8 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_8, L_im_1_8, K_re_8_1, K_im_8_1,
    LK_pre_1_1_8]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_pim_eq_1_1_8 :
    L_re_1_8 * K_im_8_1 + L_im_1_8 * K_re_8_1 =
      LK_pim_1_1_8 := by
  refine Polynomial.funext fun r => ?_
  simp only [L_re_1_8, L_im_1_8, K_re_8_1, K_im_8_1,
    LK_pim_1_1_8]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem LK_term_1_1_8 :
    L_entry_1_8 * K_entry_8_1 =
      ofLadj LK_pre_1_1_8 LK_pim_1_1_8 := by
  rw [L_entry_1_8, K_entry_8_1, ofLadj_mul,
    LK_pre_eq_1_1_8, LK_pim_eq_1_1_8]

theorem LK_sum_poly_re_1_1 :
    LK_pre_1_1_0 + LK_pre_1_1_1 + LK_pre_1_1_2 + LK_pre_1_1_3 + LK_pre_1_1_4 + LK_pre_1_1_5 + LK_pre_1_1_6 + LK_pre_1_1_7 + LK_pre_1_1_8 = (0 : Polynomial ℚ) + Phi11 * LK_qre_1_1 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [LK_pre_1_1_0, LK_pre_1_1_1, LK_pre_1_1_2, LK_pre_1_1_3, LK_pre_1_1_4, LK_pre_1_1_5, LK_pre_1_1_6, LK_pre_1_1_7, LK_pre_1_1_8, LK_qre_1_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem LK_sum_poly_im_1_1 :
    LK_pim_1_1_0 + LK_pim_1_1_1 + LK_pim_1_1_2 + LK_pim_1_1_3 + LK_pim_1_1_4 + LK_pim_1_1_5 + LK_pim_1_1_6 + LK_pim_1_1_7 + LK_pim_1_1_8 = (0 : Polynomial ℚ) + Phi11 * LK_qim_1_1 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [LK_pim_1_1_0, LK_pim_1_1_1, LK_pim_1_1_2, LK_pim_1_1_3, LK_pim_1_1_4, LK_pim_1_1_5, LK_pim_1_1_6, LK_pim_1_1_7, LK_pim_1_1_8, LK_qim_1_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem LK_sum_entries_1_1 :
    L_entry_1_0 * K_entry_0_1 + L_entry_1_1 * K_entry_1_1 + L_entry_1_2 * K_entry_2_1 + L_entry_1_3 * K_entry_3_1 + L_entry_1_4 * K_entry_4_1 + L_entry_1_5 * K_entry_5_1 + L_entry_1_6 * K_entry_6_1 + L_entry_1_7 * K_entry_7_1 + L_entry_1_8 * K_entry_8_1 =
      ofLadj (LK_pre_1_1_0 + LK_pre_1_1_1 + LK_pre_1_1_2 + LK_pre_1_1_3 + LK_pre_1_1_4 + LK_pre_1_1_5 + LK_pre_1_1_6 + LK_pre_1_1_7 + LK_pre_1_1_8) (LK_pim_1_1_0 + LK_pim_1_1_1 + LK_pim_1_1_2 + LK_pim_1_1_3 + LK_pim_1_1_4 + LK_pim_1_1_5 + LK_pim_1_1_6 + LK_pim_1_1_7 + LK_pim_1_1_8) := by
  simp only [LK_term_1_1_0, LK_term_1_1_1, LK_term_1_1_2, LK_term_1_1_3, LK_term_1_1_4, LK_term_1_1_5, LK_term_1_1_6, LK_term_1_1_7, LK_term_1_1_8]
  simpa [add_assoc] using ofLadj_add9 LK_pre_1_1_0 LK_pim_1_1_0 LK_pre_1_1_1 LK_pim_1_1_1 LK_pre_1_1_2 LK_pim_1_1_2 LK_pre_1_1_3 LK_pim_1_1_3 LK_pre_1_1_4 LK_pim_1_1_4 LK_pre_1_1_5 LK_pim_1_1_5 LK_pre_1_1_6 LK_pim_1_1_6 LK_pre_1_1_7 LK_pim_1_1_7 LK_pre_1_1_8 LK_pim_1_1_8

theorem LK_eval_1_1 :
    ofLadj (LK_pre_1_1_0 + LK_pre_1_1_1 + LK_pre_1_1_2 + LK_pre_1_1_3 + LK_pre_1_1_4 + LK_pre_1_1_5 + LK_pre_1_1_6 + LK_pre_1_1_7 + LK_pre_1_1_8) (LK_pim_1_1_0 + LK_pim_1_1_1 + LK_pim_1_1_2 + LK_pim_1_1_3 + LK_pim_1_1_4 + LK_pim_1_1_5 + LK_pim_1_1_6 + LK_pim_1_1_7 + LK_pim_1_1_8) = 0 := by
  rw [LK_sum_poly_re_1_1, LK_sum_poly_im_1_1, ofLadj_add_Phi11]
  exact ofLadj_zero

theorem LK_entry_1_1 : (L * K) 1 1 = 0 := by
  rw [mul_apply_fin9_LK]
  rw [L_apply_1_0, K_apply_0_1]
  rw [L_apply_1_1, K_apply_1_1]
  rw [L_apply_1_2, K_apply_2_1]
  rw [L_apply_1_3, K_apply_3_1]
  rw [L_apply_1_4, K_apply_4_1]
  rw [L_apply_1_5, K_apply_5_1]
  rw [L_apply_1_6, K_apply_6_1]
  rw [L_apply_1_7, K_apply_7_1]
  rw [L_apply_1_8, K_apply_8_1]
  exact (LK_sum_entries_1_1).trans LK_eval_1_1

end V14Formalization.D12SigmaPlusSegreCore
