/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
import V14Formalization.D12SigmaPlusSegreEval
import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def VQ_qre_0_11 : Polynomial ℚ := C (22) + C (-22) * X + C (-6) * X ^ 2 + C (-40) * X ^ 3 + C (-54) * X ^ 4 + C (-26) * X ^ 5 + C (-46) * X ^ 6 + C (-32) * X ^ 7 + C (-14) * X ^ 8
def VQ_qim_0_11 : Polynomial ℚ := (0 : Polynomial ℚ)

def VQ_pre_0_11_0 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_0 :
    spanV_entry_0_0 * Qplus_entry_0_11 =
      ofLadj VQ_pre_0_11_0 VQ_pim_0_11_0 := by
  have hz : Qplus_entry_0_11 = 0 := by
    rw [Qplus_entry_0_11]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_0, VQ_pim_0_11_0]
  simp [ofLadj_zero]

def VQ_pre_0_11_1 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_1 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_1 :
    spanV_entry_0_1 * Qplus_entry_1_11 =
      ofLadj VQ_pre_0_11_1 VQ_pim_0_11_1 := by
  have hz : Qplus_entry_1_11 = 0 := by
    rw [Qplus_entry_1_11]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_1, VQ_pim_0_11_1]
  simp [ofLadj_zero]

def VQ_pre_0_11_2 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_2 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_2 :
    spanV_entry_0_2 * Qplus_entry_2_11 =
      ofLadj VQ_pre_0_11_2 VQ_pim_0_11_2 := by
  have hz : Qplus_entry_2_11 = 0 := by
    rw [Qplus_entry_2_11]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_2, VQ_pim_0_11_2]
  simp [ofLadj_zero]

def VQ_pre_0_11_3 : Polynomial ℚ := C (10) * X ^ 3 + C (-2) * X ^ 5 + C (-28) * X ^ 6 + C (-34) * X ^ 7 + C (-30) * X ^ 8 + C (-40) * X ^ 9 + C (-36) * X ^ 10 + C (-56) * X ^ 11 + C (-36) * X ^ 12 + C (-40) * X ^ 13 + C (-40) * X ^ 14 + C (-34) * X ^ 15 + C (-28) * X ^ 16 + C (-2) * X ^ 17
def VQ_pim_0_11_3 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_pre_eq_0_11_3 :
    spanV_re_0_3 * Qplus_re_3_11 - spanV_im_0_3 * Qplus_im_3_11 =
      VQ_pre_0_11_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_3, spanV_im_0_3, Qplus_re_3_11, Qplus_im_3_11,
    VQ_pre_0_11_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_0_11_3 :
    spanV_re_0_3 * Qplus_im_3_11 + spanV_im_0_3 * Qplus_re_3_11 =
      VQ_pim_0_11_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_3, spanV_im_0_3, Qplus_re_3_11, Qplus_im_3_11,
    VQ_pim_0_11_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_0_11_3 :
    spanV_entry_0_3 * Qplus_entry_3_11 =
      ofLadj VQ_pre_0_11_3 VQ_pim_0_11_3 := by
  rw [spanV_entry_0_3, Qplus_entry_3_11, ofLadj_mul,
    VQ_pre_eq_0_11_3, VQ_pim_eq_0_11_3]

def VQ_pre_0_11_4 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_4 :
    spanV_entry_0_4 * Qplus_entry_4_11 =
      ofLadj VQ_pre_0_11_4 VQ_pim_0_11_4 := by
  have hz : Qplus_entry_4_11 = 0 := by
    rw [Qplus_entry_4_11]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_4, VQ_pim_0_11_4]
  simp [ofLadj_zero]

def VQ_pre_0_11_5 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_5 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_5 :
    spanV_entry_0_5 * Qplus_entry_5_11 =
      ofLadj VQ_pre_0_11_5 VQ_pim_0_11_5 := by
  have hz : Qplus_entry_5_11 = 0 := by
    rw [Qplus_entry_5_11]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_5, VQ_pim_0_11_5]
  simp [ofLadj_zero]

def VQ_pre_0_11_6 : Polynomial ℚ := C (-2) + C (14) * X ^ 2 + C (36) * X ^ 3 + C (54) * X ^ 4 + C (62) * X ^ 5 + C (62) * X ^ 6 + C (54) * X ^ 7 + C (36) * X ^ 8 + C (14) * X ^ 9
def VQ_pim_0_11_6 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_pre_eq_0_11_6 :
    spanV_re_0_6 * Qplus_re_6_11 - spanV_im_0_6 * Qplus_im_6_11 =
      VQ_pre_0_11_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_6, spanV_im_0_6, Qplus_re_6_11, Qplus_im_6_11,
    VQ_pre_0_11_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_0_11_6 :
    spanV_re_0_6 * Qplus_im_6_11 + spanV_im_0_6 * Qplus_re_6_11 =
      VQ_pim_0_11_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_6, spanV_im_0_6, Qplus_re_6_11, Qplus_im_6_11,
    VQ_pim_0_11_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_0_11_6 :
    spanV_entry_0_6 * Qplus_entry_6_11 =
      ofLadj VQ_pre_0_11_6 VQ_pim_0_11_6 := by
  rw [spanV_entry_0_6, Qplus_entry_6_11, ofLadj_mul,
    VQ_pre_eq_0_11_6, VQ_pim_eq_0_11_6]

def VQ_pre_0_11_7 : Polynomial ℚ := C (40) + C (-4) * X ^ 2 + C (-96) * X ^ 3 + C (-144) * X ^ 4 + C (-192) * X ^ 5 + C (-210) * X ^ 6 + C (-226) * X ^ 7 + C (-238) * X ^ 8 + C (-184) * X ^ 9 + C (-196) * X ^ 10 + C (-188) * X ^ 11 + C (-196) * X ^ 12 + C (-180) * X ^ 13 + C (-142) * X ^ 14 + C (-94) * X ^ 15 + C (-66) * X ^ 16 + C (-48) * X ^ 17 + C (-12) * X ^ 18
def VQ_pim_0_11_7 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_pre_eq_0_11_7 :
    spanV_re_0_7 * Qplus_re_7_11 - spanV_im_0_7 * Qplus_im_7_11 =
      VQ_pre_0_11_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_7, spanV_im_0_7, Qplus_re_7_11, Qplus_im_7_11,
    VQ_pre_0_11_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_0_11_7 :
    spanV_re_0_7 * Qplus_im_7_11 + spanV_im_0_7 * Qplus_re_7_11 =
      VQ_pim_0_11_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_7, spanV_im_0_7, Qplus_re_7_11, Qplus_im_7_11,
    VQ_pim_0_11_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_0_11_7 :
    spanV_entry_0_7 * Qplus_entry_7_11 =
      ofLadj VQ_pre_0_11_7 VQ_pim_0_11_7 := by
  rw [spanV_entry_0_7, Qplus_entry_7_11, ofLadj_mul,
    VQ_pre_eq_0_11_7, VQ_pim_eq_0_11_7]

def VQ_pre_0_11_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_8 :
    spanV_entry_0_8 * Qplus_entry_8_11 =
      ofLadj VQ_pre_0_11_8 VQ_pim_0_11_8 := by
  have hz : spanV_entry_0_8 = 0 := by
    rw [spanV_entry_0_8]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_8, VQ_pim_0_11_8]
  simp [ofLadj_zero]

def VQ_pre_0_11_9 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_9 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_9 :
    spanV_entry_0_9 * Qplus_entry_9_11 =
      ofLadj VQ_pre_0_11_9 VQ_pim_0_11_9 := by
  have hz : spanV_entry_0_9 = 0 := by
    rw [spanV_entry_0_9]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_9, VQ_pim_0_11_9]
  simp [ofLadj_zero]

def VQ_pre_0_11_10 : Polynomial ℚ := C (-2) + C (-4) * X ^ 2 + C (4) * X ^ 3 + C (10) * X ^ 5 + C (8) * X ^ 6 + C (12) * X ^ 7 + C (14) * X ^ 8 + C (4) * X ^ 9 + C (14) * X ^ 10 + C (4) * X ^ 11 + C (14) * X ^ 12 + C (8) * X ^ 13 + C (10) * X ^ 14 + C (10) * X ^ 15 + C (2) * X ^ 16 + C (4) * X ^ 17 + C (-2) * X ^ 18
def VQ_pim_0_11_10 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_pre_eq_0_11_10 :
    spanV_re_0_10 * Qplus_re_10_11 - spanV_im_0_10 * Qplus_im_10_11 =
      VQ_pre_0_11_10 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_10, spanV_im_0_10, Qplus_re_10_11, Qplus_im_10_11,
    VQ_pre_0_11_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_0_11_10 :
    spanV_re_0_10 * Qplus_im_10_11 + spanV_im_0_10 * Qplus_re_10_11 =
      VQ_pim_0_11_10 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_10, spanV_im_0_10, Qplus_re_10_11, Qplus_im_10_11,
    VQ_pim_0_11_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_0_11_10 :
    spanV_entry_0_10 * Qplus_entry_10_11 =
      ofLadj VQ_pre_0_11_10 VQ_pim_0_11_10 := by
  rw [spanV_entry_0_10, Qplus_entry_10_11, ofLadj_mul,
    VQ_pre_eq_0_11_10, VQ_pim_eq_0_11_10]

def VQ_pre_0_11_11 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_11 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_11 :
    spanV_entry_0_11 * Qplus_entry_11_11 =
      ofLadj VQ_pre_0_11_11 VQ_pim_0_11_11 := by
  have hz : spanV_entry_0_11 = 0 := by
    rw [spanV_entry_0_11]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_11, VQ_pim_0_11_11]
  simp [ofLadj_zero]

def VQ_pre_0_11_12 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_12 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_12 :
    spanV_entry_0_12 * Qplus_entry_12_11 =
      ofLadj VQ_pre_0_11_12 VQ_pim_0_11_12 := by
  have hz : spanV_entry_0_12 = 0 := by
    rw [spanV_entry_0_12]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_12, VQ_pim_0_11_12]
  simp [ofLadj_zero]

def VQ_pre_0_11_13 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_13 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_13 :
    spanV_entry_0_13 * Qplus_entry_13_11 =
      ofLadj VQ_pre_0_11_13 VQ_pim_0_11_13 := by
  have hz : spanV_entry_0_13 = 0 := by
    rw [spanV_entry_0_13]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_13, VQ_pim_0_11_13]
  simp [ofLadj_zero]

def VQ_pre_0_11_14 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_11_14 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_11_14 :
    spanV_entry_0_14 * Qplus_entry_14_11 =
      ofLadj VQ_pre_0_11_14 VQ_pim_0_11_14 := by
  have hz : spanV_entry_0_14 = 0 := by
    rw [spanV_entry_0_14]; exact ofLadj_zero
  rw [hz, VQ_pre_0_11_14, VQ_pim_0_11_14]
  simp [ofLadj_zero]

theorem VQ_sum_poly_re_0_11 :
    VQ_pre_0_11_0 + VQ_pre_0_11_1 + VQ_pre_0_11_2 + VQ_pre_0_11_3 + VQ_pre_0_11_4 + VQ_pre_0_11_5 + VQ_pre_0_11_6 + VQ_pre_0_11_7 + VQ_pre_0_11_8 + VQ_pre_0_11_9 + VQ_pre_0_11_10 + VQ_pre_0_11_11 + VQ_pre_0_11_12 + VQ_pre_0_11_13 + VQ_pre_0_11_14 = minorQ_re_0_11 + Phi11 * VQ_qre_0_11 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [VQ_pre_0_11_0, VQ_pre_0_11_1, VQ_pre_0_11_2, VQ_pre_0_11_3, VQ_pre_0_11_4, VQ_pre_0_11_5, VQ_pre_0_11_6, VQ_pre_0_11_7, VQ_pre_0_11_8, VQ_pre_0_11_9, VQ_pre_0_11_10, VQ_pre_0_11_11, VQ_pre_0_11_12, VQ_pre_0_11_13, VQ_pre_0_11_14, minorQ_re_0_11, VQ_qre_0_11]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem VQ_sum_poly_im_0_11 :
    VQ_pim_0_11_0 + VQ_pim_0_11_1 + VQ_pim_0_11_2 + VQ_pim_0_11_3 + VQ_pim_0_11_4 + VQ_pim_0_11_5 + VQ_pim_0_11_6 + VQ_pim_0_11_7 + VQ_pim_0_11_8 + VQ_pim_0_11_9 + VQ_pim_0_11_10 + VQ_pim_0_11_11 + VQ_pim_0_11_12 + VQ_pim_0_11_13 + VQ_pim_0_11_14 = minorQ_im_0_11 + Phi11 * VQ_qim_0_11 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [VQ_pim_0_11_0, VQ_pim_0_11_1, VQ_pim_0_11_2, VQ_pim_0_11_3, VQ_pim_0_11_4, VQ_pim_0_11_5, VQ_pim_0_11_6, VQ_pim_0_11_7, VQ_pim_0_11_8, VQ_pim_0_11_9, VQ_pim_0_11_10, VQ_pim_0_11_11, VQ_pim_0_11_12, VQ_pim_0_11_13, VQ_pim_0_11_14, minorQ_im_0_11, VQ_qim_0_11]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem VQ_sum_entries_0_11 :
    spanV_entry_0_0 * Qplus_entry_0_11 + spanV_entry_0_1 * Qplus_entry_1_11 + spanV_entry_0_2 * Qplus_entry_2_11 + spanV_entry_0_3 * Qplus_entry_3_11 + spanV_entry_0_4 * Qplus_entry_4_11 + spanV_entry_0_5 * Qplus_entry_5_11 + spanV_entry_0_6 * Qplus_entry_6_11 + spanV_entry_0_7 * Qplus_entry_7_11 + spanV_entry_0_8 * Qplus_entry_8_11 + spanV_entry_0_9 * Qplus_entry_9_11 + spanV_entry_0_10 * Qplus_entry_10_11 + spanV_entry_0_11 * Qplus_entry_11_11 + spanV_entry_0_12 * Qplus_entry_12_11 + spanV_entry_0_13 * Qplus_entry_13_11 + spanV_entry_0_14 * Qplus_entry_14_11 =
      ofLadj (VQ_pre_0_11_0 + VQ_pre_0_11_1 + VQ_pre_0_11_2 + VQ_pre_0_11_3 + VQ_pre_0_11_4 + VQ_pre_0_11_5 + VQ_pre_0_11_6 + VQ_pre_0_11_7 + VQ_pre_0_11_8 + VQ_pre_0_11_9 + VQ_pre_0_11_10 + VQ_pre_0_11_11 + VQ_pre_0_11_12 + VQ_pre_0_11_13 + VQ_pre_0_11_14) (VQ_pim_0_11_0 + VQ_pim_0_11_1 + VQ_pim_0_11_2 + VQ_pim_0_11_3 + VQ_pim_0_11_4 + VQ_pim_0_11_5 + VQ_pim_0_11_6 + VQ_pim_0_11_7 + VQ_pim_0_11_8 + VQ_pim_0_11_9 + VQ_pim_0_11_10 + VQ_pim_0_11_11 + VQ_pim_0_11_12 + VQ_pim_0_11_13 + VQ_pim_0_11_14) := by
  simp only [VQ_term_0_11_0, VQ_term_0_11_1, VQ_term_0_11_2, VQ_term_0_11_3, VQ_term_0_11_4, VQ_term_0_11_5, VQ_term_0_11_6, VQ_term_0_11_7, VQ_term_0_11_8, VQ_term_0_11_9, VQ_term_0_11_10, VQ_term_0_11_11, VQ_term_0_11_12, VQ_term_0_11_13, VQ_term_0_11_14]
  simpa [add_assoc] using ofLadj_add15 VQ_pre_0_11_0 VQ_pim_0_11_0 VQ_pre_0_11_1 VQ_pim_0_11_1 VQ_pre_0_11_2 VQ_pim_0_11_2 VQ_pre_0_11_3 VQ_pim_0_11_3 VQ_pre_0_11_4 VQ_pim_0_11_4 VQ_pre_0_11_5 VQ_pim_0_11_5 VQ_pre_0_11_6 VQ_pim_0_11_6 VQ_pre_0_11_7 VQ_pim_0_11_7 VQ_pre_0_11_8 VQ_pim_0_11_8 VQ_pre_0_11_9 VQ_pim_0_11_9 VQ_pre_0_11_10 VQ_pim_0_11_10 VQ_pre_0_11_11 VQ_pim_0_11_11 VQ_pre_0_11_12 VQ_pim_0_11_12 VQ_pre_0_11_13 VQ_pim_0_11_13 VQ_pre_0_11_14 VQ_pim_0_11_14

theorem VQ_eval_0_11 :
    ofLadj (VQ_pre_0_11_0 + VQ_pre_0_11_1 + VQ_pre_0_11_2 + VQ_pre_0_11_3 + VQ_pre_0_11_4 + VQ_pre_0_11_5 + VQ_pre_0_11_6 + VQ_pre_0_11_7 + VQ_pre_0_11_8 + VQ_pre_0_11_9 + VQ_pre_0_11_10 + VQ_pre_0_11_11 + VQ_pre_0_11_12 + VQ_pre_0_11_13 + VQ_pre_0_11_14) (VQ_pim_0_11_0 + VQ_pim_0_11_1 + VQ_pim_0_11_2 + VQ_pim_0_11_3 + VQ_pim_0_11_4 + VQ_pim_0_11_5 + VQ_pim_0_11_6 + VQ_pim_0_11_7 + VQ_pim_0_11_8 + VQ_pim_0_11_9 + VQ_pim_0_11_10 + VQ_pim_0_11_11 + VQ_pim_0_11_12 + VQ_pim_0_11_13 + VQ_pim_0_11_14) = minorQ_entry_0_11 := by
  rw [VQ_sum_poly_re_0_11, VQ_sum_poly_im_0_11,
    ofLadj_add_Phi11, minorQ_entry_0_11]

theorem VQ_entry_0_11 : (spanV * Qplus) 0 11 = minorQ 0 11 := by
  rw [Matrix.mul_apply]
  rw [sum_fin15]
  change spanV_entry_0_0 * Qplus_entry_0_11 + spanV_entry_0_1 * Qplus_entry_1_11 + spanV_entry_0_2 * Qplus_entry_2_11 + spanV_entry_0_3 * Qplus_entry_3_11 + spanV_entry_0_4 * Qplus_entry_4_11 + spanV_entry_0_5 * Qplus_entry_5_11 + spanV_entry_0_6 * Qplus_entry_6_11 + spanV_entry_0_7 * Qplus_entry_7_11 + spanV_entry_0_8 * Qplus_entry_8_11 + spanV_entry_0_9 * Qplus_entry_9_11 + spanV_entry_0_10 * Qplus_entry_10_11 + spanV_entry_0_11 * Qplus_entry_11_11 + spanV_entry_0_12 * Qplus_entry_12_11 + spanV_entry_0_13 * Qplus_entry_13_11 + spanV_entry_0_14 * Qplus_entry_14_11 = minorQ_entry_0_11
  exact (VQ_sum_entries_0_11).trans VQ_eval_0_11

end V14Formalization.D12SigmaPlusSegreCore
