/-
Auto-generated by scripts/export_sigma_plus_minor_h.py.
Stock-limit, kernel-checkable H-minor vs stored minorQ identities.
-/
import V14Formalization.D12SigmaPlusSegreEval
import V14Formalization.D12PolyZReflectionBridges
import V14Formalization.D12SigmaPlusSegreApplyH
import V14Formalization.D12SigmaPlusSegreMinorQ
import V14Formalization.D12SigmaPlusSegreGeom
import V14Formalization.D12PolyZExpand

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData
open V14Formalization.D12PolyZReflection
open D12SigmaPlusQuadric6

def HM_1_3_A_pre : Polynomial ℚ := C (-4) * X ^ 3 + C (-8) * X ^ 4 + C (4) * X ^ 6 + C (4) * X ^ 9 + C (-8) * X ^ 10 + C (-16) * X ^ 11 + C (-8) * X ^ 12 + C (4) * X ^ 13 + C (4) * X ^ 14 + C (8) * X ^ 15 + C (12) * X ^ 16 + C (8) * X ^ 17
theorem z_HM_1_3_A_pre : HM_1_3_A_pre = interpQ 1 [0, 0, 0, -4, -8, 0, 4, 0, 0, 4, -8, -16, -8, 4, 4, 8, 12, 8] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_18_66 (-4) (-8) 4 4 (-8) (-16) (-8) 4 4 8 12 8

def HM_1_3_A_pim : Polynomial ℚ := C (8) * X ^ 3 + C (24) * X ^ 5 + C (12) * X ^ 6 + C (24) * X ^ 7 + C (16) * X ^ 8 + C (24) * X ^ 9 + C (-24) * X ^ 13 + C (-24) * X ^ 14 + C (-24) * X ^ 15 + C (-12) * X ^ 16 + C (-24) * X ^ 17
theorem z_HM_1_3_A_pim : HM_1_3_A_pim = interpQ 1 [0, 0, 0, 8, 0, 24, 12, 24, 16, 24, 0, 0, 0, -24, -24, -24, -12, -24] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_18_69 8 24 12 24 16 24 (-24) (-24) (-24) (-12) (-24)

theorem HM_1_3_A_pre_eq :
    H_re_0_0 * H_re_5_3 - H_im_0_0 * H_im_5_3 =
      HM_1_3_A_pre := by
  rw [z_H_re_0_0, z_H_re_5_3, z_H_im_0_0, z_H_im_5_3, z_HM_1_3_A_pre]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_1_3_A_pim_eq :
    H_re_0_0 * H_im_5_3 + H_im_0_0 * H_re_5_3 =
      HM_1_3_A_pim := by
  rw [z_H_re_0_0, z_H_im_5_3, z_H_im_0_0, z_H_re_5_3, z_HM_1_3_A_pim]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_1_3_A_mul :
    H_entry_0_0 * H_entry_5_3 =
      ofLadj HM_1_3_A_pre HM_1_3_A_pim := by
  rw [H_entry_0_0, H_entry_5_3, ofLadj_mul,
    HM_1_3_A_pre_eq, HM_1_3_A_pim_eq]

def HM_1_3_B_pre : Polynomial ℚ := C (6) + C (24) * X + C (56) * X ^ 2 + C (76) * X ^ 3 + C (88) * X ^ 4 + C (94) * X ^ 5 + C (96) * X ^ 6 + C (84) * X ^ 7 + C (74) * X ^ 8 + C (60) * X ^ 9 + C (38) * X ^ 10 + C (20) * X ^ 11 + C (14) * X ^ 12 + C (4) * X ^ 13 + C (-2) * X ^ 14 + C (-2) * X ^ 15 + C (-2) * X ^ 16 + C (-4) * X ^ 17 + C (2) * X ^ 18
theorem z_HM_1_3_B_pre : HM_1_3_B_pre = interpQ 1 [6, 24, 56, 76, 88, 94, 96, 84, 74, 60, 38, 20, 14, 4, -2, -2, -2, -4, 2] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_19_73 6 24 56 76 88 94 96 84 74 60 38 20 14 4 (-2) (-2) (-2) (-4) 2

def HM_1_3_B_pim : Polynomial ℚ := C (-6) + C (-12) * X + C (-20) * X ^ 2 + C (66) * X ^ 4 + C (162) * X ^ 5 + C (258) * X ^ 6 + C (338) * X ^ 7 + C (388) * X ^ 8 + C (366) * X ^ 9 + C (290) * X ^ 10 + C (204) * X ^ 11 + C (118) * X ^ 12 + C (50) * X ^ 13 + C (8) * X ^ 14 + C (-10) * X ^ 15 + C (-16) * X ^ 16 + C (-8) * X ^ 17 + C (2) * X ^ 18
theorem z_HM_1_3_B_pim : HM_1_3_B_pim = interpQ 1 [-6, -12, -20, 0, 66, 162, 258, 338, 388, 366, 290, 204, 118, 50, 8, -10, -16, -8, 2] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_19_94 (-6) (-12) (-20) 66 162 258 338 388 366 290 204 118 50 8 (-10) (-16) (-8) 2

theorem HM_1_3_B_pre_eq :
    H_re_0_3 * H_re_5_0 - H_im_0_3 * H_im_5_0 =
      HM_1_3_B_pre := by
  rw [z_H_re_0_3, z_H_re_5_0, z_H_im_0_3, z_H_im_5_0, z_HM_1_3_B_pre]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_1_3_B_pim_eq :
    H_re_0_3 * H_im_5_0 + H_im_0_3 * H_re_5_0 =
      HM_1_3_B_pim := by
  rw [z_H_re_0_3, z_H_im_5_0, z_H_im_0_3, z_H_re_5_0, z_HM_1_3_B_pim]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_1_3_B_mul :
    H_entry_0_3 * H_entry_5_0 =
      ofLadj HM_1_3_B_pre HM_1_3_B_pim := by
  rw [H_entry_0_3, H_entry_5_0, ofLadj_mul,
    HM_1_3_B_pre_eq, HM_1_3_B_pim_eq]

def HM_1_3_C_pre : Polynomial ℚ := C (-4) * X ^ 2 + C (4) * X ^ 3 + C (-6) * X ^ 4 + C (-20) * X ^ 5 + C (-46) * X ^ 6 + C (-100) * X ^ 7 + C (-160) * X ^ 8 + C (-214) * X ^ 9 + C (-268) * X ^ 10 + C (-308) * X ^ 11 + C (-268) * X ^ 12 + C (-210) * X ^ 13 + C (-164) * X ^ 14 + C (-104) * X ^ 15 + C (-42) * X ^ 16 + C (-16) * X ^ 17 + C (-10) * X ^ 18
theorem z_HM_1_3_C_pre : HM_1_3_C_pre = interpQ 1 [0, 0, -4, 4, -6, -20, -46, -100, -160, -214, -268, -308, -268, -210, -164, -104, -42, -16, -10] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_19_113 (-4) 4 (-6) (-20) (-46) (-100) (-160) (-214) (-268) (-308) (-268) (-210) (-164) (-104) (-42) (-16) (-10)

def HM_1_3_C_pim : Polynomial ℚ := C (8) * X ^ 2 + C (24) * X ^ 3 + C (46) * X ^ 4 + C (96) * X ^ 5 + C (142) * X ^ 6 + C (190) * X ^ 7 + C (216) * X ^ 8 + C (204) * X ^ 9 + C (140) * X ^ 10 + C (88) * X ^ 11 + C (36) * X ^ 12 + C (-36) * X ^ 13 + C (-64) * X ^ 14 + C (-50) * X ^ 15 + C (-34) * X ^ 16 + C (-28) * X ^ 17 + C (-10) * X ^ 18
theorem z_HM_1_3_C_pim : HM_1_3_C_pim = interpQ 1 [0, 0, 8, 24, 46, 96, 142, 190, 216, 204, 140, 88, 36, -36, -64, -50, -34, -28, -10] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_19_113 8 24 46 96 142 190 216 204 140 88 36 (-36) (-64) (-50) (-34) (-28) (-10)

theorem HM_1_3_C_pre_eq :
    H_re_2_0 * H_re_3_3 - H_im_2_0 * H_im_3_3 =
      HM_1_3_C_pre := by
  rw [z_H_re_2_0, z_H_re_3_3, z_H_im_2_0, z_H_im_3_3, z_HM_1_3_C_pre]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_1_3_C_pim_eq :
    H_re_2_0 * H_im_3_3 + H_im_2_0 * H_re_3_3 =
      HM_1_3_C_pim := by
  rw [z_H_re_2_0, z_H_im_3_3, z_H_im_2_0, z_H_re_3_3, z_HM_1_3_C_pim]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_1_3_C_mul :
    H_entry_2_0 * H_entry_3_3 =
      ofLadj HM_1_3_C_pre HM_1_3_C_pim := by
  rw [H_entry_2_0, H_entry_3_3, ofLadj_mul,
    HM_1_3_C_pre_eq, HM_1_3_C_pim_eq]

def HM_1_3_D_pre : Polynomial ℚ := C (12) + C (4) * X ^ 2 + C (-48) * X ^ 3 + C (-80) * X ^ 4 + C (-150) * X ^ 5 + C (-186) * X ^ 6 + C (-212) * X ^ 7 + C (-188) * X ^ 8 + C (-140) * X ^ 9 + C (-124) * X ^ 10 + C (-120) * X ^ 11 + C (-124) * X ^ 12 + C (-144) * X ^ 13 + C (-140) * X ^ 14 + C (-140) * X ^ 15 + C (-92) * X ^ 16 + C (-56) * X ^ 17 + C (-8) * X ^ 18
theorem z_HM_1_3_D_pre : HM_1_3_D_pre = interpQ 1 [12, 0, 4, -48, -80, -150, -186, -212, -188, -140, -124, -120, -124, -144, -140, -140, -92, -56, -8] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_19_99 12 4 (-48) (-80) (-150) (-186) (-212) (-188) (-140) (-124) (-120) (-124) (-144) (-140) (-140) (-92) (-56) (-8)

def HM_1_3_D_pim : Polynomial ℚ := C (-12) + C (-24) * X + C (-56) * X ^ 2 + C (-84) * X ^ 3 + C (-100) * X ^ 4 + C (-94) * X ^ 5 + C (-74) * X ^ 6 + C (-24) * X ^ 7 + C (8) * X ^ 8 + C (-42) * X ^ 10 + C (-76) * X ^ 11 + C (-110) * X ^ 12 + C (-120) * X ^ 13 + C (-100) * X ^ 14 + C (-64) * X ^ 15 + C (-16) * X ^ 16 + C (8) * X ^ 17 + C (12) * X ^ 18
theorem z_HM_1_3_D_pim : HM_1_3_D_pim = interpQ 1 [-12, -24, -56, -84, -100, -94, -74, -24, 8, 0, -42, -76, -110, -120, -100, -64, -16, 8, 12] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_19_88 (-12) (-24) (-56) (-84) (-100) (-94) (-74) (-24) 8 (-42) (-76) (-110) (-120) (-100) (-64) (-16) 8 12

theorem HM_1_3_D_pre_eq :
    H_re_2_3 * H_re_3_0 - H_im_2_3 * H_im_3_0 =
      HM_1_3_D_pre := by
  rw [z_H_re_2_3, z_H_re_3_0, z_H_im_2_3, z_H_im_3_0, z_HM_1_3_D_pre]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_1_3_D_pim_eq :
    H_re_2_3 * H_im_3_0 + H_im_2_3 * H_re_3_0 =
      HM_1_3_D_pim := by
  rw [z_H_re_2_3, z_H_im_3_0, z_H_im_2_3, z_H_re_3_0, z_HM_1_3_D_pim]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_1_3_D_mul :
    H_entry_2_3 * H_entry_3_0 =
      ofLadj HM_1_3_D_pre HM_1_3_D_pim := by
  rw [H_entry_2_3, H_entry_3_0, ofLadj_mul,
    HM_1_3_D_pre_eq, HM_1_3_D_pim_eq]

def HM_1_3_qre : Polynomial ℚ := C (-10) + C (34) * X + C (36) * X ^ 2 + C (56) * X ^ 3 + C (56) * X ^ 4 + C (106) * X ^ 5 + C (68) * X ^ 6 + C (56) * X ^ 7 + C (20) * X ^ 8
theorem z_HM_1_3_qre : HM_1_3_qre = interpQ 1 [-10, 34, 36, 56, 56, 106, 68, 56, 20] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_9_7 (-10) 34 36 56 56 106 68 56 20

def HM_1_3_qim : Polynomial ℚ := C (10) * X ^ 2 + C (34) * X ^ 3 + C (68) * X ^ 4 + C (58) * X ^ 5 + C (34) * X ^ 6 + C (-12) * X ^ 7
theorem z_HM_1_3_qim : HM_1_3_qim = interpQ 1 [0, 0, 10, 34, 68, 58, 34, -12] :=
  V14Formalization.D12PolyZReflection.interpQ_expand_8_6 10 34 68 58 34 (-12)

theorem HM_1_3_bilin :
    bilinearCoeffs (Hrow 0) (Hrow 5) 3 -
        bilinearCoeffs (Hrow 2) (Hrow 3) 3 =
      (ofLadj HM_1_3_A_pre HM_1_3_A_pim +
          ofLadj HM_1_3_B_pre HM_1_3_B_pim) -
        (ofLadj HM_1_3_C_pre HM_1_3_C_pim +
            ofLadj HM_1_3_D_pre HM_1_3_D_pim) := by
  have hpq : bilinearCoeffs (Hrow 0) (Hrow 5) 3 =
      H_entry_0_0 * H_entry_5_3 +
        H_entry_0_3 * H_entry_5_0 := by
    simp [bilinearCoeffs, monomPair_3, Hrow, H_apply_0_0,
      H_apply_5_3, H_apply_0_3, H_apply_5_0]
  have hrt : bilinearCoeffs (Hrow 2) (Hrow 3) 3 =
      H_entry_2_0 * H_entry_3_3 +
        H_entry_2_3 * H_entry_3_0 := by
    simp [bilinearCoeffs, monomPair_3, Hrow, H_apply_2_0,
      H_apply_3_3, H_apply_2_3, H_apply_3_0]
  rw [hpq, hrt, HM_1_3_A_mul, HM_1_3_B_mul, HM_1_3_C_mul, HM_1_3_D_mul]
theorem HM_1_3_sum :
    (ofLadj HM_1_3_A_pre HM_1_3_A_pim +
        ofLadj HM_1_3_B_pre HM_1_3_B_pim) -
      (ofLadj HM_1_3_C_pre HM_1_3_C_pim +
          ofLadj HM_1_3_D_pre HM_1_3_D_pim) =
      ofLadj (HM_1_3_A_pre + HM_1_3_B_pre - HM_1_3_C_pre - HM_1_3_D_pre)
        (HM_1_3_A_pim + HM_1_3_B_pim - HM_1_3_C_pim - HM_1_3_D_pim) := by
  rw [ofLadj_add, ofLadj_add, ofLadj_sub, sub_add_eq_sub_sub,
    sub_add_eq_sub_sub]
theorem HM_1_3_red :
    HM_1_3_A_pre + HM_1_3_B_pre - HM_1_3_C_pre - HM_1_3_D_pre =
      minorQ_re_1_3 + Phi11 * HM_1_3_qre := by
  rw [z_HM_1_3_A_pre, z_HM_1_3_B_pre, z_HM_1_3_C_pre, z_HM_1_3_D_pre, z_minorQ_re_1_3, z_Phi11, z_HM_1_3_qre]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_1_3_redim :
    HM_1_3_A_pim + HM_1_3_B_pim - HM_1_3_C_pim - HM_1_3_D_pim =
      minorQ_im_1_3 + Phi11 * HM_1_3_qim := by
  rw [z_HM_1_3_A_pim, z_HM_1_3_B_pim, z_HM_1_3_C_pim, z_HM_1_3_D_pim, z_minorQ_im_1_3, z_Phi11, z_HM_1_3_qim]
  simp (disch := decide) only [interp_mul, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem HM_entry_1_3 :
    minorCoeffsH 1 3 = minorQ 1 3 := by
  unfold minorCoeffsH
  simp [minorOrder_1, crossIndex]
  change bilinearCoeffs (Hrow 0) (Hrow 5) 3 -
      bilinearCoeffs (Hrow 2) (Hrow 3) 3 =
    minorQ 1 3
  rw [HM_1_3_bilin, HM_1_3_sum, HM_1_3_red, HM_1_3_redim,
    ofLadj_add_Phi11]
  change ofLadj minorQ_re_1_3 minorQ_im_1_3 = minorQ 1 3
  rfl

end V14Formalization.D12SigmaPlusSegreCore
