/-
Auto-generated by scripts/export_sigma_plus_identities.py.
Stock-limit, kernel-checkable plus Segre entry identities.
-/
module

public import V14Formalization.D12SigmaPlusSegreEval
public import V14Formalization.D12PolyZReflection
public import V14Formalization.D12SigmaPlusSegreApplyN
public import V14Formalization.D12SigmaPlusSegreApplyH
public import V14Formalization.D12SigmaPlusSegreApplyHZ

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData
open V14Formalization.D12PolyZReflection

def NH_qre_2_1 : Polynomial ℚ := interpQ 1 [-36, -64, -54, -160, -50, -30, -196, -280, -142]
def NH_qim_2_1 : Polynomial ℚ := interpQ 1 [28, 28, -88, -194, -121, -5, -17, -140, -5]

private theorem phi11_interp :
    (Phi11 : Polynomial ℚ) = interpQ 1 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] := by
  rw [Phi11_expand]
  refine Polynomial.funext fun r => ?_
  simp [interpQ, toPolyZ, Polynomial.eval_add, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow]
  try grind

def NH_pre_2_1_0 : Polynomial ℚ := interpQ 1 [-4, -16, -20, -14, -16, -22, -28, -32, -44, -46, -46, -36, -30, -26, -30, -24, -24, -18, -8]
def NH_pim_2_1_0 : Polynomial ℚ := interpQ 1 [0, 0, 0, 5, 8, 6, 13, 13, 11, 11, 18, 16, 14, 21, 16, 11, 8, 5]
theorem NH_pre_eq_2_1_0 :
    N_re_2_0 * H_re_0_1 - N_im_2_0 * H_im_0_1 =
      NH_pre_2_1_0 := by
  rw [z_N_re_2_0, z_H_re_0_1, z_N_im_2_0,
    z_H_im_0_1]
  simp only [NH_pre_2_1_0]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_pim_eq_2_1_0 :
    N_re_2_0 * H_im_0_1 + N_im_2_0 * H_re_0_1 =
      NH_pim_2_1_0 := by
  rw [z_N_re_2_0, z_H_im_0_1, z_N_im_2_0,
    z_H_re_0_1]
  simp only [NH_pim_2_1_0]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_term_2_1_0 :
    N_entry_2_0 * H_entry_0_1 =
      ofLadj NH_pre_2_1_0 NH_pim_2_1_0 := by
  rw [N_entry_2_0, H_entry_0_1, ofLadj_mul,
    NH_pre_eq_2_1_0, NH_pim_eq_2_1_0]

def NH_pre_2_1_1 : Polynomial ℚ := interpQ 1 [0, 0, -31, -124, -127, -101, -187, -208, -199, -195, -191, -201, -191, -164, -75, -71, -99, -13, 10]
def NH_pim_2_1_1 : Polynomial ℚ := interpQ 1 [0, 0, 18, 10, -66, -26, -45, -116, -139, -142, -142, -143, -144, -162, -157, -79, -111, -104, -25]
theorem NH_pre_eq_2_1_1 :
    N_re_2_1 * H_re_1_1 - N_im_2_1 * H_im_1_1 =
      NH_pre_2_1_1 := by
  rw [z_N_re_2_1, z_H_re_1_1, z_N_im_2_1,
    z_H_im_1_1]
  simp only [NH_pre_2_1_1]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_pim_eq_2_1_1 :
    N_re_2_1 * H_im_1_1 + N_im_2_1 * H_re_1_1 =
      NH_pim_2_1_1 := by
  rw [z_N_re_2_1, z_H_im_1_1, z_N_im_2_1,
    z_H_re_1_1]
  simp only [NH_pim_2_1_1]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_term_2_1_1 :
    N_entry_2_1 * H_entry_1_1 =
      ofLadj NH_pre_2_1_1 NH_pim_2_1_1 := by
  rw [N_entry_2_1, H_entry_1_1, ofLadj_mul,
    NH_pre_eq_2_1_1, NH_pim_eq_2_1_1]

def NH_pre_2_1_2 : Polynomial ℚ := interpQ 1 [-8, 12, -10, -12, -6, -6, 8, -22, -18, -18, -24, -14, -36, -8, -6, -24, -14, -28, -8]
def NH_pim_2_1_2 : Polynomial ℚ := interpQ 1 [-14, -28, -30, -64, -48, -62, -72, -76, -90, -84, -96, -74, -52, -62, -22, -36, -26, -16, -16]
theorem NH_pre_eq_2_1_2 :
    N_re_2_2 * H_re_2_1 - N_im_2_2 * H_im_2_1 =
      NH_pre_2_1_2 := by
  rw [z_N_re_2_2, z_H_re_2_1, z_N_im_2_2,
    z_H_im_2_1]
  simp only [NH_pre_2_1_2]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_pim_eq_2_1_2 :
    N_re_2_2 * H_im_2_1 + N_im_2_2 * H_re_2_1 =
      NH_pim_2_1_2 := by
  rw [z_N_re_2_2, z_H_im_2_1, z_N_im_2_2,
    z_H_re_2_1]
  simp only [NH_pim_2_1_2]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_term_2_1_2 :
    N_entry_2_2 * H_entry_2_1 =
      ofLadj NH_pre_2_1_2 NH_pim_2_1_2 := by
  rw [N_entry_2_2, H_entry_2_1, ofLadj_mul,
    NH_pre_eq_2_1_2, NH_pim_eq_2_1_2]

def NH_pre_2_1_3 : Polynomial ℚ := interpQ 1 [0, 0, -33, -132, -159, -211, -259, -402, -507, -471, -465, -501, -465, -438, -375, -317, -287, -239, -74]
def NH_pim_2_1_3 : Polynomial ℚ := interpQ 1 [0, 0, -80, -254, -290, -322, -387, -468, -487, -526, -502, -517, -532, -428, -293, -237, -177, -148, -39]
theorem NH_pre_eq_2_1_3 :
    N_re_2_3 * H_re_3_1 - N_im_2_3 * H_im_3_1 =
      NH_pre_2_1_3 := by
  rw [z_N_re_2_3, z_H_re_3_1, z_N_im_2_3,
    z_H_im_3_1]
  simp only [NH_pre_2_1_3]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_pim_eq_2_1_3 :
    N_re_2_3 * H_im_3_1 + N_im_2_3 * H_re_3_1 =
      NH_pim_2_1_3 := by
  rw [z_N_re_2_3, z_H_im_3_1, z_N_im_2_3,
    z_H_re_3_1]
  simp only [NH_pim_2_1_3]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_term_2_1_3 :
    N_entry_2_3 * H_entry_3_1 =
      ofLadj NH_pre_2_1_3 NH_pim_2_1_3 := by
  rw [N_entry_2_3, H_entry_3_1, ofLadj_mul,
    NH_pre_eq_2_1_3, NH_pim_eq_2_1_3]

def NH_pre_2_1_4 : Polynomial ℚ := interpQ 1 [0, 0, 12, 60, 94, 74, 84, 38, -6, -4, 2, -12, 2, -16, -66, -82, -72, -82, -26]
def NH_pim_2_1_4 : Polynomial ℚ := interpQ 1 [0, 0, -22, -66, -51, -64, -50, -6, -2, -13, 4, 0, -4, 35, 68, 50, 72, 42, 7]
theorem NH_pre_eq_2_1_4 :
    N_re_2_4 * H_re_4_1 - N_im_2_4 * H_im_4_1 =
      NH_pre_2_1_4 := by
  rw [z_N_re_2_4, z_H_re_4_1, z_N_im_2_4,
    z_H_im_4_1]
  simp only [NH_pre_2_1_4]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_pim_eq_2_1_4 :
    N_re_2_4 * H_im_4_1 + N_im_2_4 * H_re_4_1 =
      NH_pim_2_1_4 := by
  rw [z_N_re_2_4, z_H_im_4_1, z_N_im_2_4,
    z_H_re_4_1]
  simp only [NH_pim_2_1_4]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_term_2_1_4 :
    N_entry_2_4 * H_entry_4_1 =
      ofLadj NH_pre_2_1_4 NH_pim_2_1_4 := by
  rw [N_entry_2_4, H_entry_4_1, ofLadj_mul,
    NH_pre_eq_2_1_4, NH_pim_eq_2_1_4]

def NH_pre_2_1_5 : Polynomial ℚ := interpQ 1 [-24, -96, -72, -92, -150, -128, -208, -244, -238, -278, -288, -212, -192, -206, -146, -130, -122, -42, -36]
def NH_pim_2_1_5 : Polynomial ℚ := interpQ 1 [44, 88, 84, 146, 102, 120, 172, 146, 194, 242, 204, 176, 148, 114, 100, 124, 72, 76, 68]
theorem NH_pre_eq_2_1_5 :
    N_re_2_5 * H_re_5_1 - N_im_2_5 * H_im_5_1 =
      NH_pre_2_1_5 := by
  rw [z_N_re_2_5, z_H_re_5_1, z_N_im_2_5,
    z_H_im_5_1]
  simp only [NH_pre_2_1_5]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_pim_eq_2_1_5 :
    N_re_2_5 * H_im_5_1 + N_im_2_5 * H_re_5_1 =
      NH_pim_2_1_5 := by
  rw [z_N_re_2_5, z_H_im_5_1, z_N_im_2_5,
    z_H_re_5_1]
  simp only [NH_pim_2_1_5]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_term_2_1_5 :
    N_entry_2_5 * H_entry_5_1 =
      ofLadj NH_pre_2_1_5 NH_pim_2_1_5 := by
  rw [N_entry_2_5, H_entry_5_1, ofLadj_mul,
    NH_pre_eq_2_1_5, NH_pim_eq_2_1_5]

def NH_pre_2_1_6 : Polynomial ℚ := interpQ 1 []
def NH_pim_2_1_6 : Polynomial ℚ := interpQ 1 []
theorem NH_pre_eq_2_1_6 :
    N_re_2_6 * H_re_6_1 - N_im_2_6 * H_im_6_1 =
      NH_pre_2_1_6 := by
  rw [z_N_re_2_6, z_H_re_6_1, z_N_im_2_6,
    z_H_im_6_1]
  simp only [NH_pre_2_1_6]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_pim_eq_2_1_6 :
    N_re_2_6 * H_im_6_1 + N_im_2_6 * H_re_6_1 =
      NH_pim_2_1_6 := by
  rw [z_N_re_2_6, z_H_im_6_1, z_N_im_2_6,
    z_H_re_6_1]
  simp only [NH_pim_2_1_6]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_term_2_1_6 :
    N_entry_2_6 * H_entry_6_1 =
      ofLadj NH_pre_2_1_6 NH_pim_2_1_6 := by
  rw [N_entry_2_6, H_entry_6_1, ofLadj_mul,
    NH_pre_eq_2_1_6, NH_pim_eq_2_1_6]

def NH_pre_2_1_7 : Polynomial ℚ := interpQ 1 []
def NH_pim_2_1_7 : Polynomial ℚ := interpQ 1 []
theorem NH_pre_eq_2_1_7 :
    N_re_2_7 * H_re_7_1 - N_im_2_7 * H_im_7_1 =
      NH_pre_2_1_7 := by
  rw [z_N_re_2_7, z_H_re_7_1, z_N_im_2_7,
    z_H_im_7_1]
  simp only [NH_pre_2_1_7]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_pim_eq_2_1_7 :
    N_re_2_7 * H_im_7_1 + N_im_2_7 * H_re_7_1 =
      NH_pim_2_1_7 := by
  rw [z_N_re_2_7, z_H_im_7_1, z_N_im_2_7,
    z_H_re_7_1]
  simp only [NH_pim_2_1_7]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_term_2_1_7 :
    N_entry_2_7 * H_entry_7_1 =
      ofLadj NH_pre_2_1_7 NH_pim_2_1_7 := by
  rw [N_entry_2_7, H_entry_7_1, ofLadj_mul,
    NH_pre_eq_2_1_7, NH_pim_eq_2_1_7]

def NH_pre_2_1_8 : Polynomial ℚ := interpQ 1 []
def NH_pim_2_1_8 : Polynomial ℚ := interpQ 1 [-2, -4, -2, -3, -2, -4, 0, -2, -1, -2]
theorem NH_pre_eq_2_1_8 :
    N_re_2_8 * H_re_8_1 - N_im_2_8 * H_im_8_1 =
      NH_pre_2_1_8 := by
  rw [z_N_re_2_8, z_H_re_8_1, z_N_im_2_8,
    z_H_im_8_1]
  simp only [NH_pre_2_1_8]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_pim_eq_2_1_8 :
    N_re_2_8 * H_im_8_1 + N_im_2_8 * H_re_8_1 =
      NH_pim_2_1_8 := by
  rw [z_N_re_2_8, z_H_im_8_1, z_N_im_2_8,
    z_H_re_8_1]
  simp only [NH_pim_2_1_8]
  simp (disch := decide) only [interp_neg, interp_mul, interp_add,
    interp_sub, interp_add_gen, interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide
theorem NH_term_2_1_8 :
    N_entry_2_8 * H_entry_8_1 =
      ofLadj NH_pre_2_1_8 NH_pim_2_1_8 := by
  rw [N_entry_2_8, H_entry_8_1, ofLadj_mul,
    NH_pre_eq_2_1_8, NH_pim_eq_2_1_8]

theorem NH_sum_poly_re_2_1 :
    NH_pre_2_1_0 + NH_pre_2_1_1 + NH_pre_2_1_2 + NH_pre_2_1_3 + NH_pre_2_1_4 + NH_pre_2_1_5 + NH_pre_2_1_6 + NH_pre_2_1_7 + NH_pre_2_1_8 = (0 : Polynomial ℚ) + Phi11 * NH_qre_2_1 := by
  rw [phi11_interp]
  simp only [NH_pre_2_1_0, NH_pre_2_1_1, NH_pre_2_1_2, NH_pre_2_1_3, NH_pre_2_1_4, NH_pre_2_1_5, NH_pre_2_1_6, NH_pre_2_1_7, NH_pre_2_1_8, NH_qre_2_1]
  simp (disch := decide) only [interp_zero, interp_one, interp_ofNat,
    interp_neg, interp_mul, interp_add, interp_sub, interp_add_gen,
    interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide

theorem NH_sum_poly_im_2_1 :
    NH_pim_2_1_0 + NH_pim_2_1_1 + NH_pim_2_1_2 + NH_pim_2_1_3 + NH_pim_2_1_4 + NH_pim_2_1_5 + NH_pim_2_1_6 + NH_pim_2_1_7 + NH_pim_2_1_8 = (0 : Polynomial ℚ) + Phi11 * NH_qim_2_1 := by
  rw [phi11_interp]
  simp only [NH_pim_2_1_0, NH_pim_2_1_1, NH_pim_2_1_2, NH_pim_2_1_3, NH_pim_2_1_4, NH_pim_2_1_5, NH_pim_2_1_6, NH_pim_2_1_7, NH_pim_2_1_8, NH_qim_2_1]
  simp (disch := decide) only [interp_zero, interp_one, interp_ofNat,
    interp_neg, interp_mul, interp_add, interp_sub, interp_add_gen,
    interp_sub_gen, Nat.reduceMul]
  apply interp_eq
  · decide
  · decide
  · decide

theorem NH_sum_entries_2_1 :
    N_entry_2_0 * H_entry_0_1 + N_entry_2_1 * H_entry_1_1 + N_entry_2_2 * H_entry_2_1 + N_entry_2_3 * H_entry_3_1 + N_entry_2_4 * H_entry_4_1 + N_entry_2_5 * H_entry_5_1 + N_entry_2_6 * H_entry_6_1 + N_entry_2_7 * H_entry_7_1 + N_entry_2_8 * H_entry_8_1 =
      ofLadj (NH_pre_2_1_0 + NH_pre_2_1_1 + NH_pre_2_1_2 + NH_pre_2_1_3 + NH_pre_2_1_4 + NH_pre_2_1_5 + NH_pre_2_1_6 + NH_pre_2_1_7 + NH_pre_2_1_8) (NH_pim_2_1_0 + NH_pim_2_1_1 + NH_pim_2_1_2 + NH_pim_2_1_3 + NH_pim_2_1_4 + NH_pim_2_1_5 + NH_pim_2_1_6 + NH_pim_2_1_7 + NH_pim_2_1_8) := by
  simp only [NH_term_2_1_0, NH_term_2_1_1, NH_term_2_1_2, NH_term_2_1_3, NH_term_2_1_4, NH_term_2_1_5, NH_term_2_1_6, NH_term_2_1_7, NH_term_2_1_8]
  simpa [add_assoc] using ofLadj_add9 NH_pre_2_1_0 NH_pim_2_1_0 NH_pre_2_1_1 NH_pim_2_1_1 NH_pre_2_1_2 NH_pim_2_1_2 NH_pre_2_1_3 NH_pim_2_1_3 NH_pre_2_1_4 NH_pim_2_1_4 NH_pre_2_1_5 NH_pim_2_1_5 NH_pre_2_1_6 NH_pim_2_1_6 NH_pre_2_1_7 NH_pim_2_1_7 NH_pre_2_1_8 NH_pim_2_1_8

theorem NH_eval_2_1 :
    ofLadj (NH_pre_2_1_0 + NH_pre_2_1_1 + NH_pre_2_1_2 + NH_pre_2_1_3 + NH_pre_2_1_4 + NH_pre_2_1_5 + NH_pre_2_1_6 + NH_pre_2_1_7 + NH_pre_2_1_8) (NH_pim_2_1_0 + NH_pim_2_1_1 + NH_pim_2_1_2 + NH_pim_2_1_3 + NH_pim_2_1_4 + NH_pim_2_1_5 + NH_pim_2_1_6 + NH_pim_2_1_7 + NH_pim_2_1_8) = 0 := by
  rw [NH_sum_poly_re_2_1, NH_sum_poly_im_2_1, ofLadj_add_Phi11]
  exact ofLadj_zero

public theorem NH_entry_2_1 : (N * H) 2 1 = 0 := by
  rw [mul_apply_fin9_N]
  rw [N_apply_2_0, H_apply_0_1]
  rw [N_apply_2_1, H_apply_1_1]
  rw [N_apply_2_2, H_apply_2_1]
  rw [N_apply_2_3, H_apply_3_1]
  rw [N_apply_2_4, H_apply_4_1]
  rw [N_apply_2_5, H_apply_5_1]
  rw [N_apply_2_6, H_apply_6_1]
  rw [N_apply_2_7, H_apply_7_1]
  rw [N_apply_2_8, H_apply_8_1]
  exact (NH_sum_entries_2_1).trans NH_eval_2_1

end V14Formalization.D12SigmaPlusSegreCore
