/-
Apply lemmas for spanV.
-/
import V14Formalization.D12SigmaPlusSegreApply_spanV_0
import V14Formalization.D12SigmaPlusSegreApply_spanV_1
import V14Formalization.D12SigmaPlusSegreApply_spanV_2
import V14Formalization.D12SigmaPlusSegreApply_spanV_3
import V14Formalization.D12SigmaPlusSegreApply_spanV_4
import V14Formalization.D12SigmaPlusSegreApply_spanV_5
import V14Formalization.D12SigmaPlusSegreApply_spanV_6
import V14Formalization.D12SigmaPlusSegreApply_spanV_7
import V14Formalization.D12SigmaPlusSegreApply_spanV_8
