/-
Apply lemmas for spanU.
-/
import V14Formalization.D12SigmaPlusSegreApply_spanU_0
import V14Formalization.D12SigmaPlusSegreApply_spanU_1
import V14Formalization.D12SigmaPlusSegreApply_spanU_2
import V14Formalization.D12SigmaPlusSegreApply_spanU_3
import V14Formalization.D12SigmaPlusSegreApply_spanU_4
import V14Formalization.D12SigmaPlusSegreApply_spanU_5
import V14Formalization.D12SigmaPlusSegreApply_spanU_6
import V14Formalization.D12SigmaPlusSegreApply_spanU_7
import V14Formalization.D12SigmaPlusSegreApply_spanU_8
import V14Formalization.D12SigmaPlusSegreApply_spanU_9
import V14Formalization.D12SigmaPlusSegreApply_spanU_10
import V14Formalization.D12SigmaPlusSegreApply_spanU_11
import V14Formalization.D12SigmaPlusSegreApply_spanU_12
import V14Formalization.D12SigmaPlusSegreApply_spanU_13
import V14Formalization.D12SigmaPlusSegreApply_spanU_14
