/-
Auto-generated by scripts/export_sigma_plus_minor_h.py.
Stock-limit, kernel-checkable H-minor vs stored minorQ identities.
-/
import V14Formalization.D12SigmaPlusSegreEval
import V14Formalization.D12SigmaPlusSegreApplyH
import V14Formalization.D12SigmaPlusSegreMinorQ
import V14Formalization.D12SigmaPlusSegreGeom

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData
open D12SigmaPlusQuadric6

def HM_4_1_A_pre : Polynomial ℚ := C (8) * X ^ 3 + C (16) * X ^ 4 + C (8) * X ^ 5 + C (12) * X ^ 6 + C (8) * X ^ 7 + C (8) * X ^ 8 + C (-16) * X ^ 9 + C (-8) * X ^ 11 + C (-16) * X ^ 13 + C (-8) * X ^ 15 + C (-4) * X ^ 16 + C (-8) * X ^ 17
def HM_4_1_A_pim : Polynomial ℚ := (0 : Polynomial ℚ)
theorem HM_4_1_A_pre_eq :
    H_re_0_0 * H_re_8_1 - H_im_0_0 * H_im_8_1 =
      HM_4_1_A_pre := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_0_0, H_im_0_0, H_re_8_1, H_im_8_1,
    HM_4_1_A_pre]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_4_1_A_pim_eq :
    H_re_0_0 * H_im_8_1 + H_im_0_0 * H_re_8_1 =
      HM_4_1_A_pim := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_0_0, H_im_0_0, H_re_8_1, H_im_8_1,
    HM_4_1_A_pim]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_4_1_A_mul :
    H_entry_0_0 * H_entry_8_1 =
      ofLadj HM_4_1_A_pre HM_4_1_A_pim := by
  rw [H_entry_0_0, H_entry_8_1, ofLadj_mul,
    HM_4_1_A_pre_eq, HM_4_1_A_pim_eq]

def HM_4_1_B_pre : Polynomial ℚ := C (-4) + C (-16) * X + C (-32) * X ^ 2 + C (-36) * X ^ 3 + C (-30) * X ^ 4 + C (-38) * X ^ 5 + C (-40) * X ^ 6 + C (-32) * X ^ 7 + C (-38) * X ^ 8 + C (-60) * X ^ 9 + C (-56) * X ^ 10 + C (-44) * X ^ 11 + C (-40) * X ^ 12 + C (-28) * X ^ 13 + C (-2) * X ^ 14 + C (2) * X ^ 15 + C (2) * X ^ 16 + C (4) * X ^ 17 + C (4) * X ^ 18
def HM_4_1_B_pim : Polynomial ℚ := (0 : Polynomial ℚ)
theorem HM_4_1_B_pre_eq :
    H_re_0_1 * H_re_8_0 - H_im_0_1 * H_im_8_0 =
      HM_4_1_B_pre := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_0_1, H_im_0_1, H_re_8_0, H_im_8_0,
    HM_4_1_B_pre]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_4_1_B_pim_eq :
    H_re_0_1 * H_im_8_0 + H_im_0_1 * H_re_8_0 =
      HM_4_1_B_pim := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_0_1, H_im_0_1, H_re_8_0, H_im_8_0,
    HM_4_1_B_pim]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_4_1_B_mul :
    H_entry_0_1 * H_entry_8_0 =
      ofLadj HM_4_1_B_pre HM_4_1_B_pim := by
  rw [H_entry_0_1, H_entry_8_0, ofLadj_mul,
    HM_4_1_B_pre_eq, HM_4_1_B_pim_eq]

def HM_4_1_C_pre : Polynomial ℚ := C (8) * X + C (10) * X ^ 2 + C (22) * X ^ 3 + C (20) * X ^ 4 + C (14) * X ^ 5 + C (2) * X ^ 6 + C (-8) * X ^ 7 + C (-18) * X ^ 8 + C (-34) * X ^ 9 + C (-26) * X ^ 10 + C (-26) * X ^ 11 + C (-34) * X ^ 12 + C (-44) * X ^ 13 + C (-40) * X ^ 14 + C (-36) * X ^ 15 + C (-28) * X ^ 16 + C (-16) * X ^ 17 + C (-8) * X ^ 18
def HM_4_1_C_pim : Polynomial ℚ := C (4) + C (8) * X + C (18) * X ^ 2 + C (34) * X ^ 3 + C (48) * X ^ 4 + C (68) * X ^ 5 + C (72) * X ^ 6 + C (76) * X ^ 7 + C (70) * X ^ 8 + C (74) * X ^ 9 + C (68) * X ^ 10 + C (62) * X ^ 11 + C (56) * X ^ 12 + C (40) * X ^ 13 + C (28) * X ^ 14 + C (12) * X ^ 15 + C (-8) * X ^ 17 + C (-4) * X ^ 18
theorem HM_4_1_C_pre_eq :
    H_re_2_0 * H_re_6_1 - H_im_2_0 * H_im_6_1 =
      HM_4_1_C_pre := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_2_0, H_im_2_0, H_re_6_1, H_im_6_1,
    HM_4_1_C_pre]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_4_1_C_pim_eq :
    H_re_2_0 * H_im_6_1 + H_im_2_0 * H_re_6_1 =
      HM_4_1_C_pim := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_2_0, H_im_2_0, H_re_6_1, H_im_6_1,
    HM_4_1_C_pim]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_4_1_C_mul :
    H_entry_2_0 * H_entry_6_1 =
      ofLadj HM_4_1_C_pre HM_4_1_C_pim := by
  rw [H_entry_2_0, H_entry_6_1, ofLadj_mul,
    HM_4_1_C_pre_eq, HM_4_1_C_pim_eq]

def HM_4_1_D_pre : Polynomial ℚ := C (8) * X + C (10) * X ^ 2 + C (22) * X ^ 3 + C (20) * X ^ 4 + C (14) * X ^ 5 + C (2) * X ^ 6 + C (-8) * X ^ 7 + C (-18) * X ^ 8 + C (-34) * X ^ 9 + C (-26) * X ^ 10 + C (-26) * X ^ 11 + C (-34) * X ^ 12 + C (-44) * X ^ 13 + C (-40) * X ^ 14 + C (-36) * X ^ 15 + C (-28) * X ^ 16 + C (-16) * X ^ 17 + C (-8) * X ^ 18
def HM_4_1_D_pim : Polynomial ℚ := C (-4) + C (-8) * X + C (-18) * X ^ 2 + C (-34) * X ^ 3 + C (-48) * X ^ 4 + C (-68) * X ^ 5 + C (-72) * X ^ 6 + C (-76) * X ^ 7 + C (-70) * X ^ 8 + C (-74) * X ^ 9 + C (-68) * X ^ 10 + C (-62) * X ^ 11 + C (-56) * X ^ 12 + C (-40) * X ^ 13 + C (-28) * X ^ 14 + C (-12) * X ^ 15 + C (8) * X ^ 17 + C (4) * X ^ 18
theorem HM_4_1_D_pre_eq :
    H_re_2_1 * H_re_6_0 - H_im_2_1 * H_im_6_0 =
      HM_4_1_D_pre := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_2_1, H_im_2_1, H_re_6_0, H_im_6_0,
    HM_4_1_D_pre]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_4_1_D_pim_eq :
    H_re_2_1 * H_im_6_0 + H_im_2_1 * H_re_6_0 =
      HM_4_1_D_pim := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_2_1, H_im_2_1, H_re_6_0, H_im_6_0,
    HM_4_1_D_pim]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_4_1_D_mul :
    H_entry_2_1 * H_entry_6_0 =
      ofLadj HM_4_1_D_pre HM_4_1_D_pim := by
  rw [H_entry_2_1, H_entry_6_0, ofLadj_mul,
    HM_4_1_D_pre_eq, HM_4_1_D_pim_eq]

def HM_4_1_qre : Polynomial ℚ := C (-4) + C (-28) * X + C (-16) * X ^ 2 + C (-34) * X ^ 3 + C (12) * X ^ 4 + C (12) * X ^ 5 + C (26) * X ^ 6 + C (8) * X ^ 7 + C (20) * X ^ 8
def HM_4_1_qim : Polynomial ℚ := (0 : Polynomial ℚ)
theorem HM_4_1_bilin :
    bilinearCoeffs (Hrow 0) (Hrow 8) 1 -
        bilinearCoeffs (Hrow 2) (Hrow 6) 1 =
      (ofLadj HM_4_1_A_pre HM_4_1_A_pim +
          ofLadj HM_4_1_B_pre HM_4_1_B_pim) -
        (ofLadj HM_4_1_C_pre HM_4_1_C_pim +
            ofLadj HM_4_1_D_pre HM_4_1_D_pim) := by
  have hpq : bilinearCoeffs (Hrow 0) (Hrow 8) 1 =
      H_entry_0_0 * H_entry_8_1 +
        H_entry_0_1 * H_entry_8_0 := by
    simp [bilinearCoeffs, monomPair_1, Hrow, H_apply_0_0,
      H_apply_8_1, H_apply_0_1, H_apply_8_0]
  have hrt : bilinearCoeffs (Hrow 2) (Hrow 6) 1 =
      H_entry_2_0 * H_entry_6_1 +
        H_entry_2_1 * H_entry_6_0 := by
    simp [bilinearCoeffs, monomPair_1, Hrow, H_apply_2_0,
      H_apply_6_1, H_apply_2_1, H_apply_6_0]
  rw [hpq, hrt, HM_4_1_A_mul, HM_4_1_B_mul, HM_4_1_C_mul, HM_4_1_D_mul]
theorem HM_4_1_sum :
    (ofLadj HM_4_1_A_pre HM_4_1_A_pim +
        ofLadj HM_4_1_B_pre HM_4_1_B_pim) -
      (ofLadj HM_4_1_C_pre HM_4_1_C_pim +
          ofLadj HM_4_1_D_pre HM_4_1_D_pim) =
      ofLadj (HM_4_1_A_pre + HM_4_1_B_pre - HM_4_1_C_pre - HM_4_1_D_pre)
        (HM_4_1_A_pim + HM_4_1_B_pim - HM_4_1_C_pim - HM_4_1_D_pim) := by
  rw [ofLadj_add, ofLadj_add, ofLadj_sub, sub_add_eq_sub_sub,
    sub_add_eq_sub_sub]
theorem HM_4_1_red :
    HM_4_1_A_pre + HM_4_1_B_pre - HM_4_1_C_pre - HM_4_1_D_pre =
      minorQ_re_4_1 + Phi11 * HM_4_1_qre := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [HM_4_1_A_pre, HM_4_1_B_pre, HM_4_1_C_pre, HM_4_1_D_pre,
    minorQ_re_4_1, HM_4_1_qre]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_4_1_redim :
    HM_4_1_A_pim + HM_4_1_B_pim - HM_4_1_C_pim - HM_4_1_D_pim =
      minorQ_im_4_1 + Phi11 * HM_4_1_qim := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [HM_4_1_A_pim, HM_4_1_B_pim, HM_4_1_C_pim, HM_4_1_D_pim,
    minorQ_im_4_1, HM_4_1_qim]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem HM_entry_4_1 :
    minorCoeffsH 4 1 = minorQ 4 1 := by
  unfold minorCoeffsH
  simp [minorOrder_4, crossIndex]
  change bilinearCoeffs (Hrow 0) (Hrow 8) 1 -
      bilinearCoeffs (Hrow 2) (Hrow 6) 1 =
    minorQ 4 1
  rw [HM_4_1_bilin, HM_4_1_sum, HM_4_1_red, HM_4_1_redim,
    ofLadj_add_Phi11]
  change ofLadj minorQ_re_4_1 minorQ_im_4_1 = minorQ 4 1
  rfl

end V14Formalization.D12SigmaPlusSegreCore
