/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
module

public import V14Formalization.D12SigmaPlusSegreEval
public import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def UM_qre_4_5 : Polynomial ℚ := C ((-3 / 11 : ℚ)) + C ((5 / 11 : ℚ)) * X + C ((1 / 11 : ℚ)) * X ^ 2 + C ((5 / 11 : ℚ)) * X ^ 3 + C ((9 / 11 : ℚ)) * X ^ 4 + C ((-12 / 11 : ℚ)) * X ^ 5 + C ((2 / 11 : ℚ)) * X ^ 6 + C ((-9 / 11 : ℚ)) * X ^ 7 + C ((2 / 11 : ℚ)) * X ^ 8
def UM_qim_4_5 : Polynomial ℚ := (0 : Polynomial ℚ)

def UM_pre_4_5_0 : Polynomial ℚ := C ((-2 / 11 : ℚ)) * X ^ 5 + C ((-4 / 11 : ℚ)) * X ^ 6 + C ((-7 / 11 : ℚ)) * X ^ 7 + C ((-1 / 11 : ℚ)) * X ^ 8 + C ((6 / 11 : ℚ)) * X ^ 9 + C ((5 / 11 : ℚ)) * X ^ 10 + C ((6 / 11 : ℚ)) * X ^ 11 + C ((5 / 11 : ℚ)) * X ^ 12 + C ((6 / 11 : ℚ)) * X ^ 13 + C ((-1 / 11 : ℚ)) * X ^ 14 + C ((-7 / 11 : ℚ)) * X ^ 15 + C ((-4 / 11 : ℚ)) * X ^ 16 + C ((-2 / 11 : ℚ)) * X ^ 17
def UM_pim_4_5_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_pre_eq_4_5_0 :
    spanU_re_4_0 * minorQ_re_0_5 - spanU_im_4_0 * minorQ_im_0_5 =
      UM_pre_4_5_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_0, spanU_im_4_0, minorQ_re_0_5, minorQ_im_0_5,
    UM_pre_4_5_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_4_5_0 :
    spanU_re_4_0 * minorQ_im_0_5 + spanU_im_4_0 * minorQ_re_0_5 =
      UM_pim_4_5_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_0, spanU_im_4_0, minorQ_re_0_5, minorQ_im_0_5,
    UM_pim_4_5_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_4_5_0 :
    spanU_entry_4_0 * minorQ_entry_0_5 =
      ofLadj UM_pre_4_5_0 UM_pim_4_5_0 := by
  rw [spanU_entry_4_0, minorQ_entry_0_5, ofLadj_mul,
    UM_pre_eq_4_5_0, UM_pim_eq_4_5_0]

def UM_pre_4_5_1 : Polynomial ℚ := C ((-1 / 11 : ℚ)) + C ((-3 / 22 : ℚ)) * X ^ 2 + C ((-3 / 22 : ℚ)) * X ^ 3 + C ((-1 / 22 : ℚ)) * X ^ 4 + C ((-5 / 22 : ℚ)) * X ^ 5 + C ((-3 / 22 : ℚ)) * X ^ 6 + C ((-3 / 22 : ℚ)) * X ^ 8 + C ((1 / 11 : ℚ)) * X ^ 9 + C ((3 / 11 : ℚ)) * X ^ 10 + C ((2 / 11 : ℚ)) * X ^ 11 + C ((3 / 11 : ℚ)) * X ^ 12 + C ((5 / 22 : ℚ)) * X ^ 13 + C ((-1 / 11 : ℚ)) * X ^ 17 + C ((-1 / 22 : ℚ)) * X ^ 18
def UM_pim_4_5_1 : Polynomial ℚ := C ((-1 / 11 : ℚ)) * X ^ 3 + C ((-1 / 11 : ℚ)) * X ^ 4 + C ((-1 / 22 : ℚ)) * X ^ 5 + C ((-1 / 11 : ℚ)) * X ^ 6 + C ((3 / 22 : ℚ)) * X ^ 7 + C ((5 / 22 : ℚ)) * X ^ 8 + C ((3 / 22 : ℚ)) * X ^ 9 + C ((5 / 22 : ℚ)) * X ^ 10 + C ((-5 / 22 : ℚ)) * X ^ 12 + C ((-3 / 22 : ℚ)) * X ^ 13 + C ((-3 / 22 : ℚ)) * X ^ 14 + C ((-1 / 22 : ℚ)) * X ^ 15 + C ((1 / 11 : ℚ)) * X ^ 16 + C ((1 / 22 : ℚ)) * X ^ 17
theorem UM_pre_eq_4_5_1 :
    spanU_re_4_1 * minorQ_re_1_5 - spanU_im_4_1 * minorQ_im_1_5 =
      UM_pre_4_5_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_1, spanU_im_4_1, minorQ_re_1_5, minorQ_im_1_5,
    UM_pre_4_5_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_4_5_1 :
    spanU_re_4_1 * minorQ_im_1_5 + spanU_im_4_1 * minorQ_re_1_5 =
      UM_pim_4_5_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_1, spanU_im_4_1, minorQ_re_1_5, minorQ_im_1_5,
    UM_pim_4_5_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_4_5_1 :
    spanU_entry_4_1 * minorQ_entry_1_5 =
      ofLadj UM_pre_4_5_1 UM_pim_4_5_1 := by
  rw [spanU_entry_4_1, minorQ_entry_1_5, ofLadj_mul,
    UM_pre_eq_4_5_1, UM_pim_eq_4_5_1]

def UM_pre_4_5_2 : Polynomial ℚ := C ((-1 / 22 : ℚ)) + C ((1 / 11 : ℚ)) * X + C ((3 / 11 : ℚ)) * X ^ 2 + C ((1 / 2 : ℚ)) * X ^ 3 + C ((9 / 11 : ℚ)) * X ^ 4 + C ((6 / 11 : ℚ)) * X ^ 5 + C ((7 / 11 : ℚ)) * X ^ 6 + C ((5 / 22 : ℚ)) * X ^ 7 + C ((2 / 11 : ℚ)) * X ^ 8 + C ((-4 / 11 : ℚ)) * X ^ 9 + C ((-1 / 2 : ℚ)) * X ^ 10 + C ((-7 / 22 : ℚ)) * X ^ 11 + C ((-13 / 22 : ℚ)) * X ^ 12 + C ((-7 / 11 : ℚ)) * X ^ 13 + C ((-7 / 22 : ℚ)) * X ^ 14 + C ((-5 / 11 : ℚ)) * X ^ 15 + C ((-1 / 22 : ℚ)) * X ^ 16 + C ((-3 / 22 : ℚ)) * X ^ 17 + C ((3 / 22 : ℚ)) * X ^ 18
def UM_pim_4_5_2 : Polynomial ℚ := C ((1 / 11 : ℚ)) + C ((2 / 11 : ℚ)) * X + C ((5 / 22 : ℚ)) * X ^ 2 + C ((1 / 11 : ℚ)) * X ^ 3 + C ((-1 / 22 : ℚ)) * X ^ 4 + C ((-15 / 22 : ℚ)) * X ^ 5 + C ((-7 / 11 : ℚ)) * X ^ 6 + C ((-10 / 11 : ℚ)) * X ^ 7 + C ((-27 / 22 : ℚ)) * X ^ 8 + C ((-19 / 22 : ℚ)) * X ^ 9 + C ((-19 / 22 : ℚ)) * X ^ 10 + C ((-13 / 22 : ℚ)) * X ^ 11 + C ((-7 / 22 : ℚ)) * X ^ 12 + C ((-4 / 11 : ℚ)) * X ^ 13 + C ((3 / 22 : ℚ)) * X ^ 14 + C ((-1 / 11 : ℚ)) * X ^ 15 + C ((3 / 22 : ℚ)) * X ^ 16 + C ((2 / 11 : ℚ)) * X ^ 17 + C ((1 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_4_5_2 :
    spanU_re_4_2 * minorQ_re_2_5 - spanU_im_4_2 * minorQ_im_2_5 =
      UM_pre_4_5_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_2, spanU_im_4_2, minorQ_re_2_5, minorQ_im_2_5,
    UM_pre_4_5_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_4_5_2 :
    spanU_re_4_2 * minorQ_im_2_5 + spanU_im_4_2 * minorQ_re_2_5 =
      UM_pim_4_5_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_2, spanU_im_4_2, minorQ_re_2_5, minorQ_im_2_5,
    UM_pim_4_5_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_4_5_2 :
    spanU_entry_4_2 * minorQ_entry_2_5 =
      ofLadj UM_pre_4_5_2 UM_pim_4_5_2 := by
  rw [spanU_entry_4_2, minorQ_entry_2_5, ofLadj_mul,
    UM_pre_eq_4_5_2, UM_pim_eq_4_5_2]

def UM_pre_4_5_3 : Polynomial ℚ := C ((-1 / 11 : ℚ)) + C ((-3 / 22 : ℚ)) * X ^ 2 + C ((-3 / 22 : ℚ)) * X ^ 3 + C ((-1 / 22 : ℚ)) * X ^ 4 + C ((-5 / 22 : ℚ)) * X ^ 5 + C ((-3 / 22 : ℚ)) * X ^ 6 + C ((-3 / 22 : ℚ)) * X ^ 8 + C ((1 / 11 : ℚ)) * X ^ 9 + C ((3 / 11 : ℚ)) * X ^ 10 + C ((2 / 11 : ℚ)) * X ^ 11 + C ((3 / 11 : ℚ)) * X ^ 12 + C ((5 / 22 : ℚ)) * X ^ 13 + C ((-1 / 11 : ℚ)) * X ^ 17 + C ((-1 / 22 : ℚ)) * X ^ 18
def UM_pim_4_5_3 : Polynomial ℚ := C ((1 / 11 : ℚ)) * X ^ 3 + C ((1 / 11 : ℚ)) * X ^ 4 + C ((1 / 22 : ℚ)) * X ^ 5 + C ((1 / 11 : ℚ)) * X ^ 6 + C ((-3 / 22 : ℚ)) * X ^ 7 + C ((-5 / 22 : ℚ)) * X ^ 8 + C ((-3 / 22 : ℚ)) * X ^ 9 + C ((-5 / 22 : ℚ)) * X ^ 10 + C ((5 / 22 : ℚ)) * X ^ 12 + C ((3 / 22 : ℚ)) * X ^ 13 + C ((3 / 22 : ℚ)) * X ^ 14 + C ((1 / 22 : ℚ)) * X ^ 15 + C ((-1 / 11 : ℚ)) * X ^ 16 + C ((-1 / 22 : ℚ)) * X ^ 17
theorem UM_pre_eq_4_5_3 :
    spanU_re_4_3 * minorQ_re_3_5 - spanU_im_4_3 * minorQ_im_3_5 =
      UM_pre_4_5_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_3, spanU_im_4_3, minorQ_re_3_5, minorQ_im_3_5,
    UM_pre_4_5_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_4_5_3 :
    spanU_re_4_3 * minorQ_im_3_5 + spanU_im_4_3 * minorQ_re_3_5 =
      UM_pim_4_5_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_3, spanU_im_4_3, minorQ_re_3_5, minorQ_im_3_5,
    UM_pim_4_5_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_4_5_3 :
    spanU_entry_4_3 * minorQ_entry_3_5 =
      ofLadj UM_pre_4_5_3 UM_pim_4_5_3 := by
  rw [spanU_entry_4_3, minorQ_entry_3_5, ofLadj_mul,
    UM_pre_eq_4_5_3, UM_pim_eq_4_5_3]

def UM_pre_4_5_4 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_4_5_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_4_5_4 :
    spanU_entry_4_4 * minorQ_entry_4_5 =
      ofLadj UM_pre_4_5_4 UM_pim_4_5_4 := by
  have hz : spanU_entry_4_4 = 0 := by
    rw [spanU_entry_4_4]; exact ofLadj_zero
  rw [hz, UM_pre_4_5_4, UM_pim_4_5_4]
  simp [ofLadj_zero]

def UM_pre_4_5_5 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_4_5_5 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_4_5_5 :
    spanU_entry_4_5 * minorQ_entry_5_5 =
      ofLadj UM_pre_4_5_5 UM_pim_4_5_5 := by
  have hz : spanU_entry_4_5 = 0 := by
    rw [spanU_entry_4_5]; exact ofLadj_zero
  rw [hz, UM_pre_4_5_5, UM_pim_4_5_5]
  simp [ofLadj_zero]

def UM_pre_4_5_6 : Polynomial ℚ := C ((-1 / 22 : ℚ)) + C ((1 / 11 : ℚ)) * X + C ((3 / 11 : ℚ)) * X ^ 2 + C ((1 / 2 : ℚ)) * X ^ 3 + C ((9 / 11 : ℚ)) * X ^ 4 + C ((6 / 11 : ℚ)) * X ^ 5 + C ((7 / 11 : ℚ)) * X ^ 6 + C ((5 / 22 : ℚ)) * X ^ 7 + C ((2 / 11 : ℚ)) * X ^ 8 + C ((-4 / 11 : ℚ)) * X ^ 9 + C ((-1 / 2 : ℚ)) * X ^ 10 + C ((-7 / 22 : ℚ)) * X ^ 11 + C ((-13 / 22 : ℚ)) * X ^ 12 + C ((-7 / 11 : ℚ)) * X ^ 13 + C ((-7 / 22 : ℚ)) * X ^ 14 + C ((-5 / 11 : ℚ)) * X ^ 15 + C ((-1 / 22 : ℚ)) * X ^ 16 + C ((-3 / 22 : ℚ)) * X ^ 17 + C ((3 / 22 : ℚ)) * X ^ 18
def UM_pim_4_5_6 : Polynomial ℚ := C ((-1 / 11 : ℚ)) + C ((-2 / 11 : ℚ)) * X + C ((-5 / 22 : ℚ)) * X ^ 2 + C ((-1 / 11 : ℚ)) * X ^ 3 + C ((1 / 22 : ℚ)) * X ^ 4 + C ((15 / 22 : ℚ)) * X ^ 5 + C ((7 / 11 : ℚ)) * X ^ 6 + C ((10 / 11 : ℚ)) * X ^ 7 + C ((27 / 22 : ℚ)) * X ^ 8 + C ((19 / 22 : ℚ)) * X ^ 9 + C ((19 / 22 : ℚ)) * X ^ 10 + C ((13 / 22 : ℚ)) * X ^ 11 + C ((7 / 22 : ℚ)) * X ^ 12 + C ((4 / 11 : ℚ)) * X ^ 13 + C ((-3 / 22 : ℚ)) * X ^ 14 + C ((1 / 11 : ℚ)) * X ^ 15 + C ((-3 / 22 : ℚ)) * X ^ 16 + C ((-2 / 11 : ℚ)) * X ^ 17 + C ((-1 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_4_5_6 :
    spanU_re_4_6 * minorQ_re_6_5 - spanU_im_4_6 * minorQ_im_6_5 =
      UM_pre_4_5_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_6, spanU_im_4_6, minorQ_re_6_5, minorQ_im_6_5,
    UM_pre_4_5_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_4_5_6 :
    spanU_re_4_6 * minorQ_im_6_5 + spanU_im_4_6 * minorQ_re_6_5 =
      UM_pim_4_5_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_4_6, spanU_im_4_6, minorQ_re_6_5, minorQ_im_6_5,
    UM_pim_4_5_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_4_5_6 :
    spanU_entry_4_6 * minorQ_entry_6_5 =
      ofLadj UM_pre_4_5_6 UM_pim_4_5_6 := by
  rw [spanU_entry_4_6, minorQ_entry_6_5, ofLadj_mul,
    UM_pre_eq_4_5_6, UM_pim_eq_4_5_6]

def UM_pre_4_5_7 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_4_5_7 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_4_5_7 :
    spanU_entry_4_7 * minorQ_entry_7_5 =
      ofLadj UM_pre_4_5_7 UM_pim_4_5_7 := by
  have hz : spanU_entry_4_7 = 0 := by
    rw [spanU_entry_4_7]; exact ofLadj_zero
  rw [hz, UM_pre_4_5_7, UM_pim_4_5_7]
  simp [ofLadj_zero]

def UM_pre_4_5_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_4_5_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_4_5_8 :
    spanU_entry_4_8 * minorQ_entry_8_5 =
      ofLadj UM_pre_4_5_8 UM_pim_4_5_8 := by
  have hz : spanU_entry_4_8 = 0 := by
    rw [spanU_entry_4_8]; exact ofLadj_zero
  rw [hz, UM_pre_4_5_8, UM_pim_4_5_8]
  simp [ofLadj_zero]

theorem UM_sum_poly_re_4_5 :
    UM_pre_4_5_0 + UM_pre_4_5_1 + UM_pre_4_5_2 + UM_pre_4_5_3 + UM_pre_4_5_4 + UM_pre_4_5_5 + UM_pre_4_5_6 + UM_pre_4_5_7 + UM_pre_4_5_8 = Qplus_re_4_5 + Phi11 * UM_qre_4_5 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pre_4_5_0, UM_pre_4_5_1, UM_pre_4_5_2, UM_pre_4_5_3, UM_pre_4_5_4, UM_pre_4_5_5, UM_pre_4_5_6, UM_pre_4_5_7, UM_pre_4_5_8, Qplus_re_4_5, UM_qre_4_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_poly_im_4_5 :
    UM_pim_4_5_0 + UM_pim_4_5_1 + UM_pim_4_5_2 + UM_pim_4_5_3 + UM_pim_4_5_4 + UM_pim_4_5_5 + UM_pim_4_5_6 + UM_pim_4_5_7 + UM_pim_4_5_8 = Qplus_im_4_5 + Phi11 * UM_qim_4_5 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pim_4_5_0, UM_pim_4_5_1, UM_pim_4_5_2, UM_pim_4_5_3, UM_pim_4_5_4, UM_pim_4_5_5, UM_pim_4_5_6, UM_pim_4_5_7, UM_pim_4_5_8, Qplus_im_4_5, UM_qim_4_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_entries_4_5 :
    spanU_entry_4_0 * minorQ_entry_0_5 + spanU_entry_4_1 * minorQ_entry_1_5 + spanU_entry_4_2 * minorQ_entry_2_5 + spanU_entry_4_3 * minorQ_entry_3_5 + spanU_entry_4_4 * minorQ_entry_4_5 + spanU_entry_4_5 * minorQ_entry_5_5 + spanU_entry_4_6 * minorQ_entry_6_5 + spanU_entry_4_7 * minorQ_entry_7_5 + spanU_entry_4_8 * minorQ_entry_8_5 =
      ofLadj (UM_pre_4_5_0 + UM_pre_4_5_1 + UM_pre_4_5_2 + UM_pre_4_5_3 + UM_pre_4_5_4 + UM_pre_4_5_5 + UM_pre_4_5_6 + UM_pre_4_5_7 + UM_pre_4_5_8) (UM_pim_4_5_0 + UM_pim_4_5_1 + UM_pim_4_5_2 + UM_pim_4_5_3 + UM_pim_4_5_4 + UM_pim_4_5_5 + UM_pim_4_5_6 + UM_pim_4_5_7 + UM_pim_4_5_8) := by
  simp only [UM_term_4_5_0, UM_term_4_5_1, UM_term_4_5_2, UM_term_4_5_3, UM_term_4_5_4, UM_term_4_5_5, UM_term_4_5_6, UM_term_4_5_7, UM_term_4_5_8]
  simpa [add_assoc] using ofLadj_add9 UM_pre_4_5_0 UM_pim_4_5_0 UM_pre_4_5_1 UM_pim_4_5_1 UM_pre_4_5_2 UM_pim_4_5_2 UM_pre_4_5_3 UM_pim_4_5_3 UM_pre_4_5_4 UM_pim_4_5_4 UM_pre_4_5_5 UM_pim_4_5_5 UM_pre_4_5_6 UM_pim_4_5_6 UM_pre_4_5_7 UM_pim_4_5_7 UM_pre_4_5_8 UM_pim_4_5_8

theorem UM_eval_4_5 :
    ofLadj (UM_pre_4_5_0 + UM_pre_4_5_1 + UM_pre_4_5_2 + UM_pre_4_5_3 + UM_pre_4_5_4 + UM_pre_4_5_5 + UM_pre_4_5_6 + UM_pre_4_5_7 + UM_pre_4_5_8) (UM_pim_4_5_0 + UM_pim_4_5_1 + UM_pim_4_5_2 + UM_pim_4_5_3 + UM_pim_4_5_4 + UM_pim_4_5_5 + UM_pim_4_5_6 + UM_pim_4_5_7 + UM_pim_4_5_8) = Qplus_entry_4_5 := by
  rw [UM_sum_poly_re_4_5, UM_sum_poly_im_4_5,
    ofLadj_add_Phi11, Qplus_entry_4_5]

public theorem UM_entry_4_5 : (spanU * minorQ) 4 5 = Qplus 4 5 := by
  rw [Matrix.mul_apply]
  rw [sum_fin9]
  change spanU_entry_4_0 * minorQ_entry_0_5 + spanU_entry_4_1 * minorQ_entry_1_5 + spanU_entry_4_2 * minorQ_entry_2_5 + spanU_entry_4_3 * minorQ_entry_3_5 + spanU_entry_4_4 * minorQ_entry_4_5 + spanU_entry_4_5 * minorQ_entry_5_5 + spanU_entry_4_6 * minorQ_entry_6_5 + spanU_entry_4_7 * minorQ_entry_7_5 + spanU_entry_4_8 * minorQ_entry_8_5 = Qplus_entry_4_5
  exact (UM_sum_entries_4_5).trans UM_eval_4_5

end V14Formalization.D12SigmaPlusSegreCore
