/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
module

public import V14Formalization.D12SigmaPlusSegreEval
public import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def UM_qre_1_12 : Polynomial ℚ := C ((-73 / 22 : ℚ)) + C ((129 / 22 : ℚ)) * X + C ((-151 / 22 : ℚ)) * X ^ 2 + C ((239 / 22 : ℚ)) * X ^ 3 + C ((-265 / 22 : ℚ)) * X ^ 4 + C ((155 / 11 : ℚ)) * X ^ 5 + C ((-227 / 22 : ℚ)) * X ^ 6 + C (6) * X ^ 7 + C ((-17 / 22 : ℚ)) * X ^ 8
def UM_qim_1_12 : Polynomial ℚ := (0 : Polynomial ℚ)

def UM_pre_1_12_0 : Polynomial ℚ := C ((-3 / 22 : ℚ)) * X ^ 2 + C ((3 / 22 : ℚ)) * X ^ 4 + C ((-3 / 22 : ℚ)) * X ^ 5 + C ((-7 / 22 : ℚ)) * X ^ 6 + C ((1 / 22 : ℚ)) * X ^ 7 + C ((1 / 11 : ℚ)) * X ^ 8 + C ((-5 / 22 : ℚ)) * X ^ 9 + C ((5 / 22 : ℚ)) * X ^ 10 + C ((7 / 11 : ℚ)) * X ^ 11 + C ((5 / 22 : ℚ)) * X ^ 12 + C ((-1 / 11 : ℚ)) * X ^ 13 + C ((1 / 11 : ℚ)) * X ^ 14 + C ((-1 / 11 : ℚ)) * X ^ 15 + C ((-7 / 22 : ℚ)) * X ^ 16 + C ((-3 / 22 : ℚ)) * X ^ 17
def UM_pim_1_12_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_pre_eq_1_12_0 :
    spanU_re_1_0 * minorQ_re_0_12 - spanU_im_1_0 * minorQ_im_0_12 =
      UM_pre_1_12_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_0, spanU_im_1_0, minorQ_re_0_12, minorQ_im_0_12,
    UM_pre_1_12_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_12_0 :
    spanU_re_1_0 * minorQ_im_0_12 + spanU_im_1_0 * minorQ_re_0_12 =
      UM_pim_1_12_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_0, spanU_im_1_0, minorQ_re_0_12, minorQ_im_0_12,
    UM_pim_1_12_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_12_0 :
    spanU_entry_1_0 * minorQ_entry_0_12 =
      ofLadj UM_pre_1_12_0 UM_pim_1_12_0 := by
  rw [spanU_entry_1_0, minorQ_entry_0_12, ofLadj_mul,
    UM_pre_eq_1_12_0, UM_pim_eq_1_12_0]

def UM_pre_1_12_1 : Polynomial ℚ := C ((1 / 44 : ℚ)) + C ((8 / 11 : ℚ)) * X + C ((23 / 22 : ℚ)) * X ^ 2 + C ((41 / 22 : ℚ)) * X ^ 3 + C ((20 / 11 : ℚ)) * X ^ 4 + C ((163 / 44 : ℚ)) * X ^ 5 + C ((24 / 11 : ℚ)) * X ^ 6 + C ((57 / 22 : ℚ)) * X ^ 7 + C ((16 / 11 : ℚ)) * X ^ 8 + C ((25 / 11 : ℚ)) * X ^ 9 + C ((19 / 22 : ℚ)) * X ^ 10 + C ((21 / 22 : ℚ)) * X ^ 11 + C ((3 / 22 : ℚ)) * X ^ 12 + C ((27 / 22 : ℚ)) * X ^ 13 + C ((-9 / 22 : ℚ)) * X ^ 14 + C ((15 / 44 : ℚ)) * X ^ 15 + C ((-29 / 22 : ℚ)) * X ^ 16 + C ((9 / 44 : ℚ)) * X ^ 17 + C ((-19 / 44 : ℚ)) * X ^ 18
def UM_pim_1_12_1 : Polynomial ℚ := C ((-9 / 22 : ℚ)) + C ((-9 / 11 : ℚ)) * X + C ((-37 / 44 : ℚ)) * X ^ 2 + C ((-27 / 22 : ℚ)) * X ^ 3 + C ((-14 / 11 : ℚ)) * X ^ 4 + C ((-39 / 22 : ℚ)) * X ^ 5 + C ((-7 / 4 : ℚ)) * X ^ 6 + C ((-5 / 4 : ℚ)) * X ^ 7 + C ((-89 / 44 : ℚ)) * X ^ 8 + C ((-75 / 44 : ℚ)) * X ^ 9 + C ((-43 / 22 : ℚ)) * X ^ 10 + C ((-12 / 11 : ℚ)) * X ^ 11 + C ((-5 / 22 : ℚ)) * X ^ 12 + C ((-5 / 11 : ℚ)) * X ^ 13 + C ((1 / 4 : ℚ)) * X ^ 14 + C ((-1 / 11 : ℚ)) * X ^ 15 + C ((21 / 44 : ℚ)) * X ^ 16 + C ((1 / 22 : ℚ)) * X ^ 17 + C ((-17 / 44 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_12_1 :
    spanU_re_1_1 * minorQ_re_1_12 - spanU_im_1_1 * minorQ_im_1_12 =
      UM_pre_1_12_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_1, spanU_im_1_1, minorQ_re_1_12, minorQ_im_1_12,
    UM_pre_1_12_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_12_1 :
    spanU_re_1_1 * minorQ_im_1_12 + spanU_im_1_1 * minorQ_re_1_12 =
      UM_pim_1_12_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_1, spanU_im_1_1, minorQ_re_1_12, minorQ_im_1_12,
    UM_pim_1_12_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_12_1 :
    spanU_entry_1_1 * minorQ_entry_1_12 =
      ofLadj UM_pre_1_12_1 UM_pim_1_12_1 := by
  rw [spanU_entry_1_1, minorQ_entry_1_12, ofLadj_mul,
    UM_pre_eq_1_12_1, UM_pim_eq_1_12_1]

def UM_pre_1_12_2 : Polynomial ℚ := C ((-5 / 11 : ℚ)) + C ((-27 / 22 : ℚ)) * X ^ 2 + C ((-7 / 11 : ℚ)) * X ^ 3 + C ((-25 / 22 : ℚ)) * X ^ 4 + C ((-69 / 44 : ℚ)) * X ^ 5 + C ((-61 / 44 : ℚ)) * X ^ 6 + C ((-65 / 44 : ℚ)) * X ^ 7 + C ((-5 / 4 : ℚ)) * X ^ 8 + C ((-20 / 11 : ℚ)) * X ^ 9 + C ((-10 / 11 : ℚ)) * X ^ 10 + C ((-9 / 11 : ℚ)) * X ^ 11 + C ((-10 / 11 : ℚ)) * X ^ 12 + C ((-13 / 22 : ℚ)) * X ^ 13 + C ((-27 / 44 : ℚ)) * X ^ 14 + C ((-25 / 44 : ℚ)) * X ^ 15 + C ((-4 / 11 : ℚ)) * X ^ 16 + C ((-6 / 11 : ℚ)) * X ^ 17 + C ((-5 / 22 : ℚ)) * X ^ 18
def UM_pim_1_12_2 : Polynomial ℚ := C ((1 / 11 : ℚ)) + C ((2 / 11 : ℚ)) * X + C ((7 / 22 : ℚ)) * X ^ 2 + C ((10 / 11 : ℚ)) * X ^ 3 + C ((17 / 22 : ℚ)) * X ^ 4 + C ((61 / 44 : ℚ)) * X ^ 5 + C ((87 / 44 : ℚ)) * X ^ 6 + C ((5 / 4 : ℚ)) * X ^ 7 + C ((105 / 44 : ℚ)) * X ^ 8 + C ((21 / 11 : ℚ)) * X ^ 9 + C ((17 / 11 : ℚ)) * X ^ 10 + C ((31 / 22 : ℚ)) * X ^ 11 + C ((14 / 11 : ℚ)) * X ^ 12 + C ((17 / 22 : ℚ)) * X ^ 13 + C ((-13 / 44 : ℚ)) * X ^ 14 + C ((3 / 4 : ℚ)) * X ^ 15 + C ((-4 / 11 : ℚ)) * X ^ 17 + C ((5 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_12_2 :
    spanU_re_1_2 * minorQ_re_2_12 - spanU_im_1_2 * minorQ_im_2_12 =
      UM_pre_1_12_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_2, spanU_im_1_2, minorQ_re_2_12, minorQ_im_2_12,
    UM_pre_1_12_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_12_2 :
    spanU_re_1_2 * minorQ_im_2_12 + spanU_im_1_2 * minorQ_re_2_12 =
      UM_pim_1_12_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_2, spanU_im_1_2, minorQ_re_2_12, minorQ_im_2_12,
    UM_pim_1_12_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_12_2 :
    spanU_entry_1_2 * minorQ_entry_2_12 =
      ofLadj UM_pre_1_12_2 UM_pim_1_12_2 := by
  rw [spanU_entry_1_2, minorQ_entry_2_12, ofLadj_mul,
    UM_pre_eq_1_12_2, UM_pim_eq_1_12_2]

def UM_pre_1_12_3 : Polynomial ℚ := C ((1 / 44 : ℚ)) + C ((8 / 11 : ℚ)) * X + C ((23 / 22 : ℚ)) * X ^ 2 + C ((41 / 22 : ℚ)) * X ^ 3 + C ((20 / 11 : ℚ)) * X ^ 4 + C ((163 / 44 : ℚ)) * X ^ 5 + C ((24 / 11 : ℚ)) * X ^ 6 + C ((57 / 22 : ℚ)) * X ^ 7 + C ((16 / 11 : ℚ)) * X ^ 8 + C ((25 / 11 : ℚ)) * X ^ 9 + C ((19 / 22 : ℚ)) * X ^ 10 + C ((21 / 22 : ℚ)) * X ^ 11 + C ((3 / 22 : ℚ)) * X ^ 12 + C ((27 / 22 : ℚ)) * X ^ 13 + C ((-9 / 22 : ℚ)) * X ^ 14 + C ((15 / 44 : ℚ)) * X ^ 15 + C ((-29 / 22 : ℚ)) * X ^ 16 + C ((9 / 44 : ℚ)) * X ^ 17 + C ((-19 / 44 : ℚ)) * X ^ 18
def UM_pim_1_12_3 : Polynomial ℚ := C ((9 / 22 : ℚ)) + C ((9 / 11 : ℚ)) * X + C ((37 / 44 : ℚ)) * X ^ 2 + C ((27 / 22 : ℚ)) * X ^ 3 + C ((14 / 11 : ℚ)) * X ^ 4 + C ((39 / 22 : ℚ)) * X ^ 5 + C ((7 / 4 : ℚ)) * X ^ 6 + C ((5 / 4 : ℚ)) * X ^ 7 + C ((89 / 44 : ℚ)) * X ^ 8 + C ((75 / 44 : ℚ)) * X ^ 9 + C ((43 / 22 : ℚ)) * X ^ 10 + C ((12 / 11 : ℚ)) * X ^ 11 + C ((5 / 22 : ℚ)) * X ^ 12 + C ((5 / 11 : ℚ)) * X ^ 13 + C ((-1 / 4 : ℚ)) * X ^ 14 + C ((1 / 11 : ℚ)) * X ^ 15 + C ((-21 / 44 : ℚ)) * X ^ 16 + C ((-1 / 22 : ℚ)) * X ^ 17 + C ((17 / 44 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_12_3 :
    spanU_re_1_3 * minorQ_re_3_12 - spanU_im_1_3 * minorQ_im_3_12 =
      UM_pre_1_12_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_3, spanU_im_1_3, minorQ_re_3_12, minorQ_im_3_12,
    UM_pre_1_12_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_12_3 :
    spanU_re_1_3 * minorQ_im_3_12 + spanU_im_1_3 * minorQ_re_3_12 =
      UM_pim_1_12_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_3, spanU_im_1_3, minorQ_re_3_12, minorQ_im_3_12,
    UM_pim_1_12_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_12_3 :
    spanU_entry_1_3 * minorQ_entry_3_12 =
      ofLadj UM_pre_1_12_3 UM_pim_1_12_3 := by
  rw [spanU_entry_1_3, minorQ_entry_3_12, ofLadj_mul,
    UM_pre_eq_1_12_3, UM_pim_eq_1_12_3]

def UM_pre_1_12_4 : Polynomial ℚ := C ((-14 / 11 : ℚ)) * X ^ 2 + C ((14 / 11 : ℚ)) * X ^ 3 + C ((-13 / 11 : ℚ)) * X ^ 4 + C ((7 / 11 : ℚ)) * X ^ 5 + C ((-13 / 11 : ℚ)) * X ^ 6 + C ((7 / 22 : ℚ)) * X ^ 7 + C ((14 / 11 : ℚ)) * X ^ 8 + C ((-35 / 22 : ℚ)) * X ^ 9 + C ((26 / 11 : ℚ)) * X ^ 10 + C ((-14 / 11 : ℚ)) * X ^ 11 + C ((26 / 11 : ℚ)) * X ^ 12 + C ((-7 / 22 : ℚ)) * X ^ 13 + C ((7 / 22 : ℚ)) * X ^ 15 + C ((-13 / 11 : ℚ)) * X ^ 16 + C ((7 / 11 : ℚ)) * X ^ 17 + C ((-13 / 11 : ℚ)) * X ^ 18
def UM_pim_1_12_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_pre_eq_1_12_4 :
    spanU_re_1_4 * minorQ_re_4_12 - spanU_im_1_4 * minorQ_im_4_12 =
      UM_pre_1_12_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_4, spanU_im_1_4, minorQ_re_4_12, minorQ_im_4_12,
    UM_pre_1_12_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_12_4 :
    spanU_re_1_4 * minorQ_im_4_12 + spanU_im_1_4 * minorQ_re_4_12 =
      UM_pim_1_12_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_4, spanU_im_1_4, minorQ_re_4_12, minorQ_im_4_12,
    UM_pim_1_12_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_12_4 :
    spanU_entry_1_4 * minorQ_entry_4_12 =
      ofLadj UM_pre_1_12_4 UM_pim_1_12_4 := by
  rw [spanU_entry_1_4, minorQ_entry_4_12, ofLadj_mul,
    UM_pre_eq_1_12_4, UM_pim_eq_1_12_4]

def UM_pre_1_12_5 : Polynomial ℚ := C ((-27 / 22 : ℚ)) + C ((6 / 11 : ℚ)) * X + C ((-14 / 11 : ℚ)) * X ^ 2 + C ((9 / 44 : ℚ)) * X ^ 3 + C ((-75 / 44 : ℚ)) * X ^ 4 + C ((10 / 11 : ℚ)) * X ^ 5 + C ((-3 / 11 : ℚ)) * X ^ 6 + C ((31 / 22 : ℚ)) * X ^ 7 + C ((141 / 44 : ℚ)) * X ^ 9 + C ((-21 / 44 : ℚ)) * X ^ 10 + C ((107 / 22 : ℚ)) * X ^ 11 + C ((-45 / 44 : ℚ)) * X ^ 12 + C ((197 / 44 : ℚ)) * X ^ 13 + C ((-9 / 44 : ℚ)) * X ^ 14 + C ((175 / 44 : ℚ)) * X ^ 15 + C ((23 / 44 : ℚ)) * X ^ 16 + C ((75 / 44 : ℚ)) * X ^ 17 + C ((19 / 22 : ℚ)) * X ^ 18
def UM_pim_1_12_5 : Polynomial ℚ := C ((-3 / 2 : ℚ)) + C (-3) * X + C ((-47 / 22 : ℚ)) * X ^ 2 + C ((-179 / 44 : ℚ)) * X ^ 3 + C ((-173 / 44 : ℚ)) * X ^ 4 + C ((-46 / 11 : ℚ)) * X ^ 5 + C ((-71 / 11 : ℚ)) * X ^ 6 + C ((-58 / 11 : ℚ)) * X ^ 7 + C ((-387 / 44 : ℚ)) * X ^ 8 + C ((-317 / 44 : ℚ)) * X ^ 9 + C ((-359 / 44 : ℚ)) * X ^ 10 + C (-6) * X ^ 11 + C ((-169 / 44 : ℚ)) * X ^ 12 + C ((-249 / 44 : ℚ)) * X ^ 13 + C ((-47 / 22 : ℚ)) * X ^ 14 + C ((-195 / 44 : ℚ)) * X ^ 15 + C ((-113 / 44 : ℚ)) * X ^ 16 + C ((-79 / 44 : ℚ)) * X ^ 17 + C ((-15 / 11 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_12_5 :
    spanU_re_1_5 * minorQ_re_5_12 - spanU_im_1_5 * minorQ_im_5_12 =
      UM_pre_1_12_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_5, spanU_im_1_5, minorQ_re_5_12, minorQ_im_5_12,
    UM_pre_1_12_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_12_5 :
    spanU_re_1_5 * minorQ_im_5_12 + spanU_im_1_5 * minorQ_re_5_12 =
      UM_pim_1_12_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_5, spanU_im_1_5, minorQ_re_5_12, minorQ_im_5_12,
    UM_pim_1_12_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_12_5 :
    spanU_entry_1_5 * minorQ_entry_5_12 =
      ofLadj UM_pre_1_12_5 UM_pim_1_12_5 := by
  rw [spanU_entry_1_5, minorQ_entry_5_12, ofLadj_mul,
    UM_pre_eq_1_12_5, UM_pim_eq_1_12_5]

def UM_pre_1_12_6 : Polynomial ℚ := C ((-5 / 11 : ℚ)) + C ((-27 / 22 : ℚ)) * X ^ 2 + C ((-7 / 11 : ℚ)) * X ^ 3 + C ((-25 / 22 : ℚ)) * X ^ 4 + C ((-69 / 44 : ℚ)) * X ^ 5 + C ((-61 / 44 : ℚ)) * X ^ 6 + C ((-65 / 44 : ℚ)) * X ^ 7 + C ((-5 / 4 : ℚ)) * X ^ 8 + C ((-20 / 11 : ℚ)) * X ^ 9 + C ((-10 / 11 : ℚ)) * X ^ 10 + C ((-9 / 11 : ℚ)) * X ^ 11 + C ((-10 / 11 : ℚ)) * X ^ 12 + C ((-13 / 22 : ℚ)) * X ^ 13 + C ((-27 / 44 : ℚ)) * X ^ 14 + C ((-25 / 44 : ℚ)) * X ^ 15 + C ((-4 / 11 : ℚ)) * X ^ 16 + C ((-6 / 11 : ℚ)) * X ^ 17 + C ((-5 / 22 : ℚ)) * X ^ 18
def UM_pim_1_12_6 : Polynomial ℚ := C ((-1 / 11 : ℚ)) + C ((-2 / 11 : ℚ)) * X + C ((-7 / 22 : ℚ)) * X ^ 2 + C ((-10 / 11 : ℚ)) * X ^ 3 + C ((-17 / 22 : ℚ)) * X ^ 4 + C ((-61 / 44 : ℚ)) * X ^ 5 + C ((-87 / 44 : ℚ)) * X ^ 6 + C ((-5 / 4 : ℚ)) * X ^ 7 + C ((-105 / 44 : ℚ)) * X ^ 8 + C ((-21 / 11 : ℚ)) * X ^ 9 + C ((-17 / 11 : ℚ)) * X ^ 10 + C ((-31 / 22 : ℚ)) * X ^ 11 + C ((-14 / 11 : ℚ)) * X ^ 12 + C ((-17 / 22 : ℚ)) * X ^ 13 + C ((13 / 44 : ℚ)) * X ^ 14 + C ((-3 / 4 : ℚ)) * X ^ 15 + C ((4 / 11 : ℚ)) * X ^ 17 + C ((-5 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_12_6 :
    spanU_re_1_6 * minorQ_re_6_12 - spanU_im_1_6 * minorQ_im_6_12 =
      UM_pre_1_12_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_6, spanU_im_1_6, minorQ_re_6_12, minorQ_im_6_12,
    UM_pre_1_12_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_12_6 :
    spanU_re_1_6 * minorQ_im_6_12 + spanU_im_1_6 * minorQ_re_6_12 =
      UM_pim_1_12_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_6, spanU_im_1_6, minorQ_re_6_12, minorQ_im_6_12,
    UM_pim_1_12_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_12_6 :
    spanU_entry_1_6 * minorQ_entry_6_12 =
      ofLadj UM_pre_1_12_6 UM_pim_1_12_6 := by
  rw [spanU_entry_1_6, minorQ_entry_6_12, ofLadj_mul,
    UM_pre_eq_1_12_6, UM_pim_eq_1_12_6]

def UM_pre_1_12_7 : Polynomial ℚ := C ((-27 / 22 : ℚ)) + C ((6 / 11 : ℚ)) * X + C ((-14 / 11 : ℚ)) * X ^ 2 + C ((9 / 44 : ℚ)) * X ^ 3 + C ((-75 / 44 : ℚ)) * X ^ 4 + C ((10 / 11 : ℚ)) * X ^ 5 + C ((-3 / 11 : ℚ)) * X ^ 6 + C ((31 / 22 : ℚ)) * X ^ 7 + C ((141 / 44 : ℚ)) * X ^ 9 + C ((-21 / 44 : ℚ)) * X ^ 10 + C ((107 / 22 : ℚ)) * X ^ 11 + C ((-45 / 44 : ℚ)) * X ^ 12 + C ((197 / 44 : ℚ)) * X ^ 13 + C ((-9 / 44 : ℚ)) * X ^ 14 + C ((175 / 44 : ℚ)) * X ^ 15 + C ((23 / 44 : ℚ)) * X ^ 16 + C ((75 / 44 : ℚ)) * X ^ 17 + C ((19 / 22 : ℚ)) * X ^ 18
def UM_pim_1_12_7 : Polynomial ℚ := C ((3 / 2 : ℚ)) + C (3) * X + C ((47 / 22 : ℚ)) * X ^ 2 + C ((179 / 44 : ℚ)) * X ^ 3 + C ((173 / 44 : ℚ)) * X ^ 4 + C ((46 / 11 : ℚ)) * X ^ 5 + C ((71 / 11 : ℚ)) * X ^ 6 + C ((58 / 11 : ℚ)) * X ^ 7 + C ((387 / 44 : ℚ)) * X ^ 8 + C ((317 / 44 : ℚ)) * X ^ 9 + C ((359 / 44 : ℚ)) * X ^ 10 + C (6) * X ^ 11 + C ((169 / 44 : ℚ)) * X ^ 12 + C ((249 / 44 : ℚ)) * X ^ 13 + C ((47 / 22 : ℚ)) * X ^ 14 + C ((195 / 44 : ℚ)) * X ^ 15 + C ((113 / 44 : ℚ)) * X ^ 16 + C ((79 / 44 : ℚ)) * X ^ 17 + C ((15 / 11 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_12_7 :
    spanU_re_1_7 * minorQ_re_7_12 - spanU_im_1_7 * minorQ_im_7_12 =
      UM_pre_1_12_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_7, spanU_im_1_7, minorQ_re_7_12, minorQ_im_7_12,
    UM_pre_1_12_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_12_7 :
    spanU_re_1_7 * minorQ_im_7_12 + spanU_im_1_7 * minorQ_re_7_12 =
      UM_pim_1_12_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_7, spanU_im_1_7, minorQ_re_7_12, minorQ_im_7_12,
    UM_pim_1_12_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_12_7 :
    spanU_entry_1_7 * minorQ_entry_7_12 =
      ofLadj UM_pre_1_12_7 UM_pim_1_12_7 := by
  rw [spanU_entry_1_7, minorQ_entry_7_12, ofLadj_mul,
    UM_pre_eq_1_12_7, UM_pim_eq_1_12_7]

def UM_pre_1_12_8 : Polynomial ℚ := C ((53 / 22 : ℚ)) * X ^ 3 + C ((-53 / 22 : ℚ)) * X ^ 4 + C (2) * X ^ 5 + C ((-14 / 11 : ℚ)) * X ^ 6 + C ((-25 / 22 : ℚ)) * X ^ 7 + C ((19 / 11 : ℚ)) * X ^ 8 + C (-2) * X ^ 9 + C ((43 / 22 : ℚ)) * X ^ 10 + C ((-28 / 11 : ℚ)) * X ^ 11 + C ((43 / 22 : ℚ)) * X ^ 12 + C (-2) * X ^ 13 + C ((-15 / 22 : ℚ)) * X ^ 14 + C ((14 / 11 : ℚ)) * X ^ 15 + C ((-14 / 11 : ℚ)) * X ^ 16 + C (2) * X ^ 17
def UM_pim_1_12_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_pre_eq_1_12_8 :
    spanU_re_1_8 * minorQ_re_8_12 - spanU_im_1_8 * minorQ_im_8_12 =
      UM_pre_1_12_8 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_8, spanU_im_1_8, minorQ_re_8_12, minorQ_im_8_12,
    UM_pre_1_12_8]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_12_8 :
    spanU_re_1_8 * minorQ_im_8_12 + spanU_im_1_8 * minorQ_re_8_12 =
      UM_pim_1_12_8 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_8, spanU_im_1_8, minorQ_re_8_12, minorQ_im_8_12,
    UM_pim_1_12_8]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_12_8 :
    spanU_entry_1_8 * minorQ_entry_8_12 =
      ofLadj UM_pre_1_12_8 UM_pim_1_12_8 := by
  rw [spanU_entry_1_8, minorQ_entry_8_12, ofLadj_mul,
    UM_pre_eq_1_12_8, UM_pim_eq_1_12_8]

theorem UM_sum_poly_re_1_12 :
    UM_pre_1_12_0 + UM_pre_1_12_1 + UM_pre_1_12_2 + UM_pre_1_12_3 + UM_pre_1_12_4 + UM_pre_1_12_5 + UM_pre_1_12_6 + UM_pre_1_12_7 + UM_pre_1_12_8 = Qplus_re_1_12 + Phi11 * UM_qre_1_12 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pre_1_12_0, UM_pre_1_12_1, UM_pre_1_12_2, UM_pre_1_12_3, UM_pre_1_12_4, UM_pre_1_12_5, UM_pre_1_12_6, UM_pre_1_12_7, UM_pre_1_12_8, Qplus_re_1_12, UM_qre_1_12]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_poly_im_1_12 :
    UM_pim_1_12_0 + UM_pim_1_12_1 + UM_pim_1_12_2 + UM_pim_1_12_3 + UM_pim_1_12_4 + UM_pim_1_12_5 + UM_pim_1_12_6 + UM_pim_1_12_7 + UM_pim_1_12_8 = Qplus_im_1_12 + Phi11 * UM_qim_1_12 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pim_1_12_0, UM_pim_1_12_1, UM_pim_1_12_2, UM_pim_1_12_3, UM_pim_1_12_4, UM_pim_1_12_5, UM_pim_1_12_6, UM_pim_1_12_7, UM_pim_1_12_8, Qplus_im_1_12, UM_qim_1_12]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_entries_1_12 :
    spanU_entry_1_0 * minorQ_entry_0_12 + spanU_entry_1_1 * minorQ_entry_1_12 + spanU_entry_1_2 * minorQ_entry_2_12 + spanU_entry_1_3 * minorQ_entry_3_12 + spanU_entry_1_4 * minorQ_entry_4_12 + spanU_entry_1_5 * minorQ_entry_5_12 + spanU_entry_1_6 * minorQ_entry_6_12 + spanU_entry_1_7 * minorQ_entry_7_12 + spanU_entry_1_8 * minorQ_entry_8_12 =
      ofLadj (UM_pre_1_12_0 + UM_pre_1_12_1 + UM_pre_1_12_2 + UM_pre_1_12_3 + UM_pre_1_12_4 + UM_pre_1_12_5 + UM_pre_1_12_6 + UM_pre_1_12_7 + UM_pre_1_12_8) (UM_pim_1_12_0 + UM_pim_1_12_1 + UM_pim_1_12_2 + UM_pim_1_12_3 + UM_pim_1_12_4 + UM_pim_1_12_5 + UM_pim_1_12_6 + UM_pim_1_12_7 + UM_pim_1_12_8) := by
  simp only [UM_term_1_12_0, UM_term_1_12_1, UM_term_1_12_2, UM_term_1_12_3, UM_term_1_12_4, UM_term_1_12_5, UM_term_1_12_6, UM_term_1_12_7, UM_term_1_12_8]
  simpa [add_assoc] using ofLadj_add9 UM_pre_1_12_0 UM_pim_1_12_0 UM_pre_1_12_1 UM_pim_1_12_1 UM_pre_1_12_2 UM_pim_1_12_2 UM_pre_1_12_3 UM_pim_1_12_3 UM_pre_1_12_4 UM_pim_1_12_4 UM_pre_1_12_5 UM_pim_1_12_5 UM_pre_1_12_6 UM_pim_1_12_6 UM_pre_1_12_7 UM_pim_1_12_7 UM_pre_1_12_8 UM_pim_1_12_8

theorem UM_eval_1_12 :
    ofLadj (UM_pre_1_12_0 + UM_pre_1_12_1 + UM_pre_1_12_2 + UM_pre_1_12_3 + UM_pre_1_12_4 + UM_pre_1_12_5 + UM_pre_1_12_6 + UM_pre_1_12_7 + UM_pre_1_12_8) (UM_pim_1_12_0 + UM_pim_1_12_1 + UM_pim_1_12_2 + UM_pim_1_12_3 + UM_pim_1_12_4 + UM_pim_1_12_5 + UM_pim_1_12_6 + UM_pim_1_12_7 + UM_pim_1_12_8) = Qplus_entry_1_12 := by
  rw [UM_sum_poly_re_1_12, UM_sum_poly_im_1_12,
    ofLadj_add_Phi11, Qplus_entry_1_12]

public theorem UM_entry_1_12 : (spanU * minorQ) 1 12 = Qplus 1 12 := by
  rw [Matrix.mul_apply]
  rw [sum_fin9]
  change spanU_entry_1_0 * minorQ_entry_0_12 + spanU_entry_1_1 * minorQ_entry_1_12 + spanU_entry_1_2 * minorQ_entry_2_12 + spanU_entry_1_3 * minorQ_entry_3_12 + spanU_entry_1_4 * minorQ_entry_4_12 + spanU_entry_1_5 * minorQ_entry_5_12 + spanU_entry_1_6 * minorQ_entry_6_12 + spanU_entry_1_7 * minorQ_entry_7_12 + spanU_entry_1_8 * minorQ_entry_8_12 = Qplus_entry_1_12
  exact (UM_sum_entries_1_12).trans UM_eval_1_12

end V14Formalization.D12SigmaPlusSegreCore
