/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
import V14Formalization.D12SigmaPlusSegreEval
import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def UM_qre_14_18 : Polynomial ℚ := C ((17 / 44 : ℚ)) * X ^ 2 + C ((-5 / 44 : ℚ)) * X ^ 3 + C ((-1 / 4 : ℚ)) * X ^ 4 + C ((3 / 22 : ℚ)) * X ^ 7 + C ((-5 / 44 : ℚ)) * X ^ 8
def UM_qim_14_18 : Polynomial ℚ := (0 : Polynomial ℚ)

def UM_pre_14_18_0 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_14_18_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_14_18_0 :
    spanU_entry_14_0 * minorQ_entry_0_18 =
      ofLadj UM_pre_14_18_0 UM_pim_14_18_0 := by
  have hz : spanU_entry_14_0 = 0 := by
    rw [spanU_entry_14_0]; exact ofLadj_zero
  rw [hz, UM_pre_14_18_0, UM_pim_14_18_0]
  simp [ofLadj_zero]

def UM_pre_14_18_1 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_14_18_1 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_14_18_1 :
    spanU_entry_14_1 * minorQ_entry_1_18 =
      ofLadj UM_pre_14_18_1 UM_pim_14_18_1 := by
  have hz : spanU_entry_14_1 = 0 := by
    rw [spanU_entry_14_1]; exact ofLadj_zero
  rw [hz, UM_pre_14_18_1, UM_pim_14_18_1]
  simp [ofLadj_zero]

def UM_pre_14_18_2 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_14_18_2 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_14_18_2 :
    spanU_entry_14_2 * minorQ_entry_2_18 =
      ofLadj UM_pre_14_18_2 UM_pim_14_18_2 := by
  have hz : spanU_entry_14_2 = 0 := by
    rw [spanU_entry_14_2]; exact ofLadj_zero
  rw [hz, UM_pre_14_18_2, UM_pim_14_18_2]
  simp [ofLadj_zero]

def UM_pre_14_18_3 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_14_18_3 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_14_18_3 :
    spanU_entry_14_3 * minorQ_entry_3_18 =
      ofLadj UM_pre_14_18_3 UM_pim_14_18_3 := by
  have hz : spanU_entry_14_3 = 0 := by
    rw [spanU_entry_14_3]; exact ofLadj_zero
  rw [hz, UM_pre_14_18_3, UM_pim_14_18_3]
  simp [ofLadj_zero]

def UM_pre_14_18_4 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_14_18_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_14_18_4 :
    spanU_entry_14_4 * minorQ_entry_4_18 =
      ofLadj UM_pre_14_18_4 UM_pim_14_18_4 := by
  have hz : spanU_entry_14_4 = 0 := by
    rw [spanU_entry_14_4]; exact ofLadj_zero
  rw [hz, UM_pre_14_18_4, UM_pim_14_18_4]
  simp [ofLadj_zero]

def UM_pre_14_18_5 : Polynomial ℚ := C ((3 / 44 : ℚ)) * X ^ 2 + C ((3 / 22 : ℚ)) * X ^ 3 + C ((1 / 88 : ℚ)) * X ^ 4 + C ((1 / 88 : ℚ)) * X ^ 5 + C ((1 / 88 : ℚ)) * X ^ 6 + C ((7 / 88 : ℚ)) * X ^ 7 + C ((1 / 44 : ℚ)) * X ^ 8 + C ((-9 / 88 : ℚ)) * X ^ 9 + C ((1 / 44 : ℚ)) * X ^ 10 + C ((1 / 44 : ℚ)) * X ^ 11 + C ((1 / 44 : ℚ)) * X ^ 12 + C ((-15 / 88 : ℚ)) * X ^ 13 + C ((-5 / 44 : ℚ)) * X ^ 14 + C ((1 / 88 : ℚ)) * X ^ 15 + C ((1 / 88 : ℚ)) * X ^ 16 + C ((1 / 88 : ℚ)) * X ^ 17 + C ((-5 / 88 : ℚ)) * X ^ 18
def UM_pim_14_18_5 : Polynomial ℚ := C ((-3 / 44 : ℚ)) * X ^ 2 + C ((7 / 88 : ℚ)) * X ^ 4 + C ((15 / 88 : ℚ)) * X ^ 5 + C ((15 / 88 : ℚ)) * X ^ 6 + C ((5 / 88 : ℚ)) * X ^ 7 + C ((5 / 44 : ℚ)) * X ^ 8 + C ((-3 / 88 : ℚ)) * X ^ 9 + C ((1 / 22 : ℚ)) * X ^ 10 + C ((-1 / 22 : ℚ)) * X ^ 12 + C ((9 / 88 : ℚ)) * X ^ 13 + C ((-5 / 44 : ℚ)) * X ^ 14 + C ((-1 / 8 : ℚ)) * X ^ 15 + C ((-15 / 88 : ℚ)) * X ^ 16 + C ((-15 / 88 : ℚ)) * X ^ 17 + C ((-1 / 88 : ℚ)) * X ^ 18
theorem UM_pre_eq_14_18_5 :
    spanU_re_14_5 * minorQ_re_5_18 - spanU_im_14_5 * minorQ_im_5_18 =
      UM_pre_14_18_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_14_5, spanU_im_14_5, minorQ_re_5_18, minorQ_im_5_18,
    UM_pre_14_18_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_14_18_5 :
    spanU_re_14_5 * minorQ_im_5_18 + spanU_im_14_5 * minorQ_re_5_18 =
      UM_pim_14_18_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_14_5, spanU_im_14_5, minorQ_re_5_18, minorQ_im_5_18,
    UM_pim_14_18_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_14_18_5 :
    spanU_entry_14_5 * minorQ_entry_5_18 =
      ofLadj UM_pre_14_18_5 UM_pim_14_18_5 := by
  rw [spanU_entry_14_5, minorQ_entry_5_18, ofLadj_mul,
    UM_pre_eq_14_18_5, UM_pim_eq_14_18_5]

def UM_pre_14_18_6 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_14_18_6 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_14_18_6 :
    spanU_entry_14_6 * minorQ_entry_6_18 =
      ofLadj UM_pre_14_18_6 UM_pim_14_18_6 := by
  have hz : spanU_entry_14_6 = 0 := by
    rw [spanU_entry_14_6]; exact ofLadj_zero
  rw [hz, UM_pre_14_18_6, UM_pim_14_18_6]
  simp [ofLadj_zero]

def UM_pre_14_18_7 : Polynomial ℚ := C ((3 / 44 : ℚ)) * X ^ 2 + C ((3 / 22 : ℚ)) * X ^ 3 + C ((1 / 88 : ℚ)) * X ^ 4 + C ((1 / 88 : ℚ)) * X ^ 5 + C ((1 / 88 : ℚ)) * X ^ 6 + C ((7 / 88 : ℚ)) * X ^ 7 + C ((1 / 44 : ℚ)) * X ^ 8 + C ((-9 / 88 : ℚ)) * X ^ 9 + C ((1 / 44 : ℚ)) * X ^ 10 + C ((1 / 44 : ℚ)) * X ^ 11 + C ((1 / 44 : ℚ)) * X ^ 12 + C ((-15 / 88 : ℚ)) * X ^ 13 + C ((-5 / 44 : ℚ)) * X ^ 14 + C ((1 / 88 : ℚ)) * X ^ 15 + C ((1 / 88 : ℚ)) * X ^ 16 + C ((1 / 88 : ℚ)) * X ^ 17 + C ((-5 / 88 : ℚ)) * X ^ 18
def UM_pim_14_18_7 : Polynomial ℚ := C ((3 / 44 : ℚ)) * X ^ 2 + C ((-7 / 88 : ℚ)) * X ^ 4 + C ((-15 / 88 : ℚ)) * X ^ 5 + C ((-15 / 88 : ℚ)) * X ^ 6 + C ((-5 / 88 : ℚ)) * X ^ 7 + C ((-5 / 44 : ℚ)) * X ^ 8 + C ((3 / 88 : ℚ)) * X ^ 9 + C ((-1 / 22 : ℚ)) * X ^ 10 + C ((1 / 22 : ℚ)) * X ^ 12 + C ((-9 / 88 : ℚ)) * X ^ 13 + C ((5 / 44 : ℚ)) * X ^ 14 + C ((1 / 8 : ℚ)) * X ^ 15 + C ((15 / 88 : ℚ)) * X ^ 16 + C ((15 / 88 : ℚ)) * X ^ 17 + C ((1 / 88 : ℚ)) * X ^ 18
theorem UM_pre_eq_14_18_7 :
    spanU_re_14_7 * minorQ_re_7_18 - spanU_im_14_7 * minorQ_im_7_18 =
      UM_pre_14_18_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_14_7, spanU_im_14_7, minorQ_re_7_18, minorQ_im_7_18,
    UM_pre_14_18_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_14_18_7 :
    spanU_re_14_7 * minorQ_im_7_18 + spanU_im_14_7 * minorQ_re_7_18 =
      UM_pim_14_18_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_14_7, spanU_im_14_7, minorQ_re_7_18, minorQ_im_7_18,
    UM_pim_14_18_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_14_18_7 :
    spanU_entry_14_7 * minorQ_entry_7_18 =
      ofLadj UM_pre_14_18_7 UM_pim_14_18_7 := by
  rw [spanU_entry_14_7, minorQ_entry_7_18, ofLadj_mul,
    UM_pre_eq_14_18_7, UM_pim_eq_14_18_7]

def UM_pre_14_18_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_14_18_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_14_18_8 :
    spanU_entry_14_8 * minorQ_entry_8_18 =
      ofLadj UM_pre_14_18_8 UM_pim_14_18_8 := by
  have hz : spanU_entry_14_8 = 0 := by
    rw [spanU_entry_14_8]; exact ofLadj_zero
  rw [hz, UM_pre_14_18_8, UM_pim_14_18_8]
  simp [ofLadj_zero]

theorem UM_sum_poly_re_14_18 :
    UM_pre_14_18_0 + UM_pre_14_18_1 + UM_pre_14_18_2 + UM_pre_14_18_3 + UM_pre_14_18_4 + UM_pre_14_18_5 + UM_pre_14_18_6 + UM_pre_14_18_7 + UM_pre_14_18_8 = Qplus_re_14_18 + Phi11 * UM_qre_14_18 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pre_14_18_0, UM_pre_14_18_1, UM_pre_14_18_2, UM_pre_14_18_3, UM_pre_14_18_4, UM_pre_14_18_5, UM_pre_14_18_6, UM_pre_14_18_7, UM_pre_14_18_8, Qplus_re_14_18, UM_qre_14_18]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_poly_im_14_18 :
    UM_pim_14_18_0 + UM_pim_14_18_1 + UM_pim_14_18_2 + UM_pim_14_18_3 + UM_pim_14_18_4 + UM_pim_14_18_5 + UM_pim_14_18_6 + UM_pim_14_18_7 + UM_pim_14_18_8 = Qplus_im_14_18 + Phi11 * UM_qim_14_18 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pim_14_18_0, UM_pim_14_18_1, UM_pim_14_18_2, UM_pim_14_18_3, UM_pim_14_18_4, UM_pim_14_18_5, UM_pim_14_18_6, UM_pim_14_18_7, UM_pim_14_18_8, Qplus_im_14_18, UM_qim_14_18]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_entries_14_18 :
    spanU_entry_14_0 * minorQ_entry_0_18 + spanU_entry_14_1 * minorQ_entry_1_18 + spanU_entry_14_2 * minorQ_entry_2_18 + spanU_entry_14_3 * minorQ_entry_3_18 + spanU_entry_14_4 * minorQ_entry_4_18 + spanU_entry_14_5 * minorQ_entry_5_18 + spanU_entry_14_6 * minorQ_entry_6_18 + spanU_entry_14_7 * minorQ_entry_7_18 + spanU_entry_14_8 * minorQ_entry_8_18 =
      ofLadj (UM_pre_14_18_0 + UM_pre_14_18_1 + UM_pre_14_18_2 + UM_pre_14_18_3 + UM_pre_14_18_4 + UM_pre_14_18_5 + UM_pre_14_18_6 + UM_pre_14_18_7 + UM_pre_14_18_8) (UM_pim_14_18_0 + UM_pim_14_18_1 + UM_pim_14_18_2 + UM_pim_14_18_3 + UM_pim_14_18_4 + UM_pim_14_18_5 + UM_pim_14_18_6 + UM_pim_14_18_7 + UM_pim_14_18_8) := by
  simp only [UM_term_14_18_0, UM_term_14_18_1, UM_term_14_18_2, UM_term_14_18_3, UM_term_14_18_4, UM_term_14_18_5, UM_term_14_18_6, UM_term_14_18_7, UM_term_14_18_8]
  simpa [add_assoc] using ofLadj_add9 UM_pre_14_18_0 UM_pim_14_18_0 UM_pre_14_18_1 UM_pim_14_18_1 UM_pre_14_18_2 UM_pim_14_18_2 UM_pre_14_18_3 UM_pim_14_18_3 UM_pre_14_18_4 UM_pim_14_18_4 UM_pre_14_18_5 UM_pim_14_18_5 UM_pre_14_18_6 UM_pim_14_18_6 UM_pre_14_18_7 UM_pim_14_18_7 UM_pre_14_18_8 UM_pim_14_18_8

theorem UM_eval_14_18 :
    ofLadj (UM_pre_14_18_0 + UM_pre_14_18_1 + UM_pre_14_18_2 + UM_pre_14_18_3 + UM_pre_14_18_4 + UM_pre_14_18_5 + UM_pre_14_18_6 + UM_pre_14_18_7 + UM_pre_14_18_8) (UM_pim_14_18_0 + UM_pim_14_18_1 + UM_pim_14_18_2 + UM_pim_14_18_3 + UM_pim_14_18_4 + UM_pim_14_18_5 + UM_pim_14_18_6 + UM_pim_14_18_7 + UM_pim_14_18_8) = Qplus_entry_14_18 := by
  rw [UM_sum_poly_re_14_18, UM_sum_poly_im_14_18,
    ofLadj_add_Phi11, Qplus_entry_14_18]

theorem UM_entry_14_18 : (spanU * minorQ) 14 18 = Qplus 14 18 := by
  rw [Matrix.mul_apply]
  rw [sum_fin9]
  change spanU_entry_14_0 * minorQ_entry_0_18 + spanU_entry_14_1 * minorQ_entry_1_18 + spanU_entry_14_2 * minorQ_entry_2_18 + spanU_entry_14_3 * minorQ_entry_3_18 + spanU_entry_14_4 * minorQ_entry_4_18 + spanU_entry_14_5 * minorQ_entry_5_18 + spanU_entry_14_6 * minorQ_entry_6_18 + spanU_entry_14_7 * minorQ_entry_7_18 + spanU_entry_14_8 * minorQ_entry_8_18 = Qplus_entry_14_18
  exact (UM_sum_entries_14_18).trans UM_eval_14_18

end V14Formalization.D12SigmaPlusSegreCore
