/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
import V14Formalization.D12SigmaPlusSegreEval
import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def VQ_qre_3_12 : Polynomial ℚ := C (46) + C (-46) * X + C (-30) * X ^ 2 + C (-78) * X ^ 3 + C (-70) * X ^ 4 + C (-24) * X ^ 5 + C (-24) * X ^ 6 + C (10) * X ^ 7 + C (-14) * X ^ 8
def VQ_qim_3_12 : Polynomial ℚ := C (-58) + C (-58) * X + C (-64) * X ^ 2 + C (2) * X ^ 3 + C (-4) * X ^ 4 + C (26) * X ^ 5 + C (-10) * X ^ 6 + C (6) * X ^ 7 + C (6) * X ^ 8

def VQ_pre_3_12_0 : Polynomial ℚ := C (28) + C (-24) * X ^ 2 + C (-78) * X ^ 3 + C (-118) * X ^ 4 + C (-146) * X ^ 5 + C (-146) * X ^ 6 + C (-118) * X ^ 7 + C (-78) * X ^ 8 + C (-24) * X ^ 9
def VQ_pim_3_12_0 : Polynomial ℚ := C (-38) + C (-76) * X + C (-114) * X ^ 2 + C (-108) * X ^ 3 + C (-102) * X ^ 4 + C (-52) * X ^ 5 + C (-24) * X ^ 6 + C (26) * X ^ 7 + C (32) * X ^ 8 + C (38) * X ^ 9
theorem VQ_pre_eq_3_12_0 :
    spanV_re_3_0 * Qplus_re_0_12 - spanV_im_3_0 * Qplus_im_0_12 =
      VQ_pre_3_12_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_0, spanV_im_3_0, Qplus_re_0_12, Qplus_im_0_12,
    VQ_pre_3_12_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_3_12_0 :
    spanV_re_3_0 * Qplus_im_0_12 + spanV_im_3_0 * Qplus_re_0_12 =
      VQ_pim_3_12_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_0, spanV_im_3_0, Qplus_re_0_12, Qplus_im_0_12,
    VQ_pim_3_12_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_3_12_0 :
    spanV_entry_3_0 * Qplus_entry_0_12 =
      ofLadj VQ_pre_3_12_0 VQ_pim_3_12_0 := by
  rw [spanV_entry_3_0, Qplus_entry_0_12, ofLadj_mul,
    VQ_pre_eq_3_12_0, VQ_pim_eq_3_12_0]

def VQ_pre_3_12_1 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_1 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_1 :
    spanV_entry_3_1 * Qplus_entry_1_12 =
      ofLadj VQ_pre_3_12_1 VQ_pim_3_12_1 := by
  have hz : Qplus_entry_1_12 = 0 := by
    rw [Qplus_entry_1_12]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_1, VQ_pim_3_12_1]
  simp [ofLadj_zero]

def VQ_pre_3_12_2 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_2 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_2 :
    spanV_entry_3_2 * Qplus_entry_2_12 =
      ofLadj VQ_pre_3_12_2 VQ_pim_3_12_2 := by
  have hz : Qplus_entry_2_12 = 0 := by
    rw [Qplus_entry_2_12]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_2, VQ_pim_3_12_2]
  simp [ofLadj_zero]

def VQ_pre_3_12_3 : Polynomial ℚ := C (-2) + C (26) * X ^ 2 + C (54) * X ^ 3 + C (80) * X ^ 4 + C (92) * X ^ 5 + C (118) * X ^ 6 + C (134) * X ^ 7 + C (136) * X ^ 8 + C (144) * X ^ 9 + C (146) * X ^ 10 + C (164) * X ^ 11 + C (146) * X ^ 12 + C (118) * X ^ 13 + C (82) * X ^ 14 + C (54) * X ^ 15 + C (26) * X ^ 16
def VQ_pim_3_12_3 : Polynomial ℚ := C (30) + C (60) * X + C (68) * X ^ 2 + C (76) * X ^ 3 + C (92) * X ^ 4 + C (108) * X ^ 5 + C (80) * X ^ 6 + C (104) * X ^ 7 + C (106) * X ^ 8 + C (108) * X ^ 9 + C (88) * X ^ 10 + C (60) * X ^ 11 + C (32) * X ^ 12 + C (4) * X ^ 13 + C (-2) * X ^ 14 + C (-16) * X ^ 15 + C (-8) * X ^ 16
theorem VQ_pre_eq_3_12_3 :
    spanV_re_3_3 * Qplus_re_3_12 - spanV_im_3_3 * Qplus_im_3_12 =
      VQ_pre_3_12_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_3, spanV_im_3_3, Qplus_re_3_12, Qplus_im_3_12,
    VQ_pre_3_12_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_3_12_3 :
    spanV_re_3_3 * Qplus_im_3_12 + spanV_im_3_3 * Qplus_re_3_12 =
      VQ_pim_3_12_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_3, spanV_im_3_3, Qplus_re_3_12, Qplus_im_3_12,
    VQ_pim_3_12_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_3_12_3 :
    spanV_entry_3_3 * Qplus_entry_3_12 =
      ofLadj VQ_pre_3_12_3 VQ_pim_3_12_3 := by
  rw [spanV_entry_3_3, Qplus_entry_3_12, ofLadj_mul,
    VQ_pre_eq_3_12_3, VQ_pim_eq_3_12_3]

def VQ_pre_3_12_4 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_4 :
    spanV_entry_3_4 * Qplus_entry_4_12 =
      ofLadj VQ_pre_3_12_4 VQ_pim_3_12_4 := by
  have hz : Qplus_entry_4_12 = 0 := by
    rw [Qplus_entry_4_12]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_4, VQ_pim_3_12_4]
  simp [ofLadj_zero]

def VQ_pre_3_12_5 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_5 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_5 :
    spanV_entry_3_5 * Qplus_entry_5_12 =
      ofLadj VQ_pre_3_12_5 VQ_pim_3_12_5 := by
  have hz : Qplus_entry_5_12 = 0 := by
    rw [Qplus_entry_5_12]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_5, VQ_pim_3_12_5]
  simp [ofLadj_zero]

def VQ_pre_3_12_6 : Polynomial ℚ := C (4) + C (32) * X ^ 2 + C (48) * X ^ 3 + C (104) * X ^ 4 + C (136) * X ^ 5 + C (164) * X ^ 6 + C (164) * X ^ 7 + C (136) * X ^ 8 + C (108) * X ^ 9 + C (48) * X ^ 10 + C (56) * X ^ 11 + C (48) * X ^ 12 + C (76) * X ^ 13 + C (88) * X ^ 14 + C (88) * X ^ 15 + C (76) * X ^ 16 + C (48) * X ^ 17 + C (28) * X ^ 18
def VQ_pim_3_12_6 : Polynomial ℚ := C (30) + C (60) * X + C (98) * X ^ 2 + C (136) * X ^ 3 + C (130) * X ^ 4 + C (124) * X ^ 5 + C (74) * X ^ 6 + C (46) * X ^ 7 + C (-4) * X ^ 8 + C (20) * X ^ 9 + C (44) * X ^ 10 + C (60) * X ^ 11 + C (76) * X ^ 12 + C (62) * X ^ 13 + C (48) * X ^ 14 + C (12) * X ^ 15 + C (-2) * X ^ 16 + C (-16) * X ^ 17 + C (-8) * X ^ 18
theorem VQ_pre_eq_3_12_6 :
    spanV_re_3_6 * Qplus_re_6_12 - spanV_im_3_6 * Qplus_im_6_12 =
      VQ_pre_3_12_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_6, spanV_im_3_6, Qplus_re_6_12, Qplus_im_6_12,
    VQ_pre_3_12_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_3_12_6 :
    spanV_re_3_6 * Qplus_im_6_12 + spanV_im_3_6 * Qplus_re_6_12 =
      VQ_pim_3_12_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_6, spanV_im_3_6, Qplus_re_6_12, Qplus_im_6_12,
    VQ_pim_3_12_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_3_12_6 :
    spanV_entry_3_6 * Qplus_entry_6_12 =
      ofLadj VQ_pre_3_12_6 VQ_pim_3_12_6 := by
  rw [spanV_entry_3_6, Qplus_entry_6_12, ofLadj_mul,
    VQ_pre_eq_3_12_6, VQ_pim_eq_3_12_6]

def VQ_pre_3_12_7 : Polynomial ℚ := C (4) + C (-70) * X ^ 2 + C (-128) * X ^ 3 + C (-238) * X ^ 4 + C (-298) * X ^ 5 + C (-372) * X ^ 6 + C (-420) * X ^ 7 + C (-448) * X ^ 8 + C (-492) * X ^ 9 + C (-466) * X ^ 10 + C (-512) * X ^ 11 + C (-466) * X ^ 12 + C (-422) * X ^ 13 + C (-320) * X ^ 14 + C (-218) * X ^ 15 + C (-138) * X ^ 16 + C (-64) * X ^ 17 + C (-36) * X ^ 18
def VQ_pim_3_12_7 : Polynomial ℚ := C (-72) + C (-144) * X + C (-208) * X ^ 2 + C (-272) * X ^ 3 + C (-262) * X ^ 4 + C (-332) * X ^ 5 + C (-284) * X ^ 6 + C (-360) * X ^ 7 + C (-282) * X ^ 8 + C (-328) * X ^ 9 + C (-286) * X ^ 10 + C (-216) * X ^ 11 + C (-146) * X ^ 12 + C (-40) * X ^ 13 + C (-22) * X ^ 14 + C (32) * X ^ 15 + C (12) * X ^ 16 + C (28) * X ^ 17 + C (14) * X ^ 18
theorem VQ_pre_eq_3_12_7 :
    spanV_re_3_7 * Qplus_re_7_12 - spanV_im_3_7 * Qplus_im_7_12 =
      VQ_pre_3_12_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_7, spanV_im_3_7, Qplus_re_7_12, Qplus_im_7_12,
    VQ_pre_3_12_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_3_12_7 :
    spanV_re_3_7 * Qplus_im_7_12 + spanV_im_3_7 * Qplus_re_7_12 =
      VQ_pim_3_12_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_7, spanV_im_3_7, Qplus_re_7_12, Qplus_im_7_12,
    VQ_pim_3_12_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_3_12_7 :
    spanV_entry_3_7 * Qplus_entry_7_12 =
      ofLadj VQ_pre_3_12_7 VQ_pim_3_12_7 := by
  rw [spanV_entry_3_7, Qplus_entry_7_12, ofLadj_mul,
    VQ_pre_eq_3_12_7, VQ_pim_eq_3_12_7]

def VQ_pre_3_12_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_8 :
    spanV_entry_3_8 * Qplus_entry_8_12 =
      ofLadj VQ_pre_3_12_8 VQ_pim_3_12_8 := by
  have hz : spanV_entry_3_8 = 0 := by
    rw [spanV_entry_3_8]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_8, VQ_pim_3_12_8]
  simp [ofLadj_zero]

def VQ_pre_3_12_9 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_9 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_9 :
    spanV_entry_3_9 * Qplus_entry_9_12 =
      ofLadj VQ_pre_3_12_9 VQ_pim_3_12_9 := by
  have hz : spanV_entry_3_9 = 0 := by
    rw [spanV_entry_3_9]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_9, VQ_pim_3_12_9]
  simp [ofLadj_zero]

def VQ_pre_3_12_10 : Polynomial ℚ := C (-2) + C (-8) * X ^ 2 + C (4) * X ^ 3 + C (-6) * X ^ 4 + C (16) * X ^ 5 + C (12) * X ^ 6 + C (24) * X ^ 7 + C (32) * X ^ 8 + C (20) * X ^ 9 + C (42) * X ^ 10 + C (16) * X ^ 11 + C (42) * X ^ 12 + C (28) * X ^ 13 + C (28) * X ^ 14 + C (24) * X ^ 15 + C (8) * X ^ 16 + C (12) * X ^ 17 + C (-6) * X ^ 18
def VQ_pim_3_12_10 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_pre_eq_3_12_10 :
    spanV_re_3_10 * Qplus_re_10_12 - spanV_im_3_10 * Qplus_im_10_12 =
      VQ_pre_3_12_10 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_10, spanV_im_3_10, Qplus_re_10_12, Qplus_im_10_12,
    VQ_pre_3_12_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_3_12_10 :
    spanV_re_3_10 * Qplus_im_10_12 + spanV_im_3_10 * Qplus_re_10_12 =
      VQ_pim_3_12_10 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_3_10, spanV_im_3_10, Qplus_re_10_12, Qplus_im_10_12,
    VQ_pim_3_12_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_3_12_10 :
    spanV_entry_3_10 * Qplus_entry_10_12 =
      ofLadj VQ_pre_3_12_10 VQ_pim_3_12_10 := by
  rw [spanV_entry_3_10, Qplus_entry_10_12, ofLadj_mul,
    VQ_pre_eq_3_12_10, VQ_pim_eq_3_12_10]

def VQ_pre_3_12_11 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_11 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_11 :
    spanV_entry_3_11 * Qplus_entry_11_12 =
      ofLadj VQ_pre_3_12_11 VQ_pim_3_12_11 := by
  have hz : spanV_entry_3_11 = 0 := by
    rw [spanV_entry_3_11]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_11, VQ_pim_3_12_11]
  simp [ofLadj_zero]

def VQ_pre_3_12_12 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_12 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_12 :
    spanV_entry_3_12 * Qplus_entry_12_12 =
      ofLadj VQ_pre_3_12_12 VQ_pim_3_12_12 := by
  have hz : spanV_entry_3_12 = 0 := by
    rw [spanV_entry_3_12]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_12, VQ_pim_3_12_12]
  simp [ofLadj_zero]

def VQ_pre_3_12_13 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_13 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_13 :
    spanV_entry_3_13 * Qplus_entry_13_12 =
      ofLadj VQ_pre_3_12_13 VQ_pim_3_12_13 := by
  have hz : spanV_entry_3_13 = 0 := by
    rw [spanV_entry_3_13]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_13, VQ_pim_3_12_13]
  simp [ofLadj_zero]

def VQ_pre_3_12_14 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_3_12_14 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_3_12_14 :
    spanV_entry_3_14 * Qplus_entry_14_12 =
      ofLadj VQ_pre_3_12_14 VQ_pim_3_12_14 := by
  have hz : spanV_entry_3_14 = 0 := by
    rw [spanV_entry_3_14]; exact ofLadj_zero
  rw [hz, VQ_pre_3_12_14, VQ_pim_3_12_14]
  simp [ofLadj_zero]

theorem VQ_sum_poly_re_3_12 :
    VQ_pre_3_12_0 + VQ_pre_3_12_1 + VQ_pre_3_12_2 + VQ_pre_3_12_3 + VQ_pre_3_12_4 + VQ_pre_3_12_5 + VQ_pre_3_12_6 + VQ_pre_3_12_7 + VQ_pre_3_12_8 + VQ_pre_3_12_9 + VQ_pre_3_12_10 + VQ_pre_3_12_11 + VQ_pre_3_12_12 + VQ_pre_3_12_13 + VQ_pre_3_12_14 = minorQ_re_3_12 + Phi11 * VQ_qre_3_12 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [VQ_pre_3_12_0, VQ_pre_3_12_1, VQ_pre_3_12_2, VQ_pre_3_12_3, VQ_pre_3_12_4, VQ_pre_3_12_5, VQ_pre_3_12_6, VQ_pre_3_12_7, VQ_pre_3_12_8, VQ_pre_3_12_9, VQ_pre_3_12_10, VQ_pre_3_12_11, VQ_pre_3_12_12, VQ_pre_3_12_13, VQ_pre_3_12_14, minorQ_re_3_12, VQ_qre_3_12]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem VQ_sum_poly_im_3_12 :
    VQ_pim_3_12_0 + VQ_pim_3_12_1 + VQ_pim_3_12_2 + VQ_pim_3_12_3 + VQ_pim_3_12_4 + VQ_pim_3_12_5 + VQ_pim_3_12_6 + VQ_pim_3_12_7 + VQ_pim_3_12_8 + VQ_pim_3_12_9 + VQ_pim_3_12_10 + VQ_pim_3_12_11 + VQ_pim_3_12_12 + VQ_pim_3_12_13 + VQ_pim_3_12_14 = minorQ_im_3_12 + Phi11 * VQ_qim_3_12 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [VQ_pim_3_12_0, VQ_pim_3_12_1, VQ_pim_3_12_2, VQ_pim_3_12_3, VQ_pim_3_12_4, VQ_pim_3_12_5, VQ_pim_3_12_6, VQ_pim_3_12_7, VQ_pim_3_12_8, VQ_pim_3_12_9, VQ_pim_3_12_10, VQ_pim_3_12_11, VQ_pim_3_12_12, VQ_pim_3_12_13, VQ_pim_3_12_14, minorQ_im_3_12, VQ_qim_3_12]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem VQ_sum_entries_3_12 :
    spanV_entry_3_0 * Qplus_entry_0_12 + spanV_entry_3_1 * Qplus_entry_1_12 + spanV_entry_3_2 * Qplus_entry_2_12 + spanV_entry_3_3 * Qplus_entry_3_12 + spanV_entry_3_4 * Qplus_entry_4_12 + spanV_entry_3_5 * Qplus_entry_5_12 + spanV_entry_3_6 * Qplus_entry_6_12 + spanV_entry_3_7 * Qplus_entry_7_12 + spanV_entry_3_8 * Qplus_entry_8_12 + spanV_entry_3_9 * Qplus_entry_9_12 + spanV_entry_3_10 * Qplus_entry_10_12 + spanV_entry_3_11 * Qplus_entry_11_12 + spanV_entry_3_12 * Qplus_entry_12_12 + spanV_entry_3_13 * Qplus_entry_13_12 + spanV_entry_3_14 * Qplus_entry_14_12 =
      ofLadj (VQ_pre_3_12_0 + VQ_pre_3_12_1 + VQ_pre_3_12_2 + VQ_pre_3_12_3 + VQ_pre_3_12_4 + VQ_pre_3_12_5 + VQ_pre_3_12_6 + VQ_pre_3_12_7 + VQ_pre_3_12_8 + VQ_pre_3_12_9 + VQ_pre_3_12_10 + VQ_pre_3_12_11 + VQ_pre_3_12_12 + VQ_pre_3_12_13 + VQ_pre_3_12_14) (VQ_pim_3_12_0 + VQ_pim_3_12_1 + VQ_pim_3_12_2 + VQ_pim_3_12_3 + VQ_pim_3_12_4 + VQ_pim_3_12_5 + VQ_pim_3_12_6 + VQ_pim_3_12_7 + VQ_pim_3_12_8 + VQ_pim_3_12_9 + VQ_pim_3_12_10 + VQ_pim_3_12_11 + VQ_pim_3_12_12 + VQ_pim_3_12_13 + VQ_pim_3_12_14) := by
  simp only [VQ_term_3_12_0, VQ_term_3_12_1, VQ_term_3_12_2, VQ_term_3_12_3, VQ_term_3_12_4, VQ_term_3_12_5, VQ_term_3_12_6, VQ_term_3_12_7, VQ_term_3_12_8, VQ_term_3_12_9, VQ_term_3_12_10, VQ_term_3_12_11, VQ_term_3_12_12, VQ_term_3_12_13, VQ_term_3_12_14]
  simpa [add_assoc] using ofLadj_add15 VQ_pre_3_12_0 VQ_pim_3_12_0 VQ_pre_3_12_1 VQ_pim_3_12_1 VQ_pre_3_12_2 VQ_pim_3_12_2 VQ_pre_3_12_3 VQ_pim_3_12_3 VQ_pre_3_12_4 VQ_pim_3_12_4 VQ_pre_3_12_5 VQ_pim_3_12_5 VQ_pre_3_12_6 VQ_pim_3_12_6 VQ_pre_3_12_7 VQ_pim_3_12_7 VQ_pre_3_12_8 VQ_pim_3_12_8 VQ_pre_3_12_9 VQ_pim_3_12_9 VQ_pre_3_12_10 VQ_pim_3_12_10 VQ_pre_3_12_11 VQ_pim_3_12_11 VQ_pre_3_12_12 VQ_pim_3_12_12 VQ_pre_3_12_13 VQ_pim_3_12_13 VQ_pre_3_12_14 VQ_pim_3_12_14

theorem VQ_eval_3_12 :
    ofLadj (VQ_pre_3_12_0 + VQ_pre_3_12_1 + VQ_pre_3_12_2 + VQ_pre_3_12_3 + VQ_pre_3_12_4 + VQ_pre_3_12_5 + VQ_pre_3_12_6 + VQ_pre_3_12_7 + VQ_pre_3_12_8 + VQ_pre_3_12_9 + VQ_pre_3_12_10 + VQ_pre_3_12_11 + VQ_pre_3_12_12 + VQ_pre_3_12_13 + VQ_pre_3_12_14) (VQ_pim_3_12_0 + VQ_pim_3_12_1 + VQ_pim_3_12_2 + VQ_pim_3_12_3 + VQ_pim_3_12_4 + VQ_pim_3_12_5 + VQ_pim_3_12_6 + VQ_pim_3_12_7 + VQ_pim_3_12_8 + VQ_pim_3_12_9 + VQ_pim_3_12_10 + VQ_pim_3_12_11 + VQ_pim_3_12_12 + VQ_pim_3_12_13 + VQ_pim_3_12_14) = minorQ_entry_3_12 := by
  rw [VQ_sum_poly_re_3_12, VQ_sum_poly_im_3_12,
    ofLadj_add_Phi11, minorQ_entry_3_12]

theorem VQ_entry_3_12 : (spanV * Qplus) 3 12 = minorQ 3 12 := by
  rw [Matrix.mul_apply]
  rw [sum_fin15]
  change spanV_entry_3_0 * Qplus_entry_0_12 + spanV_entry_3_1 * Qplus_entry_1_12 + spanV_entry_3_2 * Qplus_entry_2_12 + spanV_entry_3_3 * Qplus_entry_3_12 + spanV_entry_3_4 * Qplus_entry_4_12 + spanV_entry_3_5 * Qplus_entry_5_12 + spanV_entry_3_6 * Qplus_entry_6_12 + spanV_entry_3_7 * Qplus_entry_7_12 + spanV_entry_3_8 * Qplus_entry_8_12 + spanV_entry_3_9 * Qplus_entry_9_12 + spanV_entry_3_10 * Qplus_entry_10_12 + spanV_entry_3_11 * Qplus_entry_11_12 + spanV_entry_3_12 * Qplus_entry_12_12 + spanV_entry_3_13 * Qplus_entry_13_12 + spanV_entry_3_14 * Qplus_entry_14_12 = minorQ_entry_3_12
  exact (VQ_sum_entries_3_12).trans VQ_eval_3_12

end V14Formalization.D12SigmaPlusSegreCore
