/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
import V14Formalization.D12SigmaPlusSegreEval
import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def VQ_qre_0_18 : Polynomial ℚ := C (-14) + C (14) * X + C (16) * X ^ 2 + C (46) * X ^ 3 + C (48) * X ^ 4 + C (-2) * X ^ 5 + C (-8) * X ^ 6 + C (-2) * X ^ 7
def VQ_qim_0_18 : Polynomial ℚ := (0 : Polynomial ℚ)

def VQ_pre_0_18_0 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_0 :
    spanV_entry_0_0 * Qplus_entry_0_18 =
      ofLadj VQ_pre_0_18_0 VQ_pim_0_18_0 := by
  have hz : Qplus_entry_0_18 = 0 := by
    rw [Qplus_entry_0_18]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_0, VQ_pim_0_18_0]
  simp [ofLadj_zero]

def VQ_pre_0_18_1 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_1 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_1 :
    spanV_entry_0_1 * Qplus_entry_1_18 =
      ofLadj VQ_pre_0_18_1 VQ_pim_0_18_1 := by
  have hz : Qplus_entry_1_18 = 0 := by
    rw [Qplus_entry_1_18]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_1, VQ_pim_0_18_1]
  simp [ofLadj_zero]

def VQ_pre_0_18_2 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_2 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_2 :
    spanV_entry_0_2 * Qplus_entry_2_18 =
      ofLadj VQ_pre_0_18_2 VQ_pim_0_18_2 := by
  have hz : Qplus_entry_2_18 = 0 := by
    rw [Qplus_entry_2_18]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_2, VQ_pim_0_18_2]
  simp [ofLadj_zero]

def VQ_pre_0_18_3 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_3 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_3 :
    spanV_entry_0_3 * Qplus_entry_3_18 =
      ofLadj VQ_pre_0_18_3 VQ_pim_0_18_3 := by
  have hz : Qplus_entry_3_18 = 0 := by
    rw [Qplus_entry_3_18]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_3, VQ_pim_0_18_3]
  simp [ofLadj_zero]

def VQ_pre_0_18_4 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_4 :
    spanV_entry_0_4 * Qplus_entry_4_18 =
      ofLadj VQ_pre_0_18_4 VQ_pim_0_18_4 := by
  have hz : Qplus_entry_4_18 = 0 := by
    rw [Qplus_entry_4_18]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_4, VQ_pim_0_18_4]
  simp [ofLadj_zero]

def VQ_pre_0_18_5 : Polynomial ℚ := C (4) * X ^ 5 + C (4) * X ^ 6 + C (32) * X ^ 7 + C (88) * X ^ 8 + C (150) * X ^ 9 + C (196) * X ^ 10 + C (204) * X ^ 11 + C (196) * X ^ 12 + C (150) * X ^ 13 + C (88) * X ^ 14 + C (32) * X ^ 15
def VQ_pim_0_18_5 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_pre_eq_0_18_5 :
    spanV_re_0_5 * Qplus_re_5_18 - spanV_im_0_5 * Qplus_im_5_18 =
      VQ_pre_0_18_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_5, spanV_im_0_5, Qplus_re_5_18, Qplus_im_5_18,
    VQ_pre_0_18_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_0_18_5 :
    spanV_re_0_5 * Qplus_im_5_18 + spanV_im_0_5 * Qplus_re_5_18 =
      VQ_pim_0_18_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_5, spanV_im_0_5, Qplus_re_5_18, Qplus_im_5_18,
    VQ_pim_0_18_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_0_18_5 :
    spanV_entry_0_5 * Qplus_entry_5_18 =
      ofLadj VQ_pre_0_18_5 VQ_pim_0_18_5 := by
  rw [spanV_entry_0_5, Qplus_entry_5_18, ofLadj_mul,
    VQ_pre_eq_0_18_5, VQ_pim_eq_0_18_5]

def VQ_pre_0_18_6 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_6 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_6 :
    spanV_entry_0_6 * Qplus_entry_6_18 =
      ofLadj VQ_pre_0_18_6 VQ_pim_0_18_6 := by
  have hz : Qplus_entry_6_18 = 0 := by
    rw [Qplus_entry_6_18]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_6, VQ_pim_0_18_6]
  simp [ofLadj_zero]

def VQ_pre_0_18_7 : Polynomial ℚ := C (-20) + C (12) * X ^ 2 + C (48) * X ^ 3 + C (86) * X ^ 4 + C (82) * X ^ 5 + C (70) * X ^ 6 + C (38) * X ^ 7 + C (-18) * X ^ 8 + C (-82) * X ^ 9 + C (-130) * X ^ 10 + C (-132) * X ^ 11 + C (-130) * X ^ 12 + C (-94) * X ^ 13 + C (-66) * X ^ 14 + C (-48) * X ^ 15 + C (-12) * X ^ 16
def VQ_pim_0_18_7 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_pre_eq_0_18_7 :
    spanV_re_0_7 * Qplus_re_7_18 - spanV_im_0_7 * Qplus_im_7_18 =
      VQ_pre_0_18_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_7, spanV_im_0_7, Qplus_re_7_18, Qplus_im_7_18,
    VQ_pre_0_18_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_0_18_7 :
    spanV_re_0_7 * Qplus_im_7_18 + spanV_im_0_7 * Qplus_re_7_18 =
      VQ_pim_0_18_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_7, spanV_im_0_7, Qplus_re_7_18, Qplus_im_7_18,
    VQ_pim_0_18_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_0_18_7 :
    spanV_entry_0_7 * Qplus_entry_7_18 =
      ofLadj VQ_pre_0_18_7 VQ_pim_0_18_7 := by
  rw [spanV_entry_0_7, Qplus_entry_7_18, ofLadj_mul,
    VQ_pre_eq_0_18_7, VQ_pim_eq_0_18_7]

def VQ_pre_0_18_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_8 :
    spanV_entry_0_8 * Qplus_entry_8_18 =
      ofLadj VQ_pre_0_18_8 VQ_pim_0_18_8 := by
  have hz : spanV_entry_0_8 = 0 := by
    rw [spanV_entry_0_8]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_8, VQ_pim_0_18_8]
  simp [ofLadj_zero]

def VQ_pre_0_18_9 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_9 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_9 :
    spanV_entry_0_9 * Qplus_entry_9_18 =
      ofLadj VQ_pre_0_18_9 VQ_pim_0_18_9 := by
  have hz : spanV_entry_0_9 = 0 := by
    rw [spanV_entry_0_9]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_9, VQ_pim_0_18_9]
  simp [ofLadj_zero]

def VQ_pre_0_18_10 : Polynomial ℚ := C (-2) + C (-2) * X ^ 2 + C (2) * X ^ 3 + C (2) * X ^ 4 + C (4) * X ^ 6 + C (6) * X ^ 7 + C (16) * X ^ 8 + C (24) * X ^ 9 + C (32) * X ^ 10 + C (40) * X ^ 11 + C (32) * X ^ 12 + C (26) * X ^ 13 + C (14) * X ^ 14 + C (4) * X ^ 15 + C (2) * X ^ 16 + C (-2) * X ^ 17
def VQ_pim_0_18_10 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_pre_eq_0_18_10 :
    spanV_re_0_10 * Qplus_re_10_18 - spanV_im_0_10 * Qplus_im_10_18 =
      VQ_pre_0_18_10 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_10, spanV_im_0_10, Qplus_re_10_18, Qplus_im_10_18,
    VQ_pre_0_18_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_pim_eq_0_18_10 :
    spanV_re_0_10 * Qplus_im_10_18 + spanV_im_0_10 * Qplus_re_10_18 =
      VQ_pim_0_18_10 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_10, spanV_im_0_10, Qplus_re_10_18, Qplus_im_10_18,
    VQ_pim_0_18_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem VQ_term_0_18_10 :
    spanV_entry_0_10 * Qplus_entry_10_18 =
      ofLadj VQ_pre_0_18_10 VQ_pim_0_18_10 := by
  rw [spanV_entry_0_10, Qplus_entry_10_18, ofLadj_mul,
    VQ_pre_eq_0_18_10, VQ_pim_eq_0_18_10]

def VQ_pre_0_18_11 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_11 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_11 :
    spanV_entry_0_11 * Qplus_entry_11_18 =
      ofLadj VQ_pre_0_18_11 VQ_pim_0_18_11 := by
  have hz : spanV_entry_0_11 = 0 := by
    rw [spanV_entry_0_11]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_11, VQ_pim_0_18_11]
  simp [ofLadj_zero]

def VQ_pre_0_18_12 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_12 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_12 :
    spanV_entry_0_12 * Qplus_entry_12_18 =
      ofLadj VQ_pre_0_18_12 VQ_pim_0_18_12 := by
  have hz : spanV_entry_0_12 = 0 := by
    rw [spanV_entry_0_12]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_12, VQ_pim_0_18_12]
  simp [ofLadj_zero]

def VQ_pre_0_18_13 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_13 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_13 :
    spanV_entry_0_13 * Qplus_entry_13_18 =
      ofLadj VQ_pre_0_18_13 VQ_pim_0_18_13 := by
  have hz : spanV_entry_0_13 = 0 := by
    rw [spanV_entry_0_13]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_13, VQ_pim_0_18_13]
  simp [ofLadj_zero]

def VQ_pre_0_18_14 : Polynomial ℚ := (0 : Polynomial ℚ)
def VQ_pim_0_18_14 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem VQ_term_0_18_14 :
    spanV_entry_0_14 * Qplus_entry_14_18 =
      ofLadj VQ_pre_0_18_14 VQ_pim_0_18_14 := by
  have hz : spanV_entry_0_14 = 0 := by
    rw [spanV_entry_0_14]; exact ofLadj_zero
  rw [hz, VQ_pre_0_18_14, VQ_pim_0_18_14]
  simp [ofLadj_zero]

theorem VQ_sum_poly_re_0_18 :
    VQ_pre_0_18_0 + VQ_pre_0_18_1 + VQ_pre_0_18_2 + VQ_pre_0_18_3 + VQ_pre_0_18_4 + VQ_pre_0_18_5 + VQ_pre_0_18_6 + VQ_pre_0_18_7 + VQ_pre_0_18_8 + VQ_pre_0_18_9 + VQ_pre_0_18_10 + VQ_pre_0_18_11 + VQ_pre_0_18_12 + VQ_pre_0_18_13 + VQ_pre_0_18_14 = minorQ_re_0_18 + Phi11 * VQ_qre_0_18 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [VQ_pre_0_18_0, VQ_pre_0_18_1, VQ_pre_0_18_2, VQ_pre_0_18_3, VQ_pre_0_18_4, VQ_pre_0_18_5, VQ_pre_0_18_6, VQ_pre_0_18_7, VQ_pre_0_18_8, VQ_pre_0_18_9, VQ_pre_0_18_10, VQ_pre_0_18_11, VQ_pre_0_18_12, VQ_pre_0_18_13, VQ_pre_0_18_14, minorQ_re_0_18, VQ_qre_0_18]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem VQ_sum_poly_im_0_18 :
    VQ_pim_0_18_0 + VQ_pim_0_18_1 + VQ_pim_0_18_2 + VQ_pim_0_18_3 + VQ_pim_0_18_4 + VQ_pim_0_18_5 + VQ_pim_0_18_6 + VQ_pim_0_18_7 + VQ_pim_0_18_8 + VQ_pim_0_18_9 + VQ_pim_0_18_10 + VQ_pim_0_18_11 + VQ_pim_0_18_12 + VQ_pim_0_18_13 + VQ_pim_0_18_14 = minorQ_im_0_18 + Phi11 * VQ_qim_0_18 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [VQ_pim_0_18_0, VQ_pim_0_18_1, VQ_pim_0_18_2, VQ_pim_0_18_3, VQ_pim_0_18_4, VQ_pim_0_18_5, VQ_pim_0_18_6, VQ_pim_0_18_7, VQ_pim_0_18_8, VQ_pim_0_18_9, VQ_pim_0_18_10, VQ_pim_0_18_11, VQ_pim_0_18_12, VQ_pim_0_18_13, VQ_pim_0_18_14, minorQ_im_0_18, VQ_qim_0_18]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem VQ_sum_entries_0_18 :
    spanV_entry_0_0 * Qplus_entry_0_18 + spanV_entry_0_1 * Qplus_entry_1_18 + spanV_entry_0_2 * Qplus_entry_2_18 + spanV_entry_0_3 * Qplus_entry_3_18 + spanV_entry_0_4 * Qplus_entry_4_18 + spanV_entry_0_5 * Qplus_entry_5_18 + spanV_entry_0_6 * Qplus_entry_6_18 + spanV_entry_0_7 * Qplus_entry_7_18 + spanV_entry_0_8 * Qplus_entry_8_18 + spanV_entry_0_9 * Qplus_entry_9_18 + spanV_entry_0_10 * Qplus_entry_10_18 + spanV_entry_0_11 * Qplus_entry_11_18 + spanV_entry_0_12 * Qplus_entry_12_18 + spanV_entry_0_13 * Qplus_entry_13_18 + spanV_entry_0_14 * Qplus_entry_14_18 =
      ofLadj (VQ_pre_0_18_0 + VQ_pre_0_18_1 + VQ_pre_0_18_2 + VQ_pre_0_18_3 + VQ_pre_0_18_4 + VQ_pre_0_18_5 + VQ_pre_0_18_6 + VQ_pre_0_18_7 + VQ_pre_0_18_8 + VQ_pre_0_18_9 + VQ_pre_0_18_10 + VQ_pre_0_18_11 + VQ_pre_0_18_12 + VQ_pre_0_18_13 + VQ_pre_0_18_14) (VQ_pim_0_18_0 + VQ_pim_0_18_1 + VQ_pim_0_18_2 + VQ_pim_0_18_3 + VQ_pim_0_18_4 + VQ_pim_0_18_5 + VQ_pim_0_18_6 + VQ_pim_0_18_7 + VQ_pim_0_18_8 + VQ_pim_0_18_9 + VQ_pim_0_18_10 + VQ_pim_0_18_11 + VQ_pim_0_18_12 + VQ_pim_0_18_13 + VQ_pim_0_18_14) := by
  simp only [VQ_term_0_18_0, VQ_term_0_18_1, VQ_term_0_18_2, VQ_term_0_18_3, VQ_term_0_18_4, VQ_term_0_18_5, VQ_term_0_18_6, VQ_term_0_18_7, VQ_term_0_18_8, VQ_term_0_18_9, VQ_term_0_18_10, VQ_term_0_18_11, VQ_term_0_18_12, VQ_term_0_18_13, VQ_term_0_18_14]
  simpa [add_assoc] using ofLadj_add15 VQ_pre_0_18_0 VQ_pim_0_18_0 VQ_pre_0_18_1 VQ_pim_0_18_1 VQ_pre_0_18_2 VQ_pim_0_18_2 VQ_pre_0_18_3 VQ_pim_0_18_3 VQ_pre_0_18_4 VQ_pim_0_18_4 VQ_pre_0_18_5 VQ_pim_0_18_5 VQ_pre_0_18_6 VQ_pim_0_18_6 VQ_pre_0_18_7 VQ_pim_0_18_7 VQ_pre_0_18_8 VQ_pim_0_18_8 VQ_pre_0_18_9 VQ_pim_0_18_9 VQ_pre_0_18_10 VQ_pim_0_18_10 VQ_pre_0_18_11 VQ_pim_0_18_11 VQ_pre_0_18_12 VQ_pim_0_18_12 VQ_pre_0_18_13 VQ_pim_0_18_13 VQ_pre_0_18_14 VQ_pim_0_18_14

theorem VQ_eval_0_18 :
    ofLadj (VQ_pre_0_18_0 + VQ_pre_0_18_1 + VQ_pre_0_18_2 + VQ_pre_0_18_3 + VQ_pre_0_18_4 + VQ_pre_0_18_5 + VQ_pre_0_18_6 + VQ_pre_0_18_7 + VQ_pre_0_18_8 + VQ_pre_0_18_9 + VQ_pre_0_18_10 + VQ_pre_0_18_11 + VQ_pre_0_18_12 + VQ_pre_0_18_13 + VQ_pre_0_18_14) (VQ_pim_0_18_0 + VQ_pim_0_18_1 + VQ_pim_0_18_2 + VQ_pim_0_18_3 + VQ_pim_0_18_4 + VQ_pim_0_18_5 + VQ_pim_0_18_6 + VQ_pim_0_18_7 + VQ_pim_0_18_8 + VQ_pim_0_18_9 + VQ_pim_0_18_10 + VQ_pim_0_18_11 + VQ_pim_0_18_12 + VQ_pim_0_18_13 + VQ_pim_0_18_14) = minorQ_entry_0_18 := by
  rw [VQ_sum_poly_re_0_18, VQ_sum_poly_im_0_18,
    ofLadj_add_Phi11, minorQ_entry_0_18]

theorem VQ_entry_0_18 : (spanV * Qplus) 0 18 = minorQ 0 18 := by
  rw [Matrix.mul_apply]
  rw [sum_fin15]
  change spanV_entry_0_0 * Qplus_entry_0_18 + spanV_entry_0_1 * Qplus_entry_1_18 + spanV_entry_0_2 * Qplus_entry_2_18 + spanV_entry_0_3 * Qplus_entry_3_18 + spanV_entry_0_4 * Qplus_entry_4_18 + spanV_entry_0_5 * Qplus_entry_5_18 + spanV_entry_0_6 * Qplus_entry_6_18 + spanV_entry_0_7 * Qplus_entry_7_18 + spanV_entry_0_8 * Qplus_entry_8_18 + spanV_entry_0_9 * Qplus_entry_9_18 + spanV_entry_0_10 * Qplus_entry_10_18 + spanV_entry_0_11 * Qplus_entry_11_18 + spanV_entry_0_12 * Qplus_entry_12_18 + spanV_entry_0_13 * Qplus_entry_13_18 + spanV_entry_0_14 * Qplus_entry_14_18 = minorQ_entry_0_18
  exact (VQ_sum_entries_0_18).trans VQ_eval_0_18

end V14Formalization.D12SigmaPlusSegreCore
