/-
Auto-generated by scripts/export_sigma_plus_identities.py.
Stock-limit, kernel-checkable plus Segre entry identities.
-/
module

public import V14Formalization.D12SigmaPlusSegreEval
public import V14Formalization.D12SigmaPlusSegreQplus
public import V14Formalization.D12SigmaPlusSegreApply_Qplus
public import V14Formalization.D12SigmaPlusSegreApply_BplusPoly
public import V14Formalization.D12SigmaPlusSegreBplus
public import V14Formalization.D12SigmaPlusQuadric6

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

open D12SigmaPlusQuadric6

def Qraw_3_0 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_0 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_0 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (0 : Fin 21) =
      Bplus_poly_0_0 * Bplus_poly_12_0 - Bplus_poly_2_0 * Bplus_poly_7_0 + Bplus_poly_3_0 * Bplus_poly_6_0 := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_0, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_0 :
    Bplus_poly_0_0 * Bplus_poly_12_0 - Bplus_poly_2_0 * Bplus_poly_7_0 + Bplus_poly_3_0 * Bplus_poly_6_0 = Qraw_3_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_0, Bplus_poly_12_0, Bplus_poly_2_0, Bplus_poly_7_0, Bplus_poly_3_0, Bplus_poly_6_0, Qraw_3_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_0 :
    Qraw_3_0 = Qplus_re_3_0 + Phi11 * Qquot_3_0 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_0, Qplus_re_3_0, Qquot_3_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_0 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (0 : Fin 21) =
      Qplus_entry_3_0 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (0 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (0 : Fin 21),
    Qexpand_3_0, Qraw_eq_3_0, Qrel_3_0, ofPoly_add_Phi11]
  simp [Qplus_entry_3_0, Qplus_im_3_0, ofLadj_ofPoly]

def Qraw_3_1 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_1 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_1 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (1 : Fin 21) =
      (Bplus_poly_0_0 * Bplus_poly_12_1 + Bplus_poly_0_1 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_1 + Bplus_poly_2_1 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_1 + Bplus_poly_3_1 * Bplus_poly_6_0) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_1, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_1 :
    (Bplus_poly_0_0 * Bplus_poly_12_1 + Bplus_poly_0_1 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_1 + Bplus_poly_2_1 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_1 + Bplus_poly_3_1 * Bplus_poly_6_0) = Qraw_3_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_0, Bplus_poly_0_1, Bplus_poly_12_0, Bplus_poly_12_1, Bplus_poly_2_0, Bplus_poly_2_1, Bplus_poly_7_0, Bplus_poly_7_1, Bplus_poly_3_0, Bplus_poly_3_1, Bplus_poly_6_0, Bplus_poly_6_1, Qraw_3_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_1 :
    Qraw_3_1 = Qplus_re_3_1 + Phi11 * Qquot_3_1 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_1, Qplus_re_3_1, Qquot_3_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_1 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (1 : Fin 21) =
      Qplus_entry_3_1 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (1 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (1 : Fin 21),
    Qexpand_3_1, Qraw_eq_3_1, Qrel_3_1, ofPoly_add_Phi11]
  simp [Qplus_entry_3_1, Qplus_im_3_1, ofLadj_ofPoly]

def Qraw_3_2 : Polynomial ℚ := C ((1 / 2 : ℚ)) * X ^ 2 + C ((1 / 2 : ℚ)) * X ^ 3 + C ((1 / 2 : ℚ)) * X ^ 4 + C ((1 / 2 : ℚ)) * X ^ 5 + C ((1 / 2 : ℚ)) * X ^ 6 + C ((1 / 2 : ℚ)) * X ^ 7 + C ((1 / 2 : ℚ)) * X ^ 8 + C ((1 / 2 : ℚ)) * X ^ 9
def Qquot_3_2 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_2 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (2 : Fin 21) =
      (Bplus_poly_0_0 * Bplus_poly_12_2 + Bplus_poly_0_2 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_2 + Bplus_poly_2_2 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_2 + Bplus_poly_3_2 * Bplus_poly_6_0) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_2, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_2 :
    (Bplus_poly_0_0 * Bplus_poly_12_2 + Bplus_poly_0_2 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_2 + Bplus_poly_2_2 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_2 + Bplus_poly_3_2 * Bplus_poly_6_0) = Qraw_3_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_0, Bplus_poly_0_2, Bplus_poly_12_0, Bplus_poly_12_2, Bplus_poly_2_0, Bplus_poly_2_2, Bplus_poly_7_0, Bplus_poly_7_2, Bplus_poly_3_0, Bplus_poly_3_2, Bplus_poly_6_0, Bplus_poly_6_2, Qraw_3_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_2 :
    Qraw_3_2 = Qplus_re_3_2 + Phi11 * Qquot_3_2 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_2, Qplus_re_3_2, Qquot_3_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_2 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (2 : Fin 21) =
      Qplus_entry_3_2 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (2 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (2 : Fin 21),
    Qexpand_3_2, Qraw_eq_3_2, Qrel_3_2, ofPoly_add_Phi11]
  simp [Qplus_entry_3_2, Qplus_im_3_2, ofLadj_ofPoly]

def Qraw_3_3 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_3 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_3 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (3 : Fin 21) =
      (Bplus_poly_0_0 * Bplus_poly_12_3 + Bplus_poly_0_3 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_3 + Bplus_poly_2_3 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_3 + Bplus_poly_3_3 * Bplus_poly_6_0) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_3, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_3 :
    (Bplus_poly_0_0 * Bplus_poly_12_3 + Bplus_poly_0_3 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_3 + Bplus_poly_2_3 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_3 + Bplus_poly_3_3 * Bplus_poly_6_0) = Qraw_3_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_0, Bplus_poly_0_3, Bplus_poly_12_0, Bplus_poly_12_3, Bplus_poly_2_0, Bplus_poly_2_3, Bplus_poly_7_0, Bplus_poly_7_3, Bplus_poly_3_0, Bplus_poly_3_3, Bplus_poly_6_0, Bplus_poly_6_3, Qraw_3_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_3 :
    Qraw_3_3 = Qplus_re_3_3 + Phi11 * Qquot_3_3 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_3, Qplus_re_3_3, Qquot_3_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_3 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (3 : Fin 21) =
      Qplus_entry_3_3 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (3 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (3 : Fin 21),
    Qexpand_3_3, Qraw_eq_3_3, Qrel_3_3, ofPoly_add_Phi11]
  simp [Qplus_entry_3_3, Qplus_im_3_3, ofLadj_ofPoly]

def Qraw_3_4 : Polynomial ℚ := C ((1 / 2 : ℚ))
def Qquot_3_4 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_4 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (4 : Fin 21) =
      (Bplus_poly_0_0 * Bplus_poly_12_4 + Bplus_poly_0_4 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_4 + Bplus_poly_2_4 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_4 + Bplus_poly_3_4 * Bplus_poly_6_0) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_4, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_4 :
    (Bplus_poly_0_0 * Bplus_poly_12_4 + Bplus_poly_0_4 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_4 + Bplus_poly_2_4 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_4 + Bplus_poly_3_4 * Bplus_poly_6_0) = Qraw_3_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_0, Bplus_poly_0_4, Bplus_poly_12_0, Bplus_poly_12_4, Bplus_poly_2_0, Bplus_poly_2_4, Bplus_poly_7_0, Bplus_poly_7_4, Bplus_poly_3_0, Bplus_poly_3_4, Bplus_poly_6_0, Bplus_poly_6_4, Qraw_3_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_4 :
    Qraw_3_4 = Qplus_re_3_4 + Phi11 * Qquot_3_4 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_4, Qplus_re_3_4, Qquot_3_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_4 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (4 : Fin 21) =
      Qplus_entry_3_4 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (4 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (4 : Fin 21),
    Qexpand_3_4, Qraw_eq_3_4, Qrel_3_4, ofPoly_add_Phi11]
  simp [Qplus_entry_3_4, Qplus_im_3_4, ofLadj_ofPoly]

def Qraw_3_5 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_5 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_5 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (5 : Fin 21) =
      (Bplus_poly_0_0 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_0) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_5, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_5 :
    (Bplus_poly_0_0 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_0) - (Bplus_poly_2_0 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_0) + (Bplus_poly_3_0 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_0) = Qraw_3_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_0, Bplus_poly_0_5, Bplus_poly_12_0, Bplus_poly_12_5, Bplus_poly_2_0, Bplus_poly_2_5, Bplus_poly_7_0, Bplus_poly_7_5, Bplus_poly_3_0, Bplus_poly_3_5, Bplus_poly_6_0, Bplus_poly_6_5, Qraw_3_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_5 :
    Qraw_3_5 = Qplus_re_3_5 + Phi11 * Qquot_3_5 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_5, Qplus_re_3_5, Qquot_3_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_5 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (5 : Fin 21) =
      Qplus_entry_3_5 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (5 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (5 : Fin 21),
    Qexpand_3_5, Qraw_eq_3_5, Qrel_3_5, ofPoly_add_Phi11]
  simp [Qplus_entry_3_5, Qplus_im_3_5, ofLadj_ofPoly]

def Qraw_3_6 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_6 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_6 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (6 : Fin 21) =
      Bplus_poly_0_1 * Bplus_poly_12_1 - Bplus_poly_2_1 * Bplus_poly_7_1 + Bplus_poly_3_1 * Bplus_poly_6_1 := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_6, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_6 :
    Bplus_poly_0_1 * Bplus_poly_12_1 - Bplus_poly_2_1 * Bplus_poly_7_1 + Bplus_poly_3_1 * Bplus_poly_6_1 = Qraw_3_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_1, Bplus_poly_12_1, Bplus_poly_2_1, Bplus_poly_7_1, Bplus_poly_3_1, Bplus_poly_6_1, Qraw_3_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_6 :
    Qraw_3_6 = Qplus_re_3_6 + Phi11 * Qquot_3_6 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_6, Qplus_re_3_6, Qquot_3_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_6 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (6 : Fin 21) =
      Qplus_entry_3_6 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (6 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (6 : Fin 21),
    Qexpand_3_6, Qraw_eq_3_6, Qrel_3_6, ofPoly_add_Phi11]
  simp [Qplus_entry_3_6, Qplus_im_3_6, ofLadj_ofPoly]

def Qraw_3_7 : Polynomial ℚ := C ((1 / 2 : ℚ)) + C ((-1 / 2 : ℚ)) * X ^ 2 + C ((-1 / 2 : ℚ)) * X ^ 9
def Qquot_3_7 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_7 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (7 : Fin 21) =
      (Bplus_poly_0_1 * Bplus_poly_12_2 + Bplus_poly_0_2 * Bplus_poly_12_1) - (Bplus_poly_2_1 * Bplus_poly_7_2 + Bplus_poly_2_2 * Bplus_poly_7_1) + (Bplus_poly_3_1 * Bplus_poly_6_2 + Bplus_poly_3_2 * Bplus_poly_6_1) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_7, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_7 :
    (Bplus_poly_0_1 * Bplus_poly_12_2 + Bplus_poly_0_2 * Bplus_poly_12_1) - (Bplus_poly_2_1 * Bplus_poly_7_2 + Bplus_poly_2_2 * Bplus_poly_7_1) + (Bplus_poly_3_1 * Bplus_poly_6_2 + Bplus_poly_3_2 * Bplus_poly_6_1) = Qraw_3_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_1, Bplus_poly_0_2, Bplus_poly_12_1, Bplus_poly_12_2, Bplus_poly_2_1, Bplus_poly_2_2, Bplus_poly_7_1, Bplus_poly_7_2, Bplus_poly_3_1, Bplus_poly_3_2, Bplus_poly_6_1, Bplus_poly_6_2, Qraw_3_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_7 :
    Qraw_3_7 = Qplus_re_3_7 + Phi11 * Qquot_3_7 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_7, Qplus_re_3_7, Qquot_3_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_7 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (7 : Fin 21) =
      Qplus_entry_3_7 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (7 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (7 : Fin 21),
    Qexpand_3_7, Qraw_eq_3_7, Qrel_3_7, ofPoly_add_Phi11]
  simp [Qplus_entry_3_7, Qplus_im_3_7, ofLadj_ofPoly]

def Qraw_3_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_8 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_8 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (8 : Fin 21) =
      (Bplus_poly_0_1 * Bplus_poly_12_3 + Bplus_poly_0_3 * Bplus_poly_12_1) - (Bplus_poly_2_1 * Bplus_poly_7_3 + Bplus_poly_2_3 * Bplus_poly_7_1) + (Bplus_poly_3_1 * Bplus_poly_6_3 + Bplus_poly_3_3 * Bplus_poly_6_1) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_8, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_8 :
    (Bplus_poly_0_1 * Bplus_poly_12_3 + Bplus_poly_0_3 * Bplus_poly_12_1) - (Bplus_poly_2_1 * Bplus_poly_7_3 + Bplus_poly_2_3 * Bplus_poly_7_1) + (Bplus_poly_3_1 * Bplus_poly_6_3 + Bplus_poly_3_3 * Bplus_poly_6_1) = Qraw_3_8 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_1, Bplus_poly_0_3, Bplus_poly_12_1, Bplus_poly_12_3, Bplus_poly_2_1, Bplus_poly_2_3, Bplus_poly_7_1, Bplus_poly_7_3, Bplus_poly_3_1, Bplus_poly_3_3, Bplus_poly_6_1, Bplus_poly_6_3, Qraw_3_8]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_8 :
    Qraw_3_8 = Qplus_re_3_8 + Phi11 * Qquot_3_8 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_8, Qplus_re_3_8, Qquot_3_8]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_8 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (8 : Fin 21) =
      Qplus_entry_3_8 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (8 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (8 : Fin 21),
    Qexpand_3_8, Qraw_eq_3_8, Qrel_3_8, ofPoly_add_Phi11]
  simp [Qplus_entry_3_8, Qplus_im_3_8, ofLadj_ofPoly]

def Qraw_3_9 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_9 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_9 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (9 : Fin 21) =
      (Bplus_poly_0_1 * Bplus_poly_12_4 + Bplus_poly_0_4 * Bplus_poly_12_1) - (Bplus_poly_2_1 * Bplus_poly_7_4 + Bplus_poly_2_4 * Bplus_poly_7_1) + (Bplus_poly_3_1 * Bplus_poly_6_4 + Bplus_poly_3_4 * Bplus_poly_6_1) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_9, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_9 :
    (Bplus_poly_0_1 * Bplus_poly_12_4 + Bplus_poly_0_4 * Bplus_poly_12_1) - (Bplus_poly_2_1 * Bplus_poly_7_4 + Bplus_poly_2_4 * Bplus_poly_7_1) + (Bplus_poly_3_1 * Bplus_poly_6_4 + Bplus_poly_3_4 * Bplus_poly_6_1) = Qraw_3_9 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_1, Bplus_poly_0_4, Bplus_poly_12_1, Bplus_poly_12_4, Bplus_poly_2_1, Bplus_poly_2_4, Bplus_poly_7_1, Bplus_poly_7_4, Bplus_poly_3_1, Bplus_poly_3_4, Bplus_poly_6_1, Bplus_poly_6_4, Qraw_3_9]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_9 :
    Qraw_3_9 = Qplus_re_3_9 + Phi11 * Qquot_3_9 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_9, Qplus_re_3_9, Qquot_3_9]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_9 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (9 : Fin 21) =
      Qplus_entry_3_9 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (9 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (9 : Fin 21),
    Qexpand_3_9, Qraw_eq_3_9, Qrel_3_9, ofPoly_add_Phi11]
  simp [Qplus_entry_3_9, Qplus_im_3_9, ofLadj_ofPoly]

def Qraw_3_10 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_10 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_10 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (10 : Fin 21) =
      (Bplus_poly_0_1 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_1) - (Bplus_poly_2_1 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_1) + (Bplus_poly_3_1 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_1) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_10, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_10 :
    (Bplus_poly_0_1 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_1) - (Bplus_poly_2_1 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_1) + (Bplus_poly_3_1 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_1) = Qraw_3_10 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_1, Bplus_poly_0_5, Bplus_poly_12_1, Bplus_poly_12_5, Bplus_poly_2_1, Bplus_poly_2_5, Bplus_poly_7_1, Bplus_poly_7_5, Bplus_poly_3_1, Bplus_poly_3_5, Bplus_poly_6_1, Bplus_poly_6_5, Qraw_3_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_10 :
    Qraw_3_10 = Qplus_re_3_10 + Phi11 * Qquot_3_10 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_10, Qplus_re_3_10, Qquot_3_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_10 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (10 : Fin 21) =
      Qplus_entry_3_10 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (10 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (10 : Fin 21),
    Qexpand_3_10, Qraw_eq_3_10, Qrel_3_10, ofPoly_add_Phi11]
  simp [Qplus_entry_3_10, Qplus_im_3_10, ofLadj_ofPoly]

def Qraw_3_11 : Polynomial ℚ := C ((-1 / 2 : ℚ)) * X ^ 3 + C ((-1 / 2 : ℚ)) * X ^ 8
def Qquot_3_11 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_11 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (11 : Fin 21) =
      Bplus_poly_0_2 * Bplus_poly_12_2 - Bplus_poly_2_2 * Bplus_poly_7_2 + Bplus_poly_3_2 * Bplus_poly_6_2 := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_11, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_11 :
    Bplus_poly_0_2 * Bplus_poly_12_2 - Bplus_poly_2_2 * Bplus_poly_7_2 + Bplus_poly_3_2 * Bplus_poly_6_2 = Qraw_3_11 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_2, Bplus_poly_12_2, Bplus_poly_2_2, Bplus_poly_7_2, Bplus_poly_3_2, Bplus_poly_6_2, Qraw_3_11]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_11 :
    Qraw_3_11 = Qplus_re_3_11 + Phi11 * Qquot_3_11 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_11, Qplus_re_3_11, Qquot_3_11]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_11 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (11 : Fin 21) =
      Qplus_entry_3_11 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (11 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (11 : Fin 21),
    Qexpand_3_11, Qraw_eq_3_11, Qrel_3_11, ofPoly_add_Phi11]
  simp [Qplus_entry_3_11, Qplus_im_3_11, ofLadj_ofPoly]

def Qraw_3_12 : Polynomial ℚ := C ((-1 / 2 : ℚ)) + C ((-1 / 2 : ℚ)) * X ^ 4 + C ((-1 / 2 : ℚ)) * X ^ 7
def Qquot_3_12 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_12 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (12 : Fin 21) =
      (Bplus_poly_0_2 * Bplus_poly_12_3 + Bplus_poly_0_3 * Bplus_poly_12_2) - (Bplus_poly_2_2 * Bplus_poly_7_3 + Bplus_poly_2_3 * Bplus_poly_7_2) + (Bplus_poly_3_2 * Bplus_poly_6_3 + Bplus_poly_3_3 * Bplus_poly_6_2) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_12, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_12 :
    (Bplus_poly_0_2 * Bplus_poly_12_3 + Bplus_poly_0_3 * Bplus_poly_12_2) - (Bplus_poly_2_2 * Bplus_poly_7_3 + Bplus_poly_2_3 * Bplus_poly_7_2) + (Bplus_poly_3_2 * Bplus_poly_6_3 + Bplus_poly_3_3 * Bplus_poly_6_2) = Qraw_3_12 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_2, Bplus_poly_0_3, Bplus_poly_12_2, Bplus_poly_12_3, Bplus_poly_2_2, Bplus_poly_2_3, Bplus_poly_7_2, Bplus_poly_7_3, Bplus_poly_3_2, Bplus_poly_3_3, Bplus_poly_6_2, Bplus_poly_6_3, Qraw_3_12]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_12 :
    Qraw_3_12 = Qplus_re_3_12 + Phi11 * Qquot_3_12 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_12, Qplus_re_3_12, Qquot_3_12]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_12 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (12 : Fin 21) =
      Qplus_entry_3_12 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (12 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (12 : Fin 21),
    Qexpand_3_12, Qraw_eq_3_12, Qrel_3_12, ofPoly_add_Phi11]
  simp [Qplus_entry_3_12, Qplus_im_3_12, ofLadj_ofPoly]

def Qraw_3_13 : Polynomial ℚ := C ((-1 / 2 : ℚ)) * X ^ 5 + C ((-1 / 2 : ℚ)) * X ^ 6
def Qquot_3_13 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_13 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (13 : Fin 21) =
      (Bplus_poly_0_2 * Bplus_poly_12_4 + Bplus_poly_0_4 * Bplus_poly_12_2) - (Bplus_poly_2_2 * Bplus_poly_7_4 + Bplus_poly_2_4 * Bplus_poly_7_2) + (Bplus_poly_3_2 * Bplus_poly_6_4 + Bplus_poly_3_4 * Bplus_poly_6_2) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_13, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_13 :
    (Bplus_poly_0_2 * Bplus_poly_12_4 + Bplus_poly_0_4 * Bplus_poly_12_2) - (Bplus_poly_2_2 * Bplus_poly_7_4 + Bplus_poly_2_4 * Bplus_poly_7_2) + (Bplus_poly_3_2 * Bplus_poly_6_4 + Bplus_poly_3_4 * Bplus_poly_6_2) = Qraw_3_13 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_2, Bplus_poly_0_4, Bplus_poly_12_2, Bplus_poly_12_4, Bplus_poly_2_2, Bplus_poly_2_4, Bplus_poly_7_2, Bplus_poly_7_4, Bplus_poly_3_2, Bplus_poly_3_4, Bplus_poly_6_2, Bplus_poly_6_4, Qraw_3_13]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_13 :
    Qraw_3_13 = Qplus_re_3_13 + Phi11 * Qquot_3_13 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_13, Qplus_re_3_13, Qquot_3_13]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_13 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (13 : Fin 21) =
      Qplus_entry_3_13 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (13 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (13 : Fin 21),
    Qexpand_3_13, Qraw_eq_3_13, Qrel_3_13, ofPoly_add_Phi11]
  simp [Qplus_entry_3_13, Qplus_im_3_13, ofLadj_ofPoly]

def Qraw_3_14 : Polynomial ℚ := C (1)
def Qquot_3_14 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_14 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (14 : Fin 21) =
      (Bplus_poly_0_2 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_2) - (Bplus_poly_2_2 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_2) + (Bplus_poly_3_2 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_2) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_14, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_14 :
    (Bplus_poly_0_2 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_2) - (Bplus_poly_2_2 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_2) + (Bplus_poly_3_2 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_2) = Qraw_3_14 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_2, Bplus_poly_0_5, Bplus_poly_12_2, Bplus_poly_12_5, Bplus_poly_2_2, Bplus_poly_2_5, Bplus_poly_7_2, Bplus_poly_7_5, Bplus_poly_3_2, Bplus_poly_3_5, Bplus_poly_6_2, Bplus_poly_6_5, Qraw_3_14]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_14 :
    Qraw_3_14 = Qplus_re_3_14 + Phi11 * Qquot_3_14 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_14, Qplus_re_3_14, Qquot_3_14]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_14 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (14 : Fin 21) =
      Qplus_entry_3_14 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (14 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (14 : Fin 21),
    Qexpand_3_14, Qraw_eq_3_14, Qrel_3_14, ofPoly_add_Phi11]
  simp [Qplus_entry_3_14, Qplus_im_3_14, ofLadj_ofPoly]

def Qraw_3_15 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_15 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_15 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (15 : Fin 21) =
      Bplus_poly_0_3 * Bplus_poly_12_3 - Bplus_poly_2_3 * Bplus_poly_7_3 + Bplus_poly_3_3 * Bplus_poly_6_3 := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_15, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_15 :
    Bplus_poly_0_3 * Bplus_poly_12_3 - Bplus_poly_2_3 * Bplus_poly_7_3 + Bplus_poly_3_3 * Bplus_poly_6_3 = Qraw_3_15 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_3, Bplus_poly_12_3, Bplus_poly_2_3, Bplus_poly_7_3, Bplus_poly_3_3, Bplus_poly_6_3, Qraw_3_15]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_15 :
    Qraw_3_15 = Qplus_re_3_15 + Phi11 * Qquot_3_15 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_15, Qplus_re_3_15, Qquot_3_15]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_15 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (15 : Fin 21) =
      Qplus_entry_3_15 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (15 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (15 : Fin 21),
    Qexpand_3_15, Qraw_eq_3_15, Qrel_3_15, ofPoly_add_Phi11]
  simp [Qplus_entry_3_15, Qplus_im_3_15, ofLadj_ofPoly]

def Qraw_3_16 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_16 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_16 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (16 : Fin 21) =
      (Bplus_poly_0_3 * Bplus_poly_12_4 + Bplus_poly_0_4 * Bplus_poly_12_3) - (Bplus_poly_2_3 * Bplus_poly_7_4 + Bplus_poly_2_4 * Bplus_poly_7_3) + (Bplus_poly_3_3 * Bplus_poly_6_4 + Bplus_poly_3_4 * Bplus_poly_6_3) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_16, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_16 :
    (Bplus_poly_0_3 * Bplus_poly_12_4 + Bplus_poly_0_4 * Bplus_poly_12_3) - (Bplus_poly_2_3 * Bplus_poly_7_4 + Bplus_poly_2_4 * Bplus_poly_7_3) + (Bplus_poly_3_3 * Bplus_poly_6_4 + Bplus_poly_3_4 * Bplus_poly_6_3) = Qraw_3_16 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_3, Bplus_poly_0_4, Bplus_poly_12_3, Bplus_poly_12_4, Bplus_poly_2_3, Bplus_poly_2_4, Bplus_poly_7_3, Bplus_poly_7_4, Bplus_poly_3_3, Bplus_poly_3_4, Bplus_poly_6_3, Bplus_poly_6_4, Qraw_3_16]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_16 :
    Qraw_3_16 = Qplus_re_3_16 + Phi11 * Qquot_3_16 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_16, Qplus_re_3_16, Qquot_3_16]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_16 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (16 : Fin 21) =
      Qplus_entry_3_16 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (16 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (16 : Fin 21),
    Qexpand_3_16, Qraw_eq_3_16, Qrel_3_16, ofPoly_add_Phi11]
  simp [Qplus_entry_3_16, Qplus_im_3_16, ofLadj_ofPoly]

def Qraw_3_17 : Polynomial ℚ := C (1)
def Qquot_3_17 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_17 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (17 : Fin 21) =
      (Bplus_poly_0_3 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_3) - (Bplus_poly_2_3 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_3) + (Bplus_poly_3_3 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_3) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_17, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_17 :
    (Bplus_poly_0_3 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_3) - (Bplus_poly_2_3 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_3) + (Bplus_poly_3_3 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_3) = Qraw_3_17 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_3, Bplus_poly_0_5, Bplus_poly_12_3, Bplus_poly_12_5, Bplus_poly_2_3, Bplus_poly_2_5, Bplus_poly_7_3, Bplus_poly_7_5, Bplus_poly_3_3, Bplus_poly_3_5, Bplus_poly_6_3, Bplus_poly_6_5, Qraw_3_17]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_17 :
    Qraw_3_17 = Qplus_re_3_17 + Phi11 * Qquot_3_17 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_17, Qplus_re_3_17, Qquot_3_17]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_17 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (17 : Fin 21) =
      Qplus_entry_3_17 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (17 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (17 : Fin 21),
    Qexpand_3_17, Qraw_eq_3_17, Qrel_3_17, ofPoly_add_Phi11]
  simp [Qplus_entry_3_17, Qplus_im_3_17, ofLadj_ofPoly]

def Qraw_3_18 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_18 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_18 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (18 : Fin 21) =
      Bplus_poly_0_4 * Bplus_poly_12_4 - Bplus_poly_2_4 * Bplus_poly_7_4 + Bplus_poly_3_4 * Bplus_poly_6_4 := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_18, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_18 :
    Bplus_poly_0_4 * Bplus_poly_12_4 - Bplus_poly_2_4 * Bplus_poly_7_4 + Bplus_poly_3_4 * Bplus_poly_6_4 = Qraw_3_18 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_4, Bplus_poly_12_4, Bplus_poly_2_4, Bplus_poly_7_4, Bplus_poly_3_4, Bplus_poly_6_4, Qraw_3_18]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_18 :
    Qraw_3_18 = Qplus_re_3_18 + Phi11 * Qquot_3_18 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_18, Qplus_re_3_18, Qquot_3_18]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_18 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (18 : Fin 21) =
      Qplus_entry_3_18 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (18 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (18 : Fin 21),
    Qexpand_3_18, Qraw_eq_3_18, Qrel_3_18, ofPoly_add_Phi11]
  simp [Qplus_entry_3_18, Qplus_im_3_18, ofLadj_ofPoly]

def Qraw_3_19 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_19 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_19 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (19 : Fin 21) =
      (Bplus_poly_0_4 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_4) - (Bplus_poly_2_4 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_4) + (Bplus_poly_3_4 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_4) := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_19, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_19 :
    (Bplus_poly_0_4 * Bplus_poly_12_5 + Bplus_poly_0_5 * Bplus_poly_12_4) - (Bplus_poly_2_4 * Bplus_poly_7_5 + Bplus_poly_2_5 * Bplus_poly_7_4) + (Bplus_poly_3_4 * Bplus_poly_6_5 + Bplus_poly_3_5 * Bplus_poly_6_4) = Qraw_3_19 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_4, Bplus_poly_0_5, Bplus_poly_12_4, Bplus_poly_12_5, Bplus_poly_2_4, Bplus_poly_2_5, Bplus_poly_7_4, Bplus_poly_7_5, Bplus_poly_3_4, Bplus_poly_3_5, Bplus_poly_6_4, Bplus_poly_6_5, Qraw_3_19]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_19 :
    Qraw_3_19 = Qplus_re_3_19 + Phi11 * Qquot_3_19 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_19, Qplus_re_3_19, Qquot_3_19]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_19 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (19 : Fin 21) =
      Qplus_entry_3_19 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (19 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (19 : Fin 21),
    Qexpand_3_19, Qraw_eq_3_19, Qrel_3_19, ofPoly_add_Phi11]
  simp [Qplus_entry_3_19, Qplus_im_3_19, ofLadj_ofPoly]

def Qraw_3_20 : Polynomial ℚ := (0 : Polynomial ℚ)
def Qquot_3_20 : Polynomial ℚ := (0 : Polynomial ℚ)

theorem Qexpand_3_20 :
    restrictedPluckerCoeffs Bplus_poly (3 : Fin 15) (20 : Fin 21) =
      Bplus_poly_0_5 * Bplus_poly_12_5 - Bplus_poly_2_5 * Bplus_poly_7_5 + Bplus_poly_3_5 * Bplus_poly_6_5 := by
  simp [restrictedPluckerCoeffs, bilinearCoeffs,
    monomPair_20, pluckerRelation_3, Bplus_poly, Bplus_poly_row0, Bplus_poly_row12, Bplus_poly_row2, Bplus_poly_row7, Bplus_poly_row3, Bplus_poly_row6]
  try ring

theorem Qraw_eq_3_20 :
    Bplus_poly_0_5 * Bplus_poly_12_5 - Bplus_poly_2_5 * Bplus_poly_7_5 + Bplus_poly_3_5 * Bplus_poly_6_5 = Qraw_3_20 := by
  refine Polynomial.funext fun r => ?_
  simp only [Bplus_poly_0_5, Bplus_poly_12_5, Bplus_poly_2_5, Bplus_poly_7_5, Bplus_poly_3_5, Bplus_poly_6_5, Qraw_3_20]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qrel_3_20 :
    Qraw_3_20 = Qplus_re_3_20 + Phi11 * Qquot_3_20 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [Qraw_3_20, Qplus_re_3_20, Qquot_3_20]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem Qplus_eq_restricted_3_20 :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) (20 : Fin 21) =
      Qplus_entry_3_20 := by
  rw [congrFun (restrictedPluckerCoeffs_BplusKi_map (3 : Fin 15)) (20 : Fin 21),
    congrFun (restrictedPluckerCoeffs_evalMatrixK (3 : Fin 15)) (20 : Fin 21),
    Qexpand_3_20, Qraw_eq_3_20, Qrel_3_20, ofPoly_add_Phi11]
  simp [Qplus_entry_3_20, Qplus_im_3_20, ofLadj_ofPoly]

public theorem Qplus_eq_restricted_row_3 (m : Fin 21) :
    restrictedPluckerCoeffs BplusKi (3 : Fin 15) m = Qplus (3 : Fin 15) m := by
  fin_cases m
  · simpa [Qplus_apply_3_0] using Qplus_eq_restricted_3_0
  · simpa [Qplus_apply_3_1] using Qplus_eq_restricted_3_1
  · simpa [Qplus_apply_3_2] using Qplus_eq_restricted_3_2
  · simpa [Qplus_apply_3_3] using Qplus_eq_restricted_3_3
  · simpa [Qplus_apply_3_4] using Qplus_eq_restricted_3_4
  · simpa [Qplus_apply_3_5] using Qplus_eq_restricted_3_5
  · simpa [Qplus_apply_3_6] using Qplus_eq_restricted_3_6
  · simpa [Qplus_apply_3_7] using Qplus_eq_restricted_3_7
  · simpa [Qplus_apply_3_8] using Qplus_eq_restricted_3_8
  · simpa [Qplus_apply_3_9] using Qplus_eq_restricted_3_9
  · simpa [Qplus_apply_3_10] using Qplus_eq_restricted_3_10
  · simpa [Qplus_apply_3_11] using Qplus_eq_restricted_3_11
  · simpa [Qplus_apply_3_12] using Qplus_eq_restricted_3_12
  · simpa [Qplus_apply_3_13] using Qplus_eq_restricted_3_13
  · simpa [Qplus_apply_3_14] using Qplus_eq_restricted_3_14
  · simpa [Qplus_apply_3_15] using Qplus_eq_restricted_3_15
  · simpa [Qplus_apply_3_16] using Qplus_eq_restricted_3_16
  · simpa [Qplus_apply_3_17] using Qplus_eq_restricted_3_17
  · simpa [Qplus_apply_3_18] using Qplus_eq_restricted_3_18
  · simpa [Qplus_apply_3_19] using Qplus_eq_restricted_3_19
  · simpa [Qplus_apply_3_20] using Qplus_eq_restricted_3_20

end V14Formalization.D12SigmaPlusSegreCore
