/-
Apply lemmas for Bplus_poly.
-/
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_0
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_1
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_2
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_3
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_4
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_5
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_6
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_7
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_8
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_9
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_10
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_11
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_12
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_13
import V14Formalization.D12SigmaPlusSegreApply_BplusPoly_14
