/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
module

public import V14Formalization.D12SigmaPlusSegreEval
public import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def UM_qre_1_4 : Polynomial ℚ := C ((1 / 11 : ℚ)) + C ((-48 / 11 : ℚ)) * X + C ((-5 / 2 : ℚ)) * X ^ 2 + C ((-69 / 11 : ℚ)) * X ^ 3 + C ((-19 / 11 : ℚ)) * X ^ 4 + C (-2) * X ^ 5 + C ((1 / 11 : ℚ)) * X ^ 6 + C ((8 / 11 : ℚ)) * X ^ 7 + C ((5 / 11 : ℚ)) * X ^ 8
def UM_qim_1_4 : Polynomial ℚ := (0 : Polynomial ℚ)

def UM_pre_1_4_0 : Polynomial ℚ := C ((-7 / 22 : ℚ)) * X ^ 2 + C ((9 / 22 : ℚ)) * X ^ 4 + C ((1 / 2 : ℚ)) * X ^ 5 + C ((1 / 2 : ℚ)) * X ^ 6 + C ((6 / 11 : ℚ)) * X ^ 7 + C ((3 / 22 : ℚ)) * X ^ 8 + C ((-6 / 11 : ℚ)) * X ^ 9 + C ((-8 / 11 : ℚ)) * X ^ 10 + C (-1) * X ^ 11 + C ((-8 / 11 : ℚ)) * X ^ 12 + C ((-5 / 22 : ℚ)) * X ^ 13 + C ((3 / 22 : ℚ)) * X ^ 14 + C ((5 / 22 : ℚ)) * X ^ 15 + C ((1 / 2 : ℚ)) * X ^ 16 + C ((1 / 2 : ℚ)) * X ^ 17 + C ((1 / 11 : ℚ)) * X ^ 18
def UM_pim_1_4_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_pre_eq_1_4_0 :
    spanU_re_1_0 * minorQ_re_0_4 - spanU_im_1_0 * minorQ_im_0_4 =
      UM_pre_1_4_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_0, spanU_im_1_0, minorQ_re_0_4, minorQ_im_0_4,
    UM_pre_1_4_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_4_0 :
    spanU_re_1_0 * minorQ_im_0_4 + spanU_im_1_0 * minorQ_re_0_4 =
      UM_pim_1_4_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_0, spanU_im_1_0, minorQ_re_0_4, minorQ_im_0_4,
    UM_pim_1_4_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_4_0 :
    spanU_entry_1_0 * minorQ_entry_0_4 =
      ofLadj UM_pre_1_4_0 UM_pim_1_4_0 := by
  rw [spanU_entry_1_0, minorQ_entry_0_4, ofLadj_mul,
    UM_pre_eq_1_4_0, UM_pim_eq_1_4_0]

def UM_pre_1_4_1 : Polynomial ℚ := C ((5 / 44 : ℚ)) + C ((7 / 44 : ℚ)) * X ^ 2 + C ((-7 / 44 : ℚ)) * X ^ 3 + C ((5 / 44 : ℚ)) * X ^ 4 + C ((-15 / 44 : ℚ)) * X ^ 5 + C ((-7 / 22 : ℚ)) * X ^ 6 + C ((-29 / 44 : ℚ)) * X ^ 7 + C ((-61 / 44 : ℚ)) * X ^ 8 + C ((-57 / 44 : ℚ)) * X ^ 9 + C ((-23 / 11 : ℚ)) * X ^ 10 + C ((-47 / 22 : ℚ)) * X ^ 11 + C ((-23 / 11 : ℚ)) * X ^ 12 + C ((-16 / 11 : ℚ)) * X ^ 13 + C ((-27 / 22 : ℚ)) * X ^ 14 + C ((-8 / 11 : ℚ)) * X ^ 15 + C ((-3 / 22 : ℚ)) * X ^ 16 + C ((-7 / 44 : ℚ)) * X ^ 17 + C ((1 / 22 : ℚ)) * X ^ 18
def UM_pim_1_4_1 : Polynomial ℚ := C ((5 / 22 : ℚ)) + C ((5 / 11 : ℚ)) * X + C ((9 / 44 : ℚ)) * X ^ 2 + C ((9 / 44 : ℚ)) * X ^ 3 + C ((-35 / 44 : ℚ)) * X ^ 4 + C ((-5 / 4 : ℚ)) * X ^ 5 + C ((-105 / 44 : ℚ)) * X ^ 6 + C ((-133 / 44 : ℚ)) * X ^ 7 + C ((-173 / 44 : ℚ)) * X ^ 8 + C ((-145 / 44 : ℚ)) * X ^ 9 + C ((-131 / 44 : ℚ)) * X ^ 10 + C ((-30 / 11 : ℚ)) * X ^ 11 + C ((-109 / 44 : ℚ)) * X ^ 12 + C ((-21 / 11 : ℚ)) * X ^ 13 + C ((-14 / 11 : ℚ)) * X ^ 14 + C ((-29 / 22 : ℚ)) * X ^ 15 + C ((-41 / 44 : ℚ)) * X ^ 16 + C ((-19 / 44 : ℚ)) * X ^ 17 + C ((3 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_4_1 :
    spanU_re_1_1 * minorQ_re_1_4 - spanU_im_1_1 * minorQ_im_1_4 =
      UM_pre_1_4_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_1, spanU_im_1_1, minorQ_re_1_4, minorQ_im_1_4,
    UM_pre_1_4_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_4_1 :
    spanU_re_1_1 * minorQ_im_1_4 + spanU_im_1_1 * minorQ_re_1_4 =
      UM_pim_1_4_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_1, spanU_im_1_1, minorQ_re_1_4, minorQ_im_1_4,
    UM_pim_1_4_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_4_1 :
    spanU_entry_1_1 * minorQ_entry_1_4 =
      ofLadj UM_pre_1_4_1 UM_pim_1_4_1 := by
  rw [spanU_entry_1_1, minorQ_entry_1_4, ofLadj_mul,
    UM_pre_eq_1_4_1, UM_pim_eq_1_4_1]

def UM_pre_1_4_2 : Polynomial ℚ := C ((15 / 44 : ℚ)) + C ((-5 / 22 : ℚ)) * X + C ((-9 / 44 : ℚ)) * X ^ 2 + C ((-53 / 44 : ℚ)) * X ^ 3 + C ((-39 / 22 : ℚ)) * X ^ 4 + C ((-109 / 44 : ℚ)) * X ^ 5 + C ((-32 / 11 : ℚ)) * X ^ 6 + C ((-47 / 22 : ℚ)) * X ^ 7 + C ((-67 / 44 : ℚ)) * X ^ 8 + C ((-27 / 44 : ℚ)) * X ^ 9 + C ((-3 / 44 : ℚ)) * X ^ 10 + C ((3 / 11 : ℚ)) * X ^ 11 + C ((7 / 44 : ℚ)) * X ^ 12 + C ((-9 / 22 : ℚ)) * X ^ 13 + C ((-7 / 22 : ℚ)) * X ^ 14 + C ((-3 / 11 : ℚ)) * X ^ 15 + C ((-5 / 11 : ℚ)) * X ^ 16 + C ((-1 / 44 : ℚ)) * X ^ 17 + C ((1 / 11 : ℚ)) * X ^ 18
def UM_pim_1_4_2 : Polynomial ℚ := C ((-4 / 11 : ℚ)) + C ((-8 / 11 : ℚ)) * X + C ((-45 / 44 : ℚ)) * X ^ 2 + C ((-73 / 44 : ℚ)) * X ^ 3 + C ((-49 / 44 : ℚ)) * X ^ 4 + C ((-23 / 44 : ℚ)) * X ^ 5 + C ((-1 / 22 : ℚ)) * X ^ 6 + C ((25 / 22 : ℚ)) * X ^ 7 + C ((69 / 44 : ℚ)) * X ^ 8 + C ((69 / 44 : ℚ)) * X ^ 9 + C ((25 / 44 : ℚ)) * X ^ 10 + C ((4 / 11 : ℚ)) * X ^ 11 + C ((7 / 44 : ℚ)) * X ^ 12 + C ((-6 / 11 : ℚ)) * X ^ 13 + C ((1 / 11 : ℚ)) * X ^ 14 + C ((-1 / 22 : ℚ)) * X ^ 15 + C ((2 / 11 : ℚ)) * X ^ 16 + C ((17 / 44 : ℚ)) * X ^ 17 + C ((1 / 44 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_4_2 :
    spanU_re_1_2 * minorQ_re_2_4 - spanU_im_1_2 * minorQ_im_2_4 =
      UM_pre_1_4_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_2, spanU_im_1_2, minorQ_re_2_4, minorQ_im_2_4,
    UM_pre_1_4_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_4_2 :
    spanU_re_1_2 * minorQ_im_2_4 + spanU_im_1_2 * minorQ_re_2_4 =
      UM_pim_1_4_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_2, spanU_im_1_2, minorQ_re_2_4, minorQ_im_2_4,
    UM_pim_1_4_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_4_2 :
    spanU_entry_1_2 * minorQ_entry_2_4 =
      ofLadj UM_pre_1_4_2 UM_pim_1_4_2 := by
  rw [spanU_entry_1_2, minorQ_entry_2_4, ofLadj_mul,
    UM_pre_eq_1_4_2, UM_pim_eq_1_4_2]

def UM_pre_1_4_3 : Polynomial ℚ := C ((5 / 44 : ℚ)) + C ((7 / 44 : ℚ)) * X ^ 2 + C ((-7 / 44 : ℚ)) * X ^ 3 + C ((5 / 44 : ℚ)) * X ^ 4 + C ((-15 / 44 : ℚ)) * X ^ 5 + C ((-7 / 22 : ℚ)) * X ^ 6 + C ((-29 / 44 : ℚ)) * X ^ 7 + C ((-61 / 44 : ℚ)) * X ^ 8 + C ((-57 / 44 : ℚ)) * X ^ 9 + C ((-23 / 11 : ℚ)) * X ^ 10 + C ((-47 / 22 : ℚ)) * X ^ 11 + C ((-23 / 11 : ℚ)) * X ^ 12 + C ((-16 / 11 : ℚ)) * X ^ 13 + C ((-27 / 22 : ℚ)) * X ^ 14 + C ((-8 / 11 : ℚ)) * X ^ 15 + C ((-3 / 22 : ℚ)) * X ^ 16 + C ((-7 / 44 : ℚ)) * X ^ 17 + C ((1 / 22 : ℚ)) * X ^ 18
def UM_pim_1_4_3 : Polynomial ℚ := C ((-5 / 22 : ℚ)) + C ((-5 / 11 : ℚ)) * X + C ((-9 / 44 : ℚ)) * X ^ 2 + C ((-9 / 44 : ℚ)) * X ^ 3 + C ((35 / 44 : ℚ)) * X ^ 4 + C ((5 / 4 : ℚ)) * X ^ 5 + C ((105 / 44 : ℚ)) * X ^ 6 + C ((133 / 44 : ℚ)) * X ^ 7 + C ((173 / 44 : ℚ)) * X ^ 8 + C ((145 / 44 : ℚ)) * X ^ 9 + C ((131 / 44 : ℚ)) * X ^ 10 + C ((30 / 11 : ℚ)) * X ^ 11 + C ((109 / 44 : ℚ)) * X ^ 12 + C ((21 / 11 : ℚ)) * X ^ 13 + C ((14 / 11 : ℚ)) * X ^ 14 + C ((29 / 22 : ℚ)) * X ^ 15 + C ((41 / 44 : ℚ)) * X ^ 16 + C ((19 / 44 : ℚ)) * X ^ 17 + C ((-3 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_4_3 :
    spanU_re_1_3 * minorQ_re_3_4 - spanU_im_1_3 * minorQ_im_3_4 =
      UM_pre_1_4_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_3, spanU_im_1_3, minorQ_re_3_4, minorQ_im_3_4,
    UM_pre_1_4_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_4_3 :
    spanU_re_1_3 * minorQ_im_3_4 + spanU_im_1_3 * minorQ_re_3_4 =
      UM_pim_1_4_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_3, spanU_im_1_3, minorQ_re_3_4, minorQ_im_3_4,
    UM_pim_1_4_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_4_3 :
    spanU_entry_1_3 * minorQ_entry_3_4 =
      ofLadj UM_pre_1_4_3 UM_pim_1_4_3 := by
  rw [spanU_entry_1_3, minorQ_entry_3_4, ofLadj_mul,
    UM_pre_eq_1_4_3, UM_pim_eq_1_4_3]

def UM_pre_1_4_4 : Polynomial ℚ := C ((7 / 22 : ℚ)) * X ^ 2 + C ((-7 / 22 : ℚ)) * X ^ 3 + C ((3 / 22 : ℚ)) * X ^ 4 + C ((-3 / 11 : ℚ)) * X ^ 5 + C ((-9 / 22 : ℚ)) * X ^ 6 + C ((2 / 11 : ℚ)) * X ^ 7 + C ((-7 / 22 : ℚ)) * X ^ 8 + C ((3 / 22 : ℚ)) * X ^ 9 + C ((3 / 11 : ℚ)) * X ^ 10 + C ((6 / 11 : ℚ)) * X ^ 11 + C ((3 / 11 : ℚ)) * X ^ 12 + C ((-2 / 11 : ℚ)) * X ^ 13 + C ((2 / 11 : ℚ)) * X ^ 15 + C ((-9 / 22 : ℚ)) * X ^ 16 + C ((-3 / 11 : ℚ)) * X ^ 17 + C ((3 / 22 : ℚ)) * X ^ 18
def UM_pim_1_4_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_pre_eq_1_4_4 :
    spanU_re_1_4 * minorQ_re_4_4 - spanU_im_1_4 * minorQ_im_4_4 =
      UM_pre_1_4_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_4, spanU_im_1_4, minorQ_re_4_4, minorQ_im_4_4,
    UM_pre_1_4_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_4_4 :
    spanU_re_1_4 * minorQ_im_4_4 + spanU_im_1_4 * minorQ_re_4_4 =
      UM_pim_1_4_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_4, spanU_im_1_4, minorQ_re_4_4, minorQ_im_4_4,
    UM_pim_1_4_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_4_4 :
    spanU_entry_1_4 * minorQ_entry_4_4 =
      ofLadj UM_pre_1_4_4 UM_pim_1_4_4 := by
  rw [spanU_entry_1_4, minorQ_entry_4_4, ofLadj_mul,
    UM_pre_eq_1_4_4, UM_pim_eq_1_4_4]

def UM_pre_1_4_5 : Polynomial ℚ := C ((-9 / 22 : ℚ)) + C ((-21 / 11 : ℚ)) * X + C ((-147 / 44 : ℚ)) * X ^ 2 + C ((-105 / 22 : ℚ)) * X ^ 3 + C ((-137 / 22 : ℚ)) * X ^ 4 + C ((-65 / 11 : ℚ)) * X ^ 5 + C ((-247 / 44 : ℚ)) * X ^ 6 + C ((-281 / 44 : ℚ)) * X ^ 7 + C ((-51 / 11 : ℚ)) * X ^ 8 + C ((-119 / 22 : ℚ)) * X ^ 9 + C ((-211 / 44 : ℚ)) * X ^ 10 + C ((-197 / 44 : ℚ)) * X ^ 11 + C ((-127 / 44 : ℚ)) * X ^ 12 + C ((-91 / 44 : ℚ)) * X ^ 13 + C ((3 / 22 : ℚ)) * X ^ 14 + C ((-2 / 11 : ℚ)) * X ^ 15 + C ((8 / 11 : ℚ)) * X ^ 16 + C ((19 / 44 : ℚ)) * X ^ 17 + C ((-1 / 44 : ℚ)) * X ^ 18
def UM_pim_1_4_5 : Polynomial ℚ := C ((6 / 11 : ℚ)) + C ((12 / 11 : ℚ)) * X + C ((43 / 44 : ℚ)) * X ^ 2 + C ((39 / 44 : ℚ)) * X ^ 3 + C ((-1 / 4 : ℚ)) * X ^ 4 + C ((-27 / 22 : ℚ)) * X ^ 5 + C ((-103 / 44 : ℚ)) * X ^ 6 + C ((-59 / 22 : ℚ)) * X ^ 7 + C ((-7 / 2 : ℚ)) * X ^ 8 + C ((-36 / 11 : ℚ)) * X ^ 9 + C ((-57 / 22 : ℚ)) * X ^ 10 + C ((-123 / 44 : ℚ)) * X ^ 11 + C (-3) * X ^ 12 + C ((-97 / 44 : ℚ)) * X ^ 13 + C ((-83 / 44 : ℚ)) * X ^ 14 + C ((-17 / 11 : ℚ)) * X ^ 15 + C ((-27 / 44 : ℚ)) * X ^ 16 + C ((-7 / 22 : ℚ)) * X ^ 17 + C ((-1 / 44 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_4_5 :
    spanU_re_1_5 * minorQ_re_5_4 - spanU_im_1_5 * minorQ_im_5_4 =
      UM_pre_1_4_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_5, spanU_im_1_5, minorQ_re_5_4, minorQ_im_5_4,
    UM_pre_1_4_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_4_5 :
    spanU_re_1_5 * minorQ_im_5_4 + spanU_im_1_5 * minorQ_re_5_4 =
      UM_pim_1_4_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_5, spanU_im_1_5, minorQ_re_5_4, minorQ_im_5_4,
    UM_pim_1_4_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_4_5 :
    spanU_entry_1_5 * minorQ_entry_5_4 =
      ofLadj UM_pre_1_4_5 UM_pim_1_4_5 := by
  rw [spanU_entry_1_5, minorQ_entry_5_4, ofLadj_mul,
    UM_pre_eq_1_4_5, UM_pim_eq_1_4_5]

def UM_pre_1_4_6 : Polynomial ℚ := C ((15 / 44 : ℚ)) + C ((-5 / 22 : ℚ)) * X + C ((-9 / 44 : ℚ)) * X ^ 2 + C ((-53 / 44 : ℚ)) * X ^ 3 + C ((-39 / 22 : ℚ)) * X ^ 4 + C ((-109 / 44 : ℚ)) * X ^ 5 + C ((-32 / 11 : ℚ)) * X ^ 6 + C ((-47 / 22 : ℚ)) * X ^ 7 + C ((-67 / 44 : ℚ)) * X ^ 8 + C ((-27 / 44 : ℚ)) * X ^ 9 + C ((-3 / 44 : ℚ)) * X ^ 10 + C ((3 / 11 : ℚ)) * X ^ 11 + C ((7 / 44 : ℚ)) * X ^ 12 + C ((-9 / 22 : ℚ)) * X ^ 13 + C ((-7 / 22 : ℚ)) * X ^ 14 + C ((-3 / 11 : ℚ)) * X ^ 15 + C ((-5 / 11 : ℚ)) * X ^ 16 + C ((-1 / 44 : ℚ)) * X ^ 17 + C ((1 / 11 : ℚ)) * X ^ 18
def UM_pim_1_4_6 : Polynomial ℚ := C ((4 / 11 : ℚ)) + C ((8 / 11 : ℚ)) * X + C ((45 / 44 : ℚ)) * X ^ 2 + C ((73 / 44 : ℚ)) * X ^ 3 + C ((49 / 44 : ℚ)) * X ^ 4 + C ((23 / 44 : ℚ)) * X ^ 5 + C ((1 / 22 : ℚ)) * X ^ 6 + C ((-25 / 22 : ℚ)) * X ^ 7 + C ((-69 / 44 : ℚ)) * X ^ 8 + C ((-69 / 44 : ℚ)) * X ^ 9 + C ((-25 / 44 : ℚ)) * X ^ 10 + C ((-4 / 11 : ℚ)) * X ^ 11 + C ((-7 / 44 : ℚ)) * X ^ 12 + C ((6 / 11 : ℚ)) * X ^ 13 + C ((-1 / 11 : ℚ)) * X ^ 14 + C ((1 / 22 : ℚ)) * X ^ 15 + C ((-2 / 11 : ℚ)) * X ^ 16 + C ((-17 / 44 : ℚ)) * X ^ 17 + C ((-1 / 44 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_4_6 :
    spanU_re_1_6 * minorQ_re_6_4 - spanU_im_1_6 * minorQ_im_6_4 =
      UM_pre_1_4_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_6, spanU_im_1_6, minorQ_re_6_4, minorQ_im_6_4,
    UM_pre_1_4_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_4_6 :
    spanU_re_1_6 * minorQ_im_6_4 + spanU_im_1_6 * minorQ_re_6_4 =
      UM_pim_1_4_6 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_6, spanU_im_1_6, minorQ_re_6_4, minorQ_im_6_4,
    UM_pim_1_4_6]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_4_6 :
    spanU_entry_1_6 * minorQ_entry_6_4 =
      ofLadj UM_pre_1_4_6 UM_pim_1_4_6 := by
  rw [spanU_entry_1_6, minorQ_entry_6_4, ofLadj_mul,
    UM_pre_eq_1_4_6, UM_pim_eq_1_4_6]

def UM_pre_1_4_7 : Polynomial ℚ := C ((-9 / 22 : ℚ)) + C ((-21 / 11 : ℚ)) * X + C ((-147 / 44 : ℚ)) * X ^ 2 + C ((-105 / 22 : ℚ)) * X ^ 3 + C ((-137 / 22 : ℚ)) * X ^ 4 + C ((-65 / 11 : ℚ)) * X ^ 5 + C ((-247 / 44 : ℚ)) * X ^ 6 + C ((-281 / 44 : ℚ)) * X ^ 7 + C ((-51 / 11 : ℚ)) * X ^ 8 + C ((-119 / 22 : ℚ)) * X ^ 9 + C ((-211 / 44 : ℚ)) * X ^ 10 + C ((-197 / 44 : ℚ)) * X ^ 11 + C ((-127 / 44 : ℚ)) * X ^ 12 + C ((-91 / 44 : ℚ)) * X ^ 13 + C ((3 / 22 : ℚ)) * X ^ 14 + C ((-2 / 11 : ℚ)) * X ^ 15 + C ((8 / 11 : ℚ)) * X ^ 16 + C ((19 / 44 : ℚ)) * X ^ 17 + C ((-1 / 44 : ℚ)) * X ^ 18
def UM_pim_1_4_7 : Polynomial ℚ := C ((-6 / 11 : ℚ)) + C ((-12 / 11 : ℚ)) * X + C ((-43 / 44 : ℚ)) * X ^ 2 + C ((-39 / 44 : ℚ)) * X ^ 3 + C ((1 / 4 : ℚ)) * X ^ 4 + C ((27 / 22 : ℚ)) * X ^ 5 + C ((103 / 44 : ℚ)) * X ^ 6 + C ((59 / 22 : ℚ)) * X ^ 7 + C ((7 / 2 : ℚ)) * X ^ 8 + C ((36 / 11 : ℚ)) * X ^ 9 + C ((57 / 22 : ℚ)) * X ^ 10 + C ((123 / 44 : ℚ)) * X ^ 11 + C (3) * X ^ 12 + C ((97 / 44 : ℚ)) * X ^ 13 + C ((83 / 44 : ℚ)) * X ^ 14 + C ((17 / 11 : ℚ)) * X ^ 15 + C ((27 / 44 : ℚ)) * X ^ 16 + C ((7 / 22 : ℚ)) * X ^ 17 + C ((1 / 44 : ℚ)) * X ^ 18
theorem UM_pre_eq_1_4_7 :
    spanU_re_1_7 * minorQ_re_7_4 - spanU_im_1_7 * minorQ_im_7_4 =
      UM_pre_1_4_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_7, spanU_im_1_7, minorQ_re_7_4, minorQ_im_7_4,
    UM_pre_1_4_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_4_7 :
    spanU_re_1_7 * minorQ_im_7_4 + spanU_im_1_7 * minorQ_re_7_4 =
      UM_pim_1_4_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_7, spanU_im_1_7, minorQ_re_7_4, minorQ_im_7_4,
    UM_pim_1_4_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_4_7 :
    spanU_entry_1_7 * minorQ_entry_7_4 =
      ofLadj UM_pre_1_4_7 UM_pim_1_4_7 := by
  rw [spanU_entry_1_7, minorQ_entry_7_4, ofLadj_mul,
    UM_pre_eq_1_4_7, UM_pim_eq_1_4_7]

def UM_pre_1_4_8 : Polynomial ℚ := C ((-5 / 11 : ℚ)) * X ^ 3 + C ((5 / 11 : ℚ)) * X ^ 4 + C ((5 / 11 : ℚ)) * X ^ 5 + C ((10 / 11 : ℚ)) * X ^ 6 + C ((37 / 22 : ℚ)) * X ^ 7 + C ((-5 / 22 : ℚ)) * X ^ 8 + C ((-5 / 11 : ℚ)) * X ^ 9 + C ((-25 / 22 : ℚ)) * X ^ 10 + C ((-27 / 11 : ℚ)) * X ^ 11 + C ((-25 / 22 : ℚ)) * X ^ 12 + C ((-5 / 11 : ℚ)) * X ^ 13 + C ((5 / 22 : ℚ)) * X ^ 14 + C ((27 / 22 : ℚ)) * X ^ 15 + C ((10 / 11 : ℚ)) * X ^ 16 + C ((5 / 11 : ℚ)) * X ^ 17
def UM_pim_1_4_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_pre_eq_1_4_8 :
    spanU_re_1_8 * minorQ_re_8_4 - spanU_im_1_8 * minorQ_im_8_4 =
      UM_pre_1_4_8 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_8, spanU_im_1_8, minorQ_re_8_4, minorQ_im_8_4,
    UM_pre_1_4_8]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_1_4_8 :
    spanU_re_1_8 * minorQ_im_8_4 + spanU_im_1_8 * minorQ_re_8_4 =
      UM_pim_1_4_8 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_1_8, spanU_im_1_8, minorQ_re_8_4, minorQ_im_8_4,
    UM_pim_1_4_8]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_1_4_8 :
    spanU_entry_1_8 * minorQ_entry_8_4 =
      ofLadj UM_pre_1_4_8 UM_pim_1_4_8 := by
  rw [spanU_entry_1_8, minorQ_entry_8_4, ofLadj_mul,
    UM_pre_eq_1_4_8, UM_pim_eq_1_4_8]

theorem UM_sum_poly_re_1_4 :
    UM_pre_1_4_0 + UM_pre_1_4_1 + UM_pre_1_4_2 + UM_pre_1_4_3 + UM_pre_1_4_4 + UM_pre_1_4_5 + UM_pre_1_4_6 + UM_pre_1_4_7 + UM_pre_1_4_8 = Qplus_re_1_4 + Phi11 * UM_qre_1_4 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pre_1_4_0, UM_pre_1_4_1, UM_pre_1_4_2, UM_pre_1_4_3, UM_pre_1_4_4, UM_pre_1_4_5, UM_pre_1_4_6, UM_pre_1_4_7, UM_pre_1_4_8, Qplus_re_1_4, UM_qre_1_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_poly_im_1_4 :
    UM_pim_1_4_0 + UM_pim_1_4_1 + UM_pim_1_4_2 + UM_pim_1_4_3 + UM_pim_1_4_4 + UM_pim_1_4_5 + UM_pim_1_4_6 + UM_pim_1_4_7 + UM_pim_1_4_8 = Qplus_im_1_4 + Phi11 * UM_qim_1_4 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pim_1_4_0, UM_pim_1_4_1, UM_pim_1_4_2, UM_pim_1_4_3, UM_pim_1_4_4, UM_pim_1_4_5, UM_pim_1_4_6, UM_pim_1_4_7, UM_pim_1_4_8, Qplus_im_1_4, UM_qim_1_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_entries_1_4 :
    spanU_entry_1_0 * minorQ_entry_0_4 + spanU_entry_1_1 * minorQ_entry_1_4 + spanU_entry_1_2 * minorQ_entry_2_4 + spanU_entry_1_3 * minorQ_entry_3_4 + spanU_entry_1_4 * minorQ_entry_4_4 + spanU_entry_1_5 * minorQ_entry_5_4 + spanU_entry_1_6 * minorQ_entry_6_4 + spanU_entry_1_7 * minorQ_entry_7_4 + spanU_entry_1_8 * minorQ_entry_8_4 =
      ofLadj (UM_pre_1_4_0 + UM_pre_1_4_1 + UM_pre_1_4_2 + UM_pre_1_4_3 + UM_pre_1_4_4 + UM_pre_1_4_5 + UM_pre_1_4_6 + UM_pre_1_4_7 + UM_pre_1_4_8) (UM_pim_1_4_0 + UM_pim_1_4_1 + UM_pim_1_4_2 + UM_pim_1_4_3 + UM_pim_1_4_4 + UM_pim_1_4_5 + UM_pim_1_4_6 + UM_pim_1_4_7 + UM_pim_1_4_8) := by
  simp only [UM_term_1_4_0, UM_term_1_4_1, UM_term_1_4_2, UM_term_1_4_3, UM_term_1_4_4, UM_term_1_4_5, UM_term_1_4_6, UM_term_1_4_7, UM_term_1_4_8]
  simpa [add_assoc] using ofLadj_add9 UM_pre_1_4_0 UM_pim_1_4_0 UM_pre_1_4_1 UM_pim_1_4_1 UM_pre_1_4_2 UM_pim_1_4_2 UM_pre_1_4_3 UM_pim_1_4_3 UM_pre_1_4_4 UM_pim_1_4_4 UM_pre_1_4_5 UM_pim_1_4_5 UM_pre_1_4_6 UM_pim_1_4_6 UM_pre_1_4_7 UM_pim_1_4_7 UM_pre_1_4_8 UM_pim_1_4_8

theorem UM_eval_1_4 :
    ofLadj (UM_pre_1_4_0 + UM_pre_1_4_1 + UM_pre_1_4_2 + UM_pre_1_4_3 + UM_pre_1_4_4 + UM_pre_1_4_5 + UM_pre_1_4_6 + UM_pre_1_4_7 + UM_pre_1_4_8) (UM_pim_1_4_0 + UM_pim_1_4_1 + UM_pim_1_4_2 + UM_pim_1_4_3 + UM_pim_1_4_4 + UM_pim_1_4_5 + UM_pim_1_4_6 + UM_pim_1_4_7 + UM_pim_1_4_8) = Qplus_entry_1_4 := by
  rw [UM_sum_poly_re_1_4, UM_sum_poly_im_1_4,
    ofLadj_add_Phi11, Qplus_entry_1_4]

public theorem UM_entry_1_4 : (spanU * minorQ) 1 4 = Qplus 1 4 := by
  rw [Matrix.mul_apply]
  rw [sum_fin9]
  change spanU_entry_1_0 * minorQ_entry_0_4 + spanU_entry_1_1 * minorQ_entry_1_4 + spanU_entry_1_2 * minorQ_entry_2_4 + spanU_entry_1_3 * minorQ_entry_3_4 + spanU_entry_1_4 * minorQ_entry_4_4 + spanU_entry_1_5 * minorQ_entry_5_4 + spanU_entry_1_6 * minorQ_entry_6_4 + spanU_entry_1_7 * minorQ_entry_7_4 + spanU_entry_1_8 * minorQ_entry_8_4 = Qplus_entry_1_4
  exact (UM_sum_entries_1_4).trans UM_eval_1_4

end V14Formalization.D12SigmaPlusSegreCore
