/-
Auto-generated by scripts/export_sigma_plus_identities.py.
Stock-limit, kernel-checkable plus Segre entry identities.
-/
import V14Formalization.D12SigmaPlusSegreEval
import V14Formalization.D12SigmaPlusSegreGeom
import V14Formalization.D12SigmaPlusSegreApplyH
import V14Formalization.D12SigmaPlusSegreApply_spanV
import V14Formalization.D12SigmaPlusSegreApply_Qplus

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

open D12SigmaPlusQuadric6

def SP_0_0_t1_re : Polynomial ℚ := C (20) * X ^ 3 + C (40) * X ^ 4 + C (48) * X ^ 5 + C (56) * X ^ 6 + C (44) * X ^ 7 + C (16) * X ^ 8 + C (-36) * X ^ 9 + C (-52) * X ^ 10 + C (-72) * X ^ 11 + C (-52) * X ^ 12 + C (-36) * X ^ 13 + C (-4) * X ^ 14 + C (4) * X ^ 15 + C (16) * X ^ 16 + C (8) * X ^ 17
def SP_0_0_t1_im : Polynomial ℚ := (0 : Polynomial ℚ)
theorem SP_0_0_t1_re_eq :
    H_re_0_0 * H_re_4_0 - H_im_0_0 * H_im_4_0 = SP_0_0_t1_re := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_0_0, H_im_0_0, H_re_4_0, H_im_4_0, SP_0_0_t1_re]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_t1_im_eq :
    H_re_0_0 * H_im_4_0 + H_im_0_0 * H_re_4_0 = SP_0_0_t1_im := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_0_0, H_im_0_0, H_re_4_0, H_im_4_0, SP_0_0_t1_im]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_t1_term :
    H_entry_0_0 * H_entry_4_0 =
      ofLadj SP_0_0_t1_re SP_0_0_t1_im := by
  rw [H_entry_0_0, H_entry_4_0, ofLadj_mul,
    SP_0_0_t1_re_eq, SP_0_0_t1_im_eq]

def SP_0_0_t2_re : Polynomial ℚ := C (-8) + C (-16) * X + C (-40) * X ^ 2 + C (-56) * X ^ 3 + C (-84) * X ^ 4 + C (-104) * X ^ 5 + C (-140) * X ^ 6 + C (-172) * X ^ 7 + C (-208) * X ^ 8 + C (-252) * X ^ 9 + C (-274) * X ^ 10 + C (-280) * X ^ 11 + C (-258) * X ^ 12 + C (-212) * X ^ 13 + C (-152) * X ^ 14 + C (-92) * X ^ 15 + C (-52) * X ^ 16 + C (-16) * X ^ 17 + C (-4) * X ^ 18
def SP_0_0_t2_im : Polynomial ℚ := (0 : Polynomial ℚ)
theorem SP_0_0_t2_re_eq :
    H_re_1_0 * H_re_3_0 - H_im_1_0 * H_im_3_0 = SP_0_0_t2_re := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_1_0, H_im_1_0, H_re_3_0, H_im_3_0, SP_0_0_t2_re]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_t2_im_eq :
    H_re_1_0 * H_im_3_0 + H_im_1_0 * H_re_3_0 = SP_0_0_t2_im := by
  refine Polynomial.funext fun r => ?_
  simp only [H_re_1_0, H_im_1_0, H_re_3_0, H_im_3_0, SP_0_0_t2_im]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_t2_term :
    H_entry_1_0 * H_entry_3_0 =
      ofLadj SP_0_0_t2_re SP_0_0_t2_im := by
  rw [H_entry_1_0, H_entry_3_0, ofLadj_mul,
    SP_0_0_t2_re_eq, SP_0_0_t2_im_eq]

theorem SP_0_0_minor_expand :
    minorCoeffsH (0 : Fin 9) (0 : Fin 21) =
      H_entry_0_0 * H_entry_4_0 -
        H_entry_1_0 * H_entry_3_0 := by
  simp only [minorCoeffsH, bilinearCoeffs, Hrow,
    minorOrder_0, monomPair_0]
  simp only [H_apply_0_0, H_apply_4_0, H_apply_1_0, H_apply_3_0]

theorem SP_0_0_minor_ofLadj :
    minorCoeffsH (0 : Fin 9) (0 : Fin 21) =
      ofLadj (SP_0_0_t1_re - SP_0_0_t2_re)
        (SP_0_0_t1_im - SP_0_0_t2_im) := by
  rw [SP_0_0_minor_expand, SP_0_0_t1_term, SP_0_0_t2_term, ofLadj_sub]

def SP_0_0_pre_0 : Polynomial ℚ := C (-8) + C (32) * X ^ 2 + C (54) * X ^ 3 + C (100) * X ^ 4 + C (150) * X ^ 5 + C (180) * X ^ 6 + C (200) * X ^ 7 + C (172) * X ^ 8 + C (150) * X ^ 9 + C (132) * X ^ 10 + C (124) * X ^ 11 + C (132) * X ^ 12 + C (118) * X ^ 13 + C (118) * X ^ 14 + C (100) * X ^ 15 + C (62) * X ^ 16 + C (32) * X ^ 17
def SP_0_0_pim_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem SP_0_0_pre_eq_0 :
    spanV_re_0_0 * Qplus_re_0_0 - spanV_im_0_0 * Qplus_im_0_0 = SP_0_0_pre_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_0, spanV_im_0_0, Qplus_re_0_0, Qplus_im_0_0, SP_0_0_pre_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_pim_eq_0 :
    spanV_re_0_0 * Qplus_im_0_0 + spanV_im_0_0 * Qplus_re_0_0 = SP_0_0_pim_0 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_0, spanV_im_0_0, Qplus_re_0_0, Qplus_im_0_0, SP_0_0_pim_0]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_term_0 :
    spanV_entry_0_0 * Qplus_entry_0_0 =
      ofLadj SP_0_0_pre_0 SP_0_0_pim_0 := by
  rw [spanV_entry_0_0, Qplus_entry_0_0, ofLadj_mul,
    SP_0_0_pre_eq_0, SP_0_0_pim_eq_0]

def SP_0_0_pre_2 : Polynomial ℚ := C (10) + C (10) * X ^ 2 + C (-12) * X ^ 4 + C (-26) * X ^ 5 + C (-38) * X ^ 6 + C (-40) * X ^ 7 + C (-32) * X ^ 8 + C (-18) * X ^ 9 + C (-22) * X ^ 10 + C (-20) * X ^ 11 + C (-22) * X ^ 12 + C (-28) * X ^ 13 + C (-32) * X ^ 14 + C (-28) * X ^ 15 + C (-22) * X ^ 16 + C (-10) * X ^ 17
def SP_0_0_pim_2 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem SP_0_0_pre_eq_2 :
    spanV_re_0_2 * Qplus_re_2_0 - spanV_im_0_2 * Qplus_im_2_0 = SP_0_0_pre_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_2, spanV_im_0_2, Qplus_re_2_0, Qplus_im_2_0, SP_0_0_pre_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_pim_eq_2 :
    spanV_re_0_2 * Qplus_im_2_0 + spanV_im_0_2 * Qplus_re_2_0 = SP_0_0_pim_2 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_2, spanV_im_0_2, Qplus_re_2_0, Qplus_im_2_0, SP_0_0_pim_2]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_term_2 :
    spanV_entry_0_2 * Qplus_entry_2_0 =
      ofLadj SP_0_0_pre_2 SP_0_0_pim_2 := by
  rw [spanV_entry_0_2, Qplus_entry_2_0, ofLadj_mul,
    SP_0_0_pre_eq_2, SP_0_0_pim_eq_2]

def SP_0_0_pre_4 : Polynomial ℚ := C (-2) + C (-54) * X ^ 2 + C (-102) * X ^ 3 + C (-158) * X ^ 4 + C (-180) * X ^ 5 + C (-180) * X ^ 6 + C (-158) * X ^ 7 + C (-102) * X ^ 8 + C (-54) * X ^ 9
def SP_0_0_pim_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem SP_0_0_pre_eq_4 :
    spanV_re_0_4 * Qplus_re_4_0 - spanV_im_0_4 * Qplus_im_4_0 = SP_0_0_pre_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_4, spanV_im_0_4, Qplus_re_4_0, Qplus_im_4_0, SP_0_0_pre_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_pim_eq_4 :
    spanV_re_0_4 * Qplus_im_4_0 + spanV_im_0_4 * Qplus_re_4_0 = SP_0_0_pim_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_4, spanV_im_0_4, Qplus_re_4_0, Qplus_im_4_0, SP_0_0_pim_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_term_4 :
    spanV_entry_0_4 * Qplus_entry_4_0 =
      ofLadj SP_0_0_pre_4 SP_0_0_pim_4 := by
  rw [spanV_entry_0_4, Qplus_entry_4_0, ofLadj_mul,
    SP_0_0_pre_eq_4, SP_0_0_pim_eq_4]

def SP_0_0_pre_5 : Polynomial ℚ := C (-4) * X ^ 2 + C (-4) * X ^ 3 + C (-32) * X ^ 4 + C (-92) * X ^ 5 + C (-154) * X ^ 6 + C (-228) * X ^ 7 + C (-296) * X ^ 8 + C (-350) * X ^ 9 + C (-378) * X ^ 10 + C (-380) * X ^ 11 + C (-378) * X ^ 12 + C (-346) * X ^ 13 + C (-292) * X ^ 14 + C (-228) * X ^ 15 + C (-150) * X ^ 16 + C (-88) * X ^ 17 + C (-32) * X ^ 18
def SP_0_0_pim_5 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem SP_0_0_pre_eq_5 :
    spanV_re_0_5 * Qplus_re_5_0 - spanV_im_0_5 * Qplus_im_5_0 = SP_0_0_pre_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_5, spanV_im_0_5, Qplus_re_5_0, Qplus_im_5_0, SP_0_0_pre_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_pim_eq_5 :
    spanV_re_0_5 * Qplus_im_5_0 + spanV_im_0_5 * Qplus_re_5_0 = SP_0_0_pim_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_5, spanV_im_0_5, Qplus_re_5_0, Qplus_im_5_0, SP_0_0_pim_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_term_5 :
    spanV_entry_0_5 * Qplus_entry_5_0 =
      ofLadj SP_0_0_pre_5 SP_0_0_pim_5 := by
  rw [spanV_entry_0_5, Qplus_entry_5_0, ofLadj_mul,
    SP_0_0_pre_eq_5, SP_0_0_pim_eq_5]

def SP_0_0_pre_10 : Polynomial ℚ := C (-2) * X ^ 5 + C (-2) * X ^ 6 + C (-2) * X ^ 7 + C (2) * X ^ 8 + C (8) * X ^ 9 + C (10) * X ^ 10 + C (12) * X ^ 11 + C (10) * X ^ 12 + C (8) * X ^ 13 + C (2) * X ^ 14 + C (-2) * X ^ 15
def SP_0_0_pim_10 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem SP_0_0_pre_eq_10 :
    spanV_re_0_10 * Qplus_re_10_0 - spanV_im_0_10 * Qplus_im_10_0 = SP_0_0_pre_10 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_10, spanV_im_0_10, Qplus_re_10_0, Qplus_im_10_0, SP_0_0_pre_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_pim_eq_10 :
    spanV_re_0_10 * Qplus_im_10_0 + spanV_im_0_10 * Qplus_re_10_0 = SP_0_0_pim_10 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanV_re_0_10, spanV_im_0_10, Qplus_re_10_0, Qplus_im_10_0, SP_0_0_pim_10]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_term_10 :
    spanV_entry_0_10 * Qplus_entry_10_0 =
      ofLadj SP_0_0_pre_10 SP_0_0_pim_10 := by
  rw [spanV_entry_0_10, Qplus_entry_10_0, ofLadj_mul,
    SP_0_0_pre_eq_10, SP_0_0_pim_eq_10]

def SP_0_0_qre : Polynomial ℚ := C (-8) + C (-8) * X + C (-40) * X ^ 2 + C (-72) * X ^ 3 + C (-98) * X ^ 4 + C (-76) * X ^ 5 + C (-88) * X ^ 6 + C (-54) * X ^ 7 + C (-36) * X ^ 8
def SP_0_0_qim : Polynomial ℚ := (0 : Polynomial ℚ)

theorem SP_0_0_sum_poly_re :
    SP_0_0_pre_0 + SP_0_0_pre_2 + SP_0_0_pre_4 + SP_0_0_pre_5 + SP_0_0_pre_10 = SP_0_0_t1_re - SP_0_0_t2_re + Phi11 * SP_0_0_qre := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [SP_0_0_pre_0, SP_0_0_pre_2, SP_0_0_pre_4, SP_0_0_pre_5, SP_0_0_pre_10, SP_0_0_t1_re, SP_0_0_t2_re, SP_0_0_t1_im, SP_0_0_t2_im, SP_0_0_qre]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_sum_poly_im :
    SP_0_0_pim_0 + SP_0_0_pim_2 + SP_0_0_pim_4 + SP_0_0_pim_5 + SP_0_0_pim_10 = SP_0_0_t1_im - SP_0_0_t2_im + Phi11 * SP_0_0_qim := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [SP_0_0_pim_0, SP_0_0_pim_2, SP_0_0_pim_4, SP_0_0_pim_5, SP_0_0_pim_10, SP_0_0_t1_re, SP_0_0_t2_re, SP_0_0_t1_im, SP_0_0_t2_im, SP_0_0_qim]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem SP_0_0_sum_entries :
    spanV_entry_0_0 * Qplus_entry_0_0 + spanV_entry_0_2 * Qplus_entry_2_0 + spanV_entry_0_4 * Qplus_entry_4_0 + spanV_entry_0_5 * Qplus_entry_5_0 + spanV_entry_0_10 * Qplus_entry_10_0 =
      ofLadj (SP_0_0_pre_0 + SP_0_0_pre_2 + SP_0_0_pre_4 + SP_0_0_pre_5 + SP_0_0_pre_10) (SP_0_0_pim_0 + SP_0_0_pim_2 + SP_0_0_pim_4 + SP_0_0_pim_5 + SP_0_0_pim_10) := by
  simp only [SP_0_0_term_0, SP_0_0_term_2, SP_0_0_term_4, SP_0_0_term_5, SP_0_0_term_10]
  simpa [add_assoc] using ofLadj_add5 SP_0_0_pre_0 SP_0_0_pim_0 SP_0_0_pre_2 SP_0_0_pim_2 SP_0_0_pre_4 SP_0_0_pim_4 SP_0_0_pre_5 SP_0_0_pim_5 SP_0_0_pre_10 SP_0_0_pim_10

theorem SP_0_0_eval :
    ofLadj (SP_0_0_pre_0 + SP_0_0_pre_2 + SP_0_0_pre_4 + SP_0_0_pre_5 + SP_0_0_pre_10) (SP_0_0_pim_0 + SP_0_0_pim_2 + SP_0_0_pim_4 + SP_0_0_pim_5 + SP_0_0_pim_10) =
      ofLadj (SP_0_0_t1_re - SP_0_0_t2_re) (SP_0_0_t1_im - SP_0_0_t2_im) := by
  rw [SP_0_0_sum_poly_re, SP_0_0_sum_poly_im, ofLadj_add_Phi11]

theorem SP_0_0_on_Qplus :
    minorCoeffsH (0 : Fin 9) (0 : Fin 21) =
      spanV (0 : Fin 9) (0 : Fin 15) * Qplus (0 : Fin 15) (0 : Fin 21) + spanV (0 : Fin 9) (2 : Fin 15) * Qplus (2 : Fin 15) (0 : Fin 21) + spanV (0 : Fin 9) (4 : Fin 15) * Qplus (4 : Fin 15) (0 : Fin 21) + spanV (0 : Fin 9) (5 : Fin 15) * Qplus (5 : Fin 15) (0 : Fin 21) + spanV (0 : Fin 9) (10 : Fin 15) * Qplus (10 : Fin 15) (0 : Fin 21) := by
  rw [SP_0_0_minor_ofLadj]
  rw [spanV_apply_0_0, Qplus_apply_0_0]
  rw [spanV_apply_0_2, Qplus_apply_2_0]
  rw [spanV_apply_0_4, Qplus_apply_4_0]
  rw [spanV_apply_0_5, Qplus_apply_5_0]
  rw [spanV_apply_0_10, Qplus_apply_10_0]
  exact (SP_0_0_sum_entries).trans SP_0_0_eval

theorem SP_0_0_zero_1 :
    spanV (0 : Fin 9) (1 : Fin 15) * Qplus (1 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_1, Qplus_apply_1_0,
    spanV_entry_0_1, Qplus_entry_1_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem SP_0_0_zero_3 :
    spanV (0 : Fin 9) (3 : Fin 15) * Qplus (3 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_3, Qplus_apply_3_0,
    spanV_entry_0_3, Qplus_entry_3_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem SP_0_0_zero_6 :
    spanV (0 : Fin 9) (6 : Fin 15) * Qplus (6 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_6, Qplus_apply_6_0,
    spanV_entry_0_6, Qplus_entry_6_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem SP_0_0_zero_7 :
    spanV (0 : Fin 9) (7 : Fin 15) * Qplus (7 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_7, Qplus_apply_7_0,
    spanV_entry_0_7, Qplus_entry_7_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem SP_0_0_zero_8 :
    spanV (0 : Fin 9) (8 : Fin 15) * Qplus (8 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_8, Qplus_apply_8_0,
    spanV_entry_0_8, Qplus_entry_8_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem SP_0_0_zero_9 :
    spanV (0 : Fin 9) (9 : Fin 15) * Qplus (9 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_9, Qplus_apply_9_0,
    spanV_entry_0_9, Qplus_entry_9_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem SP_0_0_zero_11 :
    spanV (0 : Fin 9) (11 : Fin 15) * Qplus (11 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_11, Qplus_apply_11_0,
    spanV_entry_0_11, Qplus_entry_11_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem SP_0_0_zero_12 :
    spanV (0 : Fin 9) (12 : Fin 15) * Qplus (12 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_12, Qplus_apply_12_0,
    spanV_entry_0_12, Qplus_entry_12_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem SP_0_0_zero_13 :
    spanV (0 : Fin 9) (13 : Fin 15) * Qplus (13 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_13, Qplus_apply_13_0,
    spanV_entry_0_13, Qplus_entry_13_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem SP_0_0_zero_14 :
    spanV (0 : Fin 9) (14 : Fin 15) * Qplus (14 : Fin 15) (0 : Fin 21) =
      0 := by
  rw [spanV_apply_0_14, Qplus_apply_14_0,
    spanV_entry_0_14, Qplus_entry_14_0]
  simp [ofLadj_mul, ofLadj_zero]

theorem span_coeff_0_0 :
    minorCoeffsH (0 : Fin 9) (0 : Fin 21) =
      ∑ q : Fin 15, spanV ({s} : Fin 9) q * Qplus q ({m} : Fin 21) := by
  rw [sum_fin15]
  rw [SP_0_0_zero_1]
  rw [SP_0_0_zero_3]
  rw [SP_0_0_zero_6]
  rw [SP_0_0_zero_7]
  rw [SP_0_0_zero_8]
  rw [SP_0_0_zero_9]
  rw [SP_0_0_zero_11]
  rw [SP_0_0_zero_12]
  rw [SP_0_0_zero_13]
  rw [SP_0_0_zero_14]
  simp only [add_zero, zero_add]
  exact SP_0_0_on_Qplus

end V14Formalization.D12SigmaPlusSegreCore
