/-
Apply lemmas for Qplus.
-/
module

public import V14Formalization.D12SigmaPlusSegreApply_Qplus_0
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_1
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_2
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_3
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_4
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_5
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_6
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_7
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_8
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_9
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_10
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_11
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_12
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_13
public import V14Formalization.D12SigmaPlusSegreApply_Qplus_14
