/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
module

public import V14Formalization.D12SigmaPlusSegreEval
public import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def UM_qre_6_20 : Polynomial ℚ := C ((12 / 11 : ℚ)) * X + C ((12 / 11 : ℚ)) * X ^ 2 + C ((30 / 11 : ℚ)) * X ^ 3 + C ((4 / 11 : ℚ)) * X ^ 4 + C ((4 / 11 : ℚ)) * X ^ 5 + C ((-18 / 11 : ℚ)) * X ^ 6
def UM_qim_6_20 : Polynomial ℚ := (0 : Polynomial ℚ)

def UM_pre_6_20_0 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_6_20_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_6_20_0 :
    spanU_entry_6_0 * minorQ_entry_0_20 =
      ofLadj UM_pre_6_20_0 UM_pim_6_20_0 := by
  have hz : spanU_entry_6_0 = 0 := by
    rw [spanU_entry_6_0]; exact ofLadj_zero
  rw [hz, UM_pre_6_20_0, UM_pim_6_20_0]
  simp [ofLadj_zero]

def UM_pre_6_20_1 : Polynomial ℚ := C ((1 / 11 : ℚ)) * X ^ 3 + C ((-1 / 11 : ℚ)) * X ^ 4 + C ((1 / 11 : ℚ)) * X ^ 5 + C ((-3 / 11 : ℚ)) * X ^ 6 + C ((-1 / 11 : ℚ)) * X ^ 7 + C ((-1 / 11 : ℚ)) * X ^ 9 + C ((4 / 11 : ℚ)) * X ^ 10 + C ((4 / 11 : ℚ)) * X ^ 12 + C ((-1 / 11 : ℚ)) * X ^ 13 + C ((-1 / 11 : ℚ)) * X ^ 14 + C ((-3 / 11 : ℚ)) * X ^ 16 + C ((1 / 11 : ℚ)) * X ^ 17
def UM_pim_6_20_1 : Polynomial ℚ := C ((-1 / 11 : ℚ)) + C ((-2 / 11 : ℚ)) * X + C ((-1 / 11 : ℚ)) * X ^ 2 + C ((-1 / 11 : ℚ)) * X ^ 3 + C ((5 / 11 : ℚ)) * X ^ 4 + C ((5 / 11 : ℚ)) * X ^ 5 + C ((9 / 11 : ℚ)) * X ^ 6 + C ((10 / 11 : ℚ)) * X ^ 7 + C (1) * X ^ 8 + C ((10 / 11 : ℚ)) * X ^ 9 + C ((9 / 11 : ℚ)) * X ^ 10 + C ((12 / 11 : ℚ)) * X ^ 11 + C ((15 / 11 : ℚ)) * X ^ 12 + C ((13 / 11 : ℚ)) * X ^ 13 + C ((12 / 11 : ℚ)) * X ^ 14 + C ((9 / 11 : ℚ)) * X ^ 15 + C ((5 / 11 : ℚ)) * X ^ 16 + C ((3 / 11 : ℚ)) * X ^ 17 + C ((-2 / 11 : ℚ)) * X ^ 18
theorem UM_pre_eq_6_20_1 :
    spanU_re_6_1 * minorQ_re_1_20 - spanU_im_6_1 * minorQ_im_1_20 =
      UM_pre_6_20_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_1, spanU_im_6_1, minorQ_re_1_20, minorQ_im_1_20,
    UM_pre_6_20_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_20_1 :
    spanU_re_6_1 * minorQ_im_1_20 + spanU_im_6_1 * minorQ_re_1_20 =
      UM_pim_6_20_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_1, spanU_im_6_1, minorQ_re_1_20, minorQ_im_1_20,
    UM_pim_6_20_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_20_1 :
    spanU_entry_6_1 * minorQ_entry_1_20 =
      ofLadj UM_pre_6_20_1 UM_pim_6_20_1 := by
  rw [spanU_entry_6_1, minorQ_entry_1_20, ofLadj_mul,
    UM_pre_eq_6_20_1, UM_pim_eq_6_20_1]

def UM_pre_6_20_2 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_6_20_2 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_6_20_2 :
    spanU_entry_6_2 * minorQ_entry_2_20 =
      ofLadj UM_pre_6_20_2 UM_pim_6_20_2 := by
  have hz : spanU_entry_6_2 = 0 := by
    rw [spanU_entry_6_2]; exact ofLadj_zero
  rw [hz, UM_pre_6_20_2, UM_pim_6_20_2]
  simp [ofLadj_zero]

def UM_pre_6_20_3 : Polynomial ℚ := C ((1 / 11 : ℚ)) * X ^ 3 + C ((-1 / 11 : ℚ)) * X ^ 4 + C ((1 / 11 : ℚ)) * X ^ 5 + C ((-3 / 11 : ℚ)) * X ^ 6 + C ((-1 / 11 : ℚ)) * X ^ 7 + C ((-1 / 11 : ℚ)) * X ^ 9 + C ((4 / 11 : ℚ)) * X ^ 10 + C ((4 / 11 : ℚ)) * X ^ 12 + C ((-1 / 11 : ℚ)) * X ^ 13 + C ((-1 / 11 : ℚ)) * X ^ 14 + C ((-3 / 11 : ℚ)) * X ^ 16 + C ((1 / 11 : ℚ)) * X ^ 17
def UM_pim_6_20_3 : Polynomial ℚ := C ((1 / 11 : ℚ)) + C ((2 / 11 : ℚ)) * X + C ((1 / 11 : ℚ)) * X ^ 2 + C ((1 / 11 : ℚ)) * X ^ 3 + C ((-5 / 11 : ℚ)) * X ^ 4 + C ((-5 / 11 : ℚ)) * X ^ 5 + C ((-9 / 11 : ℚ)) * X ^ 6 + C ((-10 / 11 : ℚ)) * X ^ 7 + C (-1) * X ^ 8 + C ((-10 / 11 : ℚ)) * X ^ 9 + C ((-9 / 11 : ℚ)) * X ^ 10 + C ((-12 / 11 : ℚ)) * X ^ 11 + C ((-15 / 11 : ℚ)) * X ^ 12 + C ((-13 / 11 : ℚ)) * X ^ 13 + C ((-12 / 11 : ℚ)) * X ^ 14 + C ((-9 / 11 : ℚ)) * X ^ 15 + C ((-5 / 11 : ℚ)) * X ^ 16 + C ((-3 / 11 : ℚ)) * X ^ 17 + C ((2 / 11 : ℚ)) * X ^ 18
theorem UM_pre_eq_6_20_3 :
    spanU_re_6_3 * minorQ_re_3_20 - spanU_im_6_3 * minorQ_im_3_20 =
      UM_pre_6_20_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_3, spanU_im_6_3, minorQ_re_3_20, minorQ_im_3_20,
    UM_pre_6_20_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_20_3 :
    spanU_re_6_3 * minorQ_im_3_20 + spanU_im_6_3 * minorQ_re_3_20 =
      UM_pim_6_20_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_3, spanU_im_6_3, minorQ_re_3_20, minorQ_im_3_20,
    UM_pim_6_20_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_20_3 :
    spanU_entry_6_3 * minorQ_entry_3_20 =
      ofLadj UM_pre_6_20_3 UM_pim_6_20_3 := by
  rw [spanU_entry_6_3, minorQ_entry_3_20, ofLadj_mul,
    UM_pre_eq_6_20_3, UM_pim_eq_6_20_3]

def UM_pre_6_20_4 : Polynomial ℚ := C ((2 / 11 : ℚ)) * X ^ 3 + C ((-6 / 11 : ℚ)) * X ^ 6 + C ((-6 / 11 : ℚ)) * X ^ 7 + C ((-2 / 11 : ℚ)) * X ^ 8 + C ((2 / 11 : ℚ)) * X ^ 9 + C ((8 / 11 : ℚ)) * X ^ 10 + C ((4 / 11 : ℚ)) * X ^ 11 + C ((8 / 11 : ℚ)) * X ^ 12 + C ((2 / 11 : ℚ)) * X ^ 13 + C ((-4 / 11 : ℚ)) * X ^ 14 + C ((-6 / 11 : ℚ)) * X ^ 15 + C ((-4 / 11 : ℚ)) * X ^ 16 + C ((2 / 11 : ℚ)) * X ^ 17
def UM_pim_6_20_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_pre_eq_6_20_4 :
    spanU_re_6_4 * minorQ_re_4_20 - spanU_im_6_4 * minorQ_im_4_20 =
      UM_pre_6_20_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_4, spanU_im_6_4, minorQ_re_4_20, minorQ_im_4_20,
    UM_pre_6_20_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_20_4 :
    spanU_re_6_4 * minorQ_im_4_20 + spanU_im_6_4 * minorQ_re_4_20 =
      UM_pim_6_20_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_4, spanU_im_6_4, minorQ_re_4_20, minorQ_im_4_20,
    UM_pim_6_20_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_20_4 :
    spanU_entry_6_4 * minorQ_entry_4_20 =
      ofLadj UM_pre_6_20_4 UM_pim_6_20_4 := by
  rw [spanU_entry_6_4, minorQ_entry_4_20, ofLadj_mul,
    UM_pre_eq_6_20_4, UM_pim_eq_6_20_4]

def UM_pre_6_20_5 : Polynomial ℚ := C ((6 / 11 : ℚ)) * X + C ((12 / 11 : ℚ)) * X ^ 2 + C ((25 / 11 : ℚ)) * X ^ 3 + C ((30 / 11 : ℚ)) * X ^ 4 + C ((30 / 11 : ℚ)) * X ^ 5 + C ((28 / 11 : ℚ)) * X ^ 6 + C ((26 / 11 : ℚ)) * X ^ 7 + C ((23 / 11 : ℚ)) * X ^ 8 + C (2) * X ^ 9 + C ((14 / 11 : ℚ)) * X ^ 10 + C ((20 / 11 : ℚ)) * X ^ 11 + C ((8 / 11 : ℚ)) * X ^ 12 + C ((10 / 11 : ℚ)) * X ^ 13 + C ((-2 / 11 : ℚ)) * X ^ 14 + C ((-4 / 11 : ℚ)) * X ^ 15 + C ((-4 / 11 : ℚ)) * X ^ 16 + C ((-2 / 11 : ℚ)) * X ^ 17
def UM_pim_6_20_5 : Polynomial ℚ := C ((-5 / 11 : ℚ)) + C ((-10 / 11 : ℚ)) * X + C ((-15 / 11 : ℚ)) * X ^ 2 + C ((-20 / 11 : ℚ)) * X ^ 3 + C ((-9 / 11 : ℚ)) * X ^ 4 + C ((-16 / 11 : ℚ)) * X ^ 5 + C ((-12 / 11 : ℚ)) * X ^ 6 + C ((-19 / 11 : ℚ)) * X ^ 7 + C ((-15 / 11 : ℚ)) * X ^ 8 + C ((-14 / 11 : ℚ)) * X ^ 9 + C ((-16 / 11 : ℚ)) * X ^ 10 + C ((-6 / 11 : ℚ)) * X ^ 11 + C ((4 / 11 : ℚ)) * X ^ 12 + C ((7 / 11 : ℚ)) * X ^ 13 + C ((13 / 11 : ℚ)) * X ^ 14 + C ((6 / 11 : ℚ)) * X ^ 15 + C ((5 / 11 : ℚ)) * X ^ 16 + C ((1 / 11 : ℚ)) * X ^ 17
theorem UM_pre_eq_6_20_5 :
    spanU_re_6_5 * minorQ_re_5_20 - spanU_im_6_5 * minorQ_im_5_20 =
      UM_pre_6_20_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_5, spanU_im_6_5, minorQ_re_5_20, minorQ_im_5_20,
    UM_pre_6_20_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_20_5 :
    spanU_re_6_5 * minorQ_im_5_20 + spanU_im_6_5 * minorQ_re_5_20 =
      UM_pim_6_20_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_5, spanU_im_6_5, minorQ_re_5_20, minorQ_im_5_20,
    UM_pim_6_20_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_20_5 :
    spanU_entry_6_5 * minorQ_entry_5_20 =
      ofLadj UM_pre_6_20_5 UM_pim_6_20_5 := by
  rw [spanU_entry_6_5, minorQ_entry_5_20, ofLadj_mul,
    UM_pre_eq_6_20_5, UM_pim_eq_6_20_5]

def UM_pre_6_20_6 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_6_20_6 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_6_20_6 :
    spanU_entry_6_6 * minorQ_entry_6_20 =
      ofLadj UM_pre_6_20_6 UM_pim_6_20_6 := by
  have hz : spanU_entry_6_6 = 0 := by
    rw [spanU_entry_6_6]; exact ofLadj_zero
  rw [hz, UM_pre_6_20_6, UM_pim_6_20_6]
  simp [ofLadj_zero]

def UM_pre_6_20_7 : Polynomial ℚ := C ((6 / 11 : ℚ)) * X + C ((12 / 11 : ℚ)) * X ^ 2 + C ((25 / 11 : ℚ)) * X ^ 3 + C ((30 / 11 : ℚ)) * X ^ 4 + C ((30 / 11 : ℚ)) * X ^ 5 + C ((28 / 11 : ℚ)) * X ^ 6 + C ((26 / 11 : ℚ)) * X ^ 7 + C ((23 / 11 : ℚ)) * X ^ 8 + C (2) * X ^ 9 + C ((14 / 11 : ℚ)) * X ^ 10 + C ((20 / 11 : ℚ)) * X ^ 11 + C ((8 / 11 : ℚ)) * X ^ 12 + C ((10 / 11 : ℚ)) * X ^ 13 + C ((-2 / 11 : ℚ)) * X ^ 14 + C ((-4 / 11 : ℚ)) * X ^ 15 + C ((-4 / 11 : ℚ)) * X ^ 16 + C ((-2 / 11 : ℚ)) * X ^ 17
def UM_pim_6_20_7 : Polynomial ℚ := C ((5 / 11 : ℚ)) + C ((10 / 11 : ℚ)) * X + C ((15 / 11 : ℚ)) * X ^ 2 + C ((20 / 11 : ℚ)) * X ^ 3 + C ((9 / 11 : ℚ)) * X ^ 4 + C ((16 / 11 : ℚ)) * X ^ 5 + C ((12 / 11 : ℚ)) * X ^ 6 + C ((19 / 11 : ℚ)) * X ^ 7 + C ((15 / 11 : ℚ)) * X ^ 8 + C ((14 / 11 : ℚ)) * X ^ 9 + C ((16 / 11 : ℚ)) * X ^ 10 + C ((6 / 11 : ℚ)) * X ^ 11 + C ((-4 / 11 : ℚ)) * X ^ 12 + C ((-7 / 11 : ℚ)) * X ^ 13 + C ((-13 / 11 : ℚ)) * X ^ 14 + C ((-6 / 11 : ℚ)) * X ^ 15 + C ((-5 / 11 : ℚ)) * X ^ 16 + C ((-1 / 11 : ℚ)) * X ^ 17
theorem UM_pre_eq_6_20_7 :
    spanU_re_6_7 * minorQ_re_7_20 - spanU_im_6_7 * minorQ_im_7_20 =
      UM_pre_6_20_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_7, spanU_im_6_7, minorQ_re_7_20, minorQ_im_7_20,
    UM_pre_6_20_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_20_7 :
    spanU_re_6_7 * minorQ_im_7_20 + spanU_im_6_7 * minorQ_re_7_20 =
      UM_pim_6_20_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_7, spanU_im_6_7, minorQ_re_7_20, minorQ_im_7_20,
    UM_pim_6_20_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_20_7 :
    spanU_entry_6_7 * minorQ_entry_7_20 =
      ofLadj UM_pre_6_20_7 UM_pim_6_20_7 := by
  rw [spanU_entry_6_7, minorQ_entry_7_20, ofLadj_mul,
    UM_pre_eq_6_20_7, UM_pim_eq_6_20_7]

def UM_pre_6_20_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_6_20_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_6_20_8 :
    spanU_entry_6_8 * minorQ_entry_8_20 =
      ofLadj UM_pre_6_20_8 UM_pim_6_20_8 := by
  have hz : spanU_entry_6_8 = 0 := by
    rw [spanU_entry_6_8]; exact ofLadj_zero
  rw [hz, UM_pre_6_20_8, UM_pim_6_20_8]
  simp [ofLadj_zero]

theorem UM_sum_poly_re_6_20 :
    UM_pre_6_20_0 + UM_pre_6_20_1 + UM_pre_6_20_2 + UM_pre_6_20_3 + UM_pre_6_20_4 + UM_pre_6_20_5 + UM_pre_6_20_6 + UM_pre_6_20_7 + UM_pre_6_20_8 = Qplus_re_6_20 + Phi11 * UM_qre_6_20 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pre_6_20_0, UM_pre_6_20_1, UM_pre_6_20_2, UM_pre_6_20_3, UM_pre_6_20_4, UM_pre_6_20_5, UM_pre_6_20_6, UM_pre_6_20_7, UM_pre_6_20_8, Qplus_re_6_20, UM_qre_6_20]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_poly_im_6_20 :
    UM_pim_6_20_0 + UM_pim_6_20_1 + UM_pim_6_20_2 + UM_pim_6_20_3 + UM_pim_6_20_4 + UM_pim_6_20_5 + UM_pim_6_20_6 + UM_pim_6_20_7 + UM_pim_6_20_8 = Qplus_im_6_20 + Phi11 * UM_qim_6_20 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pim_6_20_0, UM_pim_6_20_1, UM_pim_6_20_2, UM_pim_6_20_3, UM_pim_6_20_4, UM_pim_6_20_5, UM_pim_6_20_6, UM_pim_6_20_7, UM_pim_6_20_8, Qplus_im_6_20, UM_qim_6_20]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_entries_6_20 :
    spanU_entry_6_0 * minorQ_entry_0_20 + spanU_entry_6_1 * minorQ_entry_1_20 + spanU_entry_6_2 * minorQ_entry_2_20 + spanU_entry_6_3 * minorQ_entry_3_20 + spanU_entry_6_4 * minorQ_entry_4_20 + spanU_entry_6_5 * minorQ_entry_5_20 + spanU_entry_6_6 * minorQ_entry_6_20 + spanU_entry_6_7 * minorQ_entry_7_20 + spanU_entry_6_8 * minorQ_entry_8_20 =
      ofLadj (UM_pre_6_20_0 + UM_pre_6_20_1 + UM_pre_6_20_2 + UM_pre_6_20_3 + UM_pre_6_20_4 + UM_pre_6_20_5 + UM_pre_6_20_6 + UM_pre_6_20_7 + UM_pre_6_20_8) (UM_pim_6_20_0 + UM_pim_6_20_1 + UM_pim_6_20_2 + UM_pim_6_20_3 + UM_pim_6_20_4 + UM_pim_6_20_5 + UM_pim_6_20_6 + UM_pim_6_20_7 + UM_pim_6_20_8) := by
  simp only [UM_term_6_20_0, UM_term_6_20_1, UM_term_6_20_2, UM_term_6_20_3, UM_term_6_20_4, UM_term_6_20_5, UM_term_6_20_6, UM_term_6_20_7, UM_term_6_20_8]
  simpa [add_assoc] using ofLadj_add9 UM_pre_6_20_0 UM_pim_6_20_0 UM_pre_6_20_1 UM_pim_6_20_1 UM_pre_6_20_2 UM_pim_6_20_2 UM_pre_6_20_3 UM_pim_6_20_3 UM_pre_6_20_4 UM_pim_6_20_4 UM_pre_6_20_5 UM_pim_6_20_5 UM_pre_6_20_6 UM_pim_6_20_6 UM_pre_6_20_7 UM_pim_6_20_7 UM_pre_6_20_8 UM_pim_6_20_8

theorem UM_eval_6_20 :
    ofLadj (UM_pre_6_20_0 + UM_pre_6_20_1 + UM_pre_6_20_2 + UM_pre_6_20_3 + UM_pre_6_20_4 + UM_pre_6_20_5 + UM_pre_6_20_6 + UM_pre_6_20_7 + UM_pre_6_20_8) (UM_pim_6_20_0 + UM_pim_6_20_1 + UM_pim_6_20_2 + UM_pim_6_20_3 + UM_pim_6_20_4 + UM_pim_6_20_5 + UM_pim_6_20_6 + UM_pim_6_20_7 + UM_pim_6_20_8) = Qplus_entry_6_20 := by
  rw [UM_sum_poly_re_6_20, UM_sum_poly_im_6_20,
    ofLadj_add_Phi11, Qplus_entry_6_20]

public theorem UM_entry_6_20 : (spanU * minorQ) 6 20 = Qplus 6 20 := by
  rw [Matrix.mul_apply]
  rw [sum_fin9]
  change spanU_entry_6_0 * minorQ_entry_0_20 + spanU_entry_6_1 * minorQ_entry_1_20 + spanU_entry_6_2 * minorQ_entry_2_20 + spanU_entry_6_3 * minorQ_entry_3_20 + spanU_entry_6_4 * minorQ_entry_4_20 + spanU_entry_6_5 * minorQ_entry_5_20 + spanU_entry_6_6 * minorQ_entry_6_20 + spanU_entry_6_7 * minorQ_entry_7_20 + spanU_entry_6_8 * minorQ_entry_8_20 = Qplus_entry_6_20
  exact (UM_sum_entries_6_20).trans UM_eval_6_20

end V14Formalization.D12SigmaPlusSegreCore
