/-
Auto-generated by scripts/export_sigma_plus_span_identities.py.
Stock-limit, kernel-checkable plus Segre span identities.
-/
module

public import V14Formalization.D12SigmaPlusSegreEval
public import V14Formalization.D12SigmaPlusSegreSpanCore

noncomputable section
open Matrix Polynomial
namespace V14Formalization.D12SigmaPlusSegreCore
open D12PolynomialData

def UM_qre_6_18 : Polynomial ℚ := C ((9 / 22 : ℚ)) + C ((-9 / 22 : ℚ)) * X + C ((-1 / 11 : ℚ)) * X ^ 2 + C ((-13 / 11 : ℚ)) * X ^ 3 + C ((7 / 11 : ℚ)) * X ^ 4 + C (-1) * X ^ 5 + C ((7 / 22 : ℚ)) * X ^ 6 + C ((-10 / 11 : ℚ)) * X ^ 7 + C ((-3 / 11 : ℚ)) * X ^ 8
def UM_qim_6_18 : Polynomial ℚ := (0 : Polynomial ℚ)

def UM_pre_6_18_0 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_6_18_0 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_6_18_0 :
    spanU_entry_6_0 * minorQ_entry_0_18 =
      ofLadj UM_pre_6_18_0 UM_pim_6_18_0 := by
  have hz : spanU_entry_6_0 = 0 := by
    rw [spanU_entry_6_0]; exact ofLadj_zero
  rw [hz, UM_pre_6_18_0, UM_pim_6_18_0]
  simp [ofLadj_zero]

def UM_pre_6_18_1 : Polynomial ℚ := C ((3 / 44 : ℚ)) + C ((3 / 11 : ℚ)) * X + C ((21 / 44 : ℚ)) * X ^ 2 + C ((15 / 22 : ℚ)) * X ^ 3 + C ((10 / 11 : ℚ)) * X ^ 4 + C ((15 / 22 : ℚ)) * X ^ 5 + C ((45 / 44 : ℚ)) * X ^ 6 + C ((8 / 11 : ℚ)) * X ^ 7 + C ((37 / 44 : ℚ)) * X ^ 8 + C ((31 / 44 : ℚ)) * X ^ 9 + C ((9 / 11 : ℚ)) * X ^ 10 + C ((23 / 22 : ℚ)) * X ^ 11 + C ((6 / 11 : ℚ)) * X ^ 12 + C ((5 / 22 : ℚ)) * X ^ 13 + C ((7 / 44 : ℚ)) * X ^ 14 + C ((-7 / 22 : ℚ)) * X ^ 15 + C ((-3 / 44 : ℚ)) * X ^ 16 + C ((-9 / 22 : ℚ)) * X ^ 17 + C ((-3 / 22 : ℚ)) * X ^ 18
def UM_pim_6_18_1 : Polynomial ℚ := C ((3 / 44 : ℚ)) + C ((3 / 22 : ℚ)) * X + C ((3 / 44 : ℚ)) * X ^ 2 + C ((13 / 44 : ℚ)) * X ^ 3 + C ((7 / 22 : ℚ)) * X ^ 4 + C ((13 / 22 : ℚ)) * X ^ 5 + C ((25 / 44 : ℚ)) * X ^ 6 + C ((9 / 22 : ℚ)) * X ^ 7 + C ((31 / 44 : ℚ)) * X ^ 8 + C ((5 / 11 : ℚ)) * X ^ 9 + C ((8 / 11 : ℚ)) * X ^ 10 + C ((15 / 22 : ℚ)) * X ^ 11 + C ((7 / 11 : ℚ)) * X ^ 12 + C ((43 / 44 : ℚ)) * X ^ 13 + C ((1 / 2 : ℚ)) * X ^ 14 + C ((7 / 11 : ℚ)) * X ^ 15 + C ((13 / 44 : ℚ)) * X ^ 16 + C ((1 / 22 : ℚ)) * X ^ 17 + C ((3 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_6_18_1 :
    spanU_re_6_1 * minorQ_re_1_18 - spanU_im_6_1 * minorQ_im_1_18 =
      UM_pre_6_18_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_1, spanU_im_6_1, minorQ_re_1_18, minorQ_im_1_18,
    UM_pre_6_18_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_18_1 :
    spanU_re_6_1 * minorQ_im_1_18 + spanU_im_6_1 * minorQ_re_1_18 =
      UM_pim_6_18_1 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_1, spanU_im_6_1, minorQ_re_1_18, minorQ_im_1_18,
    UM_pim_6_18_1]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_18_1 :
    spanU_entry_6_1 * minorQ_entry_1_18 =
      ofLadj UM_pre_6_18_1 UM_pim_6_18_1 := by
  rw [spanU_entry_6_1, minorQ_entry_1_18, ofLadj_mul,
    UM_pre_eq_6_18_1, UM_pim_eq_6_18_1]

def UM_pre_6_18_2 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_6_18_2 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_6_18_2 :
    spanU_entry_6_2 * minorQ_entry_2_18 =
      ofLadj UM_pre_6_18_2 UM_pim_6_18_2 := by
  have hz : spanU_entry_6_2 = 0 := by
    rw [spanU_entry_6_2]; exact ofLadj_zero
  rw [hz, UM_pre_6_18_2, UM_pim_6_18_2]
  simp [ofLadj_zero]

def UM_pre_6_18_3 : Polynomial ℚ := C ((3 / 44 : ℚ)) + C ((3 / 11 : ℚ)) * X + C ((21 / 44 : ℚ)) * X ^ 2 + C ((15 / 22 : ℚ)) * X ^ 3 + C ((10 / 11 : ℚ)) * X ^ 4 + C ((15 / 22 : ℚ)) * X ^ 5 + C ((45 / 44 : ℚ)) * X ^ 6 + C ((8 / 11 : ℚ)) * X ^ 7 + C ((37 / 44 : ℚ)) * X ^ 8 + C ((31 / 44 : ℚ)) * X ^ 9 + C ((9 / 11 : ℚ)) * X ^ 10 + C ((23 / 22 : ℚ)) * X ^ 11 + C ((6 / 11 : ℚ)) * X ^ 12 + C ((5 / 22 : ℚ)) * X ^ 13 + C ((7 / 44 : ℚ)) * X ^ 14 + C ((-7 / 22 : ℚ)) * X ^ 15 + C ((-3 / 44 : ℚ)) * X ^ 16 + C ((-9 / 22 : ℚ)) * X ^ 17 + C ((-3 / 22 : ℚ)) * X ^ 18
def UM_pim_6_18_3 : Polynomial ℚ := C ((-3 / 44 : ℚ)) + C ((-3 / 22 : ℚ)) * X + C ((-3 / 44 : ℚ)) * X ^ 2 + C ((-13 / 44 : ℚ)) * X ^ 3 + C ((-7 / 22 : ℚ)) * X ^ 4 + C ((-13 / 22 : ℚ)) * X ^ 5 + C ((-25 / 44 : ℚ)) * X ^ 6 + C ((-9 / 22 : ℚ)) * X ^ 7 + C ((-31 / 44 : ℚ)) * X ^ 8 + C ((-5 / 11 : ℚ)) * X ^ 9 + C ((-8 / 11 : ℚ)) * X ^ 10 + C ((-15 / 22 : ℚ)) * X ^ 11 + C ((-7 / 11 : ℚ)) * X ^ 12 + C ((-43 / 44 : ℚ)) * X ^ 13 + C ((-1 / 2 : ℚ)) * X ^ 14 + C ((-7 / 11 : ℚ)) * X ^ 15 + C ((-13 / 44 : ℚ)) * X ^ 16 + C ((-1 / 22 : ℚ)) * X ^ 17 + C ((-3 / 22 : ℚ)) * X ^ 18
theorem UM_pre_eq_6_18_3 :
    spanU_re_6_3 * minorQ_re_3_18 - spanU_im_6_3 * minorQ_im_3_18 =
      UM_pre_6_18_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_3, spanU_im_6_3, minorQ_re_3_18, minorQ_im_3_18,
    UM_pre_6_18_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_18_3 :
    spanU_re_6_3 * minorQ_im_3_18 + spanU_im_6_3 * minorQ_re_3_18 =
      UM_pim_6_18_3 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_3, spanU_im_6_3, minorQ_re_3_18, minorQ_im_3_18,
    UM_pim_6_18_3]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_18_3 :
    spanU_entry_6_3 * minorQ_entry_3_18 =
      ofLadj UM_pre_6_18_3 UM_pim_6_18_3 := by
  rw [spanU_entry_6_3, minorQ_entry_3_18, ofLadj_mul,
    UM_pre_eq_6_18_3, UM_pim_eq_6_18_3]

def UM_pre_6_18_4 : Polynomial ℚ := C ((-5 / 11 : ℚ)) * X ^ 3 + C ((5 / 22 : ℚ)) * X ^ 5 + C ((2 / 11 : ℚ)) * X ^ 6 + C ((-2 / 11 : ℚ)) * X ^ 7 + C ((-7 / 22 : ℚ)) * X ^ 8 + C ((7 / 22 : ℚ)) * X ^ 9 + C ((3 / 22 : ℚ)) * X ^ 10 + C ((2 / 11 : ℚ)) * X ^ 11 + C ((3 / 22 : ℚ)) * X ^ 12 + C ((7 / 22 : ℚ)) * X ^ 13 + C ((3 / 22 : ℚ)) * X ^ 14 + C ((-2 / 11 : ℚ)) * X ^ 15 + C ((-3 / 11 : ℚ)) * X ^ 16 + C ((-5 / 22 : ℚ)) * X ^ 17
def UM_pim_6_18_4 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_pre_eq_6_18_4 :
    spanU_re_6_4 * minorQ_re_4_18 - spanU_im_6_4 * minorQ_im_4_18 =
      UM_pre_6_18_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_4, spanU_im_6_4, minorQ_re_4_18, minorQ_im_4_18,
    UM_pre_6_18_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_18_4 :
    spanU_re_6_4 * minorQ_im_4_18 + spanU_im_6_4 * minorQ_re_4_18 =
      UM_pim_6_18_4 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_4, spanU_im_6_4, minorQ_re_4_18, minorQ_im_4_18,
    UM_pim_6_18_4]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_18_4 :
    spanU_entry_6_4 * minorQ_entry_4_18 =
      ofLadj UM_pre_6_18_4 UM_pim_6_18_4 := by
  rw [spanU_entry_6_4, minorQ_entry_4_18, ofLadj_mul,
    UM_pre_eq_6_18_4, UM_pim_eq_6_18_4]

def UM_pre_6_18_5 : Polynomial ℚ := C ((3 / 22 : ℚ)) + C ((-3 / 11 : ℚ)) * X + C ((-23 / 44 : ℚ)) * X ^ 2 + C ((-12 / 11 : ℚ)) * X ^ 3 + C ((-27 / 22 : ℚ)) * X ^ 4 + C ((-71 / 44 : ℚ)) * X ^ 5 + C ((-39 / 22 : ℚ)) * X ^ 6 + C ((-7 / 4 : ℚ)) * X ^ 7 + C ((-85 / 44 : ℚ)) * X ^ 8 + C ((-93 / 44 : ℚ)) * X ^ 9 + C ((-47 / 22 : ℚ)) * X ^ 10 + C ((-57 / 22 : ℚ)) * X ^ 11 + C ((-41 / 22 : ℚ)) * X ^ 12 + C ((-35 / 22 : ℚ)) * X ^ 13 + C ((-37 / 44 : ℚ)) * X ^ 14 + C ((-23 / 44 : ℚ)) * X ^ 15 + C ((-5 / 22 : ℚ)) * X ^ 16 + C ((-3 / 44 : ℚ)) * X ^ 17
def UM_pim_6_18_5 : Polynomial ℚ := C ((3 / 11 : ℚ)) + C ((6 / 11 : ℚ)) * X + C ((4 / 11 : ℚ)) * X ^ 2 + C ((17 / 44 : ℚ)) * X ^ 3 + C ((-2 / 11 : ℚ)) * X ^ 5 + C ((-8 / 11 : ℚ)) * X ^ 6 + C ((-17 / 22 : ℚ)) * X ^ 7 + C ((-15 / 22 : ℚ)) * X ^ 8 + C ((-29 / 44 : ℚ)) * X ^ 9 + C ((-7 / 11 : ℚ)) * X ^ 10 + C ((-17 / 22 : ℚ)) * X ^ 11 + C ((-10 / 11 : ℚ)) * X ^ 12 + C ((-31 / 44 : ℚ)) * X ^ 13 + C ((-31 / 44 : ℚ)) * X ^ 14 + C ((-5 / 22 : ℚ)) * X ^ 15 + C ((-3 / 22 : ℚ)) * X ^ 16 + C ((1 / 22 : ℚ)) * X ^ 17
theorem UM_pre_eq_6_18_5 :
    spanU_re_6_5 * minorQ_re_5_18 - spanU_im_6_5 * minorQ_im_5_18 =
      UM_pre_6_18_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_5, spanU_im_6_5, minorQ_re_5_18, minorQ_im_5_18,
    UM_pre_6_18_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_18_5 :
    spanU_re_6_5 * minorQ_im_5_18 + spanU_im_6_5 * minorQ_re_5_18 =
      UM_pim_6_18_5 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_5, spanU_im_6_5, minorQ_re_5_18, minorQ_im_5_18,
    UM_pim_6_18_5]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_18_5 :
    spanU_entry_6_5 * minorQ_entry_5_18 =
      ofLadj UM_pre_6_18_5 UM_pim_6_18_5 := by
  rw [spanU_entry_6_5, minorQ_entry_5_18, ofLadj_mul,
    UM_pre_eq_6_18_5, UM_pim_eq_6_18_5]

def UM_pre_6_18_6 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_6_18_6 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_6_18_6 :
    spanU_entry_6_6 * minorQ_entry_6_18 =
      ofLadj UM_pre_6_18_6 UM_pim_6_18_6 := by
  have hz : spanU_entry_6_6 = 0 := by
    rw [spanU_entry_6_6]; exact ofLadj_zero
  rw [hz, UM_pre_6_18_6, UM_pim_6_18_6]
  simp [ofLadj_zero]

def UM_pre_6_18_7 : Polynomial ℚ := C ((3 / 22 : ℚ)) + C ((-3 / 11 : ℚ)) * X + C ((-23 / 44 : ℚ)) * X ^ 2 + C ((-12 / 11 : ℚ)) * X ^ 3 + C ((-27 / 22 : ℚ)) * X ^ 4 + C ((-71 / 44 : ℚ)) * X ^ 5 + C ((-39 / 22 : ℚ)) * X ^ 6 + C ((-7 / 4 : ℚ)) * X ^ 7 + C ((-85 / 44 : ℚ)) * X ^ 8 + C ((-93 / 44 : ℚ)) * X ^ 9 + C ((-47 / 22 : ℚ)) * X ^ 10 + C ((-57 / 22 : ℚ)) * X ^ 11 + C ((-41 / 22 : ℚ)) * X ^ 12 + C ((-35 / 22 : ℚ)) * X ^ 13 + C ((-37 / 44 : ℚ)) * X ^ 14 + C ((-23 / 44 : ℚ)) * X ^ 15 + C ((-5 / 22 : ℚ)) * X ^ 16 + C ((-3 / 44 : ℚ)) * X ^ 17
def UM_pim_6_18_7 : Polynomial ℚ := C ((-3 / 11 : ℚ)) + C ((-6 / 11 : ℚ)) * X + C ((-4 / 11 : ℚ)) * X ^ 2 + C ((-17 / 44 : ℚ)) * X ^ 3 + C ((2 / 11 : ℚ)) * X ^ 5 + C ((8 / 11 : ℚ)) * X ^ 6 + C ((17 / 22 : ℚ)) * X ^ 7 + C ((15 / 22 : ℚ)) * X ^ 8 + C ((29 / 44 : ℚ)) * X ^ 9 + C ((7 / 11 : ℚ)) * X ^ 10 + C ((17 / 22 : ℚ)) * X ^ 11 + C ((10 / 11 : ℚ)) * X ^ 12 + C ((31 / 44 : ℚ)) * X ^ 13 + C ((31 / 44 : ℚ)) * X ^ 14 + C ((5 / 22 : ℚ)) * X ^ 15 + C ((3 / 22 : ℚ)) * X ^ 16 + C ((-1 / 22 : ℚ)) * X ^ 17
theorem UM_pre_eq_6_18_7 :
    spanU_re_6_7 * minorQ_re_7_18 - spanU_im_6_7 * minorQ_im_7_18 =
      UM_pre_6_18_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_7, spanU_im_6_7, minorQ_re_7_18, minorQ_im_7_18,
    UM_pre_6_18_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_pim_eq_6_18_7 :
    spanU_re_6_7 * minorQ_im_7_18 + spanU_im_6_7 * minorQ_re_7_18 =
      UM_pim_6_18_7 := by
  refine Polynomial.funext fun r => ?_
  simp only [spanU_re_6_7, spanU_im_6_7, minorQ_re_7_18, minorQ_im_7_18,
    UM_pim_6_18_7]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero]
  try ring
theorem UM_term_6_18_7 :
    spanU_entry_6_7 * minorQ_entry_7_18 =
      ofLadj UM_pre_6_18_7 UM_pim_6_18_7 := by
  rw [spanU_entry_6_7, minorQ_entry_7_18, ofLadj_mul,
    UM_pre_eq_6_18_7, UM_pim_eq_6_18_7]

def UM_pre_6_18_8 : Polynomial ℚ := (0 : Polynomial ℚ)
def UM_pim_6_18_8 : Polynomial ℚ := (0 : Polynomial ℚ)
theorem UM_term_6_18_8 :
    spanU_entry_6_8 * minorQ_entry_8_18 =
      ofLadj UM_pre_6_18_8 UM_pim_6_18_8 := by
  have hz : spanU_entry_6_8 = 0 := by
    rw [spanU_entry_6_8]; exact ofLadj_zero
  rw [hz, UM_pre_6_18_8, UM_pim_6_18_8]
  simp [ofLadj_zero]

theorem UM_sum_poly_re_6_18 :
    UM_pre_6_18_0 + UM_pre_6_18_1 + UM_pre_6_18_2 + UM_pre_6_18_3 + UM_pre_6_18_4 + UM_pre_6_18_5 + UM_pre_6_18_6 + UM_pre_6_18_7 + UM_pre_6_18_8 = Qplus_re_6_18 + Phi11 * UM_qre_6_18 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pre_6_18_0, UM_pre_6_18_1, UM_pre_6_18_2, UM_pre_6_18_3, UM_pre_6_18_4, UM_pre_6_18_5, UM_pre_6_18_6, UM_pre_6_18_7, UM_pre_6_18_8, Qplus_re_6_18, UM_qre_6_18]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_poly_im_6_18 :
    UM_pim_6_18_0 + UM_pim_6_18_1 + UM_pim_6_18_2 + UM_pim_6_18_3 + UM_pim_6_18_4 + UM_pim_6_18_5 + UM_pim_6_18_6 + UM_pim_6_18_7 + UM_pim_6_18_8 = Qplus_im_6_18 + Phi11 * UM_qim_6_18 := by
  refine Polynomial.funext fun r => ?_
  rw [Phi11_expand]
  simp only [UM_pim_6_18_0, UM_pim_6_18_1, UM_pim_6_18_2, UM_pim_6_18_3, UM_pim_6_18_4, UM_pim_6_18_5, UM_pim_6_18_6, UM_pim_6_18_7, UM_pim_6_18_8, Qplus_im_6_18, UM_qim_6_18]
  simp [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_mul,
    Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow,
    Polynomial.eval_neg, Polynomial.eval_zero, Polynomial.eval_one]
  try ring

theorem UM_sum_entries_6_18 :
    spanU_entry_6_0 * minorQ_entry_0_18 + spanU_entry_6_1 * minorQ_entry_1_18 + spanU_entry_6_2 * minorQ_entry_2_18 + spanU_entry_6_3 * minorQ_entry_3_18 + spanU_entry_6_4 * minorQ_entry_4_18 + spanU_entry_6_5 * minorQ_entry_5_18 + spanU_entry_6_6 * minorQ_entry_6_18 + spanU_entry_6_7 * minorQ_entry_7_18 + spanU_entry_6_8 * minorQ_entry_8_18 =
      ofLadj (UM_pre_6_18_0 + UM_pre_6_18_1 + UM_pre_6_18_2 + UM_pre_6_18_3 + UM_pre_6_18_4 + UM_pre_6_18_5 + UM_pre_6_18_6 + UM_pre_6_18_7 + UM_pre_6_18_8) (UM_pim_6_18_0 + UM_pim_6_18_1 + UM_pim_6_18_2 + UM_pim_6_18_3 + UM_pim_6_18_4 + UM_pim_6_18_5 + UM_pim_6_18_6 + UM_pim_6_18_7 + UM_pim_6_18_8) := by
  simp only [UM_term_6_18_0, UM_term_6_18_1, UM_term_6_18_2, UM_term_6_18_3, UM_term_6_18_4, UM_term_6_18_5, UM_term_6_18_6, UM_term_6_18_7, UM_term_6_18_8]
  simpa [add_assoc] using ofLadj_add9 UM_pre_6_18_0 UM_pim_6_18_0 UM_pre_6_18_1 UM_pim_6_18_1 UM_pre_6_18_2 UM_pim_6_18_2 UM_pre_6_18_3 UM_pim_6_18_3 UM_pre_6_18_4 UM_pim_6_18_4 UM_pre_6_18_5 UM_pim_6_18_5 UM_pre_6_18_6 UM_pim_6_18_6 UM_pre_6_18_7 UM_pim_6_18_7 UM_pre_6_18_8 UM_pim_6_18_8

theorem UM_eval_6_18 :
    ofLadj (UM_pre_6_18_0 + UM_pre_6_18_1 + UM_pre_6_18_2 + UM_pre_6_18_3 + UM_pre_6_18_4 + UM_pre_6_18_5 + UM_pre_6_18_6 + UM_pre_6_18_7 + UM_pre_6_18_8) (UM_pim_6_18_0 + UM_pim_6_18_1 + UM_pim_6_18_2 + UM_pim_6_18_3 + UM_pim_6_18_4 + UM_pim_6_18_5 + UM_pim_6_18_6 + UM_pim_6_18_7 + UM_pim_6_18_8) = Qplus_entry_6_18 := by
  rw [UM_sum_poly_re_6_18, UM_sum_poly_im_6_18,
    ofLadj_add_Phi11, Qplus_entry_6_18]

public theorem UM_entry_6_18 : (spanU * minorQ) 6 18 = Qplus 6 18 := by
  rw [Matrix.mul_apply]
  rw [sum_fin9]
  change spanU_entry_6_0 * minorQ_entry_0_18 + spanU_entry_6_1 * minorQ_entry_1_18 + spanU_entry_6_2 * minorQ_entry_2_18 + spanU_entry_6_3 * minorQ_entry_3_18 + spanU_entry_6_4 * minorQ_entry_4_18 + spanU_entry_6_5 * minorQ_entry_5_18 + spanU_entry_6_6 * minorQ_entry_6_18 + spanU_entry_6_7 * minorQ_entry_7_18 + spanU_entry_6_8 * minorQ_entry_8_18 = Qplus_entry_6_18
  exact (UM_sum_entries_6_18).trans UM_eval_6_18

end V14Formalization.D12SigmaPlusSegreCore
