/-
Apply lemmas for Qplus.
-/
import V14Formalization.D12SigmaPlusSegreApply_Qplus_0
import V14Formalization.D12SigmaPlusSegreApply_Qplus_1
import V14Formalization.D12SigmaPlusSegreApply_Qplus_2
import V14Formalization.D12SigmaPlusSegreApply_Qplus_3
import V14Formalization.D12SigmaPlusSegreApply_Qplus_4
import V14Formalization.D12SigmaPlusSegreApply_Qplus_5
import V14Formalization.D12SigmaPlusSegreApply_Qplus_6
import V14Formalization.D12SigmaPlusSegreApply_Qplus_7
import V14Formalization.D12SigmaPlusSegreApply_Qplus_8
import V14Formalization.D12SigmaPlusSegreApply_Qplus_9
import V14Formalization.D12SigmaPlusSegreApply_Qplus_10
import V14Formalization.D12SigmaPlusSegreApply_Qplus_11
import V14Formalization.D12SigmaPlusSegreApply_Qplus_12
import V14Formalization.D12SigmaPlusSegreApply_Qplus_13
import V14Formalization.D12SigmaPlusSegreApply_Qplus_14
