/-
Copyright (c) 2026 V14Formalization contributors.
Released under Apache 2.0 license.
-/
module

public import V14Formalization.SymmetricAlgebraGraded
public import V14Formalization.GradedQuotient
public import Mathlib.LinearAlgebra.Contraction

/-!
# Degree-two generators from a bilinear map, without a basis

A bilinear map `w : M →ₗ M →ₗ N` on a finite-dimensional `M` determines a
family of quadrics on `M`, one for each functional on `N`: the quadratic form
`x ↦ φ (w x x)`.  To cut a subscheme out of `ℙ(M) = Proj (Sym (M*))` these
quadrics have to be *elements of* `Sym (M*)`, not functions, and the passage
from one to the other is the only place a basis is usually introduced.

It is not needed.  The composite

    N*  --(lift w)ᵀ-->  (M ⊗ M)*  --dualDistribEquiv⁻¹-->  M* ⊗ M*  --mul-->  Sym (M*)

is three canonical maps; `dualDistribEquiv` is basis-free in its statement and
needs only `Module.Finite`/`Module.Free`.  `quadrics w` is that composite, and
`quadrics_mem_grade_two` says it lands in degree two.

For the Grassmannian quadrics take `w` to be the wedge product
`⋀²U →ₗ ⋀²U →ₗ ⋀⁴U`, which Mathlib supplies as `DirectSum.gMulLHom` on the
graded pieces of the exterior algebra, restricted along `M ↪ ⋀²U`.
-/

noncomputable section

open Module TensorProduct SymmetricAlgebra

namespace V14Formalization
namespace IntrinsicQuadrics

variable {k M N : Type*} [Field k] [AddCommGroup M] [Module k M]
  [FiniteDimensional k M] [AddCommGroup N] [Module k N]

/-- Multiplication of two linear forms inside the symmetric algebra. -/
@[expose] public def symMul2 (k M : Type*) [Field k] [AddCommGroup M] [Module k M] :
    Dual k M ⊗[k] Dual k M →ₗ[k] SymmetricAlgebra k (Dual k M) :=
  TensorProduct.lift
    ((LinearMap.mul k (SymmetricAlgebra k (Dual k M))).compl₁₂
      (SymmetricAlgebra.ι k (Dual k M)) (SymmetricAlgebra.ι k (Dual k M)))

omit [FiniteDimensional k M] in
public theorem symMul2_tmul (f g : Dual k M) :
    symMul2 k M (f ⊗ₜ g) = SymmetricAlgebra.ι k _ f * SymmetricAlgebra.ι k _ g :=
  rfl

/-- The quadrics attached to a bilinear map `w : M →ₗ M →ₗ N`: for each
functional on `N`, a degree-two element of `Sym (M*)`.  No basis of `M`, and no
system of coordinates on `N`, is involved. -/
@[expose] public def quadrics (w : M →ₗ[k] M →ₗ[k] N) :
    Dual k N →ₗ[k] SymmetricAlgebra k (Dual k M) :=
  symMul2 k M ∘ₗ (TensorProduct.dualDistribEquiv k M M).symm.toLinearMap ∘ₗ
    (TensorProduct.lift w).dualMap

/-- The quadrics are homogeneous of degree two. -/
public theorem quadrics_mem_grade_two (w : M →ₗ[k] M →ₗ[k] N) (φ : Dual k N) :
    quadrics w φ ∈ SymmetricAlgebra.grade k (Dual k M) 2 := by
  show symMul2 k M _ ∈ _
  generalize (((TensorProduct.dualDistribEquiv k M M).symm.toLinearMap ∘ₗ
    (TensorProduct.lift w).dualMap) φ) = t
  induction t using TensorProduct.induction_on with
  | zero => simp
  | tmul f g =>
    rw [symMul2_tmul]
    show _ ∈ LinearMap.range (SymmetricAlgebra.ι k (Dual k M)) ^ 2
    rw [sq]
    exact Submodule.mul_mem_mul (LinearMap.mem_range_self _ f) (LinearMap.mem_range_self _ g)
  | add x y hx hy => rw [map_add]; exact Submodule.add_mem _ hx hy

/-- The homogeneous ideal of `Sym (M*)` generated by the quadrics of `w`. -/
@[expose] public def quadricIdeal (w : M →ₗ[k] M →ₗ[k] N) :
    HomogeneousIdeal (SymmetricAlgebra.grade k (Dual k M)) :=
  ⟨Ideal.span (Set.range (quadrics w)), by
    refine Ideal.homogeneous_span _ _ ?_
    rintro _ ⟨φ, rfl⟩
    exact ⟨2, quadrics_mem_grade_two w φ⟩⟩

public theorem quadrics_mem_quadricIdeal (w : M →ₗ[k] M →ₗ[k] N) (φ : Dual k N) :
    quadrics w φ ∈ (quadricIdeal w).toIdeal :=
  Ideal.subset_span ⟨φ, rfl⟩

end IntrinsicQuadrics
end V14Formalization
