/-
Copyright (c) 2026 V14Formalization contributors.
Released under Apache 2.0 license.
-/
module

public import V14Formalization.IntrinsicQuadrics
public import Mathlib.LinearAlgebra.ExteriorPower.Basis
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Grading
public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Functor

/-!
# `V₁₄` as a closed subscheme of `ℙ(M)`, with no basis

`V₁₄ = {[ω] ∈ ℙ(M) : ω ∧ ω = 0}` for a subspace `M ⊆ ⋀²U`.  Everything here is
built from three canonical ingredients and nothing else:

* the wedge pairing `⋀²U →ₗ ⋀²U →ₗ ⋀⁴U`, which is Mathlib's
  `DirectSum.gMulLHom` on the graded pieces of the exterior algebra;
* `IntrinsicQuadrics.quadricIdeal`, the homogeneous ideal of `Sym (M*)` it
  generates;
* `GradedQuotient` + `AlgebraicGeometry.Proj.map`, which turn that ideal into a
  scheme with a morphism to the ambient `ℙ(M) = Proj (Sym (M*))`.

No basis of `U`, no basis of `⋀²U`, no Plücker coordinates and no matrix
appear.

The subspace is presented as a module `M` together with a linear map
`incl : M →ₗ ⋀²U` rather than as a `Submodule`, so that instantiating at a
`Submodule` does not force the caller through the `Submodule.addCommMonoid` /
`Submodule.addCommGroup.toAddCommMonoid` diamond.
-/

noncomputable section

universe u

open Module AlgebraicGeometry SymmetricAlgebra

namespace V14Formalization
namespace IntrinsicV14

variable (k U : Type u) [Field k] [AddCommGroup U] [Module k U] [FiniteDimensional k U]
  [Module.Free k U]

/-- The wedge product of two bivectors, valued in `⋀⁴`.  This is the graded
multiplication of the exterior algebra in degrees `2 + 2 = 4`. -/
@[expose] public def wedgePairing :
    ↥(⋀[k]^2 U) →ₗ[k] ↥(⋀[k]^2 U) →ₗ[k] ↥(⋀[k]^4 U) :=
  DirectSum.gMulLHom k (fun n => ⋀[k]^n U)

omit [FiniteDimensional k U] [Module.Free k U] in
public theorem coe_wedgePairing (x y : ↥(⋀[k]^2 U)) :
    ((wedgePairing k U x y : ↥(⋀[k]^4 U)) : ExteriorAlgebra k U) =
      (x : ExteriorAlgebra k U) * (y : ExteriorAlgebra k U) :=
  rfl

variable {M : Type u} [AddCommGroup M] [Module k M] [FiniteDimensional k M]
  (incl : M →ₗ[k] ↥(⋀[k]^2 U))

/-- The wedge pairing pulled back to `M` along `incl`. -/
@[expose] public def wedgeOn : M →ₗ[k] M →ₗ[k] ↥(⋀[k]^4 U) :=
  (wedgePairing k U).compl₁₂ incl incl

omit [FiniteDimensional k U] [Module.Free k U] [FiniteDimensional k M] in
public theorem wedgeOn_apply (x y : M) :
    wedgeOn k U incl x y = wedgePairing k U (incl x) (incl y) := rfl

/-- The homogeneous ideal of `Sym (M*)` generated by the `⋀⁴`-components of
`ω ↦ ω ∧ ω`.  For `dim U = 6` these are the 15 Plücker quadrics. -/
@[expose] public def pluckerIdeal :
    HomogeneousIdeal (SymmetricAlgebra.grade k (Dual k M)) :=
  IntrinsicQuadrics.quadricIdeal (wedgeOn k U incl)

/-- The homogeneous coordinate ring of `V₁₄`, graded. -/
@[expose] public def coordinateRing :
    ℕ → Submodule k (SymmetricAlgebra k (Dual k M) ⧸ (pluckerIdeal k U incl).toIdeal) :=
  GradedQuotient.grading (SymmetricAlgebra.grade k (Dual k M)) (pluckerIdeal k U incl)

public instance : GradedAlgebra (coordinateRing k U incl) :=
  GradedQuotient.gradedAlgebraQuotient _ _

/-- **`V₁₄`, intrinsically.**  `Proj` of the quotient of `Sym (M*)` by the
Plücker quadrics. -/
@[expose] public def scheme : Scheme.{u} :=
  Proj (coordinateRing k U incl)

/-- The closed embedding of `V₁₄` into the ambient projective space `ℙ(M)`. -/
@[expose] public def toAmbient :
    scheme k U incl ⟶ Proj (SymmetricAlgebra.grade k (Dual k M)) :=
  Proj.map (GradedQuotient.mkGraded _ (pluckerIdeal k U incl))
    (GradedQuotient.irrelevant_le_map_mkGraded _ (pluckerIdeal k U incl))

end IntrinsicV14
end V14Formalization
