/-
Copyright (c) 2026 V14Formalization contributors.
Released under Apache 2.0 license.
-/
import V14Formalization.V14Application
import V14Formalization.Ord11CharacterSum
import V14Formalization.ResidualNotInM
import V14Formalization.ProjectiveAwayNaturality
import V14Formalization.ProjectiveFamilyFieldPoint
import V14Formalization.SchemeEquivariantSpecialization
import V14Formalization.SchemeFunctionFieldPrecomp
import V14Formalization.SchemeFunctionFieldNaturality
import V14Formalization.SchemeRationalConstancy
import V14Formalization.EllipticPolynomialConstancy
import V14Formalization.LinearNormalEquivariant
import V14Formalization.LinearNormalProjectiveChart
import V14Formalization.XAdicSemidirectAction
import V14Formalization.LinearNormalActionReduction
import V14Formalization.SemidirectChartIntegration
import V14Formalization.CorrectedBirationalField
import V14Formalization.LinearNormalOrderedPresentation
import V14Formalization.GenericCharts
import V14Formalization.CorrectedOrderedProjectiveChart
import V14Formalization.PointwiseSemidirect
import V14Formalization.ActionSpecific
import V14Formalization.CorrectedOrderedConstructor
import V14Formalization.BlockSemidirectConstructor
import V14Formalization.BlockSourceFieldMap
import V14Formalization.BlockNormalSigma
import V14Formalization.FaithfulHeadlineReduction
import V14Formalization.HeadlineStatement
import V14Formalization.CorrectedSourceFunctionFieldRatio
import V14Formalization.V14SchemeModel
import V14Formalization.V14SchemeBaseChange
import V14Formalization.BiprojectiveIntegral
import V14Formalization.BiprojectiveFunctionFieldProjection
import V14Formalization.BiprojectiveActionFunctionField
import V14Formalization.BiprojectiveFunctionFieldRows
import V14Formalization.UniversalNormalDivisor
import V14Formalization.PlusMinusBlockMatrix
import V14Formalization.V14FixedPointSegreBridge
import V14Formalization.V14FieldPointReconstruction
import V14Formalization.ProjectiveDiagonalAction
import V14Formalization.SchemeFixedProjectiveCoordinates
import V14Formalization.UniversalSigmaDiagonal
import V14Formalization.V14FixedByAmbientPoint
import V14Formalization.V14FixedPointEquations
import V14Formalization.ProjectiveEigenvectorReduction
import V14Formalization.V14ProjectorEigenspaceFactorization
import V14Formalization.V14CarrierDimensionFactorization
import V14Formalization.V14FixedPointCarrierDimensionFactorization
import V14Formalization.D12SigmaCarrier
import V14Formalization.D12SigmaCarrierConcrete
import V14Formalization.V14FixedPointCarrierConcrete
import V14Formalization.V14FixedPointCarrierFactorization
import V14Formalization.V14D12FixedPointExclusion
import V14Formalization.V14D12CertificateExclusion
import V14Formalization.WeierstrassSchemeDescent
import V14Formalization.MvFracConstantField
import V14Formalization.BinaryQuadraticDescent
import V14Formalization.D12SigmaMinusConcrete
import V14Formalization.D12SigmaMinusDescent
import V14Formalization.FaithfulHeadline
import V14Formalization.ProjectiveGVariety
import V14Formalization.V14FixedRationalConstancy
import V14Formalization.D12SigmaPlusDescent
import V14Formalization.KernelLineDescent
import V14Formalization.D12PolynomialEvaluation
import V14Formalization.D12U6PolynomialSeal
import V14Formalization.D12CompoundR
import V14Formalization.D12CompoundF
import V14Formalization.D12ProjectorReduction
import V14Formalization.D12RestrictedProjector
import V14Formalization.D12ActionCoreCertificate
import V14Formalization.D12CertificateK

/-!
# Kernel trust guards

These checks fail during elaboration when an audited result depends on anything
other than Lean's standard classical axioms.  In particular, they reject
unfinished proofs and per-call axioms introduced by the native evaluator.
-/

open Lean Elab Command in
/-- Fail unless the named declaration depends only on the standard classical axioms. -/
elab "#guard_kernel_checked " id:ident : command => do
  let n ← liftCoreM <| realizeGlobalConstNoOverloadWithInfo id
  let axs ← liftCoreM <| collectAxioms n
  let allowed : Array Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let bad := axs.filter fun a => !allowed.contains a
  unless bad.isEmpty do
    throwError "{n} was expected to be kernel-checked but depends on: {bad}"

namespace V14Formalization

-- The abstract operational endpoints are currently kernel-checked.
#guard_kernel_checked centralizerObstruction
#guard_kernel_checked centralizerObstruction_one_rep
#guard_kernel_checked noDegenerates_of_centerless_involution
#guard_kernel_checked V14App.V14_no_equivariant_map_from_faithful_rep
#guard_kernel_checked V14App.V14_not_weakly_versal
#guard_kernel_checked V14App.V14_not_GUnirational

-- Load-bearing M-cut gates.
#guard_kernel_checked Ord11CharacterSum.finrank_Msub_eq_ten
#guard_kernel_checked ResidualNotInM.residual_plucker_not_mem_Msub_of_model_match

-- Imported projective-geometry infrastructure and unconditional naturality.
#guard_kernel_checked AlgebraicGeometry.Proj.map_toSpecZero
#guard_kernel_checked BConicBundleMultisections.mapLinearSubst_toSpec
#guard_kernel_checked SchemeGeometry.familyIdeal_eq_of_span_eq
#guard_kernel_checked SchemeGeometry.projectiveZeroLocusIdeal_comap_mapLinearSubst_of_away_restriction
#guard_kernel_checked SchemeGeometry.projectiveZeroLocusIdeal_comap_awayι
#guard_kernel_checked SchemeGeometry.projectiveZeroLocusIdeal_comap_mapLinearSubst
#guard_kernel_checked SchemeGeometry.projectiveZeroLocusFamilyIdeal_comap_mapLinearSubst_aeval
#guard_kernel_checked SchemeGeometry.projectiveZeroLocusFamilyIdeal_comap_mapLinearSubst_aeval_of_single
#guard_kernel_checked SchemeGeometry.comap_le_projectiveZeroLocusFamilyIdeal_forall_of_span_le
#guard_kernel_checked SchemeGeometry.isInvariantIdeal_of_comap_le
#guard_kernel_checked SchemeGeometry.standardChartAlgebraPoint_appTop_hypersurfaceChartΓIso
#guard_kernel_checked SchemeGeometry.standardChartEvalAlgebra_hypersurfaceChartEquation
#guard_kernel_checked SchemeGeometry.aeval_eq_zero_of_projectiveZeroLocusIdeal_le_normalizedPoint_ker
#guard_kernel_checked SchemeGeometry.eval_map_eq_zero_of_projectiveZeroLocusFamily_point

-- The actual character projector in the sealed Plücker coordinates.
#guard_kernel_checked V14SchemeModel.projectorMatrix_idempotent
#guard_kernel_checked V14SchemeModel.projectorMatrix_commutes
#guard_kernel_checked V14SchemeModel.projectorLinearCuts_vanish_iff_mem_Msub
#guard_kernel_checked PluckerNaturality.span_aeval_pluckerQuadric_compound_le
#guard_kernel_checked V14SchemeModel.plucker_span_aeval_lambda2_le
#guard_kernel_checked V14SchemeModel.v14Ideal_naturality
#guard_kernel_checked V14SchemeModel.invariantIdeal_of_plucker
#guard_kernel_checked V14SchemeModel.action_of_plucker
#guard_kernel_checked V14SchemeModel.invariantIdeal
#guard_kernel_checked V14SchemeModel.action
#guard_kernel_checked V14SchemeModel.actionOver
#guard_kernel_checked V14SchemeModel.actionOver_carrier
#guard_kernel_checked V14SchemeModel.action_hom_v14Schemeι
#guard_kernel_checked V14SchemeModel.actionOver_hom_v14Schemeι
#guard_kernel_checked V14SchemeModel.fixed_comp_v14Schemeι
#guard_kernel_checked V14SchemeModel.actionOver_isProper
#guard_kernel_checked V14SchemeModel.actionOverBaseChange
#guard_kernel_checked V14SchemeModel.actionOverBaseChange_carrier
#guard_kernel_checked V14SchemeModel.actionOverBaseChange_isProper

-- Structural evaluation of the generated D12 polynomial certificate.
#guard_kernel_checked D12PolynomialEvaluation.evalMatrixAt_mul
#guard_kernel_checked D12PolynomialEvaluation.evalMatrixAt_left_inverse
#guard_kernel_checked D12PolynomialEvaluation.evalMatrixAt_entry_eq_zero_of_entry_eq_zero
#guard_kernel_checked D12PolynomialEvaluation.evalMatrixK_left_inverse
#guard_kernel_checked D12PolynomialEvaluation.evalMatrixAt_R_mul_B_eq_B_mul_RM
#guard_kernel_checked D12PolynomialEvaluation.evalMatrixK_R_mul_B_eq_B_mul_RM
#guard_kernel_checked D12PolynomialEvaluation.evalMatrixAt_F_mul_B_eq_B_mul_SM
#guard_kernel_checked D12PolynomialEvaluation.evalMatrixK_F_mul_B_eq_B_mul_SM
#guard_kernel_checked D12PolynomialEvaluation.evalMatrixAt_extension_eq_map_evalMatrixK
#guard_kernel_checked D12PolynomialEvaluation.map_evalMatrixK_R_mul_B_eq_B_mul_RM
#guard_kernel_checked D12PolynomialEvaluation.map_evalMatrixK_F_mul_B_eq_B_mul_SM
#guard_kernel_checked D12U6Fourier.toMatrix_Seven_eq_S6
#guard_kernel_checked D12U6Semantic.actualU6_apply_eq_directValue
#guard_kernel_checked D12U6Semantic.eval_directEntryPoly
#guard_kernel_checked D12U6PolynomialSeal.Phi11_eq_WeilRep
#guard_kernel_checked D12U6PolynomialSeal.eval_R6_entry
#guard_kernel_checked D12U6PolynomialSeal.evalMatrixK_R6_eq_actualU6
#guard_kernel_checked D12CompoundR.evalMatrixAt_compound2Lex
#guard_kernel_checked D12CompoundR.evalMatrixK_R_eq_compound_R6
#guard_kernel_checked D12CompoundR.evalMatrixK_R_eq_compound_actualU6
#guard_kernel_checked D12CompoundR.actualRot_eq_compound_actualU6
#guard_kernel_checked D12CompoundR.evalMatrixK_R_eq_actualRot
#guard_kernel_checked D12F6Semantic.actualF6_eq_wordMatrix
#guard_kernel_checked D12F6Semantic.actualF6_apply_eq_directValue
#guard_kernel_checked D12F6PolynomialSeal.evalMatrixK_F6_eq_actualF6
#guard_kernel_checked D12CompoundF.evalMatrixK_F_eq_compound_F6
#guard_kernel_checked D12CompoundF.actualRefl_eq_compound_actualF6
#guard_kernel_checked D12CompoundF.evalMatrixK_F_eq_actualRefl
#guard_kernel_checked D12GeneratorSRow0Nonzero.SrestrictedAction_row0_ne_zero
#guard_kernel_checked D12RestrictedProjector.eigenPower_injective
#guard_kernel_checked D12RestrictedProjector.eq_diagonal_const_of_two_commutants
#guard_kernel_checked D12RestrictedProjector.restrictedProjector_eq_one
#guard_kernel_checked D12RestrictedProjector.projector_factor
#guard_kernel_checked D12ActionCoreCertificate.ActionCore.toCertificate
#guard_kernel_checked D12ActionCoreCertificate.actionCore

-- Proper specialization and scheme-theoretic fixed-locus landing.  These are
-- generic endpoints; the V14 application still has to construct the concrete
-- equivariant normal valuation data.
#guard_kernel_checked SchemeGeometry.EquivariantRationalMap.res
#guard_kernel_checked AlgebraicGeometry.Scheme.Hom.functionFieldMap
#guard_kernel_checked AlgebraicGeometry.Scheme.RationalMap.fromFunctionField_comp_toRationalMap
#guard_kernel_checked AlgebraicGeometry.Scheme.actionFunctionFieldMap
#guard_kernel_checked AlgebraicGeometry.Scheme.actionPrecomp_fromFunctionField_generic
#guard_kernel_checked SchemeGeometry.NormalValuationData.specialFiberMap_natural
#guard_kernel_checked SchemeGeometry.EquivariantNormalValuationData.specialize
#guard_kernel_checked SchemeGeometry.EquivariantNormalValuationData.specializeToCentralizerFixedBy
#guard_kernel_checked SchemeGeometry.EquivariantNormalValuationData.specializeToCentralizerFixedBy_of_functionField
#guard_kernel_checked SchemeGeometry.EquivariantNormalValuationData.noEquivariantRationalMap_of_noFixedSpecialization
#guard_kernel_checked SchemeGeometry.EquivariantNormalValuationData.noEquivariantRationalMap_of_noFixedSpecialization_of_functionField
#guard_kernel_checked SchemeGeometry.actionPrecomp_constant
#guard_kernel_checked SchemeGeometry.rationalMapIsConstantOver_of_fromFunctionField_descends
#guard_kernel_checked SchemeGeometry.rationalMapIsConstantOver_fixedBy_of_comp_descends
#guard_kernel_checked SchemeGeometry.noEquivariantRationalMap_of_constant
#guard_kernel_checked SchemeGeometry.noEquivariantRationalMap_of_constant_section
#guard_kernel_checked SchemeGeometry.EquivariantNormalValuationData.noEquivariantRationalMap_of_constant_fixedSpecialization
#guard_kernel_checked SchemeGeometry.EquivariantNormalValuationData.noEquivariantRationalMap_of_constant_fixedSpecialization_section
#guard_kernel_checked EllipticPolynomialConstancy.polynomial_xy_constant_of_short_weierstrass_over_field
#guard_kernel_checked EllipticPolynomialConstancy.ratfunc_xy_constant_of_unit_denominators
#guard_kernel_checked EllipticPolynomialConstancy.ratfunc_xy_constant_of_short_weierstrass
#guard_kernel_checked EllipticPolynomialConstancy.ratfunc_coordinates_constant_of_short_weierstrass_equation
#guard_kernel_checked EllipticPolynomialConstancy.short_weierstrass_point_baseChange_ratfunc_surjective
#guard_kernel_checked EllipticPolynomialConstancy.ratfunc_xy_constant_of_split_cubic_square_over_field
#guard_kernel_checked EllipticPolynomialConstancy.mvFractionSuccRingEquiv
#guard_kernel_checked EllipticPolynomialConstancy.mvfrac_xy_constant_of_split_cubic_square
#guard_kernel_checked EllipticPolynomialConstancy.mvfrac_coordinates_constant_of_short_weierstrass_equation
#guard_kernel_checked EllipticPolynomialConstancy.short_weierstrass_point_baseChange_mvfrac_surjective
#guard_kernel_checked EllipticPolynomialConstancy.short_weierstrass_point_baseChange_mvfrac_fin4_surjective
#guard_kernel_checked EllipticPolynomialConstancy.short_weierstrass_point_baseChange_of_fin4_algEquiv_surjective
#guard_kernel_checked SchemeGeometry.linearNormalDataOfChart
#guard_kernel_checked SchemeGeometry.linearNormalEquivariantDataOfChart
#guard_kernel_checked SchemeGeometry.linearNormalEquivariantDataOfChart_of_actionFunctionFieldMap
#guard_kernel_checked SchemeGeometry.projectiveFiveLinearNormalFunctionFieldEquiv
#guard_kernel_checked SchemeGeometry.biprojectiveTwoTwoFunctionFieldEquiv
#guard_kernel_checked SchemeGeometry.shortWeierstrassPoint_baseChange_biprojectiveTwoTwo_surjective
#guard_kernel_checked SchemeGeometry.projectiveFiveLinearNormal_generic_toBase
#guard_kernel_checked SchemeGeometry.biprojectiveTwoTwoLinearNormal_special_toBase
#guard_kernel_checked SchemeGeometry.linearNormalEquivariantDataOfProjectiveBiprojectiveCharts

-- Structural semidirect action on the explicit X-adic normal valuation.
#guard_kernel_checked SchemeGeometry.xAdicSemidirectPolynomialAction
#guard_kernel_checked SchemeGeometry.xAdicSemidirectRatFuncAction
#guard_kernel_checked SchemeGeometry.xAdicRatFuncEquiv_mem_iff
#guard_kernel_checked SchemeGeometry.xAdicSemidirectValuationAction
#guard_kernel_checked SchemeGeometry.xAdicSemidirect_fraction_ring
#guard_kernel_checked SchemeGeometry.xAdicSemidirect_residue_ring
#guard_kernel_checked SchemeGeometry.xAdicSemidirect_base_ring

-- Transport from the X-adic model to the actual projective carriers.
#guard_kernel_checked SchemeGeometry.xAdicRestrictAction
#guard_kernel_checked SchemeGeometry.xAdicRestrictAction_residue_ring_of_constants
#guard_kernel_checked SchemeGeometry.conjugateRingAction
#guard_kernel_checked SchemeGeometry.functionFieldAction_fixes_base_of_fromFunctionField
#guard_kernel_checked SchemeGeometry.functionFieldAction_fixes_base
#guard_kernel_checked SchemeGeometry.orderedPlusMinusEquivariantNormalData
#guard_kernel_checked SchemeGeometry.semidirectProjectiveFive_chartModel
#guard_kernel_checked SchemeGeometry.semidirectBiprojectiveTwoTwo_chartModel

-- Generic projective/biprojective charts used by the corrected ordered package.
#guard_kernel_checked SchemeGeometry.projectiveGeneralFunctionFieldEquiv
#guard_kernel_checked SchemeGeometry.projectiveGeneralFunctionFieldEquiv_base
#guard_kernel_checked SchemeGeometry.projectiveGeneralBaseToFunctionField_eq
#guard_kernel_checked SchemeGeometry.biprojectiveGeneralFunctionFieldEquiv
#guard_kernel_checked SchemeGeometry.biprojectiveGeneralFunctionFieldEquiv_base
#guard_kernel_checked SchemeGeometry.biprojectiveGeneralBaseToFunctionField_eq
#guard_kernel_checked SchemeGeometry.biprojectiveLinearNormal_special_toBase

-- Corrected ordered birational and function-field presentations.
#guard_kernel_checked SchemeGeometry.ambientToOrderedNormalFieldHom_surjective
#guard_kernel_checked SchemeGeometry.orderedNormalToAmbientFieldEquiv
#guard_kernel_checked SchemeGeometry.orderedNormalToAmbientFieldEquiv_X_normal
#guard_kernel_checked SchemeGeometry.orderedNormalToAmbientFieldEquiv_X_plus
#guard_kernel_checked SchemeGeometry.orderedNormalToAmbientFieldEquiv_X_tail
#guard_kernel_checked SchemeGeometry.orderedCoordinateFieldToLinearNormalHom_surjective
#guard_kernel_checked SchemeGeometry.linearNormalToOrderedCoordinateFieldEquiv
#guard_kernel_checked SchemeGeometry.linearNormalToOrderedCoordinateFieldEquiv_X_normal
#guard_kernel_checked SchemeGeometry.linearNormalToOrderedCoordinateFieldEquiv_C_plus
#guard_kernel_checked SchemeGeometry.linearNormalToOrderedCoordinateFieldEquiv_C_tail
#guard_kernel_checked SchemeGeometry.linearNormalToOrderedCoordinateFieldEquiv_base
#guard_kernel_checked SchemeGeometry.correctedOrderedLinearNormalFunctionFieldEquiv
#guard_kernel_checked SchemeGeometry.correctedOrderedLinearNormalFunctionFieldEquiv_X
#guard_kernel_checked SchemeGeometry.correctedOrderedLinearNormalFunctionFieldEquiv_C_plus
#guard_kernel_checked SchemeGeometry.correctedOrderedLinearNormalFunctionFieldEquiv_C_tail
#guard_kernel_checked SchemeGeometry.correctedOrderedLinearNormalFunctionFieldEquiv_base
#guard_kernel_checked SchemeGeometry.correctedOrderedLinearNormal_generic_toBase

-- Pointwise semidirect transport and the block-matrix normal multiplier.
#guard_kernel_checked SchemeGeometry.actionFunctionFieldMap_fixes_base
#guard_kernel_checked SchemeGeometry.residualEquivOfAction_base
#guard_kernel_checked SchemeGeometry.semidirectElementOfExceptionalAction_exceptional_field_map
#guard_kernel_checked SchemeGeometry.linearEquivariantNormalDataOfPointwiseSemidirect
#guard_kernel_checked SchemeGeometry.pointwiseSemidirectExceptionalEquiv_eq_one_of_right_eq_one
#guard_kernel_checked SchemeGeometry.linearEquivariantNormalDataOfPointwiseSemidirect_exceptional_identity
#guard_kernel_checked SchemeGeometry.blockNormalMultiplier_sigma
#guard_kernel_checked SchemeGeometry.pointwiseSemidirectSourceEquiv_eq_actionFunctionFieldMap_of_residual_generators
#guard_kernel_checked SchemeGeometry.pointwiseSemidirectSourceEquiv_eq_actionFunctionFieldMap_of_residual_C_X_T
#guard_kernel_checked SchemeGeometry.orderedBlockSemidirectElement_exceptional_field_map
#guard_kernel_checked SchemeGeometry.orderedBlockSemidirectElement_right_map
#guard_kernel_checked SchemeGeometry.orderedBlockSemidirectElement_right_plusGenerator
#guard_kernel_checked SchemeGeometry.orderedBlockSemidirectElement_right_minusGenerator
#guard_kernel_checked SchemeGeometry.orderedBlockSemidirectElement_right_C_base
#guard_kernel_checked SchemeGeometry.correctedOrdered_sourceFieldMap_of_residual_X_T
#guard_kernel_checked SchemeGeometry.correctedSource_coefficient_plusGenerator
#guard_kernel_checked SchemeGeometry.correctedSource_coefficient_minusGenerator
#guard_kernel_checked SchemeGeometry.correctedSource_parameter
#guard_kernel_checked SchemeGeometry.correctedSource_coefficient_generator
#guard_kernel_checked SchemeGeometry.correctedOrdered_sourceFieldMap
#guard_kernel_checked SchemeGeometry.orderedPlusMinusEquivariantNormalDataOfPointwiseSemidirect
#guard_kernel_checked SchemeGeometry.orderedPlusMinusEquivariantNormalDataOfNormalMultiplier
#guard_kernel_checked SchemeGeometry.orderedPlusMinusEquivariantNormalDataOfBlocks
#guard_kernel_checked SchemeGeometry.orderedPlusMinusEquivariantNormalDataOfCorrectedChart
#guard_kernel_checked SchemeGeometry.orderedPlusMinusEquivariantNormalDataOfCorrectedChartActual
#guard_kernel_checked SchemeGeometry.orderedPlusMinusEquivariantNormalDataOfPointwiseSemidirect_sigma

-- Scheme/function-field compatibility for the corrected projective source chart.
#guard_kernel_checked AlgebraicGeometry.Scheme.Hom.functionFieldMap_comp
#guard_kernel_checked AlgebraicGeometry.Scheme.Hom.functionFieldMap_congr
#guard_kernel_checked AlgebraicGeometry.Scheme.Hom.functionFieldMap_germToFunctionField
#guard_kernel_checked SchemeGeometry.projectiveGeneralFunctionFieldEquiv_algebraMap
#guard_kernel_checked SchemeGeometry.mapLinearSubst_appLE_awayToSection
#guard_kernel_checked SchemeGeometry.awayMap_linearSubst_normalizedCoordinate
#guard_kernel_checked SchemeGeometry.standardChartGammaIsoTop_hom_GammaSpecIso_inv
#guard_kernel_checked SchemeGeometry.mapLinearSubst_functionFieldMap_projectiveGeneral_X
#guard_kernel_checked SchemeGeometry.projectiveActionOver_actionFunctionFieldMap_X
#guard_kernel_checked SchemeGeometry.correctedOrderedPlusMinusSource_actionFunctionFieldMap_X
#guard_kernel_checked SchemeGeometry.correctedSource_actionFunctionFieldMap_C_base

-- Function-field coordinates of the two biprojective projections.
#guard_kernel_checked SchemeGeometry.GammaIsoTop_inv_eq_appLE
#guard_kernel_checked SchemeGeometry.biprojectiveGeneralFunctionFieldEquiv_algebraMap
#guard_kernel_checked SchemeGeometry.biprojective_standardChart_fst_appTop
#guard_kernel_checked SchemeGeometry.biprojective_standardChart_snd_appTop
#guard_kernel_checked SchemeGeometry.biprojectiveGeneralFunctionFieldEquiv_X_inl
#guard_kernel_checked SchemeGeometry.biprojectiveGeneralFunctionFieldEquiv_X_inr

-- Function-field naturality and row formulas for the diagonal exceptional action.
#guard_kernel_checked SchemeGeometry.diagonalPullbackAction_functionFieldMap_fst
#guard_kernel_checked SchemeGeometry.diagonalPullbackAction_functionFieldMap_snd
#guard_kernel_checked SchemeGeometry.functionFieldMap_comp_functionFieldBaseRingHom
#guard_kernel_checked SchemeGeometry.biprojective_fst_functionFieldMap_base
#guard_kernel_checked SchemeGeometry.biprojective_snd_functionFieldMap_base
#guard_kernel_checked SchemeGeometry.projectiveActionOver_actionFunctionFieldMap_X_row
#guard_kernel_checked SchemeGeometry.biprojectiveFunctionFieldEquiv_plusRowForm
#guard_kernel_checked SchemeGeometry.biprojectiveFunctionFieldEquiv_minusRowForm
#guard_kernel_checked SchemeGeometry.plusMinusPullback_fst_functionFieldMap_div
#guard_kernel_checked SchemeGeometry.plusMinusPullback_snd_functionFieldMap_div
#guard_kernel_checked SchemeGeometry.normalDivisorAction_functionFieldMap_plusGenerator
#guard_kernel_checked SchemeGeometry.normalDivisorAction_functionFieldMap_minusGenerator

-- Local glue over Problem B's imported chart and overlap APIs.
#guard_kernel_checked BConicBundleMultisections.BiprojectiveSpace.standardChartIntegral
#guard_kernel_checked BConicBundleMultisections.BiprojectiveSpace.standardChartRanges_pairwise
#guard_kernel_checked BConicBundleMultisections.BiprojectiveSpace.isIntegral

-- The actual universal normal-divisor carrier and centralizer action.
#guard_kernel_checked SchemeGeometry.ambientMatrixRepresentation
#guard_kernel_checked SchemeGeometry.ambientProjectiveActionOver
#guard_kernel_checked SchemeGeometry.ambientProjectiveActionOver_isIntegral
#guard_kernel_checked SchemeGeometry.normalDivisorActionOver
#guard_kernel_checked SchemeGeometry.normalDivisorActionOver_isIntegral
#guard_kernel_checked SchemeGeometry.plusMinusLinearEquiv_centralizer
#guard_kernel_checked SchemeGeometry.plusMinusAmbientBasis
#guard_kernel_checked SchemeGeometry.exists_plus_minus_projective_bases
#guard_kernel_checked SchemeGeometry.exists_ambient_projective_basis
#guard_kernel_checked SchemeGeometry.plusMinusLinearEquiv_conjugates_centralizer
#guard_kernel_checked SchemeGeometry.plusMinusMappedBasis_toMatrix
#guard_kernel_checked SchemeGeometry.plusMinusAmbientBasis_toMatrix
#guard_kernel_checked SchemeGeometry.ambientMatrixRepresentation_centralizer_block
#guard_kernel_checked SchemeGeometry.plusMinusMappedBasis_toMatrix_general
#guard_kernel_checked SchemeGeometry.plusMinusAmbientBasis_toMatrix_general
#guard_kernel_checked SchemeGeometry.ambientMatrixRepresentation_centralizer_block_general
#guard_kernel_checked SchemeGeometry.ambientMatrixRepresentation_sigma_diagonal
#guard_kernel_checked SchemeGeometry.exists_plusMinusBasis_sigma_diagonal
#guard_kernel_checked SchemeGeometry.exists_normalizedCoordinates_support_of_sigma_fixed
#guard_kernel_checked SchemeGeometry.ambientPointOfV14FixedBy_isOver_and_fixed
#guard_kernel_checked SchemeGeometry.v14FixedBy_schemePoint_ambient_isOver_and_fixed
#guard_kernel_checked SchemeGeometry.map_projectorLinearCut
#guard_kernel_checked SchemeGeometry.exists_normalizedCoordinates_equations_of_v14FixedBy
#guard_kernel_checked SchemeGeometry.exists_normalizedCoordinates_v14FixedBy_projector_fixed
#guard_kernel_checked SchemeGeometry.eval_map_linearSubst_eq_mappedMatrix_mulVec
#guard_kernel_checked SchemeGeometry.standardChartEvalAlgebra_linearSubstRatio
#guard_kernel_checked SchemeGeometry.standardChartEvalAlgebra_isLocalizationElem_linearSubst
#guard_kernel_checked SchemeGeometry.mappedMatrix_mulVec_normalizingCoordinate_ne_zero_of_fixed
#guard_kernel_checked SchemeGeometry.pointOfNormalizedCoordinatesAlgebra_comp_mapLinearSubst
#guard_kernel_checked SchemeGeometry.exists_eigenScalar_of_pointOfNormalizedCoordinatesAlgebra_fixed
#guard_kernel_checked SchemeGeometry.exists_eigenScalar_of_mapLinearSubst_fixed
#guard_kernel_checked SigmaProjectorLinearAlgebra.eigenvalue_eq_one_or_neg_one_of_involution
#guard_kernel_checked SigmaProjectorLinearAlgebra.plusProjector_mulVec_eq_self
#guard_kernel_checked SigmaProjectorLinearAlgebra.minusProjector_mulVec_eq_self
#guard_kernel_checked SigmaProjectorLinearAlgebra.eq_mulVec_mulVec_of_projector_fixed
#guard_kernel_checked SigmaProjectorLinearAlgebra.eq_plus_or_minus_carrier_of_projector_involution_eigenvector
#guard_kernel_checked SigmaProjectorLinearAlgebra.fin15_eq_plus6_or_minus4_carrier
#guard_kernel_checked SigmaProjectorLinearAlgebra.plusMinusCarrierMap_injective
#guard_kernel_checked SigmaProjectorLinearAlgebra.exists_plusMinusCarrier_coordinates
#guard_kernel_checked SigmaProjectorLinearAlgebra.exists_plus_or_minus_carrier_of_eigen
#guard_kernel_checked SchemeGeometry.exists_normalizedCoordinates_v14FixedBy_plus_or_minus_carrier_of_dimension
#guard_kernel_checked D12SigmaCarrier.Core.left_inverse_plus
#guard_kernel_checked D12SigmaCarrier.Core.left_inverse_minus
#guard_kernel_checked D12SigmaCarrier.Core.ambient_factor_plus
#guard_kernel_checked D12SigmaCarrier.Core.ambient_factor_minus
#guard_kernel_checked D12SigmaCarrier.Core.sigma_eigen_plus
#guard_kernel_checked D12SigmaCarrier.Core.sigma_eigen_minus
#guard_kernel_checked D12SigmaCarrierConcrete.evalMatrixK_Srestricted_reduced_poly
#guard_kernel_checked D12SigmaCarrierConcrete.plus_eigen_eval
#guard_kernel_checked D12SigmaCarrierConcrete.minus_eigen_eval
#guard_kernel_checked D12SigmaCarrierConcrete.plus_top
#guard_kernel_checked D12SigmaCarrierConcrete.minus_top
#guard_kernel_checked D12SigmaCarrierConcrete.core
#guard_kernel_checked SchemeGeometry.exists_normalizedCoordinates_v14FixedBy_concrete_plus_or_minus_carrier
#guard_kernel_checked SchemeGeometry.no_centralizer_fixed_section_of_certificate
#guard_kernel_checked SchemeGeometry.noEquivariantRationalMap_of_d12_certificate
#guard_kernel_checked SchemeGeometry.exists_normalizedCoordinates_v14FixedBy_plus_or_minus_carrier

-- The complete four-piece D12 certificate over the geometric base field.
#guard_kernel_checked D12PiecePPCertificate.certificate
#guard_kernel_checked D12PiecePACertificate.certificate
#guard_kernel_checked D12PieceAPCertificate.certificate
#guard_kernel_checked D12PieceAACertificate.certificate
#guard_kernel_checked D12CertificateK.certificate
#guard_kernel_checked D12CertificateK.certificate_P
#guard_kernel_checked D12CertificateK.certificate_R
#guard_kernel_checked D12CertificateK.certificate_F
#guard_kernel_checked SchemeGeometry.noEquivariantRationalMap_of_normal_specialization

-- The actual corrected normal chart has sigma-trivial residual action.
#guard_kernel_checked SchemeGeometry.exceptionalPlusRowForm_one_succ
#guard_kernel_checked SchemeGeometry.exceptionalMinusRowForm_neg_one_succ
#guard_kernel_checked SchemeGeometry.orderedBlockSemidirectElement_sigma_right_eq_one
#guard_kernel_checked SchemeGeometry.orderedPlusMinusEquivariantNormalDataOfCorrectedChartActual_sigma
#guard_kernel_checked SchemeGeometry.noEquivariantRationalMap_from_ambient_of_constancy

-- Structural reduction of the genuine rank-ten character projector.
#guard_kernel_checked PSLGenerators.closure_mk_Smat_Tmat
#guard_kernel_checked PSLGenerators.closure_mk_Smat_Tmat_pow_two
#guard_kernel_checked D12ProjectorReduction.mem_stabilizer_range_of_mul_eq
#guard_kernel_checked D12ProjectorReduction.all_mul_eq_of_two_generators
#guard_kernel_checked D12ProjectorReduction.idempotent_eq_one_of_trace_eq_card
#guard_kernel_checked D12ProjectorReduction.projectorMatrix_eq_character_sum
#guard_kernel_checked D12ProjectorReduction.projector_invariant_of_all_representation
#guard_kernel_checked D12ProjectorReduction.projector_invariant_of_standard_generators
#guard_kernel_checked D12ProjectorReduction.projector_invariant_of_standard_generators_pow_two
#guard_kernel_checked D12ProjectorReduction.projectorMatrix_trace
#guard_kernel_checked D12ProjectorReduction.projector_factor_of_invariant_trace

-- Point-level fixed-locus and Segre-to-cubic reductions.
#guard_kernel_checked FaithfulLinearRep.mem_plus_or_minus_projectiveStratum_of_fixed
#guard_kernel_checked exists_pureTensor_of_twoByTwoMinors_eq_zero
#guard_kernel_checked det_bilinearCoefficientMatrix_eq_zero
#guard_kernel_checked exists_pureTensor_and_det_eq_zero_of_linearSection
#guard_kernel_checked SchemeGeometry.normalizedCoordinates_eq_of_pointOfNormalizedCoordinatesAlgebra_eq
#guard_kernel_checked SchemeGeometry.fieldPoint_eq_pointOfMappedNormalizedResidueCoordinates
#guard_kernel_checked SchemeGeometry.exists_normalizedResidueCoordinates_for_fieldPoint
#guard_kernel_checked SchemeGeometry.standardChartι_comp_mapLinearSubst_diagonal
#guard_kernel_checked SchemeGeometry.diagonalChartHom_normalizedCoordinate_eq_self_of_eq
#guard_kernel_checked SchemeGeometry.diagonalChartHom_normalizedCoordinate_eq_neg_of_eq_neg
#guard_kernel_checked SchemeGeometry.exists_normalizedCoordinates_support_of_diagonal_sign_fixed
#guard_kernel_checked SchemeGeometry.exists_normalizedCoordinates_support_of_projectiveActionHom_fixed
#guard_kernel_checked WeierstrassSchemeDescent.affine_morphism_descends_of_point_baseChange_surjective
#guard_kernel_checked WeierstrassSchemeDescent.affine_morphism_descends_mvfrac
#guard_kernel_checked WeierstrassSchemeDescent.projective_weierstrass_triple_descends_of_pointBaseChange_surjective
#guard_kernel_checked WeierstrassSchemeDescent.projectivization_weierstrass_descends_of_pointBaseChange_surjective
#guard_kernel_checked WeierstrassSchemeDescent.projective_weierstrass_triple_descends_mvfrac
#guard_kernel_checked WeierstrassSchemeDescent.projectivization_weierstrass_descends_mvfrac
#guard_kernel_checked WeierstrassSchemeDescent.specMap_comp_pointOfNormalizedCoordinates
#guard_kernel_checked WeierstrassSchemeDescent.projectiveSpace_morphism_descends_weierstrass_mvfrac_of_coordinates
#guard_kernel_checked WeierstrassSchemeDescent.projectiveSpace_morphism_descends_weierstrass_mvfrac

#guard_kernel_checked MvFracConstantField.ratFunc_isAlgebraic_iff_constant
#guard_kernel_checked MvFracConstantField.mvFrac_isAlgebraic_iff_constant
#guard_kernel_checked MvFracConstantField.mvFrac_eq_constant_of_map_eq_constant
#guard_kernel_checked BinaryQuadraticDescent.binaryQuadratic_projective_descends_mvfrac
#guard_kernel_checked D12SigmaMinusConcrete.evalMatrixK_Bminus_poly
#guard_kernel_checked D12SigmaMinusConcrete.plucker_eq_evalQuadratic
#guard_kernel_checked D12SigmaMinusConcrete.linears_zero_of_quadrics
#guard_kernel_checked D12SigmaMinusConcrete.common_plucker_zero_parametric
#guard_kernel_checked D12SigmaMinusDescent.minusCarrier_commonPluckerZero_descends_mvfrac
#guard_kernel_checked D12SigmaMinusDescent.minusCarrier_ambient_descends_mvfrac
#guard_kernel_checked KernelLineDescent.kernelLine_descends_of_rank_eq_two
#guard_kernel_checked D12SigmaPlusDescent.plusCarrier_commonPluckerZero_descends_mvfrac
#guard_kernel_checked D12SigmaPlusDescent.plusCarrier_ambient_descends_mvfrac
#guard_kernel_checked SchemeGeometry.rationalMapIsConstantOver_v14FixedBy
#guard_kernel_checked SchemeGeometry.not_degenerates
#guard_kernel_checked SchemeGeometry.PlusMinusCoords.ofRep
#guard_kernel_checked SchemeGeometry.ambientOf
#guard_kernel_checked SchemeGeometry.ProjectiveGVariety.ofFaithfulRep
#guard_kernel_checked SchemeGeometry.noEquivariantRationalMap_from_ambient_of_plusMinusBases
#guard_kernel_checked SchemeGeometry.noEquivariantRationalMap_from_ambient
#guard_kernel_checked SchemeGeometry.noEquivariantRationalMap_projectiveGVariety

end V14Formalization
