kkbase = ZZ/100057;
omv = 1140_kkbase; kpv = 74361_kkbase; kmv = 63219_kkbase;
R = kkbase[c0,c1,c2,c3,c4,c5,c6,c7,c8,w];
om = omv; kp = kpv; km = kmv;
I = ideal(c0^3*kp + c3^3*km,3*c0^2*c1*kp + c0*c6^2 + 3*c3^2*c4*km + c3*c6^2,3*c0*c1^2*kp + c1*c6^2 + 3*c3*c4^2*km + c4*c6^2,c1^3*kp + c4^3*km,3*c0^2*c2*kp + c0*c7^2*om + 3*c3^2*c5*km - c3*c7^2*om - c3*c7^2,6*c0*c1*c2*kp - c0*c8^2*om - c0*c8^2 + c1*c7^2*om + c2*c6^2 + 6*c3*c4*c5*km + c3*c8^2*om - c4*c7^2*om - c4*c7^2 + c5*c6^2 + c6*c7*c8,3*c1^2*c2*kp - c1*c8^2*om - c1*c8^2 + 3*c4^2*c5*km + c4*c8^2*om,3*c0*c2^2*kp + c2*c7^2*om + 3*c3*c5^2*km - c5*c7^2*om - c5*c7^2,3*c1*c2^2*kp - c2*c8^2*om - c2*c8^2 + 3*c4*c5^2*km + c5*c8^2*om,c2^3*kp + c5^3*km);
print("CELL m=2 r=4 nvars=9 neqs=10");
print("dimI=" | toString dim I);
J = I + ideal(1 - w*c0);
print("EXACT-m coeff c0 -> " | (if J == ideal(1_R) then "cannot be nonzero (EMPTY)" else ("CAN be nonzero: dim=" | toString dim J)));
J = I + ideal(1 - w*c1);
print("EXACT-m coeff c1 -> " | (if J == ideal(1_R) then "cannot be nonzero (EMPTY)" else ("CAN be nonzero: dim=" | toString dim J)));
J = I + ideal(1 - w*c2);
print("EXACT-m coeff c2 -> " | (if J == ideal(1_R) then "cannot be nonzero (EMPTY)" else ("CAN be nonzero: dim=" | toString dim J)));
J = I + ideal(1 - w*c3);
print("EXACT-m coeff c3 -> " | (if J == ideal(1_R) then "cannot be nonzero (EMPTY)" else ("CAN be nonzero: dim=" | toString dim J)));
J = I + ideal(1 - w*c4);
print("EXACT-m coeff c4 -> " | (if J == ideal(1_R) then "cannot be nonzero (EMPTY)" else ("CAN be nonzero: dim=" | toString dim J)));
J = I + ideal(1 - w*c5);
print("EXACT-m coeff c5 -> " | (if J == ideal(1_R) then "cannot be nonzero (EMPTY)" else ("CAN be nonzero: dim=" | toString dim J)));
J = I + ideal(1 - w*c6);
print("EXACT-m coeff c6 -> " | (if J == ideal(1_R) then "cannot be nonzero (EMPTY)" else ("CAN be nonzero: dim=" | toString dim J)));
J = I + ideal(1 - w*c7);
print("EXACT-m coeff c7 -> " | (if J == ideal(1_R) then "cannot be nonzero (EMPTY)" else ("CAN be nonzero: dim=" | toString dim J)));
J = I + ideal(1 - w*c8);
print("EXACT-m coeff c8 -> " | (if J == ideal(1_R) then "cannot be nonzero (EMPTY)" else ("CAN be nonzero: dim=" | toString dim J)));
