/-
Copyright (c) 2026 BConicBundleMultisections contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BConicBundleMultisections contributors
-/
module

public import BConicBundleMultisections.Basic
public import BConicBundleMultisections.BinaryCubicDiscriminant
public import BConicBundleMultisections.BinaryCubicResidual
public import BConicBundleMultisections.BinaryResultant
public import BConicBundleMultisections.BiprojectiveAffineChart
public import BConicBundleMultisections.BiprojectiveAffineChartDegree
public import BConicBundleMultisections.BiprojectiveAffineChartJacobian
public import BConicBundleMultisections.BiprojectiveAffineJacobian
public import BConicBundleMultisections.BiprojectiveAffineZeroLocus
public import BConicBundleMultisections.BiprojectiveChartDimension
public import BConicBundleMultisections.BiprojectiveFiberNonempty
public import BConicBundleMultisections.BiprojectiveFiberPolynomial
public import BConicBundleMultisections.BiprojectiveFiberTangent
public import BConicBundleMultisections.BiprojectiveFiberTangentIncidence
public import BConicBundleMultisections.BiprojectiveNoWholeFiber
public import BConicBundleMultisections.BiprojectiveProjectionDominant
public import BConicBundleMultisections.BiprojectiveProjectionFiber
public import BConicBundleMultisections.BiprojectiveWholeFiberGradient
public import BConicBundleMultisections.BiprojectiveZeroLocus
public import BConicBundleMultisections.BiprojectiveZeroLocusClosedPoints
public import BConicBundleMultisections.BiprojectiveZeroLocusSmooth
public import BConicBundleMultisections.CoordinateLineResultant
public import BConicBundleMultisections.CubicQuadraticResultant
public import BConicBundleMultisections.DeterminantHomogeneous
public import BConicBundleMultisections.AffineSpaceProduct
public import BConicBundleMultisections.HomogeneousQuadraticEval
public import BConicBundleMultisections.MainTheorem
public import BConicBundleMultisections.MultisectionPrinciple
public import BConicBundleMultisections.MvPolynomialDimension
public import BConicBundleMultisections.MvPolynomialHomogeneousEvaluation
public import BConicBundleMultisections.PlaneCubicResidualIdentity
public import BConicBundleMultisections.PlaneCubicResidualLineMap
public import BConicBundleMultisections.PlaneCubicTangentForm
public import BConicBundleMultisections.PlaneCubicTangentResidual
public import BConicBundleMultisections.PointedConicRational
public import BConicBundleMultisections.ProjectiveCommonZero
public import BConicBundleMultisections.ProjectiveCoordinateNormalization
public import BConicBundleMultisections.ProjectiveHypersurfacePoints
public import BConicBundleMultisections.ProjectiveSpaceClosedPoints
public import BConicBundleMultisections.ProjectiveLineRestriction
public import BConicBundleMultisections.ProjectivePlane
public import BConicBundleMultisections.ProjectiveResidualPoint
public import BConicBundleMultisections.ProjectiveTangentHyperplane
public import BConicBundleMultisections.ResidualDivisor
public import BConicBundleMultisections.ProjectiveSpaceCoeffMap
public import BConicBundleMultisections.ResidualImage
public import BConicBundleMultisections.ResidualImageAffineParam
public import BConicBundleMultisections.ResidualImageAlgebraPoint
public import BConicBundleMultisections.ResidualImageRationalParam
public import BConicBundleMultisections.SpecializedConicFreeDir
public import BConicBundleMultisections.ResidualBaseChangeUnirational
public import BConicBundleMultisections.ResidualMultisectionDominant
public import BConicBundleMultisections.ResultantHomogeneous
public import BConicBundleMultisections.SchemeFiberClosedSubscheme
public import BConicBundleMultisections.TsenConic
public import BConicBundleMultisections.Unirationality
public import BConicBundleMultisections.UniversalResidualIdentity
public import BConicBundleMultisections.VerticalSurface

/-!
# BConicBundleMultisections

Formalization workspace for the tangent-residual proof that every smooth bidegree `(2, 3)`
threefold in `ℙ² × ℙ²` over an algebraically closed field of characteristic zero is unirational.
-/
