/-
Copyright (c) 2026 BConicBundleMultisections contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BConicBundleMultisections contributors
-/
module

public import BConicBundleMultisections.AlgebraicIndependenceJacobian
public import BConicBundleMultisections.Basic
public import BConicBundleMultisections.Bidegree23Example
public import BConicBundleMultisections.BiprojectiveSmoothCriterion
public import BConicBundleMultisections.BinaryCubicDiscriminant
public import BConicBundleMultisections.BinaryCubicResidual
public import BConicBundleMultisections.BinaryQuadraticNormalForm
public import BConicBundleMultisections.BinaryResultant
public import BConicBundleMultisections.BiprojectiveAffineChart
public import BConicBundleMultisections.BiprojectiveAffineChartDegree
public import BConicBundleMultisections.BiprojectiveAffineChartJacobian
public import BConicBundleMultisections.BiprojectiveAffineJacobian
public import BConicBundleMultisections.BiprojectiveAffineZeroLocus
public import BConicBundleMultisections.BiprojectiveChartDimension
public import BConicBundleMultisections.BiprojectiveFiberNonempty
public import BConicBundleMultisections.BiprojectiveFiberPolynomial
public import BConicBundleMultisections.BiprojectiveFiberTangent
public import BConicBundleMultisections.BiprojectiveFiberTangentIncidence
public import BConicBundleMultisections.BiprojectiveNoWholeFiber
public import BConicBundleMultisections.BiprojectiveProjectionDominant
public import BConicBundleMultisections.BiprojectiveProjectionFiber
public import BConicBundleMultisections.BiprojectiveWholeFiberGradient
public import BConicBundleMultisections.BiprojectiveZeroLocus
public import BConicBundleMultisections.BiprojectiveZeroLocusClosedPoints
public import BConicBundleMultisections.BiprojectiveZeroLocusSmooth
public import BConicBundleMultisections.ChartHomogenization
public import BConicBundleMultisections.CoordinateLineResultant
public import BConicBundleMultisections.CubicQuadraticResultant
public import BConicBundleMultisections.DeterminantHomogeneous
public import BConicBundleMultisections.AffineSpaceProduct
public import BConicBundleMultisections.GoodLine
public import BConicBundleMultisections.GoodLineExistence
public import BConicBundleMultisections.Standard.ResidualLineMapInjective
public import BConicBundleMultisections.HomogeneousQuadraticEval
public import BConicBundleMultisections.LinearSubstitution
public import BConicBundleMultisections.LinearSubstitutionNonsingular
public import BConicBundleMultisections.LinearCoordinateChange
public import BConicBundleMultisections.MainTheorem
public import BConicBundleMultisections.MainTheoremGuard
public import BConicBundleMultisections.MultisectionLine
public import BConicBundleMultisections.MultisectionPrinciple
public import BConicBundleMultisections.MvPolynomialDimension
public import BConicBundleMultisections.MvPolynomialHomogeneousEvaluation
public import BConicBundleMultisections.PlaneCubicResidualEquivariance
public import BConicBundleMultisections.PlaneCubicResidualIdentity
public import BConicBundleMultisections.PlaneCubicResidualTransport
public import BConicBundleMultisections.PlaneCubicResidualLineMap
public import BConicBundleMultisections.PlaneCubicTangentForm
public import BConicBundleMultisections.PlaneCubicTangentResidual
public import BConicBundleMultisections.PointedConicAffineModel
public import BConicBundleMultisections.PointedConicRational
public import BConicBundleMultisections.PointedConicRationalFamilies
public import BConicBundleMultisections.ProjectiveCommonZero
public import BConicBundleMultisections.ProjectiveCoordinateNormalization
public import BConicBundleMultisections.ProjectiveHypersurfacePoints
public import BConicBundleMultisections.ProjectiveSpaceAlgebraPoint
public import BConicBundleMultisections.ProjectiveSpaceChartDominance
public import BConicBundleMultisections.ProjectiveSpaceClosedPoints
public import BConicBundleMultisections.ProjectiveLineRestriction
public import BConicBundleMultisections.ProjectivePlane
public import BConicBundleMultisections.ProjectiveResidualPoint
public import BConicBundleMultisections.ProjectiveTangentHyperplane
public import BConicBundleMultisections.ResidualDivisor
public import BConicBundleMultisections.ProjectiveSpaceCoeffMap
public import BConicBundleMultisections.ResidualEquationLine
public import BConicBundleMultisections.ResidualHorizontalityLine
public import BConicBundleMultisections.ResidualLineBasePointFree
public import BConicBundleMultisections.ResidualLineNonconstant
public import BConicBundleMultisections.ResidualImage
public import BConicBundleMultisections.ResidualImageAffineParam
public import BConicBundleMultisections.ResidualImageAlgebraPoint
public import BConicBundleMultisections.ResidualImageRationalParam
public import BConicBundleMultisections.SpecializedConicFreeDir
public import BConicBundleMultisections.ResidualYCoordsPureT
public import BConicBundleMultisections.ResidualYFormVanishing
public import BConicBundleMultisections.ResidualComponent
public import BConicBundleMultisections.ResidualComponentAssembly
public import BConicBundleMultisections.ResidualComponentHorizontality
public import BConicBundleMultisections.ResidualYNonvanishing
public import BConicBundleMultisections.Standard.GenericSmoothness
public import BConicBundleMultisections.Standard.GenericPoint
public import BConicBundleMultisections.UnirationalTower
public import BConicBundleMultisections.ResidualBaseChangeUnirational
public import BConicBundleMultisections.ResidualMultisectionDominant
public import BConicBundleMultisections.ResultantHomogeneous
public import BConicBundleMultisections.SchemeFiberClosedSubscheme
public import BConicBundleMultisections.TsenConic
public import BConicBundleMultisections.Unirationality
public import BConicBundleMultisections.UniversalResidualIdentity
public import BConicBundleMultisections.VerticalSurface

/-!
# BConicBundleMultisections

Formalization workspace for the tangent-residual proof that every smooth bidegree `(2, 3)`
threefold in `ℙ² × ℙ²` over an algebraically closed field of characteristic zero is unirational.
-/
