import BConicBundleMultisections.MainTheorem

#print axioms
  BConicBundleMultisections.Standard.exists_actualG3G4LineSection_via_frameIncidence
#print axioms
  BConicBundleMultisections.targetRelationsProjectivelyIntegralAwayDiscriminant_of_smooth
#print axioms
  BConicBundleMultisections.targetRelationsResidualNegativeTwistGluingAwayDiscriminantOn
#print axioms
  BConicBundleMultisections.BiprojectiveSpace.residualEquationOn_mem_span_targetRelation_of_isIso_of_negativeTwist
#print axioms
  BConicBundleMultisections.hasUnirationalParametrization3_biprojectiveZeroLocus_of_projectivelyIntegralTargetRelations
#print axioms
  BConicBundleMultisections.hasUnirationalParametrization3_biprojectiveZeroLocus_of_actualG3G4LineSection
#print axioms
  BConicBundleMultisections.smooth_bidegree23_hasUnirationalParametrization_of_goodLineSection
#print axioms
  BConicBundleMultisections.hasUnirationalParametrization3_biprojectiveZeroLocus
#print axioms BConicBundleMultisections.smooth_bidegree23_hasUnirationalParametrization
#print axioms BConicBundleMultisections.smooth_bidegree23_isUnirationalOver
