"""CHECK 3 -- rem:toric_criterion (Duncan 3.12) and the two projective examples
that calibrate the conventions (ex:not_a_complex 3.13, ex:no_converse 4.8).

Local model: H finite abelian acts diagonally on A^I with characters chi_i,
i in I, which generate dual(H) (= toroidal form, def:toroidal(c)).  N = Z^I,
M its dual.  For a cone tau in a subdividing fan the tex asserts

    H_tau = intersection over m in tau^perp \\cap M of ker chi^m ,   chi^m = prod chi_i^{m_i}

and, for |I| = 2 and a WALL tau (an interior ray) spanned by primitive
v = (a,b):  tau^perp \\cap M has rank 1 with generator m_tau = (b,-a), so
    H_v = ker(chi_1^b chi_2^{-a}).
Consequences claimed:
  (a) H non-cyclic  =>  H_tau != 1 for every wall;
  (b) |I| = 2: the criterion fails as soon as some chi_1^b chi_2^{-a} is
      injective on H.
Also: every maximal cone sigma has sigma^perp = 0, hence H_sigma = H != 1.

This script recomputes H_tau from the DEFINITION (intersecting kernels over all
lattice points of tau^perp in a box) and compares with the closed form, then
checks (a), (b) and the maximal-cone statement over many (H, chi_1, chi_2).
"""

import sys, os
from math import gcd
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from abelian import (all_groups, elements, kernel, is_cyclic, char_word,
                     joint_kernel, generate_dual, order)

BOX = 12   # lattice box for the "by definition" recomputation


def perp_lattice_points(v, box=BOX):
    """all m in M = Z^2 with <m, v> = 0 and |m_i| <= box"""
    a, b = v
    return [(m1, m2) for m1 in range(-box, box + 1)
            for m2 in range(-box, box + 1)
            if m1 * a + m2 * b == 0]


def H_tau_by_definition(v, c1, c2, n, box=BOX):
    chars = [char_word(c1, c2, m1, m2, n) for (m1, m2) in perp_lattice_points(v, box)]
    return joint_kernel(chars, n)


def faithful_pair(c1, c2, n):
    """do chi_1, chi_2 generate dual(H)?  (= toroidal form condition (c))"""
    return len(generate_dual([c1, c2], n)) == order(n)


def interior_rays(bound):
    return [(a, b) for a in range(1, bound + 1) for b in range(1, bound + 1)
            if gcd(a, b) == 1]


def main():
    fails = []
    checked_groups = 0
    stat = {"noncyclic_all_walls_nontrivial": 0, "cyclic_has_free_wall": 0}

    for n in all_groups(36, max_factors=3):
        els = elements(n)
        pairs = [(c1, c2) for c1 in els for c2 in els if faithful_pair(c1, c2, n)]
        if not pairs:
            continue
        checked_groups += 1
        cyc = is_cyclic(n)
        for (c1, c2) in pairs:
            # standing convention of section 4: G_{D_i} = ker chi_2 != 1 and
            # G_{D_j} = ker chi_1 != 1
            if len(kernel(c1, n)) == 1 or len(kernel(c2, n)) == 1:
                continue
            free_wall = None
            for v in interior_rays(8):
                a, b = v
                closed = kernel(char_word(c1, c2, b, -a, n), n)
                bydef = H_tau_by_definition(v, c1, c2, n)
                if sorted(closed) != sorted(bydef):
                    fails.append(("H_tau closed form != definition", n, c1, c2, v))
                # generator claim: tau^perp \cap M = Z*(b,-a)
                for (m1, m2) in perp_lattice_points(v):
                    if (m1, m2) != (0, 0):
                        k = m1 / b if b else m2 / (-a)
                        if (m1, m2) != (round(k) * b, round(k) * (-a)):
                            fails.append(("tau^perp not generated by (b,-a)", n, v, (m1, m2)))
                if len(closed) == 1:
                    free_wall = free_wall or v
                    if not cyc:
                        fails.append(("non-cyclic H with a free wall", n, c1, c2, v))
            # maximal cones: sigma^perp \cap M = 0 => H_sigma = H
            for v in interior_rays(4):
                for w in interior_rays(4):
                    if v == w:
                        continue
                    pts = [m for m in perp_lattice_points(v)
                           if m[0] * w[0] + m[1] * w[1] == 0]
                    if pts != [(0, 0)]:
                        fails.append(("2-dim cone has nonzero perp", n, v, w, pts))
                        break
            if cyc and free_wall is None:
                fails.append(("cyclic H with no free wall among rays <= 8", n, c1, c2))
            if cyc and free_wall is not None:
                stat["cyclic_has_free_wall"] += 1
            if (not cyc) and free_wall is None:
                stat["noncyclic_all_walls_nontrivial"] += 1

    print(f"groups with an admissible (chi_1, chi_2): {checked_groups}")
    print(f"  (chi_1,chi_2) configurations, cyclic H, a free wall exists: "
          f"{stat['cyclic_has_free_wall']}")
    print(f"  (chi_1,chi_2) configurations, non-cyclic H, NO free wall:   "
          f"{stat['noncyclic_all_walls_nontrivial']}")
    print(f"failures: {len(fails)}")
    for f in fails[:20]:
        print("  FAIL", f)

    # ------------------------------------------------------------------
    # ex:not_a_complex (Duncan 3.13):  G = Z/6 x Z/2 acting on P^3 by
    #   (a,b).[x0:x1:x2:x3] = [x0 : z^{2a} x1 : z^{3a} x2 : (-1)^b x3],  z = zeta_6
    print()
    print("ex:not_a_complex (3.13), G = Z/6 x Z/2 on P^3")
    ex1 = projective_example(
        n=(6, 2),
        chars=[(0, 0), (2, 0), (3, 0), (0, 1)],   # lambda_0..lambda_3 as characters
        labels="0123")
    for k, v in ex1.items():
        print("   ", k, "=", v)

    print()
    print("ex:no_converse (4.8), G = (Z/2)^2 x (Z/3)^2 on P^3")
    # coordinates of G: (eps_1, eps_2, eta_1, eta_2) in Z/2 x Z/2 x Z/3 x Z/3
    # lambda_1 = eta_2, lambda_2 = eps_2, lambda_3 = eps_1 * eta_1
    ex2 = projective_example(
        n=(2, 2, 3, 3),
        chars=[(0, 0, 0, 0), (0, 0, 0, 1), (0, 1, 0, 0), (1, 0, 1, 0)],
        labels="0123")
    for k, v in ex2.items():
        print("   ", k, "=", v)

    expected1 = {"G_D0": "1", "G_D1": "Z/3", "G_D2": "Z/2", "G_D3": "Z/2",
                 "G_D12": "Z/6", "G_D13": "Z/6", "G_D23": "Z/2 x Z/2",
                 "G_D123": "Z/2 x Z/6"}
    expected2 = {"G_D0": "1", "G_D1": "Z/3", "G_D2": "Z/2", "G_D3": "Z/6",
                 "G_D12": "Z/6", "G_D13": "Z/3 x Z/6", "G_D23": "Z/2 x Z/6"}
    ex_fail = []
    for k, want in expected1.items():
        if k in ex1 and ex1[k] != want:
            ex_fail.append(("3.13", k, ex1[k], want))
    for k, want in expected2.items():
        if k in ex2 and ex2[k] != want:
            ex_fail.append(("4.8", k, ex2[k], want))
    print("example-group mismatches vs the tex:", ex_fail if ex_fail else "none")

    ok = not fails and not ex_fail
    print("RESULT:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def abstract_type(sub, n):
    """invariant-factor name of the subgroup `sub` of Z/n_1 x ... x Z/n_k"""
    from abelian import element_order
    m = len(sub)
    if m == 1:
        return "1"
    # brute force: find invariant factors by repeatedly extracting a max-order element
    orders = sorted({element_order(x, n) for x in sub}, reverse=True)
    top = orders[0]
    if top == m:
        return f"Z/{m}"
    # order-<=2 factor decomposition is enough for the cases here
    for d in range(2, m + 1):
        if m % d == 0 and d <= top:
            other = m // d
            if other <= top and all(x <= top for x in [d, other]):
                # test Z/other x Z/top  with other | top
                if other * top == m and top % other == 0:
                    cnt = sum(1 for x in sub if element_order(x, n) <= top)
                    if cnt == m:
                        return f"Z/{other} x Z/{top}"
    return f"order {m}, exponent {top}"


def projective_example(n, chars, labels):
    """G acting on P^3 with diagonal characters `chars` (lambda_0..lambda_3).
    Returns G_{D_i} and G_{D_ij}, G_{D_ijk} as abstract types.
    D_i = {x_i = 0}; g fixes D_S = {x_i = 0, i in S} pointwise iff the lambda_j,
    j not in S, are all equal."""
    from itertools import combinations
    from abelian import elements as els, pairing
    out = {}
    G = els(n)
    for r in (1, 2, 3):
        for S in combinations(range(4), r):
            comp = [j for j in range(4) if j not in S]
            sub = []
            for g in G:
                vals = {pairing(chars[j], g, n) for j in comp}
                if len(vals) == 1:
                    sub.append(g)
            out["G_D" + "".join(str(i) for i in S)] = abstract_type(sub, n)
    return out


if __name__ == "__main__":
    sys.exit(main())
