/-
Copyright (c) 2026 BConicBundleMultisections contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BConicBundleMultisections contributors
-/
module

public import BConicBundleMultisections.BiprojectiveAffineZeroLocus
public import BConicBundleMultisections.ResidualComponentExhaustion

/-!
# Affine charts of biprojective two-equation intersections

This file supplies the scheme-theoretic chart bridge for a complete intersection cut out by two
bihomogeneous Cox polynomials.  On every standard biprojective chart, the pulled-back global ideal
is the sum of the two principal chart ideals, and its subscheme is the spectrum of the ordinary
polynomial ring modulo the two dehomogenized equations.

The construction is deliberately independent of any coprimality or dimension argument.  Those
hypotheses enter only after base change to a projective-plane fibre, where the quotient has two
variables and `PlaneCurveIntersectionArtinian` can prove it Artinian.
-/

@[expose] public section

open CategoryTheory Limits
open scoped AlgebraicGeometry

namespace BConicBundleMultisections

noncomputable section

universe u

open AlgebraicGeometry
open _root_.MvPolynomial

namespace BiprojectiveSpace

/-! ## The local two-equation chart -/

/-- The sum of the two principal ideal sheaves on one standard biprojective chart. -/
def twoEquationChartIdealSheaf
    (m n : ℕ) (R : Type u) [CommRing R]
    (i : Fin (m + 1)) (j : Fin (n + 1))
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    (standardChart m n R i j).IdealSheafData :=
  chartIdealSheaf m n R i j F ⊔ chartIdealSheaf m n R i j G

/-- The ordinary affine ideal generated by both dehomogenized chart equations. -/
def twoEquationAffineChartIdeal
    (m n : ℕ) (R : Type u) [CommRing R]
    (i : Fin (m + 1)) (j : Fin (n + 1))
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    Ideal (MvPolynomial (Fin m ⊕ Fin n) R) :=
  Ideal.span
    ({affineChartEquation m n R i j F,
      affineChartEquation m n R i j G} :
      Set (MvPolynomial (Fin m ⊕ Fin n) R))

theorem twoEquationChartIdealSheaf_ideal_chartTopAffineOpen
    (m n : ℕ) (R : Type u) [CommRing R]
    (i : Fin (m + 1)) (j : Fin (n + 1))
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    (twoEquationChartIdealSheaf m n R i j F G).ideal
        (chartTopAffineOpen m n R i j) =
      chartIdealTop m n R i j F ⊔ chartIdealTop m n R i j G := by
  change ((chartIdealSheaf m n R i j F ⊔
    chartIdealSheaf m n R i j G).ideal
      (chartTopAffineOpen m n R i j)) = _
  rw [Scheme.IdealSheafData.ideal_sup]
  change (chartIdealSheaf m n R i j F).ideal
      (chartTopAffineOpen m n R i j) ⊔
    (chartIdealSheaf m n R i j G).ideal
      (chartTopAffineOpen m n R i j) = _
  rw [chartIdealSheaf_ideal_chartTopAffineOpen,
    chartIdealSheaf_ideal_chartTopAffineOpen]

/-- Transporting the sum of the two chart ideals to ordinary affine coordinates produces the
two-generated ideal of the two affine chart equations. -/
theorem map_twoEquationChartIdeal_standardChartRingEquivMvPolynomial
    (m n : ℕ) (R : Type u) [CommRing R]
    (i : Fin (m + 1)) (j : Fin (n + 1))
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    Ideal.map (chartSectionsEquivMvPolynomial m n R i j)
        ((twoEquationChartIdealSheaf m n R i j F G).ideal
          (chartTopAffineOpen m n R i j)) =
      twoEquationAffineChartIdeal m n R i j F G := by
  rw [twoEquationChartIdealSheaf_ideal_chartTopAffineOpen]
  change Ideal.map
    ((standardChartΓIso m n R i j).commRingCatIsoToRingEquiv.trans
      (standardChartRingEquivMvPolynomial m n R i j).toRingEquiv)
      (chartIdealTop m n R i j F ⊔ chartIdealTop m n R i j G) = _
  rw [Ideal.map_sup,
    map_chartIdealTop_standardChartRingEquivMvPolynomial,
    map_chartIdealTop_standardChartRingEquivMvPolynomial]
  unfold twoEquationAffineChartIdeal
  exact (Ideal.span_insert _ _).symm

/-- The quotient of chart sections by the two-equation ideal is the explicit ordinary affine
polynomial quotient. -/
noncomputable def twoEquationChartQuotientEquivMvPolynomial
    (m n : ℕ) (R : Type u) [CommRing R]
    (i : Fin (m + 1)) (j : Fin (n + 1))
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    (Γ(standardChart m n R i j, ⊤) ⧸
      (twoEquationChartIdealSheaf m n R i j F G).ideal
        (chartTopAffineOpen m n R i j)) ≃+*
      (MvPolynomial (Fin m ⊕ Fin n) R ⧸
        twoEquationAffineChartIdeal m n R i j F G) :=
  Ideal.quotientEquiv
    ((twoEquationChartIdealSheaf m n R i j F G).ideal
      (chartTopAffineOpen m n R i j))
    (twoEquationAffineChartIdeal m n R i j F G)
    (chartSectionsEquivMvPolynomial m n R i j)
    (map_twoEquationChartIdeal_standardChartRingEquivMvPolynomial
      m n R i j F G).symm

/-- The top member of the canonical affine cover of the local two-equation subscheme is an
isomorphism, because the ambient chart itself is affine. -/
instance twoEquationChartSubschemeCoverTopIsIso
    (m n : ℕ) (R : Type u) [CommRing R]
    (i : Fin (m + 1)) (j : Fin (n + 1))
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    IsIso ((twoEquationChartIdealSheaf m n R i j F G).subschemeCover.f
      (chartTopAffineOpen m n R i j)) := by
  let q := (twoEquationChartIdealSheaf m n R i j F G).subschemeCover.f
    (chartTopAffineOpen m n R i j)
  letI : Epi q.base := by
    rw [TopCat.epi_iff_surjective]
    intro x
    rw [← Set.mem_range, ← Scheme.Hom.coe_opensRange]
    simp [q, chartTopAffineOpen]
  exact IsOpenImmersion.isIso q

/-- The local two-equation zero locus is the spectrum of the polynomial ring modulo the two
explicit affine chart equations. -/
noncomputable def twoEquationChartIsoSpecAffineQuotient
    (m n : ℕ) (R : Type u) [CommRing R]
    (i : Fin (m + 1)) (j : Fin (n + 1))
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    (twoEquationChartIdealSheaf m n R i j F G).subscheme ≅
      Spec (.of (MvPolynomial (Fin m ⊕ Fin n) R ⧸
        twoEquationAffineChartIdeal m n R i j F G)) :=
  (asIso ((twoEquationChartIdealSheaf m n R i j F G).subschemeCover.f
    (chartTopAffineOpen m n R i j))).symm ≪≫
    Scheme.Spec.mapIso
      (twoEquationChartQuotientEquivMvPolynomial m n R i j F G).symm.toCommRingCatIso.op

/-! ## Restriction of the global two-equation ideal -/

/-- The global ideal sheaf generated by two bihomogeneous Cox equations. -/
def twoEquationBiprojectiveIdeal
    (m n : ℕ) (R : Type u) [CommRing R]
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    (BiprojectiveSpace m n R).IdealSheafData :=
  biprojectiveZeroLocusIdeal m n R F ⊔ biprojectiveZeroLocusIdeal m n R G

/-- The global biprojective complete intersection of the two equations. -/
abbrev twoEquationBiprojectiveZeroLocus
    (m n : ℕ) (R : Type u) [CommRing R]
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) : Scheme.{u} :=
  (twoEquationBiprojectiveIdeal m n R F G).subscheme

/-- Its canonical closed immersion into biprojective space. -/
abbrev twoEquationBiprojectiveι
    (m n : ℕ) (R : Type u) [CommRing R]
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    twoEquationBiprojectiveZeroLocus m n R F G ⟶ BiprojectiveSpace m n R :=
  (twoEquationBiprojectiveIdeal m n R F G).subschemeι

theorem ker_twoEquationBiprojectiveι
    (m n : ℕ) (R : Type u) [CommRing R]
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    (twoEquationBiprojectiveι m n R F G).ker =
      twoEquationBiprojectiveIdeal m n R F G :=
  Scheme.IdealSheafData.ker_subschemeι _

/-- The global sum ideal restricts to the sum of the two explicit principal chart ideals. -/
theorem twoEquationBiprojectiveIdeal_comap_standardChartι
    (m n : ℕ) (R : Type u) [CommRing R]
    {dF eF dG eG : ℕ}
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R)
    (hF : IsBihomogeneousOfBidegree dF eF F)
    (hG : IsBihomogeneousOfBidegree dG eG G)
    (i : Fin (m + 1)) (j : Fin (n + 1)) :
    (twoEquationBiprojectiveIdeal m n R F G).comap
        (standardChartι m n R i j) =
      twoEquationChartIdealSheaf m n R i j F G := by
  rw [twoEquationBiprojectiveIdeal, Scheme.IdealSheafData.comap_sup,
    biprojectiveZeroLocusIdeal_comap_standardChartι m n R F hF,
    biprojectiveZeroLocusIdeal_comap_standardChartι m n R G hG]
  rfl

/-- The local two-equation chart is the pullback of the global complete intersection along the
standard-chart open immersion. -/
noncomputable def twoEquationChartIsoPullback
    (m n : ℕ) (R : Type u) [CommRing R]
    {dF eF dG eG : ℕ}
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R)
    (hF : IsBihomogeneousOfBidegree dF eF F)
    (hG : IsBihomogeneousOfBidegree dG eG G)
    (i : Fin (m + 1)) (j : Fin (n + 1)) :
    (twoEquationChartIdealSheaf m n R i j F G).subscheme ≅
      pullback (standardChartι m n R i j)
        (twoEquationBiprojectiveι m n R F G) := by
  let ι := pullback.fst (standardChartι m n R i j)
    (twoEquationBiprojectiveι m n R F G)
  let ι' := (twoEquationChartIdealSheaf m n R i j F G).subschemeι
  have hker : ι.ker = ι'.ker := by
    rw [Scheme.IdealSheafData.ker_fst_of_isClosedImmersion,
      ker_twoEquationBiprojectiveι,
      twoEquationBiprojectiveIdeal_comap_standardChartι
        m n R F G hF hG,
      Scheme.IdealSheafData.ker_subschemeι]
  let f := IsClosedImmersion.lift ι ι' hker.le
  letI : IsIso f := IsClosedImmersion.isIso_lift ι ι' hker
  exact asIso f

@[reassoc]
theorem twoEquationChartIsoPullback_hom_fst
    (m n : ℕ) (R : Type u) [CommRing R]
    {dF eF dG eG : ℕ}
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R)
    (hF : IsBihomogeneousOfBidegree dF eF F)
    (hG : IsBihomogeneousOfBidegree dG eG G)
    (i : Fin (m + 1)) (j : Fin (n + 1)) :
    (twoEquationChartIsoPullback m n R F G hF hG i j).hom ≫
        pullback.fst _ _ =
      (twoEquationChartIdealSheaf m n R i j F G).subschemeι := by
  change IsClosedImmersion.lift _ _ _ ≫ _ = _
  exact IsClosedImmersion.lift_fac _ _ _

/-! ## The standard affine cover of the global intersection -/

/-- Pulling the standard biprojective cover back along the closed immersion gives the canonical
standard-chart open cover of the two-equation complete intersection. -/
def twoEquationStandardOpenCover
    (m n : ℕ) (R : Type u) [CommRing R]
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R) :
    (twoEquationBiprojectiveZeroLocus m n R F G).OpenCover :=
  (standardOpenCover m n R).pullback₁
    (twoEquationBiprojectiveι m n R F G)

/-- A member of the pulled-back standard cover is canonically the local two-equation chart
subscheme. -/
noncomputable def twoEquationStandardOpenCoverObjIsoChart
    (m n : ℕ) (R : Type u) [CommRing R]
    {dF eF dG eG : ℕ}
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R)
    (hF : IsBihomogeneousOfBidegree dF eF F)
    (hG : IsBihomogeneousOfBidegree dG eG G)
    (ij : Fin (m + 1) × Fin (n + 1)) :
    (twoEquationStandardOpenCover m n R F G).X ij ≅
      (twoEquationChartIdealSheaf m n R ij.1 ij.2 F G).subscheme :=
  pullbackSymmetry
      (twoEquationBiprojectiveι m n R F G)
      (standardChartι m n R ij.1 ij.2) ≪≫
    (twoEquationChartIsoPullback m n R F G hF hG ij.1 ij.2).symm

/-- Every member of the global standard cover has the explicit two-equation affine quotient
presentation. -/
noncomputable def twoEquationStandardOpenCoverObjIsoSpecAffineQuotient
    (m n : ℕ) (R : Type u) [CommRing R]
    {dF eF dG eG : ℕ}
    (F G : MvPolynomial (BiprojectiveCoordinate m n) R)
    (hF : IsBihomogeneousOfBidegree dF eF F)
    (hG : IsBihomogeneousOfBidegree dG eG G)
    (ij : Fin (m + 1) × Fin (n + 1)) :
    (twoEquationStandardOpenCover m n R F G).X ij ≅
      Spec (.of (MvPolynomial (Fin m ⊕ Fin n) R ⧸
        twoEquationAffineChartIdeal m n R ij.1 ij.2 F G)) :=
  twoEquationStandardOpenCoverObjIsoChart
      m n R F G hF hG ij ≪≫
    twoEquationChartIsoSpecAffineQuotient
      m n R ij.1 ij.2 F G

/-! ## The target relation -/

/-- Renaming an ordinary homogeneous polynomial into the second Cox block gives bidegree
`(0,d)`. -/
theorem rename_inr_isBihomogeneous
    {m n d : ℕ} {R : Type u} [CommSemiring R]
    {H : MvPolynomial (Fin (n + 1)) R} (hH : H.IsHomogeneous d) :
    IsBihomogeneousOfBidegree 0 d
      (_root_.MvPolynomial.rename
        (Sum.inr : Fin (n + 1) → BiprojectiveCoordinate m n) H) := by
  classical
  intro s hs
  obtain ⟨t, ht, ht0⟩ := coeff_rename_ne_zero
    (Sum.inr : Fin (n + 1) → BiprojectiveCoordinate m n) H s hs
  rw [← ht, Finsupp.weight_apply]
  rw [Finsupp.sum_mapDomain_index_inj Sum.inr_injective]
  rw [Finsupp.sum]
  apply Prod.ext
  · simp [bidegreeWeight, Prod.fst_sum]
  · have hdeg : t.degree = d := by
      rw [Finsupp.degree_eq_weight_one]
      exact hH ht0
    simpa [bidegreeWeight, Prod.snd_sum, ← Finsupp.degree_apply] using hdeg

/-- On each standard product chart, the target-relation ideal is generated by the affine chart
equations of `F` and the second-block lift of `H`. -/
theorem targetRelationIdeal_comap_standardChartι
    {k : Type u} [CommRing k]
    {dF eF dH : ℕ}
    (F : MvPolynomial (BiprojectiveCoordinate 2 2) k)
    (H : MvPolynomial (Fin 3) k)
    (hF : IsBihomogeneousOfBidegree dF eF F)
    (hH : H.IsHomogeneous dH)
    (i j : Fin 3) :
    (targetRelationIdeal F H).comap (standardChartι 2 2 k i j) =
      twoEquationChartIdealSheaf 2 2 k i j F
        (_root_.MvPolynomial.rename
          (Sum.inr : Fin 3 → BiprojectiveCoordinate 2 2) H) := by
  exact twoEquationBiprojectiveIdeal_comap_standardChartι
    2 2 k F (_root_.MvPolynomial.rename Sum.inr H) hF
      (rename_inr_isBihomogeneous hH) i j

end BiprojectiveSpace

end

end BConicBundleMultisections
