import BConicBundleMultisections.ProjectiveHypersurfaceAnchorEvaluation

open BConicBundleMultisections
open BConicBundleMultisections.ProjectiveSpace

#print axioms homogeneousPolynomialToFunctionField_eq_algebraMap_mk_dehom
#print axioms anchorCoordinates
#print axioms eval₂_anchorCoordinates_eq_zero
#print axioms chartToAnchorFunctionField
#print axioms chartToAnchorFunctionField_self
#print axioms chartToAnchorFunctionField_mk_chartDehomogenization
#print axioms hypersurfaceFunctionFieldEquivSchemeFunctionField_homogeneousPolynomial
#print axioms hypersurfaceFunctionFieldEquivSchemeFunctionField_symm_comp_chart
#print axioms hypersurfaceFunctionFieldEquivSchemeFunctionField_chartToAnchorFunctionField
