import BConicBundleMultisections.ProjectiveHypersurfaceChartTransition

open BConicBundleMultisections
open BConicBundleMultisections.ProjectiveSpace

#print axioms specMap_hypersurfaceChartQuotientToSchemeFunctionField_comp_chart
#print axioms standardChartRingEquivMvPolynomial_hypersurfaceChartEquation
#print axioms hypersurfaceAffineChartQuotientMap_chartEquation
#print axioms hypersurfaceStandardChartToSchemeFunctionField
#print axioms specMap_hypersurfaceStandardChartToSchemeFunctionField_comp_standardChartι
#print axioms hypersurfaceGenericOverlapLift
#print axioms hypersurfaceOverlapToSchemeFunctionField
#print axioms hypersurfaceOverlapToSchemeFunctionField_comp_toOverlap
#print axioms hypersurfaceOverlapToSchemeFunctionField_comp_fromOtherToOverlap
#print axioms hypersurfaceStandardChartToSchemeFunctionField_chartEquation
#print axioms hypersurfaceStandardChartToSchemeFunctionField_normalizedCoordinate
#print axioms hypersurfaceStandardChartEquation_intrinsic_transition
#print axioms hypersurfaceChartDehomogenization_intrinsic_transition_mul
#print axioms hypersurfaceFunctionFieldEquivSchemeFunctionField_normalizedCoordinate
#print axioms hypersurfaceChartDehomogenization_intrinsic_transition
#print axioms hypersurfaceChartDehomogenization_intrinsic_transition_inv
