import BConicBundleMultisections.ResidualTargetRelationGeometryNegativeTwist

open BConicBundleMultisections

#print axioms TargetRelationsResidualNegativeTwistGluingAwayDiscriminantOn
#print axioms residualTargetRelationMembershipAwayDiscriminantOn_of_negativeTwistGeometry
#print axioms hasUnirationalParametrization3_biprojectiveZeroLocus_of_negativeTwistTargetGeometry
