import BConicBundleMultisections.ResidualTargetNegativeTwistFactorTransition

#print axioms BConicBundleMultisections.BiprojectiveSpace.map_factor_eq_transitionSquare_mul_of_factorizations
#print axioms BConicBundleMultisections.BiprojectiveSpace.mapped_quadratic_mul_factor_coeff_eq
#print axioms BConicBundleMultisections.BiprojectiveSpace.residualTargetNegativeTwistFactor_coeff_intrinsic_transition
