import BConicBundleMultisections.ResidualTargetNegativeTwistGenericFiber

open BConicBundleMultisections

#print axioms ProjectiveSpace.mvPolynomial_eq_zero_of_coeff_quadraticMultiples_extendToGlobal
#print axioms ProjectiveSpace.mvPolynomial_eq_zero_of_coeff_homogeneousQuadraticMultiples_extendToGlobal
#print axioms BiprojectiveSpace.eq_zero_of_exists_factor_and_coeff_quadraticMultiples_extendToGlobal
#print axioms BiprojectiveSpace.mem_span_targetRelation_of_local_factors_quadraticMultiples_extendToGlobal
#print axioms BiprojectiveSpace.residualEquationOn_mem_span_targetRelation_of_isIso_of_quadraticMultiples_extendToGlobal
