import BConicBundleMultisections.ResidualTargetNegativeTwistAutomaticGluing

open BConicBundleMultisections

#print axioms
  ProjectiveSpace.hasCompatibleRetainedChartRepresentativesAt_of_quadraticProduct_transition
#print axioms targetRelationsResidualNegativeTwistGluingAwayDiscriminantOn_of_compatibleFactors
#print axioms targetRelationsResidualNegativeTwistGluingAwayDiscriminantOn_of_intrinsicTransitions
#print axioms targetRelationsResidualNegativeTwistGluingAwayDiscriminantOn
#print axioms BiprojectiveSpace.residualEquationOn_mem_span_targetRelation_of_isIso_of_negativeTwist
#print axioms hasUnirationalParametrization3_biprojectiveZeroLocus_of_projectivelyIntegralTargetRelations
