import BConicBundleMultisections.ResidualTargetRelationGeometry

#print axioms BConicBundleMultisections.residualTargetRelationMembershipAwayDiscriminantOn_of_reducedGeometry
#print axioms BConicBundleMultisections.residualTargetRelationMembershipAwayDiscriminantOn_of_geometry
#print axioms BConicBundleMultisections.hasUnirationalParametrization3_biprojectiveZeroLocus_of_targetRelationGeometry
