import BConicBundleMultisections.ResidualTargetRelationGeometryAutomaticArtinian

open BConicBundleMultisections

#print axioms targetRelationsGenericFiberArtinianAwayDiscriminant_of_bidegree23
#print axioms residualTargetRelationMembershipAwayDiscriminantOn_of_reducedGeometry_autoArtinian
#print axioms hasUnirationalParametrization3_biprojectiveZeroLocus_of_targetRelationGeometry_autoArtinian
