import BConicBundleMultisections.ResidualDiscriminantConsumer

#print axioms BConicBundleMultisections.eq_zero_of_aeval_residualYCoordsOn_of_membershipAwayDiscriminant
#print axioms BConicBundleMultisections.residualYCoordsOn_ne_zero_of_membershipAwayDiscriminant
#print axioms BConicBundleMultisections.exists_isDominant_residualComponentOnToBase_of_membershipAwayDiscriminant
#print axioms BConicBundleMultisections.hasUnirationalParametrization3_biprojectiveZeroLocus_of_membershipAwayDiscriminant
