import BConicBundleMultisections.ResidualTargetNegativeTwistTransitionCompatibility

open BConicBundleMultisections

#print axioms ProjectiveSpace.HasCompatibleRetainedChartRepresentativesAt
#print axioms ProjectiveSpace.exists_globalSection_toFunctionField_eq_of_hasCompatibleRetainedChartRepresentativesAt
#print axioms ProjectiveSpace.homogeneousQuadraticMultiplesExtendToGlobal_of_compatibleRetainedChartRepresentatives
#print axioms ProjectiveSpace.quadraticMultiplesExtendToGlobal_of_homogeneousQuadraticMultiplesExtendToGlobal
#print axioms ProjectiveSpace.mvPolynomial_eq_zero_of_coeff_compatibleRetainedChartRepresentatives
