import BConicBundleMultisections.ResidualTargetNegativeTwistLocal

open BConicBundleMultisections

#print axioms BiprojectiveSpace.affineChartToTargetRelationBase_affineChartEquation_rename_inr
#print axioms BiprojectiveSpace.affineChartEquationOverTargetRelationBase_rename_inr_eq_zero
#print axioms BiprojectiveSpace.exists_factor_over_targetRelationBase_of_mem_twoEquationAffineChartIdeal
#print axioms BiprojectiveSpace.exists_residualEquationOn_factor_over_targetRelationBase_of_isIso
