import BConicBundleMultisections.TargetRelationTotalSpaceIntegral

open BConicBundleMultisections

#print axioms BiprojectiveSpace.twoEquationChartIsoSpecAffineQuotient_hom_snd
#print axioms BiprojectiveSpace.targetRelationGlobalChartGenericPoint_mem_chart_range
#print axioms BiprojectiveSpace.isIntegral_targetRelationZeroLocus_of_smooth_irreducible_awayDiscriminant
#print axioms targetRelationsProjectivelyIntegralAwayDiscriminant_of_smooth
