import BConicBundleMultisections.TargetRelationGenericGlobalCoprimalityFromDiscriminant

#print axioms BConicBundleMultisections.irreducible_map_of_isFractionRing_mvPolynomial_coefficients
#print axioms BConicBundleMultisections.commAlgEquiv_genericFstCubicChart
#print axioms BConicBundleMultisections.not_dvd_genericFstCubicChart_of_not_dvd_discriminant
#print axioms BConicBundleMultisections.BiprojectiveSpace.map_genericFstCubicChart_standardChartResidueRingHom
#print axioms BConicBundleMultisections.BiprojectiveSpace.hasTargetRelationFstFiberGlobalCoprimality_generic_of_not_dvd_discriminant
#print axioms BConicBundleMultisections.BiprojectiveSpace.targetRelation_genericFiber_isLocallyArtinian_of_irreducible_not_dvd_discriminant
