import BConicBundleMultisections.TargetRelationChartDomain

open BConicBundleMultisections

#print axioms BConicBundleMultisections.BiprojectiveSpace.isPrime_span_affineChartEquationOverTargetRelationBase
#print axioms BConicBundleMultisections.BiprojectiveSpace.isPrime_twoEquationAffineChartIdeal_targetRelation
#print axioms BConicBundleMultisections.BiprojectiveSpace.quotient_X_inl_ne_zero_twoEquationAffineChartIdeal_targetRelation
#print axioms BConicBundleMultisections.BiprojectiveSpace.quotient_X_inr_ne_zero_twoEquationAffineChartIdeal_targetRelation
