import BConicBundleMultisections.UFDQuotientTorsionFree

#print axioms BConicBundleMultisections.smul_eq_zero_in_quotient_span_singleton_of_prime_not_dvd
#print axioms BConicBundleMultisections.noZeroSMulDivisors_quotient_span_singleton_of_irreducibles
#print axioms BConicBundleMultisections.isTorsionFree_quotient_span_singleton_of_irreducibles
#print axioms BConicBundleMultisections.injective_algebraMap_localization_at_base_nonZeroDivisors
#print axioms BConicBundleMultisections.isDomain_of_isLocalization_at_base_nonZeroDivisors
